### ISSUE TITLE
[feature] Bactopia Tools - Allow completed genomes as the only inputs

### ISSUE THREAD

**Issue by rpetit3** [bactopia/bactopia#100]
**Related To**

- [X] Bactopia Tools

**Is this something you would like to see added?**
At the moment Bactopia tools works against your samples and you can include completed genomes.

**Describe the solution you'd like**
It would be nice to execute the tool on just completed genomes. For example, run Roary on just the completed genomes.

Tagging: @molleraj

**Comment by haruosuz** [comment]
Dear Robert: 
I look forward to the next version of Bactopia Tools which allows completely sequenced genomes (e.g. chromosomes or plasmids) as input, retrieve nucleotide sequences of single-copy orthologous core genes, separately align them, and concatenate them (core_gene_alignment.aln) like Roary (https://sanger-pathogens.github.io/Roary/).
It would be great to execute Bactopia Tools on completed genomes from different bacterial species or genera, which can not be done using Roary (https://github.com/sanger-pathogens/Roary/issues/439).

**Comment by rpetit3** [comment]
Hi @haruosuz 

For this case, I'll still be using Roary, so we'll still be affected by the issue you linked. 

Once I add this feature there's nothing to stop you from running it on completed genomes of the same genus, but in most cases I would recommend against doing so due to the limitations of Roary (highlighted in the issue). There might be some exceptions (e.g. Bacillus cereus group), but that's for the user to decide.

If you by chance know any alternatives to Roary in mind, please feel free to suggest them!

Thank you very much for reaching out!
Robert

**Comment by uloeber** [comment]
Dear Robert, 
I would find it very helpful if one could run bactopia on assembled genomes as well. Do you know when you will have time to implement this feature as well? I would like to compare the annotations of my genomes to already existing once, but I want to make sure it is annotated exactly the same way I annotated my genomes with bactopia (same tools, versions, databases).

Best wishes,
Ulrike

**Comment by rpetit3** [comment]
I've added this option (see https://github.com/bactopia/bactopia/commit/4843af2811c45ed2afdb2069ac7bbb262701422f) 

It'll be in the next release of Bactopia. If this is something you would like sooner then later, let me know!

**Comment by rpetit3** [comment]
Hi @mollleraj @haruosuz  @uloeber 

I've released a new version of Bactopia (https://github.com/bactopia/bactopia/releases/tag/v1.4.0). The bactopia tools for Roary and PIRATE, both allow the creation of a pan-genome of only  completed genomes.

Thank you very much for your suggestion! Please let me know if there are any issues or you have more suggestions!

Going to close this isssue.

Cheers,
Robert

**Comment by rpetit3** [comment]
Ah! Thank you very much for clearing that up.

If you want to provide accessions, they'll need to be the NCBI Assembly (GCF/GCA) accessions. I don't currently support Nucleotide accessions.

I think in your case, one solution is for me to add an option to allow multiple genomes (previously downloaded) in FASTA format.

Currently I have `--reference` for a single genome and I don't think it would be too difficult to expand that to many genomes (or plasmids in your case).

**Comment by haruosuz** [comment]
I would be grateful if you could add an option to allow multiple genomes, which can be applied to any sequences (e.g. chromosomes, plasmids, viruses, mitochondria, and plastids).

**Comment by rpetit3** [comment]
Been a while, please see https://github.com/bactopia/bactopia/issues/141#issuecomment-725820250 for information on adding local sequences to Roary/PIRATE analysis

**Comment by haruosuz** [comment]
I run bactopia tools pirate using only completed genomes (*.fna of 10 plasmids) as input.
```
bactopia tools pirate --bactopia ./data/ --assembly ./data/fna/ --assembly_pattern *.fna --outdir ./data/pirate/ --cpus $(getconf _NPROCESSORS_ONLN)
```
Running the command printed the following messages:
```
Found 10 local assemblies.
fna is missing genome size estimate file
pirate is missing genome size estimate file
Did not find any samples in ./data/ to process, please check and try again.
```
[2020-11-22.zip](https://github.com/bactopia/bactopia/files/5579662/2020-11-22.zip)

**Comment by rpetit3** [comment]
You will want to add `--only_completed` since you are not using any samples processed by Bactopia.

```
  --only_completed        Pan-genome will be created using only the completed RefSeq genomes. Requires
                                either '--accessions' and/or '--species'
``

Let me know if that doesn't work.

**Comment by haruosuz** [comment]
Thank you.

```
bactopia tools pirate --only_completed --assembly ./data/fna/ --assembly_pattern *.fna --outdir ./data/pirate/ --cpus $(getconf _NPROCESSORS_ONLN)
```
worked but printed the following messages.
```
  WARNING: 8 sequences contain more than 50% gaps/ambiguity
  ****  TOTAL      83.35%  2 sequences failed composition chi2 test (p-value<5%; df=3)
  Alignment sites statistics printed to iqtree/core-genome.alninfo

*snip*

  WARNING: Sequence BN000925 contains only gaps or missing data

Command error:
  ERROR: Some sequences (see above) are problematic, please check your alignment again
```

Could I change parameters for PIRATE?
```
# data/pirate/bactopia-tools/pirate/core-genome/pirate/PIRATE.log

 - 0 core loci (0%)
 - 678 non-core loci (100%)

 - PIRATE will be run on 50,60,70,80,90,95,98 amino acid % identity thresholds.
```

I wonder if the `work/` directory (70M) is a temporary directory?

**Comment by rpetit3** [comment]
You're right, the `work` directory is a temporary directory created by Nextflow.

You have access to change a bunch of the PIRATE/IQ-Tree parameters. Here's the Usage: https://bactopia.github.io/bactopia-tools/pirate/#usage

Here's PIRATE parameters:
```
PIRATE Related Parameters:
    --steps STR                 Percent identity thresholds to use for pangenome construction
                                    Default: 50,60,70,80,90,95,98

    --features STR              Choose features to use for pangenome construction. Multiple may be
                                    entered, separated by a comma.
                                    Default: CDS

    --nucl                      Input CDS are nucleotides (e.g. not translated to AA sequence)

    --para_off                  Switch off paralog identification

    --keep_all_files            Retain all intermediate files

PIRATE Advanced Parameters:
    --perc INT                  Single percent identity threshold to use for pangenome
                                    Default: 98 %

    --cd_low INT                CDHIT lowest percentage identity threshold
                                    Default: 98 %

    --cd_step FLOAT             CDHIT step size
                                    Default: 0.5

    --evalue STR                E-value used for BLAST hit filtering
                                    Default: 1E-6

    --hsp_len FLOAT             Remove BLAST hsps that are < hsp_len proportion of query length
                                    Default: 0

    --mcl_inflation FLOAT       MCL inflation value
                                    Default: 1.5

    --use_diamond               Use Diamond instead of BLAST - incompatible with --nucl

    --split_diamond             Split diamond files into batches for processing
```

**Comment by haruosuz** [comment]
Thank you for your advice.

Running PIRATE with lower amino acid % identity thresholds (`--steps 20,30,40,50,60,70,80,90,95,98`) still resulted in 0 core loci (0%), as shown in attachment <PIRATE.log>.

However, running the gene screen method of LS-BSR (https://github.com/jasonsahl/LS-BSR) with `ls_bsr.py -g AB231906.pep -b tblastn` detected core loci for the 10 related plasmids, as shown in attachment <lsbsr_g_bsr_matrix.txt>.

[PIRATE.log](https://github.com/bactopia/bactopia/files/5596929/PIRATE.log)

[lsbsr_g_bsr_matrix.txt](https://github.com/bactopia/bactopia/files/5596928/lsbsr_g_bsr_matrix.txt)

**Comment by rpetit3** [comment]
You might want to also try changing `--cd_low`.

I'll try my best to help, but this is getting outside the scope of Bactopia. It might be more useful to reach out to the PIRATE developer to get their opinion on which parameters might work best for you.

**Comment by haruosuz** [comment]
Is it possible to run `bactopia tools pirate` using the PIRATE options `--para-off` and `--pan-opt "--evalue *"`?

https://github.com/SionBayliss/PIRATE/issues/62#issuecomment-734233581

**Comment by rpetit3** [comment]
Yep! Please check out either https://bactopia.github.io/bactopia-tools/pirate/#usage or `bactopia tools pirate --help` for the full list of parameters you can adjust.

```
    --para_off                  Switch off paralog identification
...
    --evalue STR                E-value used for BLAST hit filtering
                                    Default: 1E-6
```

**Comment by haruosuz** [comment]
The PIRATE developer explained the outputs and there are core loci.
https://github.com/SionBayliss/PIRATE/issues/62#issuecomment-734372499

```
IQ-TREE Related Parameters:
    --skip_phylogeny        Skip the creation a core-genome based phylogeny
```
is default?
There is `core-genome/clonalframe/start-tree.iqtree`, but `${PREFIX}.iqtree` is not found.
https://bactopia.github.io/bactopia-tools/pirate/#iqtree

**Comment by rpetit3** [comment]
You're right, if ` --skip_phylogeny` is not used, then IQ-TREE outputs should be created. The outputs are only created if IQ-TREE completes successfully.

Did it finish successfully?

**Comment by haruosuz** [comment]
I got the following messages:
```
  WARNING: 8 sequences contain more than 50% gaps/ambiguity
  ****  TOTAL      84.95%  2 sequences failed composition chi2 test (p-value<5%; df=3)
  Alignment sites statistics printed to iqtree/core-genome.alninfo
  WARNING: Sequence AM157767 contains only gaps or missing data
  WARNING: Sequence AM261282 contains only gaps or missing data
  WARNING: Sequence AY950444 contains only gaps or missing data
  WARNING: Sequence BN000925 contains only gaps or missing data
  WARNING: Sequence GQ983559 contains only gaps or missing data
  WARNING: Sequence KC170283 contains only gaps or missing data
  WARNING: Sequence KP324830 contains only gaps or missing data
  WARNING: Sequence KX377410 contains only gaps or missing data

Command error:
  ERROR: Some sequences (see above) are problematic, please check your alignment again
```
[pbs.bactopia.sh.o5562431.txt](https://github.com/bactopia/bactopia/files/5605352/pbs.bactopia.sh.o5562431.txt)

However, these sequences do not contain only gaps or missing data.
[core_alignment.fasta.gz](https://github.com/bactopia/bactopia/files/5605354/core_alignment.fasta.gz)

**Comment by rpetit3** [comment]
Might be worth turning off the recombination masking with `--skip_clonalframe` otherwise, I think you are going to have to play with the IQ-TREE parameters to get it to work.

What does distance matrix (`${PREFIX}.distance.txt`) look like?

**Comment by haruosuz** [comment]
In the previous analysis (pbs.bactopia.sh.o5562431.txt), there were many 0s in *core-genome.distance.txt*.

Running `bactopia tools pirate` with `--skip_clonalframe` generated the `iqtree` directory and `core-genome.iqtree` file.

https://bactopia.github.io/bactopia-tools/pirate/#usage
```
    --prefix DIR            Prefix to use for final output files
                                Default: core-genome
```

https://bactopia.github.io/bactopia-tools/pirate/#output-overview
```
        ├── pirate
        │   ├── core_alignment.fasta
        │   ├── pangenome_alignment.fasta.gz


        ├── ${PREFIX}.aligned.fa.gz
        ├── ${PREFIX}.distance.txt
        └── ${PREFIX}.iqtree
```
`core_alignment.fasta` should be changed to `core_alignment.fasta.gz` or `${PREFIX}.fasta.gz`?

`bactopia-tools/pirate/core-genome/pirate/core_alignment.fasta.gz` is equal to 
`bactopia-tools/pirate/core-genome/core-genome.aligned.fa.gz`?
Either of the files will be passed on directly to the IQ-TREE with the `--skip_clonalframe` option?

**Comment by rpetit3** [comment]
Yep, if `--skip_clonalframe` is used:
 `core-genome.aligned.fa.gz` is a copy of `pirate/core_alignment.fasta.gz` which was produced by PIRATE.  `pirate/core_alignment.fasta.gz` is then used as input for IQ-TREE

Otherwise:
 `core-genome.aligned.fa.gz` is a copy of `clonalframe/core_gene_alignment-masked.aln.gz` which has the the recombination masked by ClonalFrame. The recombination masked core genome alignment is used as input for IQ-TREE.

**Comment by haruosuz** [comment]
- bactopia can accept GFF3 files (*.gff) instead of FASTA files (*.fna) as input, like PIRATE and Roary?
- bactopia can do alignment trimming (e.g. trimAl, Gblocks) to remove gaps (-) and ambiguous bases (N) before phylogenetic analysis?
- bactopia can generate individual gene trees to assess incongruence among core gene trees and to create consensus tree?
- bactopia can use tools such as Piggy and Scoary which use Roary's output as input?

References:

https://github.com/SionBayliss/PIRATE#input-format
Input format
PIRATE accepts GFF3 annotation files containing matching nucleotide sequence at the end of the file. 

https://sanger-pathogens.github.io/Roary/
Input files
Roary takes GFF3 files as input. They must contain the nucleotide sequence at the end of the file.

http://www.iqtree.org/doc/Frequently-Asked-Questions#how-does-iq-tree-treat-gapmissingambiguous-characters
How does IQ-TREE treat gap/missing/ambiguous characters?
Gaps (-) and missing characters (? or N for DNA alignments) are treated in the same way as unknown characters, which represent no information.

https://evolution.genetics.washington.edu/phylip/doc/consense.html
Consense -- Consensus tree program

https://github.com/harry-thorpe/piggy
Piggy is a tool for analysing the intergenic component of bacterial genomes. It is designed to be used in conjunction with Roary (https://github.com/sanger-pathogens/Roary).

The output folder produced by Roary is required as an input to Piggy (specified by --roary_dir). 

https://github.com/AdmiralenOla/Scoary
Scoary is designed to take the gene_presence_absence.csv file from Roary 

LS-BSR input
You can also use as input the pan-genome as called from Jason Sahl's program LS-BSR (Large-Scale Blast Score Ratio).

**Comment by rpetit3** [comment]
I this is getting outside the scope of this issue, so I've opened https://github.com/bactopia/bactopia/issues/159 for these suggestions
