### ISSUE TITLE
[question] How much space is required for installation

### ISSUE THREAD

**Issue by uloeber** [bactopia/bactopia#101]
Hi,
I have problems getting bactopia to run and it seems that it's an installation issue?! I have more than 10GB free space in my home folder and am wondering whether this is not enough?
Thanks in advance
`bactopia --R1 RAW/20925_1_15.1.fastq.gz --R2 RAW/20925_1_15.2.fastq.gz --sample 20925_1_15 --dataset datasets/ --outdir testBACTOPIA
Unable to locate required Conda environments.
Building to /home/user/anaconda3/envs/bactopia//share/bactopia-1.3.1/conda/envs ... This might take a while
2020-04-22 18:12:28:root:INFO - Found /home/user/anaconda3/envs/bactopia/share/bactopia-1.3.1/conda/annotate_genome.yml (1 or 12), begin build to /home/user/anaconda3/envs/bactopia/share/bactopia-1.3.1/conda/envs/annotate_genome-1.3.1
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/bactopia/bin/bactopia-build.py", line 119, in <module>
    execute(f'conda env create -f {env_file} --prefix {prefix} {force}')
  File "/home/user/anaconda3/envs/bactopia/bin/bactopia-build.py", line 51, in execute
    command.start()
  File "/home/user/anaconda3/envs/bactopia/lib/python3.6/site-packages/executor/__init__.py", line 1441, in start
    self.start_once(**kw)
  File "/home/user/anaconda3/envs/bactopia/lib/python3.6/site-packages/executor/__init__.py", line 1508, in start_once
    self.wait(check=check)
  File "/home/user/anaconda3/envs/bactopia/lib/python3.6/site-packages/executor/__init__.py", line 1551, in wait
    self.check_errors(check=check)
  File "/home/user/anaconda3/envs/bactopia/lib/python3.6/site-packages/executor/__init__.py", line 1673, in check_errors
    raise self.error_type(self)
executor.ExternalCommandFailed: External command failed with exit code 1!

Command:
bash -c 'conda env create -f /home/user/anaconda3/envs/bactopia/share/bactopia-1.3.1/conda/annotate_genome.yml --prefix /home/user/anaconda3/envs/bactopia/share/bactopia-1.3.1/conda/envs/annotate_genome-1.3.1 --force'

Standard output:
EnvironmentSectionNotValid: The following section on '/home/user/anaconda3/envs/bactopia/share/bactopia-1.3.1/conda/annotate_genome.yml' is invalid and will be ignored:
 - version

Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Preparing transaction: ...working... done
Verifying transaction: ...working... failed

Standard error:
NoSpaceLeftError: No space left on devices.
N E X T F L O W  ~  version 20.01.0
Launching `/home/user/anaconda3/envs/bactopia/share/bactopia-1.3.1/main.nf` [focused_snyder] - revision: 636ad08e78
`

**Comment by rpetit3** [comment]
Hi @uloeber ,

Let's see of we can get this figured out. What's the output of `df -h`?

Thanks!

**Comment by uloeber** [comment]
Thanks for the quick reply
11G left on /home
Filesystem                             Size  Used Avail Use% Mounted on
/dev/mapper/VolGroup-lv_home            55G   45G   11G  82% /home

**Comment by rpetit3** [comment]
Looks like after all the environments are built its right at 11Gb. Although it seems weird that your's complained about out out space before the first environment was built. There are twelve that are built.

```
~/miniconda3/envs/bactopia-1.3.1$ du -h --max-depth 1
21M     ./resources
7.4G    ./pkgs
12K     ./var
336K    ./ssl
52K     ./x86_64-conda_cos6-linux-gnu
68K     ./qsci
572K    ./doc
24M     ./man
140K    ./conf
24K     ./shell
1.5M    ./libexec
16M     ./qml
320K    ./phrasebooks
100K    ./etc
14M     ./conda-meta
76M     ./jmods
792K    ./sbin
528K    ./legal
19M     ./plugins
8.0K    ./compiler_compat
26M     ./translations
146M    ./bin
81M     ./include
1.2G    ./lib
8.3M    ./opt
3.5M    ./mkspecs
2.1G    ./share
8.0K    ./condabin
11G     .
```

**Comment by uloeber** [comment]
After increasing free space on home:
`bactopia --R1 RAW/20925_1_15.1.fastq.gz --R2 RAW/20925_1_15.2.fastq.gz --sample 20925_1_15 --dataset datasets/ --outdir testBACTOPIA
Unable to locate required Conda environments.
Building to /home/user/anaconda3/envs/bactopia//share/bactopia-1.3.1/conda/envs ... This might take a while
2020-04-22 19:55:10:root:INFO - Found /home/user/anaconda3/envs/bactopia/share/bactopia-1.3.1/conda/annotate_genome.yml (1 or 12), begin build to /home/user/anaconda3/envs/bactopia/share/bactopia-1.3.1/conda/envs/annotate_genome-1.3.1
2020-04-22 19:56:13:root:INFO - Found /home/user/anaconda3/envs/bactopia/share/bactopia-1.3.1/conda/antimicrobial_resistance.yml (2 or 12), begin build to /home/user/anaconda3/envs/bactopia/share/bactopia-1.3.1/conda/envs/antimicrobial_resistance-1.3.1
2020-04-22 19:56:35:root:INFO - Found /home/user/anaconda3/envs/bactopia/share/bactopia-1.3.1/conda/ariba_analysis.yml (3 or 12), begin build to /home/user/anaconda3/envs/bactopia/share/bactopia-1.3.1/conda/envs/ariba_analysis-1.3.1
2020-04-22 19:57:17:root:INFO - Found /home/user/anaconda3/envs/bactopia/share/bactopia-1.3.1/conda/assemble_genome.yml (4 or 12), begin build to /home/user/anaconda3/envs/bactopia/share/bactopia-1.3.1/conda/envs/assemble_genome-1.3.1
2020-04-22 19:57:43:root:INFO - Found /home/user/anaconda3/envs/bactopia/share/bactopia-1.3.1/conda/call_variants.yml (5 or 12), begin build to /home/user/anaconda3/envs/bactopia/share/bactopia-1.3.1/conda/envs/call_variants-1.3.1
2020-04-22 19:58:30:root:INFO - Found /home/user/anaconda3/envs/bactopia/share/bactopia-1.3.1/conda/count_31mers.yml (6 or 12), begin build to /home/user/anaconda3/envs/bactopia/share/bactopia-1.3.1/conda/envs/count_31mers-1.3.1
2020-04-22 19:58:37:root:INFO - Found /home/user/anaconda3/envs/bactopia/share/bactopia-1.3.1/conda/download_references.yml (7 or 12), begin build to /home/user/anaconda3/envs/bactopia/share/bactopia-1.3.1/conda/envs/download_references-1.3.1
2020-04-22 19:58:55:root:INFO - Found /home/user/anaconda3/envs/bactopia/share/bactopia-1.3.1/conda/gather_fastqs.yml (8 or 12), begin build to /home/user/anaconda3/envs/bactopia/share/bactopia-1.3.1/conda/envs/gather_fastqs-1.3.1
2020-04-22 19:59:10:root:INFO - Found /home/user/anaconda3/envs/bactopia/share/bactopia-1.3.1/conda/insertion_sequences.yml (9 or 12), begin build to /home/user/anaconda3/envs/bactopia/share/bactopia-1.3.1/conda/envs/insertion_sequences-1.3.1
2020-04-22 19:59:33:root:INFO - Found /home/user/anaconda3/envs/bactopia/share/bactopia-1.3.1/conda/minmers.yml (10 or 12), begin build to /home/user/anaconda3/envs/bactopia/share/bactopia-1.3.1/conda/envs/minmers-1.3.1
2020-04-22 20:00:14:root:INFO - Found /home/user/anaconda3/envs/bactopia/share/bactopia-1.3.1/conda/qc_reads.yml (11 or 12), begin build to /home/user/anaconda3/envs/bactopia/share/bactopia-1.3.1/conda/envs/qc_reads-1.3.1
2020-04-22 20:00:28:root:INFO - Found /home/user/anaconda3/envs/bactopia/share/bactopia-1.3.1/conda/sequence_type.yml (12 or 12), begin build to /home/user/anaconda3/envs/bactopia/share/bactopia-1.3.1/conda/envs/sequence_type-1.3.1
N E X T F L O W  ~  version 20.01.0
Launching `/home/user/anaconda3/envs/bactopia/share/bactopia-1.3.1/main.nf` [sick_hoover] - revision: 636ad08e78
'--dataset' is not a known parameter
Cannot continue, please see --help for more information
`

**Comment by rpetit3** [comment]
Apologies, that's a typo in the docs. It should be `--datasets`

**Comment by uloeber** [comment]
It works. Thanks a lot!

**Comment by rpetit3** [comment]
Great! I'm glad to see its working for you. Please don't hesitate to reach out if you have any more questions.

**Comment by uloeber** [comment]
@rpetit3, you created an amazing pipeline. Applause

**Comment by rpetit3** [comment]
Thank you very much for your kind words! They are really motivating!

**Comment by uloeber** [comment]
Hi @rpetit3 , 
unfortunately I'm running into similar issues on a different system. It does not work with the fix as before. Can you please assist again?
`Unable to locate required Conda environments.
Building to /home/uloeber/anaconda3/envs/bactopia//share/bactopia-1.4.x/conda/envs ... This might take a while
2020-07-10 00:38:15:root:INFO - Found /home/uloeber/anaconda3/envs/bactopia/share/bactopia-1.4.x/conda/annotate_genome.yml (1 or 12), begin build to /home/uloeber/anaconda3/envs/bactopia/share/bactopia-1.4.x/conda/envs/annotate_genome-1.4.x
Traceback (most recent call last):
  File "/home/uloeber/anaconda3/envs/bactopia/bin/bactopia-build.py", line 121, in <module>
    execute(f'conda env create -f {env_file} --prefix {prefix} {force}')
  File "/home/uloeber/anaconda3/envs/bactopia/bin/bactopia-build.py", line 45, in execute
    from executor import ExternalCommand
ModuleNotFoundError: No module named 'executor'
N E X T F L O W  ~  version 20.04.1
Launching `/home/uloeber/anaconda3/envs/bactopia/share/bactopia-1.4.x/main.nf` [fervent_kimura] - revision: d84b68232b
bactopia - 1.4.0

Each task will use 4 CPUs out of the available 32 CPUs. At most 8 tasks will be run at 
once, this can affect the efficiency of Bactopia.

Found 2 ARIBA datasets
datasets/ariba/card.tar.gz
datasets/ariba/vfdb_core.tar.gz
Found 5 minmer sketches/signatures
datasets/minmer/genbank-k21.json.gz
datasets/minmer/genbank-k31.json.gz
datasets/minmer/genbank-k51.json.gz
datasets/minmer/refseq-k21-s1000.msh
datasets/plasmid/plsdb.msh
Found 3 PLSDB (plasmid) BLAST files
datasets/plasmid/plsdb.fna.nin
datasets/plasmid/plsdb.fna.nhr
datasets/plasmid/plsdb.fna.nsq
--species not given, skipping the following processes (analyses):
sequence_type
call_variants
primer_query
If something looks wrong, now's your chance to back out (CTRL+C 3 times).
Sleeping for 5 seconds...
[-        ] process > gather_fastqs                   -
[-        ] process > fastq_status                    -
[-        ] process > estimate_genome_size            -
[-        ] process > qc_reads                        -
[-        ] process > qc_original_summary             -
[-        ] process > qc_final_summary                -
[-        ] process > assemble_genome                 -
[-        ] process > assembly_qc                     -
[-        ] process > make_blastdb                    -
[-        ] process > annotate_genome                 -
[-        ] process > count_31mers                    -
[-        ] process > sequence_type                   -
[-        ] process > ariba_analysis                  -
[-        ] process > minmer_sketch                   -
[-        ] process > minmer_query                    -
[-        ] process > call_variants                   -
[-        ] process > download_references             -
[-        ] process > call_variants_auto              -
[-        ] process > update_antimicrobial_resistance -
[-        ] process > antimicrobial_resistance        -
[-        ] process > plasmid_blast                   -
[-        ] process > blast_genes                     -
[-        ] process > blast_primers                   -
[-        ] process > gather_fastqs                   -
[-        ] process > fastq_status                    -
[-        ] process > estimate_genome_size            -
[-        ] process > qc_reads                        -
[-        ] process > qc_original_summary             -
[-        ] process > qc_final_summary                -
[-        ] process > assemble_genome                 -
[-        ] process > assembly_qc                     -
[-        ] process > make_blastdb                    -
[-        ] process > annotate_genome                 -
[-        ] process > count_31mers                    -
[-        ] process > sequence_type                   -
[-        ] process > ariba_analysis                  -
[-        ] process > minmer_sketch                   -
[-        ] process > minmer_query                    -
[-        ] process > call_variants                   -
[-        ] process > download_references             -
[-        ] process > call_variants_auto              -
[-        ] process > update_antimicrobial_resistance -
[-        ] process > antimicrobial_resistance        -
[-        ] process > plasmid_blast                   -
[-        ] process > blast_genes                     -
[-        ] process > blast_primers                   -
[-        ] process > blast_proteins                  -
[-        ] process > mapping_query                   -
Error executing process > 'gather_fastqs (1)'

Caused by:
  Conda prefix path does not exist or it's not a directory: /home/uloeber/anaconda3/envs/bactopia/share/bactopia-1.4.x/conda/envs/gather_fastqs-1.4.x

`

**Comment by rpetit3** [comment]
Hi @uloeber ,

Let's get this figured out. 

This part, specifically the not finding `executor` stands out.
```
File "/home/uloeber/anaconda3/envs/bactopia/bin/bactopia-build.py", line 45, in execute from executor import ExternalCommand ModuleNotFoundError: No module named 'executor'
```

Just to make sure, what was the initial command used? I'm going to start the process locally to replicate.

**Comment by uloeber** [comment]
Hi @rpetit3 ,
:-)
`bactopia --R1 RAW/27098_8_8.1.fastq.gz --R2 RAW/27098_8_8.2.fastq.gz --sample 27098_8_8 --datasets datasets/ --outdir BACTOPIA`
Thanks for the quick reply!

**Comment by uloeber** [comment]
I couldn't see any conda issues before running:

conda update bactopia
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/uloeber/anaconda3/envs/bactopia

  added / updated specs:
    - bactopia


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    monotonic-1.5              |             py_0          17 KB
    python-dateutil-2.8.1      |             py_0         215 KB
    urllib3-1.25.9             |             py_0         103 KB
    ------------------------------------------------------------
                                           Total:         335 KB

The following NEW packages will be INSTALLED:

  blas               pkgs/main/linux-64::blas-1.0-mkl
  intel-openmp       pkgs/main/linux-64::intel-openmp-2019.4-243
  libgcc             pkgs/main/linux-64::libgcc-7.2.0-h69d50b8_2
  mkl                pkgs/main/linux-64::mkl-2019.4-243
  mkl-service        pkgs/main/linux-64::mkl-service-2.3.0-py36he904b0f_0
  mkl_fft            r/linux-64::mkl_fft-1.0.14-py36hd81dba3_0
  mkl_random         r/linux-64::mkl_random-1.0.4-py36hd81dba3_0
  numpy-base         r/linux-64::numpy-base-1.17.0-py36hde5b4d6_0
  openmp             conda-forge/linux-64::openmp-8.0.1-0

The following packages will be REMOVED:

  _openmp_mutex-4.5-1_llvm
  alsa-lib-1.1.5-h516909a_1002
  capnproto-0.6.1-hfc679d8_1
  fontconfig-2.13.1-h1056068_1002
  gettext-0.19.8.1-hc5be6a0_1002
  giflib-5.2.1-h516909a_2
  gsl-2.6-h294904e_0
  htslib-1.10.2-hd3b49d5_1
  jpeg-9d-h516909a_0
  lcms2-2.11-hbd6801e_0
  libblas-3.8.0-17_openblas
  libcblas-3.8.0-17_openblas
  libiconv-1.15-h516909a_1006
  libidn2-2.3.0-h516909a_0
  liblapack-3.8.0-17_openblas
  libopenblas-0.3.10-h5ec1e0e_0
  libtiff-4.1.0-hc7e4089_6
  libunistring-0.9.10-h14c3975_0
  libuuid-2.32.1-h14c3975_1000
  libwebp-base-1.1.0-h516909a_3
  libxcb-1.13-h14c3975_1002
  lz4-c-1.9.2-he1b5a44_1
  pthread-stubs-0.4-h14c3975_1001
  xorg-fixesproto-5.0-h14c3975_1002
  xorg-inputproto-2.3.2-h14c3975_1002
  xorg-kbproto-1.0.7-h14c3975_1002
  xorg-libx11-1.6.9-h516909a_0
  xorg-libxau-1.0.9-h14c3975_0
  xorg-libxdmcp-1.1.3-h516909a_0
  xorg-libxext-1.3.4-h516909a_0
  xorg-libxfixes-5.0.3-h516909a_1004
  xorg-libxi-1.7.10-h516909a_0
  xorg-libxrender-0.9.10-h516909a_1002
  xorg-libxtst-1.2.3-h516909a_1002
  xorg-recordproto-1.14.2-h516909a_1002
  xorg-renderproto-0.11.1-h14c3975_1002
  xorg-xextproto-7.3.0-h14c3975_1002
  xorg-xproto-7.0.31-h14c3975_1007
  zstd-1.4.4-h6597ccf_3

The following packages will be UPDATED:

  cd-hit                                   4.8.1-hdbcaa40_0 --> 4.8.1-h8b12597_3
  cffi               conda-forge::cffi-1.14.0-py36hd463f26~ --> pkgs/main::cffi-1.14.0-py36he30daa8_1
  conda-package-han~ conda-forge::conda-package-handling-1~ --> pkgs/main::conda-package-handling-1.6.1-py36h7b6447c_0
  fasteners              conda-forge::fasteners-0.14.1-py_3 --> pkgs/main::fasteners-0.15-py_0
  krb5                  conda-forge::krb5-1.17.1-hfafb76e_1 --> pkgs/main::krb5-1.18.2-h173b8e3_0
  libffi             conda-forge::libffi-3.2.1-he1b5a44_10~ --> pkgs/main::libffi-3.3-he6710b0_2
  libxslt            conda-forge::libxslt-1.1.33-h572872d_1 --> pkgs/main::libxslt-1.1.34-hc22bd24_0
  ncurses            conda-forge::ncurses-6.1-hf484d3e_1002 --> pkgs/main::ncurses-6.2-he6710b0_1
  ruamel_yaml        conda-forge::ruamel_yaml-0.15.80-py36~ --> pkgs/main::ruamel_yaml-0.15.87-py36h7b6447c_1
  spades                                           3.13.0-0 --> 3.14.0-h2d02072_0

The following packages will be SUPERSEDED by a higher-priority channel:

  _libgcc_mutex      conda-forge::_libgcc_mutex-0.1-conda_~ --> pkgs/main::_libgcc_mutex-0.1-main
  appdirs            conda-forge/noarch::appdirs-1.4.3-py_1 --> pkgs/main/linux-64::appdirs-1.4.3-py36h28b3542_0
  beautifulsoup4     conda-forge::beautifulsoup4-4.9.1-py3~ --> pkgs/main::beautifulsoup4-4.9.1-py36_0
  biopython          conda-forge::biopython-1.77-py36h8c4c~ --> pkgs/main::biopython-1.77-py36h7b6447c_0
  brotlipy           conda-forge::brotlipy-0.7.0-py36h8c4c~ --> pkgs/main::brotlipy-0.7.0-py36h7b6447c_1000
  bzip2                 conda-forge::bzip2-1.0.8-h516909a_2 --> pkgs/main::bzip2-1.0.8-h7b6447c_0
  chardet            conda-forge::chardet-3.0.4-py36h9f0ad~ --> pkgs/main::chardet-3.0.4-py36_1003
  coloredlogs        conda-forge::coloredlogs-14.0-py36h9f~ --> pkgs/main::coloredlogs-10.0-py36_0
  coreutils          conda-forge::coreutils-8.31-h516909a_0 --> bioconda::coreutils-8.25-1
  cryptography       conda-forge::cryptography-2.9.2-py36h~ --> pkgs/main::cryptography-2.9.2-py36h1ba5d50_0
  curl                  conda-forge::curl-7.71.1-he644dc0_0 --> pkgs/main::curl-7.71.0-hbc83047_0
  cycler             conda-forge/noarch::cycler-0.10.0-py_2 --> pkgs/main/linux-64::cycler-0.10.0-py36_0
  freetype           conda-forge::freetype-2.10.2-he06d7ca~ --> pkgs/main::freetype-2.10.2-h5ab3b9f_0
  humanfriendly      conda-forge::humanfriendly-8.2-py36h9~ --> pkgs/main::humanfriendly-8.2-py36_0
  icu                      conda-forge::icu-67.1-he1b5a44_0 --> pkgs/main::icu-58.2-he6710b0_3
  idna                  conda-forge::idna-2.10-pyh9f0ad1d_0 --> pkgs/main::idna-2.10-py_0
  kiwisolver         conda-forge::kiwisolver-1.2.0-py36hdb~ --> pkgs/main::kiwisolver-1.2.0-py36hfd86e86_0
  ld_impl_linux-64   conda-forge::ld_impl_linux-64-2.34-h5~ --> pkgs/main::ld_impl_linux-64-2.33.1-h53a641e_7
  libcurl            conda-forge::libcurl-7.71.1-hcdd3856_0 --> pkgs/main::libcurl-7.71.0-h20c2e04_0
  libdeflate         conda-forge::libdeflate-1.6-h516909a_0 --> bioconda::libdeflate-1.0-h14c3975_1
  libedit            conda-forge::libedit-3.1.20191231-h46~ --> pkgs/main::libedit-3.1.20191231-h7b6447c_0
  libgcc-ng          conda-forge::libgcc-ng-9.2.0-h24d8f2e~ --> pkgs/main::libgcc-ng-9.1.0-hdf63c60_0
  libgfortran-ng     conda-forge::libgfortran-ng-7.5.0-hdf~ --> pkgs/main::libgfortran-ng-7.3.0-hdf63c60_0
  libpng              conda-forge::libpng-1.6.37-hed695b0_1 --> pkgs/main::libpng-1.6.37-hbc83047_0
  libssh2             conda-forge::libssh2-1.9.0-hab1572f_3 --> pkgs/main::libssh2-1.9.0-h1ba5d50_1
  libstdcxx-ng       conda-forge::libstdcxx-ng-9.2.0-hdf63~ --> pkgs/main::libstdcxx-ng-9.1.0-hdf63c60_0
  libxml2            conda-forge::libxml2-2.9.10-h72b56ed_1 --> pkgs/main::libxml2-2.9.10-he19cac6_1
  lxml               conda-forge::lxml-4.5.2-py36h17c4326_0 --> pkgs/main::lxml-4.5.1-py36hefd8a0e_0
  matplotlib-base    conda-forge::matplotlib-base-3.2.2-py~ --> pkgs/main::matplotlib-base-3.2.2-py36hef1b27d_0
  monotonic                                     conda-forge --> pkgs/main
  numpy              conda-forge::numpy-1.18.5-py36h731479~ --> r::numpy-1.17.0-py36h7e9f1db_0
  openjdk            conda-forge::openjdk-11.0.1-h600c080_~ --> pkgs/main::openjdk-8.0.152-h7b6447c_3
  perl               conda-forge::perl-5.26.2-h516909a_1006 --> pkgs/main::perl-5.26.2-h14c3975_0
  pip                   conda-forge/noarch::pip-20.1.1-py_1 --> pkgs/main/linux-64::pip-20.1.1-py36_1
  pycosat            conda-forge::pycosat-0.6.3-py36h8c4c3~ --> pkgs/main::pycosat-0.6.3-py36h7b6447c_0
  pycparser          conda-forge::pycparser-2.20-pyh9f0ad1~ --> pkgs/main::pycparser-2.20-py_0
  pyopenssl          conda-forge/noarch::pyopenssl-19.1.0-~ --> pkgs/main/linux-64::pyopenssl-19.1.0-py36_0
  pyparsing          conda-forge::pyparsing-2.4.7-pyh9f0ad~ --> pkgs/main::pyparsing-2.4.7-py_0
  pysocks            conda-forge::pysocks-1.7.1-py36h9f0ad~ --> pkgs/main::pysocks-1.7.1-py36_0
  python             conda-forge::python-3.6.10-h8356626_1~ --> pkgs/main::python-3.6.10-h7579374_2
  python-dateutil                               conda-forge --> pkgs/main
  readline             conda-forge::readline-8.0-h46ee950_1 --> pkgs/main::readline-8.0-h7b6447c_0
  requests           conda-forge::requests-2.24.0-pyh9f0ad~ --> pkgs/main::requests-2.24.0-py_0
  setuptools         conda-forge::setuptools-49.1.0-py36h9~ --> pkgs/main::setuptools-47.3.1-py36_0
  six                  conda-forge::six-1.15.0-pyh9f0ad1d_0 --> pkgs/main::six-1.15.0-py_0
  soupsieve          conda-forge/linux-64::soupsieve-2.0.1~ --> pkgs/main/noarch::soupsieve-2.0.1-py_0
  sqlite              conda-forge::sqlite-3.32.3-hcee41ef_1 --> pkgs/main::sqlite-3.32.3-h62c20be_0
  tbb                    conda-forge::tbb-2020.1-hc9558a2_0 --> pkgs/main::tbb-2020.0-hfd86e86_0
  tk                      conda-forge::tk-8.6.10-hed695b0_0 --> pkgs/main::tk-8.6.10-hbc83047_0
  tornado            conda-forge::tornado-6.0.4-py36h8c4c3~ --> pkgs/main::tornado-6.0.4-py36h7b6447c_1
  tqdm               conda-forge/noarch::tqdm-4.47.0-pyh9f~ --> bioconda/linux-64::tqdm-4.7.2-py36_0
  unzip                   conda-forge::unzip-6.0-h516909a_1 --> pkgs/main::unzip-6.0-h611a1e1_0
  urllib3                                       conda-forge --> pkgs/main
  verboselogs        conda-forge/noarch::verboselogs-1.7-p~ --> pkgs/main/linux-64::verboselogs-1.7-py36_0
  wget                  conda-forge::wget-1.20.1-h22169c7_0 --> pkgs/main::wget-1.20.1-h20c2e04_0
  wheel               conda-forge/noarch::wheel-0.34.2-py_1 --> pkgs/main/linux-64::wheel-0.34.2-py36_0
  xz                       conda-forge::xz-5.2.5-h516909a_1 --> pkgs/main::xz-5.2.5-h7b6447c_0
  yaml                   conda-forge::yaml-0.2.5-h516909a_0 --> pkgs/main::yaml-0.2.5-h7b6447c_0
  zlib               conda-forge::zlib-1.2.11-h516909a_1006 --> pkgs/main::zlib-1.2.11-h7b6447c_3

The following packages will be DOWNGRADED:

  bcftools                                1.10.2-h4f4756c_1 --> 1.9-ha228f0b_4
  boost                               1.73.0-py36h6957fcd_0 --> 1.70.0-py36h9de70de_1
  boost-cpp                               1.73.0-h7b93d67_2 --> 1.70.0-ha2d47e9_1
  llvm-openmp                             10.0.0-hc9558a2_0 --> 8.0.1-hc9558a2_0
  mash                                     2.2.2-ha61e061_2 --> 1.1-0
  nextflow                               20.04.1-hecda079_1 --> 20.04.1-hecc5488_0
  pysam                             0.16.0.1-py36h71d3148_0 --> 0.15.3-py36hda2845c_1
  samtools                                  1.10-h9402c20_2 --> 1.7-1


Proceed ([y]/n)? y


Downloading and Extracting Packages
python-dateutil-2.8. | 215 KB    | ################################################################################################################################################### | 100% 
urllib3-1.25.9       | 103 KB    | ################################################################################################################################################### | 100% 
monotonic-1.5        | 17 KB     | ################################################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

**Comment by rpetit3** [comment]
What's `conda env export` look like? Just trying to make sure executor isn't missing

**Comment by uloeber** [comment]
name: bactopia
channels:
  - hcc
  - biocore
  - bioconda
  - r
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - appdirs=1.4.3=py36h28b3542_0
  - ariba=2.14.5=py36h831f99a_0
  - bactopia=1.4.0=0
  - bcftools=1.9=ha228f0b_4
  - beautifulsoup4=4.9.1=py36_0
  - biopython=1.77=py36h7b6447c_0
  - blas=1.0=mkl
  - blast=2.5.0=hc0b0e79_3
  - boost=1.70.0=py36h9de70de_1
  - boost-cpp=1.70.0=ha2d47e9_1
  - bowtie2=2.3.5.1=py36he513fc3_0
  - brotlipy=0.7.0=py36h7b6447c_1000
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2020.6.24=0
  - cd-hit=4.8.1=h8b12597_3
  - certifi=2020.6.20=py36_0
  - cffi=1.14.0=py36he30daa8_1
  - chardet=3.0.4=py36_1003
  - coloredlogs=10.0=py36_0
  - conda=4.8.3=py36h9f0ad1d_1
  - conda-package-handling=1.6.1=py36h7b6447c_0
  - coreutils=8.25=1
  - cryptography=2.9.2=py36h1ba5d50_0
  - curl=7.71.0=hbc83047_0
  - cycler=0.10.0=py36_0
  - dendropy=4.4.0=py_1
  - executor=23.1=pyh9f0ad1d_0
  - fasteners=0.15=py_0
  - freetype=2.10.2=h5ab3b9f_0
  - humanfriendly=8.2=py36_0
  - icu=58.2=he6710b0_3
  - idna=2.10=py_0
  - intel-openmp=2019.4=243
  - kiwisolver=1.2.0=py36hfd86e86_0
  - krb5=1.18.2=h173b8e3_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libcurl=7.71.0=h20c2e04_0
  - libdeflate=1.0=h14c3975_1
  - libedit=3.1.20191231=h7b6447c_0
  - libffi=3.3=he6710b0_2
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libxml2=2.9.10=he19cac6_1
  - libxslt=1.1.34=hc22bd24_0
  - llvm-openmp=8.0.1=hc9558a2_0
  - lxml=4.5.1=py36hefd8a0e_0
  - mash=1.1=0
  - matplotlib-base=3.2.2=py36hef1b27d_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.0.14=py36hd81dba3_0
  - mkl_random=1.0.4=py36hd81dba3_0
  - monotonic=1.5=py_0
  - mummer=3.23=pl526he1b5a44_11
  - ncbi-genome-download=0.3.0=pyh9f0ad1d_0
  - ncurses=6.2=he6710b0_1
  - nextflow=20.04.1=hecc5488_0
  - numpy=1.17.0=py36h7e9f1db_0
  - numpy-base=1.17.0=py36hde5b4d6_0
  - openjdk=8.0.152=h7b6447c_3
  - openmp=8.0.1=0
  - openssl=1.1.1g=h7b6447c_0
  - perl=5.26.2=h14c3975_0
  - pip=20.1.1=py36_1
  - property-manager=3.0=py_0
  - pycosat=0.6.3=py36h7b6447c_0
  - pycparser=2.20=py_0
  - pyfastaq=3.17.0=py_2
  - pymummer=0.10.3=py36_1
  - pyopenssl=19.1.0=py36_0
  - pyparsing=2.4.7=py_0
  - pysam=0.15.3=py36hda2845c_1
  - pysocks=1.7.1=py36_0
  - python=3.6.10=h7579374_2
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=py_0
  - ruamel_yaml=0.15.87=py36h7b6447c_1
  - samtools=1.7=1
  - setuptools=47.3.1=py36_0
  - six=1.15.0=py_0
  - soupsieve=2.0.1=py_0
  - spades=3.14.0=h2d02072_0
  - sqlite=3.32.3=h62c20be_0
  - tbb=2020.0=hfd86e86_0
  - tk=8.6.10=hbc83047_0
  - tornado=6.0.4=py36h7b6447c_1
  - tqdm=4.7.2=py36_0
  - unzip=6.0=h611a1e1_0
  - urllib3=1.25.9=py_0
  - verboselogs=1.7=py36_0
  - wget=1.20.1=h20c2e04_0
  - wheel=0.34.2=py36_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
prefix: /home/uloeber/anaconda3/envs/bactopia

**Comment by rpetit3** [comment]
Hmmm, that's a weird one executor is definitely there.

Let's check which Python3 is being used:
```
which python3
```

Should be: `/home/uloeber/anaconda3/envs/bactopia/bin/python3`

If so, let's try manually building:
```
bactopia build /home/uloeber/anaconda3/envs/bactopia/share/bactopia-1.4.x/conda/ /home/uloeber/anaconda3/envs/bactopia/share/bactopia-1.4.x/conda/envs/
```

**Comment by uloeber** [comment]
Very good, this might have been the error. Another package management system is preconfigured on our cluster. I'm removing python3 from it and try to rebuild my conda env.

**Comment by uloeber** [comment]
looks much better from the first sight. Thanks a lot for your support! :)

**Comment by rpetit3** [comment]
Great, glad we got it sorted for you! If you run into any other issues or have any feedback and/or suggestions let me know! 

Thank you very much for using Bactopia. I'm going to close this issue again for now.
