### ISSUE TITLE
[feature] include eggnog  mapper for additional functional annotation (optional)

### ISSUE THREAD

**Issue by uloeber** [bactopia/bactopia#104]
Hi,
what might be worth having a look at is eggnog mapper for functional annotation as well. 
https://github.com/eggnogdb/eggnog-mapper
I'm curious about your thoughts.

**Comment by rpetit3** [comment]
Hi @uloeber 

I looked into eggnog. Are you thinking of using this in place of Prokka or to supplement Prokka annotations?

I think it would be possible to tell Prokka to use the Eggnog HMM. Otherwise, I think this is a good candidate for another Bactopia Tool. This way the main analysis pipeline isn't affected and its makes eggnog completely optional.

There's a bioconda release, so I don't think it would be too hard to put together.

Let me know what you think!

Thanks for the great feedback!
Robert

**Comment by rpetit3** [comment]
Hi @uloeber 

Apologies for the delay, but I've implemented a Bactopia Tool for eggNOG-mapper (v2). It'll be in the next version update.

Quick question, what's an expected runtime for a bacterial sample (~2000 proteins)?

Thank you!

**Comment by uloeber** [comment]
Hi @rpetit3 ,
thank you for keeping me up to date. 
Here is what I got from my last run of samples:
 Processed queries:3633 total_time:958.96779418 rate:3.79 q/s
 Processed queries:1941 total_time:875.859928131 rate:2.22 q/s
 Processed queries:1835 total_time:951.074124098 rate:1.93 q/s
 Processed queries:1750 total_time:620.630259037 rate:2.82 q/s
 Processed queries:1882 total_time:1001.98185515 rate:1.88 q/s
 Processed queries:4661 total_time:1524.02245092 rate:3.06 q/s
 Processed queries:3454 total_time:1200.15618801 rate:2.88 q/s
 Processed queries:1941 total_time:931.33743 rate:2.08 q/s
 Processed queries:1969 total_time:912.801584959 rate:2.16 q/s
 Processed queries:1940 total_time:753.817185879 rate:2.57 q/s
 Processed queries:1819 total_time:467.657124996 rate:3.89 q/s
 Processed queries:2496 total_time:952.315118074 rate:2.62 q/s
 Processed queries:1968 total_time:825.682466984 rate:2.38 q/s
 Processed queries:1892 total_time:1154.62923908 rate:1.64 q/s
 Processed queries:1750 total_time:925.172072887 rate:1.89 q/s
 Processed queries:3211 total_time:910.087384939 rate:3.53 q/s
 Processed queries:1751 total_time:2108.90876889 rate:0.83 q/s
 Processed queries:2308 total_time:927.552855968 rate:2.49 q/s
 Processed queries:2475 total_time:1161.50809288 rate:2.13 q/s
 Processed queries:2494 total_time:1506.95839787 rate:1.65 q/s
 Processed queries:2231 total_time:1198.26991081 rate:1.86 q/s
 Processed queries:2168 total_time:564.561053038 rate:3.84 q/s
 Processed queries:1559 total_time:675.219319105 rate:2.31 q/s
 Processed queries:1565 total_time:940.113425016 rate:1.66 q/s
 Processed queries:1559 total_time:1116.49385214 rate:1.40 q/s
 Processed queries:1565 total_time:459.699044943 rate:3.40 q/s
 Processed queries:2068 total_time:1291.44445205 rate:1.60 q/s
 Processed queries:1690 total_time:1158.58580899 rate:1.46 q/s
 Processed queries:1565 total_time:2089.23439312 rate:0.75 q/s
 Processed queries:1862 total_time:1170.11898994 rate:1.59 q/s
 Processed queries:2011 total_time:1309.52168489 rate:1.54 q/s
 Processed queries:1917 total_time:1080.72847199 rate:1.77 q/s
 Processed queries:2108 total_time:562.757085085 rate:3.75 q/s
 Processed queries:1814 total_time:783.507149935 rate:2.32 q/s
 Processed queries:1569 total_time:1275.79091191 rate:1.23 q/s
 Processed queries:1912 total_time:637.786394835 rate:3.00 q/s
 Processed queries:1559 total_time:944.234228849 rate:1.65 q/s
 Processed queries:1987 total_time:917.851487875 rate:2.16 q/s
 Processed queries:1582 total_time:737.849381924 rate:2.14 q/s
 Processed queries:1720 total_time:641.292264223 rate:2.68 q/s
 Processed queries:1903 total_time:631.650002956 rate:3.01 q/s
 Processed queries:1912 total_time:527.268862963 rate:3.63 q/s
 Processed queries:1890 total_time:472.910640955 rate:4.00 q/s
 Processed queries:1799 total_time:379.487563848 rate:4.74 q/s
 Processed queries:1786 total_time:659.384313107 rate:2.71 q/s
 Processed queries:2031 total_time:748.38816905 rate:2.71 q/s
 Processed queries:1634 total_time:1188.09504008 rate:1.38 q/s
 Processed queries:2545 total_time:1068.43912697 rate:2.38 q/s
 Processed queries:2447 total_time:631.113639116 rate:3.88 q/s
 Processed queries:1997 total_time:643.060572863 rate:3.11 q/s
 Processed queries:2376 total_time:925.910331964 rate:2.57 q/s
 Processed queries:1982 total_time:1069.57249379 rate:1.85 q/s
 Processed queries:1824 total_time:1488.80679703 rate:1.23 q/s
 Processed queries:1507 total_time:1901.77254415 rate:0.79 q/s
 Processed queries:1952 total_time:539.676455021 rate:3.62 q/s
 Processed queries:1835 total_time:2948.76174808 rate:0.62 q/s
 Processed queries:1507 total_time:1770.99686813 rate:0.85 q/s
 Processed queries:1837 total_time:1622.90340996 rate:1.13 q/s
 Processed queries:2376 total_time:1973.56963801 rate:1.20 q/s
 Processed queries:1837 total_time:1461.20311999 rate:1.26 q/s
 Processed queries:1998 total_time:2935.00298214 rate:0.68 q/s
 Processed queries:2374 total_time:1035.897403 rate:2.29 q/s
 Processed queries:1825 total_time:1951.99921799 rate:0.93 q/s
 Processed queries:1999 total_time:1208.19380403 rate:1.65 q/s
 Processed queries:1562 total_time:2382.60885406 rate:0.66 q/s
 Processed queries:2020 total_time:412.337942123 rate:4.90 q/s
 Processed queries:1825 total_time:1755.48383403 rate:1.04 q/s
 Processed queries:1825 total_time:1247.92206311 rate:1.46 q/s
 Processed queries:2376 total_time:2344.10009408 rate:1.01 q/s
 Processed queries:2374 total_time:1771.15408397 rate:1.34 q/s
 Processed queries:1852 total_time:1569.30900407 rate:1.18 q/s
 Processed queries:1824 total_time:1221.83241296 rate:1.49 q/s
 Processed queries:2302 total_time:1329.8455689 rate:1.73 q/s
 Processed queries:1598 total_time:1157.71248388 rate:1.38 q/s
 Processed queries:1824 total_time:1115.76063395 rate:1.63 q/s
 Processed queries:2225 total_time:804.29672718 rate:2.77 q/s
 Processed queries:1927 total_time:349.715555906 rate:5.51 q/s
 Processed queries:1941 total_time:1447.23983097 rate:1.34 q/s
 Processed queries:1997 total_time:1997.27267694 rate:1.00 q/s
 Processed queries:1844 total_time:1633.21042013 rate:1.13 q/s
 Processed queries:2068 total_time:1315.290236 rate:1.57 q/s
 Processed queries:1569 total_time:1121.30935788 rate:1.40 q/s
 Processed queries:1659 total_time:901.396018028 rate:1.84 q/s
 Processed queries:1731 total_time:1211.69276786 rate:1.43 q/s
 Processed queries:1975 total_time:1163.08078814 rate:1.70 q/s
 Processed queries:1820 total_time:1488.52325487 rate:1.22 q/s
 Processed queries:1947 total_time:902.444690943 rate:2.16 q/s
 Processed queries:1542 total_time:414.452914 rate:3.72 q/s
 Processed queries:1883 total_time:1085.39254117 rate:1.73 q/s
 Processed queries:1821 total_time:1445.89260292 rate:1.26 q/s
 Processed queries:1946 total_time:1125.813936 rate:1.73 q/s
 Processed queries:1977 total_time:484.867748022 rate:4.08 q/s
 Processed queries:1581 total_time:1274.68493104 rate:1.24 q/s
 Processed queries:1820 total_time:861.57052803 rate:2.11 q/s
 Processed queries:1560 total_time:834.590283155 rate:1.87 q/s
 Processed queries:1714 total_time:1205.79236698 rate:1.42 q/s
 Processed queries:1980 total_time:776.747479916 rate:2.55 q/s
 Processed queries:2301 total_time:1038.29217219 rate:2.22 q/s
 Processed queries:1690 total_time:389.362707853 rate:4.34 q/s
 Processed queries:1739 total_time:1652.97284007 rate:1.05 q/s
 Processed queries:1609 total_time:740.851900101 rate:2.17 q/s
 Processed queries:1690 total_time:632.094240904 rate:2.67 q/s
 Processed queries:4835 total_time:942.481544018 rate:5.13 q/s
 Processed queries:2040 total_time:570.120666027 rate:3.58 q/s
 Processed queries:1960 total_time:636.596373081 rate:3.08 q/s
 Processed queries:1958 total_time:708.594856977 rate:2.76 q/s
 Processed queries:2135 total_time:1140.49252915 rate:1.87 q/s
 Processed queries:2113 total_time:653.501836061 rate:3.23 q/s
 Processed queries:2038 total_time:927.021914959 rate:2.20 q/s
 Processed queries:2087 total_time:480.812817097 rate:4.34 q/s
 Processed queries:1966 total_time:617.17937088 rate:3.19 q/s
 Processed queries:2110 total_time:1278.00214314 rate:1.65 q/s
 Processed queries:2251 total_time:1146.07931614 rate:1.96 q/s
 Processed queries:2252 total_time:1164.97205806 rate:1.93 q/s
 Processed queries:1913 total_time:821.589698076 rate:2.33 q/s
 Processed queries:2076 total_time:1216.87704587 rate:1.71 q/s
 Processed queries:1943 total_time:1212.38340878 rate:1.60 q/s
 Processed queries:4629 total_time:1436.73943901 rate:3.22 q/s
 Processed queries:3209 total_time:1620.49777412 rate:1.98 q/s
 Processed queries:1852 total_time:1356.96633601 rate:1.36 q/s
 Processed queries:1795 total_time:1175.06195903 rate:1.53 q/s
 Processed queries:2250 total_time:234.153446913 rate:9.61 q/s
 Processed queries:1817 total_time:1155.35340881 rate:1.57 q/s
 Processed queries:1948 total_time:530.762197971 rate:3.67 q/s
 Processed queries:1969 total_time:1105.48364592 rate:1.78 q/s
 Processed queries:1914 total_time:1082.639678 rate:1.77 q/s
 Processed queries:1854 total_time:637.906769991 rate:2.91 q/s
 Processed queries:1951 total_time:914.201346874 rate:2.13 q/s
 Processed queries:2264 total_time:1135.299788 rate:1.99 q/s
 Processed queries:1913 total_time:1242.38635993 rate:1.54 q/s
 Processed queries:1767 total_time:618.730213881 rate:2.86 q/s
 Processed queries:2297 total_time:1228.37790489 rate:1.87 q/s
 Processed queries:2738 total_time:641.332396984 rate:4.27 q/s
 Processed queries:1786 total_time:465.271759987 rate:3.84 q/s
 Processed queries:2265 total_time:931.693623066 rate:2.43 q/s
 Processed queries:3679 total_time:980.081918001 rate:3.75 q/s
 Processed queries:1809 total_time:970.92323494 rate:1.86 q/s
 Processed queries:1905 total_time:801.176617861 rate:2.38 q/s
 Processed queries:1565 total_time:389.041522026 rate:4.02 q/s
 Processed queries:1952 total_time:743.788609982 rate:2.62 q/s
 Processed queries:1811 total_time:1262.13530612 rate:1.43 q/s
 Processed queries:1823 total_time:967.225215912 rate:1.88 q/s
 Processed queries:1563 total_time:1084.79289913 rate:1.44 q/s
 Processed queries:1549 total_time:336.603491068 rate:4.60 q/s
 Processed queries:1583 total_time:688.124542952 rate:2.30 q/s
 Processed queries:1893 total_time:2115.01475811 rate:0.90 q/s
 Processed queries:1882 total_time:623.378090858 rate:3.02 q/s
 Processed queries:2043 total_time:2038.964746 rate:1.00 q/s
 Processed queries:1933 total_time:2067.79126191 rate:0.93 q/s
 Processed queries:1711 total_time:1334.02218986 rate:1.28 q/s
 Processed queries:1580 total_time:1784.66888094 rate:0.89 q/s
 Processed queries:1697 total_time:1330.47716093 rate:1.28 q/s
 Processed queries:1903 total_time:2267.52838397 rate:0.84 q/s
 Processed queries:1711 total_time:2660.17989588 rate:0.64 q/s
 Processed queries:2004 total_time:568.794620037 rate:3.52 q/s
 Processed queries:2242 total_time:662.952257872 rate:3.38 q/s
 Processed queries:1923 total_time:2659.10313296 rate:0.72 q/s
 Processed queries:1864 total_time:2574.57917309 rate:0.72 q/s
 Processed queries:1866 total_time:1145.73818398 rate:1.63 q/s
 Processed queries:1860 total_time:2703.14448714 rate:0.69 q/s
 Processed queries:1860 total_time:2966.90848398 rate:0.63 q/s
 Processed queries:1860 total_time:2046.689955 rate:0.91 q/s
 Processed queries:1969 total_time:1161.25642204 rate:1.70 q/s
 Processed queries:1822 total_time:2577.00812602 rate:0.71 q/s
 Processed queries:1803 total_time:1489.41417384 rate:1.21 q/s
 Processed queries:1969 total_time:377.484508991 rate:5.22 q/s
 Processed queries:1409 total_time:1607.11938906 rate:0.88 q/s
 Processed queries:1763 total_time:2178.1562171 rate:0.81 q/s
 Processed queries:1933 total_time:1619.41791606 rate:1.19 q/s
 Processed queries:1860 total_time:1647.16213083 rate:1.13 q/s
 Processed queries:1860 total_time:1502.05410385 rate:1.24 q/s
 Processed queries:1854 total_time:889.757500887 rate:2.08 q/s
 Processed queries:1860 total_time:1396.64577699 rate:1.33 q/s
 Processed queries:1851 total_time:1302.80482101 rate:1.42 q/s
 Processed queries:1914 total_time:522.840394974 rate:3.66 q/s
 Processed queries:2139 total_time:576.964566946 rate:3.71 q/s
 Processed queries:1968 total_time:515.35217309 rate:3.82 q/s
 Processed queries:2106 total_time:684.572808027 rate:3.08 q/s
 Processed queries:1551 total_time:557.108350992 rate:2.78 q/s
 Processed queries:1974 total_time:332.444561005 rate:5.94 q/s
 Processed queries:2731 total_time:868.639150858 rate:3.14 q/s
 Processed queries:2021 total_time:356.790230036 rate:5.66 q/s
 Processed queries:1596 total_time:466.183035851 rate:3.42 q/s
 Processed queries:1549 total_time:589.150379181 rate:2.63 q/s
 Processed queries:2101 total_time:447.949342966 rate:4.69 q/s
 Processed queries:1820 total_time:547.249135017 rate:3.33 q/s
 Processed queries:1552 total_time:519.132328987 rate:2.99 q/s
 Processed queries:1546 total_time:668.692013979 rate:2.31 q/s
 Processed queries:2259 total_time:1051.012115 rate:2.15 q/s
 Processed queries:1716 total_time:669.995389938 rate:2.56 q/s
 Processed queries:1886 total_time:290.911733866 rate:6.48 q/s
 Processed queries:2108 total_time:731.457566023 rate:2.88 q/s
 Processed queries:2137 total_time:570.046107054 rate:3.75 q/s
 Processed queries:1820 total_time:735.577544928 rate:2.47 q/s
 Processed queries:2135 total_time:561.115421057 rate:3.80 q/s
 Processed queries:1912 total_time:718.109965086 rate:2.66 q/s
 Processed queries:1966 total_time:1014.29379106 rate:1.94 q/s
 Processed queries:1691 total_time:734.626654863 rate:2.30 q/s
 Processed queries:2207 total_time:511.975801945 rate:4.31 q/s
 Processed queries:2109 total_time:557.535399914 rate:3.78 q/s
 Processed queries:2121 total_time:705.150099039 rate:3.01 q/s
 Processed queries:1977 total_time:462.149107218 rate:4.28 q/s
 Processed queries:2286 total_time:724.425276995 rate:3.16 q/s
 Processed queries:2345 total_time:860.525316 rate:2.73 q/s
 Processed queries:3571 total_time:803.252173901 rate:4.45 q/s
 Processed queries:1610 total_time:667.825870037 rate:2.41 q/s
 Processed queries:1591 total_time:1431.32439184 rate:1.11 q/s
 Processed queries:2107 total_time:690.736675978 rate:3.05 q/s
 Processed queries:2089 total_time:781.660171032 rate:2.67 q/s
 Processed queries:1730 total_time:562.92149806 rate:3.07 q/s
 Processed queries:1913 total_time:766.169689894 rate:2.50 q/s
 Processed queries:1937 total_time:624.898345947 rate:3.10 q/s
 Processed queries:1842 total_time:500.849140167 rate:3.68 q/s
 Processed queries:1911 total_time:776.56876111 rate:2.46 q/s
 Processed queries:2105 total_time:1085.27507997 rate:1.94 q/s
 Processed queries:1913 total_time:1079.41434002 rate:1.77 q/s
 Processed queries:1913 total_time:827.785997152 rate:2.31 q/s
 Processed queries:1690 total_time:669.483870029 rate:2.52 q/s
 Processed queries:1885 total_time:639.800417185 rate:2.95 q/s
 Processed queries:3538 total_time:524.058799028 rate:6.75 q/s
 Processed queries:1687 total_time:428.359344959 rate:3.94 q/s
 Processed queries:1689 total_time:667.046051979 rate:2.53 q/s
 Processed queries:2277 total_time:452.738356113 rate:5.03 q/s
 Processed queries:2252 total_time:370.139463902 rate:6.08 q/s
 Processed queries:2319 total_time:749.937808037 rate:3.09 q/s
 Processed queries:2322 total_time:639.660853148 rate:3.63 q/s
 Processed queries:1656 total_time:1002.65833306 rate:1.65 q/s
 Processed queries:1610 total_time:545.738795996 rate:2.95 q/s
 Processed queries:1551 total_time:590.050743103 rate:2.63 q/s
 Processed queries:1924 total_time:660.80189395 rate:2.91 q/s
 Processed queries:2112 total_time:1235.24265385 rate:1.71 q/s
 Processed queries:2179 total_time:840.976106882 rate:2.59 q/s
 Processed queries:1912 total_time:319.504194021 rate:5.98 q/s
 Processed queries:1660 total_time:707.335290909 rate:2.35 q/s
 Processed queries:1968 total_time:417.957333803 rate:4.71 q/s
 Processed queries:1545 total_time:717.028908014 rate:2.15 q/s
 Processed queries:2176 total_time:490.923202038 rate:4.43 q/s
 Processed queries:1973 total_time:745.623505116 rate:2.65 q/s
 Processed queries:2299 total_time:909.009636879 rate:2.53 q/s
 Processed queries:2006 total_time:851.03372407 rate:2.36 q/s
 Processed queries:1733 total_time:991.245431185 rate:1.75 q/s
 Processed queries:1859 total_time:611.583070993 rate:3.04 q/s
 Processed queries:1969 total_time:980.456767082 rate:2.01 q/s
 Processed queries:1636 total_time:611.294009924 rate:2.68 q/s
 Processed queries:1594 total_time:1170.04019403 rate:1.36 q/s
 Processed queries:1887 total_time:460.753427029 rate:4.10 q/s
 Processed queries:1881 total_time:905.631083012 rate:2.08 q/s
 Processed queries:2009 total_time:1001.99958992 rate:2.00 q/s
 Processed queries:1715 total_time:772.966377974 rate:2.22 q/s
 Processed queries:1886 total_time:697.629690886 rate:2.70 q/s
 Processed queries:1822 total_time:914.54963398 rate:1.99 q/s
 Processed queries:1763 total_time:1106.99605107 rate:1.59 q/s
 Processed queries:2072 total_time:919.991645098 rate:2.25 q/s
 Processed queries:1847 total_time:731.815934181 rate:2.52 q/s
 Processed queries:1970 total_time:1237.30094504 rate:1.59 q/s
 Processed queries:2139 total_time:828.720300913 rate:2.58 q/s
 Processed queries:1693 total_time:471.826056004 rate:3.59 q/s

Hope this helps!

**Comment by rpetit3** [comment]
This is perfect! I had the `--target_taxa` turned on in the Bactopia tool and it was taking forever (8+ hours). But after a removing that, I got numbers similar to yours. 

Haha, I haven't used eggNOG-mapper before and suspected my runtime was due to user error (turns out it was!). This info helped confirm it as well.

I have a few more things I'm working on adding, but hopefully a new release soon.

**Comment by rpetit3** [comment]
Hi @uloeber 

I've released a new version of Bactopia (https://github.com/bactopia/bactopia/releases/tag/v1.4.0) which now includes eggNOG-mapper as a Bactopia Tool.

Thank you very much for your suggestion and comments. Let me know if you run into any issues, or would like more tools! 

Going to close this. Thanks again!
