### ISSUE TITLE
[feature] Bactopia Tool - WhatsGNU

### ISSUE THREAD

**Issue by rpetit3** [bactopia/bactopia#111]
**Related To**

- [ ] Bactopia
- [X] Bactopia Tools

**Is this something you would like to see added?**
A bactopia tool for [WhatsGNU](https://github.com/ahmedmagds/WhatsGNU)

**Describe the solution you'd like**
Should allow users to provide their own database, build one from completed genomes, or user their samples to build one.

**Additional Information**
Tagging @ahmedmagds

**Comment by ahmedmagds** [comment]
@rpetit3 This is a great.
I believe it would be a mix of all of that. There are databases available already for all GenBank genomes of K. pneumoniae, S. enterica, S. aureus, M. tuberculosis and P. aeruginosa. The user can download them or this could be a part of Bactopia workflow. However, the user may like to build one from a specific collection or for a species that is not yet covered.

**Comment by rpetit3** [comment]
Are the links to the pre-built databases relatively static?

Are there plans to integrate auto download into WhatsGNU? (e.g. `whatsgnu_db_download k_pneumo`, `whatsgnu_db_download saureus`, something similar).

**Comment by ahmedmagds** [comment]
Yes They were previously kept on dropbox but they are on Zenodo too. I totally agree that the automated download is a needed step. I will work on that.

**Comment by ahmedmagds** [comment]
@rpetit3 Sorry for being late for adding this feature but been very busy with SARS-CoV-2.

**Comment by rpetit3** [comment]
No worries, that's just a bot. I'll remove the tale label and it will stay open

**Comment by kusandeep** [comment]
Looking forward to try this with bactopia.

**Comment by ahmedmagds** [comment]
@rpetit3 been a long time but I am currently working on the download script and we should discuss soon.
