### ISSUE TITLE
log of software + versions [question]

### ISSUE THREAD

**Issue by uloeber** [bactopia/bactopia#114]
Dear @rpetit3 ,
I'd like to submit one of our bactopia assembled and annotated genomes. From the docs I saw that SKESA is the default assembler. Is there any logfile produced by bactopia which keeps track of the software used and their versions? I could not find that info in bactopia-info/, but maybe I missed that. I even cannot call SKESA from my bactopia environment.
Thanks in advance!
Cheers,
Ulrike

**Comment by rpetit3** [comment]
There's `bactopia versions` that will list all the programs and versions that could have been used by Bactopia. You could get the SKESA version from that.

But, I've been wanting something similar (a file in bactopia-info/ that lists program version for that run). I'll get it into the next version.

**Comment by uloeber** [comment]
Cool thing. Thanks!

**Comment by uloeber** [comment]
Oh, something is wrong here with my bactopia environment?
` 
bactopia versions
usage: bactopia versions [-h] [--bactopia STR] [--version]

bactopia versions (v1.4.0) - Prints the version of tools used by Bactopia

optional arguments:
  -h, --help      show this help message and exit
  --bactopia STR  Directory where Bactopia repository is stored.
  --version       show program's version number and exit

bactopia --versions
N E X T F L O W  ~  version 20.04.1
Launching `/home/uloeber/anaconda3/envs/bactopia/share/bactopia-1.4.x/main.nf` [scruffy_bassi] - revision: d84b68232b
'--versions' is not a known parameter
One or more required parameters are missing, please check and try again.

Required Parameters:
    ### For Procesessing Multiple Samples
    --fastqs STR            An input file containing the sample name and
                                absolute paths to FASTQ/FASTAs to process

    ### For Processing A Single Sample
    --R1 STR                First set of reads for paired end in compressed (gzip)
                                FASTQ format

    --R2 STR                Second set of reads for paired end in compressed (gzip)
                                FASTQ format

    --SE STR                Single end set of reads in compressed (gzip) FASTQ format

    --hybrid                The SE should be treated as long reads for hybrid assembly.

    --sample STR            The name of the input sequences

    ### For Downloading from SRA/ENA or NCBI Assembly
    **Note: Assemblies will have error free Illumina reads simulated for processing.**
    --accessions            An input file containing ENA/SRA Experiment accessions or 
                                NCBI Assembly accessions to be processed

    --accession             A single ENA/SRA Experiment accession or NCBI Assembly accession 
                                to be processed

    ### For Processing an Assembly
    **Note: The assembly will have error free Illumina reads simulated for processing.**
    --assembly STR          A assembled genome in compressed FASTA format.
Cannot continue, please see --help for more information
`

**Comment by rpetit3** [comment]
Bah! Looks like I broke that on the 1.4.0 version. (haha will fix!)

For the time being, here's info on which SKESA version was used (v1.4.0+): https://github.com/bactopia/bactopia/blob/master/conda/assemble_genome.yml#L147

I also looked at v1.3.0 and 1.3.1 and they too used SKESA 2.3.0

**Comment by rpetit3** [comment]
Submitted fix for `bactopia versions` here: https://github.com/bactopia/bactopia/commit/bb310ea4b1ffcc420f694332dfb89dc1e0ba97d7

Looking into a "per-run" summary file now

**Comment by rpetit3** [comment]
Update!

Program versions are now captured for bioinformatic tools (I ignored unix commands (mv, cp, gzip, etc..)) directly executed by Bactopia. What this means is for example Prokka, I only capture the version of Prokka. I don't capture the version of tbl2asn, which Prokka executes internally. 

Each process (`assembled_genome`. `qc_reads`, etc) will have a `${PROCESS_NAME}.versions` file that looks something like this:

`qc_reads`
```
# BBMap (bbduk.sh, reformat.sh) Version
BBMap version 38.86
# Lighter Version
Lighter v1.1.2
# fastq-scan Version
fastq-scan 0.4.1

```

`assemble_genome`
```
# shovill Version
shovill 1.1.0
[shovill] Using bwa - /local/home/rpetit/miniconda3/envs/bactopia/share/bactopia-1.4.x/conda/envs/assemble_genome-1.4.x/bin/bwa | Version: 0.7.17-r1188
[shovill] Using flash - /local/home/rpetit/miniconda3/envs/bactopia/share/bactopia-1.4.x/conda/envs/assemble_genome-1.4.x/bin/flash | FLASH v1.2.11
[shovill] Using java - /local/home/rpetit/miniconda3/envs/bactopia/share/bactopia-1.4.x/conda/envs/assemble_genome-1.4.x/bin/java | openjdk version "11.0.1-internal" 2018-10-16
[shovill] Using kmc - /local/home/rpetit/miniconda3/envs/bactopia/share/bactopia-1.4.x/conda/envs/assemble_genome-1.4.x/bin/kmc | K-Mer Counter (KMC) ver. 3.1.1 (2019-05-19)
[shovill] Using lighter - /local/home/rpetit/miniconda3/envs/bactopia/share/bactopia-1.4.x/conda/envs/assemble_genome-1.4.x/bin/lighter | Lighter v1.1.2
[shovill] Using megahit - /local/home/rpetit/miniconda3/envs/bactopia/share/bactopia-1.4.x/conda/envs/assemble_genome-1.4.x/bin/megahit | MEGAHIT v1.2.9
[shovill] Using megahit_toolkit - /local/home/rpetit/miniconda3/envs/bactopia/share/bactopia-1.4.x/conda/envs/assemble_genome-1.4.x/bin/megahit_toolkit | v1.2.9
[shovill] Using pigz - /local/home/rpetit/miniconda3/envs/bactopia/share/bactopia-1.4.x/conda/envs/assemble_genome-1.4.x/bin/pigz | pigz 2.3.4
[shovill] Using pilon - /local/home/rpetit/miniconda3/envs/bactopia/share/bactopia-1.4.x/conda/envs/assemble_genome-1.4.x/bin/pilon | Pilon version 1.23 Mon Nov 26 16:04:05 2018 -0500
[shovill] Using samclip - /local/home/rpetit/miniconda3/envs/bactopia/share/bactopia-1.4.x/conda/envs/assemble_genome-1.4.x/bin/samclip | samclip 0.4.0
[shovill] Using samtools - /local/home/rpetit/miniconda3/envs/bactopia/share/bactopia-1.4.x/conda/envs/assemble_genome-1.4.x/bin/samtools | Version: 1.10 (using htslib 1.10.2)
[shovill] Using seqtk - /local/home/rpetit/miniconda3/envs/bactopia/share/bactopia-1.4.x/conda/envs/assemble_genome-1.4.x/bin/seqtk | Version: 1.3-r106
[shovill] Using skesa - /local/home/rpetit/miniconda3/envs/bactopia/share/bactopia-1.4.x/conda/envs/assemble_genome-1.4.x/bin/skesa | SKESA v.2.3.0
[shovill] Using spades.py - /local/home/rpetit/miniconda3/envs/bactopia/share/bactopia-1.4.x/conda/envs/assemble_genome-1.4.x/bin/spades.py | SPAdes genome assembler v3.14.0
[shovill] Using trimmomatic - /local/home/rpetit/miniconda3/envs/bactopia/share/bactopia-1.4.x/conda/envs/assemble_genome-1.4.x/bin/trimmomatic | 0.39
[shovill] Using velvetg - /local/home/rpetit/miniconda3/envs/bactopia/share/bactopia-1.4.x/conda/envs/assemble_genome-1.4.x/bin/velvetg | Version 1.2.10
[shovill] Using velveth - /local/home/rpetit/miniconda3/envs/bactopia/share/bactopia-1.4.x/conda/envs/assemble_genome-1.4.x/bin/velveth | Version 1.2.10
# SKESA Version (this assembler was used)
SKESA v.2.3.0

```

`annotate_genome`
```
# Prokka Version
prokka 1.14.6

```

When you have a moment, it would be great to get your thoughts.

Thanks again for your feed back, it has been super helpful!

**Comment by uloeber** [comment]
Dear @rpetit3 ,
this looks very good. Thanks for adding this. Will it automatically be stored in a log file or is it only printed upon request. I would guess the first option, including printing a timestamp and the command would be best for tracking. E.g. you never know if someone updates bactopia after execution, is getting back to manuscript wrinting and cannot recap which version was used.
Best,
Ulrike

**Comment by rpetit3** [comment]
It is automatically created, and if not wanted there's a `--skip_logs` parameter.

Good idea on the timestamp! I'll get that added

**Comment by rpetit3** [comment]
All right added a timestamp to the versions files. One thing I forgot though is a file containing the Bactopia version (I'll get it added).

Example for annotations
```
# Timestamp
2020-08-24T23:53:36-04:00
# Prokka Version
prokka 1.14.6
```

**Comment by rpetit3** [comment]
It's been a little while, but I think I'm done with this one. I've added a log of the Bactopia version as well as Nextflow version used at runtime (see: https://github.com/bactopia/bactopia/commit/aa903fbbfaba6cc1e60162cc14fe0110b23eb151). This will be in the next version (v1.5.0) which will hopefully be out soon.

**Comment by rpetit3** [comment]
@uloeber  v1.5.0 is now available on Bioconda, so I am going to close this for now. Please feel free to reopen. Thank you very much for your feedback and suggestions!
