### ISSUE TITLE
[bug] FASTQ Minimum Requirements Parameters not being honored?

### ISSUE THREAD

**Issue by tanaes** [bactopia/bactopia#115]
**Description**
I'm trying out an initial run on a self-generated Illumina isolate genome dataset. The pipeline quickly breaks, with the error message:

```
Error executing process > 'annotate_genome (11522_11845_115462_H3HCVAFX2_7_TCTAGGAG_GAATGCGA)'

Caused by:
  Process `annotate_genome` input file name collision -- There are multiple input files for each of the following file names: EMPTY


Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
```

Upon inspection, that file started out with very few reads -- 2091, fewer than the listed default minimum. Attempting to re-run with an explicitly set minimum total length yields the same error:

```
bactopia --fastqs 20200218_HackFlex_test.in --datasets /workdir/dbs/bactopia/datasets/ --cpus 4  --min_basepairs 10000000
```

**Steps to Reproduce**

Calling in single sample mode gives the same error:

```
bactopia --R1 11522_11845_115462_H3HCVAFX2_7_TCTAGGAG_GAATGCGA_R1.fastq.gz --R2 11522_11845_115462_H3HCVAFX2_7_TCTAGGAG_GAATGCGA_R2.fastq.gz --sample test  --datasets /workdir/dbs/bactopia/datasets/ --cpus 4  --min_basepairs 10000000
```

**Expected Behavior**

The sample should fail validation and not continue through the pipeline.

**Execution Environment**

- Bactopia Version: 1.4.2
- OS: CentOS 7.6.1810
- Environment: single cluster node, 64 cores, 512GB RAM

**Additional Information**

**Comment by rpetit3** [comment]
Beat me to it! Looking into it, I think there's been a change between Nextflow versions. Will have a fix soon

tagging @tauqeer9

**Comment by tanaes** [comment]
I am relentless. 😅 Thanks! Sadly all my workflow experience is with Snakemake, so I'm not going to be of much help for a bit. But looking forward to contributing down the road!

**Comment by rpetit3** [comment]
No, this is great (haha no issues would be ideal)! Looking forward to your contributions!

**Comment by rpetit3** [comment]
Nope, dev error on this one! I itroduced the error when I added support for prodigal training files (https://github.com/bactopia/bactopia/commit/4b8968628546617cc7c299cca2b360967300d5cd) (two 'EMPTY' files)

Testing fix now, and will likely submit fix shortly

**Comment by rpetit3** [comment]
This is fixed (https://github.com/bactopia/bactopia/commit/c5677f2f6d646c4b00b127d0057ed202b46a803f) and will be in next version. Hoping to fix another issue related to SRA accessions, which was just added to Bioconda.

**Comment by rpetit3** [comment]
Submitted release [v1.4.4](https://github.com/bactopia/bactopia/releases/tag/v1.4.4) that should fix this issue. 

Will hopefully be synced to Bioconda soon. Looking forward to the next bonehead mistake you find! (haha hopefully smooth sailing for you now!)

**Comment by rpetit3** [comment]
Fixed one, forgot the other. `--min_basepairs` and `--min_reads` works again (https://github.com/bactopia/bactopia/commit/67bf0ee2aff161b8c3d79f042835a5b499b522d3)

Was broken when the fix related to https://github.com/bactopia/bactopia/issues/107 was implemented.

**Comment by rpetit3** [comment]
Alright! v1.4.5 should be on Bioconda soon

**Comment by tanaes** [comment]
Awesome, thanks! Will have an opportunity to test later today.

**Comment by tanaes** [comment]
It's working now, thanks!
