### ISSUE TITLE
[question] Limiting total resource use?

### ISSUE THREAD

**Issue by tanaes** [bactopia/bactopia#123]
Is there any way to constrain the *total* resource use of the Nextflow pipeline? I see that the `--cpus` option constrains *individual* steps, but I'm executing in a shared cluster node environment, and would like to limit the total pipeline to, say, 32 cores.

**Comment by rpetit3** [comment]
Does the cluster have one of these (https://www.nextflow.io/docs/latest/executor.html) queue systems?

**Comment by tanaes** [comment]
It's actually a lab-owned (and shared internally) node within the cluster, so we don't have any sort of job manager at the moment. Although we may institute one later, it currently relies on our handful of lab members managing ourselves.

**Comment by rpetit3** [comment]
Ah. So as you probably saw pretty quickly Nextflow uses all available cores. There used to be a parameter to set a maximum number processors in a script, but it was removed.

One thing that might be worth trying is playing with Nextflow's queue size parameter

```
    -qs, -queue-size
       Max number of processes that can be executed in parallel by each executor
```

I read that as: If `--cpus 4` then `-qs 8` should keep it under 32 cores at maximum. I'm testing it locally to see if does keep things under 32 cores.

**Comment by tanaes** [comment]
This works great, thanks!
