### ISSUE TITLE
[bug] --locustag with long sample name in prokka call breaks job

### ISSUE THREAD

**Issue by tanaes** [bactopia/bactopia#124]
**Description**

Tracked down my error with `annotate-genome`: it turns out that my long sample names were causing Prokka to error out with the following:

```
  [10:48:44] Contig ID must <= 37 chars long: gnl|Bactopia|11522_11845_115462_H3HCVAFX2_WC-19_CAGAACTG_TGGTTCGA_1
  [10:48:44] Please rename your contigs OR try '--centre X --compliant' to generate clean contig names.
```

Happily, I found that the `--centre` and `--compliant` flags are exposed in Bactopia, and gave it another go. But it still crashed, with the same result. 

In digging around the `./work` directory, though, I was unable to unearth an actual call to Prokka, which looks like: 

```
Command: /home/jgs286/miniconda3/envs/bactopia/share/bactopia-1.4.x/conda/envs/annotate_genome-1.4.x/bin/prokka --outdir annotation --force --prefix 11522_11845_115462_H3HCVAFX2_8_TTGCAACG_GAATGCGA --locustag 11522_11845_115462_H3HCVAFX2_8_TTGCAACG_GAATGCGA --genus Genus --species species --evalue 1e-09 --coverage 80 --cpus 4 --centre Bactopia --mincontiglen 500 --addgenes --compliant 11522_11845_115462_H3HCVAFX2_8_TTGCAACG_GAATGCGA.fna
```

It turns out that the `--locustag` with the long sample name is sufficient to produce the failure, even with the `--centre X `compliant` flags enabled; it seems as if this overrides the other behavior.

**Steps to Reproduce**

Execute with sample name >37 characters.

**Expected Behavior**

Prokka renames contigs appropriately with compliant sample names and completes successfully.

**Execution Environment**

- Bactopia Version: 1.4.5
- OS: CentOS 7
- Environment: hosted server

**Additional Information**

If contig names aren't necessary for downstream use, I've tested that simply removing the `--locustag` is sufficient to complete successfully, even without `--compliant`:

```

prokka --outdir annotation-nocentre --force --prefix 11522_11845_115462_H3HCVAFX2_8_TTGCAACG_GAATGCGA --genus Genus --species species --evalue 1e-09 --coverage 80 --cpus 4 --mincontiglen 500 --addgenes 11522_11845_115462_H3HCVAFX2_8_TTGCAACG_GAATGCGA.fna
```

finishes succesfully.

**Comment by rpetit3** [comment]
Thank you for all the digging into this. I'll get this sorted out and into the next version

**Comment by rpetit3** [comment]
Alright, added a fix for this (https://github.com/bactopia/bactopia/commit/cb5d1e1d1d52bd0e29afe08149e35c1617f02374)

Basically if the sample name is >37 characters `--locustag` will not be used and `--compliant` will be turned on so that Prokka can rename the entries.


Using the sample name above (11522_11845_115462_H3HCVAFX2_8_TTGCAACG_GAATGCGA) it becomes something like this:
```
>PKMMFHHE_00001 Serine-aspartate repeat-containing protein E
```

Will be in the next version

**Comment by tanaes** [comment]
It looks like it needs to be even stricter. I tried shortening my sample names, and got this:

```
 Contig ID must <= 37 chars long: gnl|Bactopia|Ec_10_Tak_100ng_noT_b_100
```

That works out to be 39 characters, including the `gnl|Bactopia|`. So I think the logic would have to be `if(len(centre_name) + 5 + len(sample_name) + len(str(num_contigs + 1)) > 37`.

**Comment by rpetit3** [comment]
Bah! You're right I updated to this `"gnl|${params.centre}|${sample}".length()` but forgot the total contigs. Thanks for catching that!

**Comment by rpetit3** [comment]
Alright, I think we're good now (https://github.com/bactopia/bactopia/commit/ebd3f0dc33d1efa0db765a33067a93bba26b1571) 

`"gnl|${params.centre}|${sample}_${contig_count}".length()` is now the test.

It'll be in the next version

**Comment by tanaes** [comment]
Great! Thanks!

**Comment by rpetit3** [comment]
Hi @tanaes 

Going to close this, feel free to reopen if it comes back!

Thanks again for the help in identifying this bug!
Robert
