### ISSUE TITLE
[bug] Documentation wrong for phyloflash Conda install?

### ISSUE THREAD

**Issue by tanaes** [bactopia/bactopia#125]
**Description**
[This page](https://bactopia.github.io/bactopia-tools/phyloflash/) on the documentation indicates that the Phyloflash Conda environment should be named `bactopia-gtdb`. Is this correct?

**Comment by rpetit3** [comment]
Nope! Thats a copy and paste error, will fix

**Comment by tanaes** [comment]
Ok, great!

**Comment by rpetit3** [comment]
Fixed: https://github.com/bactopia/bactopia/commit/8d36d0163d844f5df816078cd0867d3e373a3f20 (I'll push doc update after I add info about log files)
