### ISSUE TITLE
[bug] bactopia tools gtdb doesn't recognize --download_gtdb parameter

### ISSUE THREAD

**Issue by tanaes** [bactopia/bactopia#127]
**Description**

This one is a little funny... Trying to initiate first GTDB analysis, and it isn't wanting to download the database, saying the parameter isn't known. 

However, it appears in the help:

```
GTDB-Tk Related Parameters:
    --download_gtdb         Download the latest GTDB database, even it exists.

    --min_perc_aa INT       Filter genomes with an insufficient percentage of AA in the MSA
                                Default: 10

    --recalculate_red       Recalculate RED values based on the reference tree and all added
                                user genomes

    --force_gtdb            Force GTDB to continue processing if an error occurrs on a single
                                genome

    --debug                 Create intermediate files for debugging purposes
```

**Steps to Reproduce**
```
bactopia tools gtdb --bactopia 20200218_HackFlex_test --cpus 4 --download_gtdb -qs 8 --force
N E X T F L O W  ~  version 20.07.1
Launching `/home/jgs286/miniconda3/envs/bactopia/share/bactopia-1.4.x/tools/gtdb/main.nf` [furious_brenner] - revision: abba85892b
bactopia tools gtdb - 1.4.5
'--download_gtdb' is not a known parameter
Cannot continue, please see --help for more information
```

**Expected Behavior**
GTDB DB download.

**Execution Environment**

- Bactopia Version: 1.4.5
- OS: CentOS
- Environment: hosted server

**Comment by rpetit3** [comment]
Bonehead mistake, fixed: https://github.com/bactopia/bactopia/commit/8d36d0163d844f5df816078cd0867d3e373a3f20

Will be in next version

**Comment by tanaes** [comment]
Awesome!

**Comment by rpetit3** [comment]
This should be fixed now, you will probably need to use `--force`, due to not using `--prefix` in the output dir. Will not have to use `--force` in the next version.

**Comment by tanaes** [comment]
Looking good, completed successfully for me. thanks!
