### ISSUE TITLE
[bug] Handling of multi-contig references

### ISSUE THREAD

**Issue by embatty** [bactopia/bactopia#139]
I've found an issue when running Bactopia variant calling on multi-contig references. I'm running samples of _Burkholderia pseudomallei_, which has 2 chromosomes. If I run variant calling automatically, it only maps to the first chromosome of the reference genome and throws away the second, the job completes successfully. If I give it a custom reference genome with two chromosomes, it fails at the variant calling step because VCF annotator cannot run on a multi-fasta file, I think everything up to that point is OK. 

Ideally I would be able to give Bactopia a multi-contig reference and get all the variant calls, I think this would mean patching VCF annotator - I'm willing to try and deliver a fix for that if that would be a good solution. It would be fine for me if the default behaviour is to automatically keep only one contig from the reference as it is at present, but maybe there could be a warning message somewhere to alert users?

**Comment by rpetit3** [comment]
Hi @embatty 

I know what's happening here. With auto-variant calling, some of the NCBI Assembly genomes include chromosome and plasmids. Naively, my solution was to just take the largest genomic feature in the GenBank file and not call variants against plasmids.  Unfortunately, this fails for cases such as yours! 

I'm working on updating vcf-annotator to support GenBanks with multiple chromosomes. Then I think that will fix this issue. 

Thank you very much for bringing this to my attention!

Robert

**Comment by rpetit3** [comment]
Hi @embatty 

I've updated vcf-annotator to work with multi sequence GenBank files. I'm going to reconfig Bactopia, then I think we might be good!

Will update with results soon. 

Robert

**Comment by rpetit3** [comment]
Hi @embatty 

I pushed a new version ([v1.4.11](https://github.com/bactopia/bactopia/releases/tag/v1.4.11)) which I think should fix this for you.

Let me know if it didn't!

**Comment by rpetit3** [comment]
Hi @embatty!

I'm going to close this for now, please feel free to reopen if the issue persists!

Thank you very much for your feedback, 
Robert
