### ISSUE TITLE
Skip QC [question] 

### ISSUE THREAD

**Issue by marcelladane** [bactopia/bactopia#140]
Is it possible to skip the QC step if you are using another sequencer than Illumina? 
Since it is on the QC that the adapters will be removed?

I can preprocess and remove adapters beforehand or should I just provide an adapters file?

Thank you very much.

Best regards
Marcela

**Comment by rpetit3** [comment]
Hi @marcelladane 

Thank you for reaching out! Which sequencer are your reads from?

Robert

**Comment by marcelladane** [comment]
Hello, I am using MGI plataform. 
And a PE150 for length. Here you can find illustrative files for the data format. 
https://en.mgitech.cn/products/reagents_info/3/

**Comment by rpetit3** [comment]
Cool! I haven't used MGI sequences yet, I think you would be fine providing your own adapter sequences (in FASTA format) 
 using the `--adapters` parameter.

Very interested to see how it goes! 

Otherwise, I don't see if being to difficult to add and option to skip the QC step.

**Comment by marcelladane** [comment]
I will try it out and give you an update once is done. Thx for replying so fast. =)

**Comment by rpetit3** [comment]
Going to close this for now, please feel free to reopen

**Comment by marcelladane** [comment]
Absolutely. I will be doing another trial this Friday.

=)

**Comment by rpetit3** [comment]
I closed this one, but forgot to push the changes (see: https://github.com/bactopia/bactopia/commit/28b412410e14574dffb99c8b2663574f94a2f956) you can now use `--skip_qc` to skip QC and use the raw FASTQs for downstream analysis.

**Comment by marcelladane** [comment]
Hey, thank you.
I will try it tomorrow then.

=)

**Comment by marcelladane** [comment]
Hello, I tried to run with --skip_qc, and the following error appears during the qc_reads step:

Command error:  rm: cannot remove '*.fq': No such file or directory.

related to this part of the code, I believe: 
if [ "false" == "false" ]; then
      # Remove intermediate FASTQ files
      rm *.fq
  fi
Since I am not running qc, I have no intermediate files to be deleted. But I also don´t have an option to skip this part. Or did I miss something?

gather_fastqs,  fastq_status, estimate_genome_size and qc_original_summary  worked fine. Then it exits during the qc_reads step.

**Comment by rpetit3** [comment]
Bummer! I overlooked the following: https://github.com/bactopia/bactopia/blob/master/templates/qc_reads.sh#L175-L178

I think if you run with `--keep_all_files` it should allow you to continue in the short term. I'll get a fixed push, very soon and push a very update.

Almost there!

**Comment by rpetit3** [comment]
Alright, pushed a fix (https://github.com/bactopia/bactopia/commit/4371bc2fb6ec0264384644dc298d480452c4a4c7). I also added a check to CI for this error. Once CI passes I'll push a version update

**Comment by marcelladane** [comment]
Take your time, I started running with the --keep_all_files and its working great. Just got the first result. =)

**Comment by rpetit3** [comment]
Alright, v1.5.2 should be available on Bioconda now. Let me know if the problem persists! Thanks again for your help!

**Comment by marcelladane** [comment]
Come on, I thank you very much for your help. :)

I will let you know by tomorrow if the new version is working. :)

**Comment by marcelladane** [comment]
Hello, the new implementation works perfectly. I just tried it.

Now I am having a new type of problem, gonna open a new issue so we can
discuss it. :)

Thx again.
