### ISSUE TITLE
How to run bactopia tools pirate/roary on a local dataset [question]

### ISSUE THREAD

**Issue by ramiroricardo** [bactopia/bactopia#141]
Hi,

I would like to use `bactopia tools pirate`/`roary` on a collection of assemblies that I have in a local directory. e.g. say I have directory `assemb` with `assembly1.fna`, `assembly2.fna`, `assembly3.fna`

I have tried several ways, but always end up in an error. My last approach was:

```
bactopia tools pirate \
    --bactopia tmp_files/assemb/ \
    --include tmp_files/genomes_include_list.txt \
    --cpus 4 \
    --outdir bactopia_pirate
```

This returned the error:
`Did not find any samples in tmp_files/assemb/ to process, please check and try again.`

Am I missing something upstream that defines "samples" for bactopia to use?

Thanks for any help

**Comment by rpetit3** [comment]
Hi @ramiroricardo!

At the moment the PIRATE and Roary tools do not support only local assemblies (more info here https://github.com/bactopia/bactopia/issues/100#issuecomment-679164508). If you wanted to proceed with your local assemblies, you would need to run them through Bactopia using `--assembly`

```
    ### For Processing an Assembly
    **Note: The assembly will have error free Illumina reads simulated for processing.**
    --assembly STR          A assembled genome in compressed FASTA format.

    --reassemble            The simulated reads will be used to create a new assembly.
                                Default: Use the original assembly, do not reassemble
```

After doing that the PIRATE/Roary tools would work.

I'll work implementing this into the PIRATE/Roary tools.

Thank you for reaching out!
Robert

**Comment by ramiroricardo** [comment]
Hi Robert,

Thanks for your quick reply. One really cool thing about the way you implemented both the pirate and roary tools is that it can include or not recombination detection through clonalframe. Thus allowing for local assemblies would also be useful if one wants to run with and without clonalframe.

Best,

Ramiro

**Comment by rpetit3** [comment]
Hi @ramiroricardo! Been a while, but I am currently working on this. Will hopefully have an update soon.

**Comment by rpetit3** [comment]
This has been implemented (see: https://github.com/bactopia/bactopia/commit/3531f76a8acab8706267131ec94992c864f2b6d1) and will be in the next version (v1.5.0).

You can either give a single assembly or a directory with assemblies with `--assembly`. If a directory is given you will also need to give a patter (`--assembly_pattern`).

```
        --assembly              A single assembly, or directory of assemblies to be included in the
                                    pan-genome analysis. If compressed, gzip and the ".gz" extension
                                    must be used.

        --assembly_pattern      If a directory is given, use the given pattern to match assemblies.
                                    Default: *.fna

```

It will give you a heads up on how many assemblies were found, and exit if no assemblies are found.
```
Launching `/data/apps/bactopia/tools/pirate/main.nf` [festering_bardeen] - revision: a4948cbfb5
bactopia tools pirate - 1.4.11
Found 1 local assemblies.
Found 1 samples to process
If this looks wrong, now's your chance to back out (CTRL+C 3 times).
Sleeping for 5 seconds...
```

```
Launching `/data/apps/bactopia/tools/pirate/main.nf` [nostalgic_nightingale] - revision: a4948cbfb5
bactopia tools pirate - 1.4.11
0 assemblies were found in assemblies/ using the pattern *.fna.gz, please check. Unable to continue.
```

I need to update the docs, then I think v1.5.0 will be ready for release.

**Comment by rpetit3** [comment]
@ramiroricardo v1.5.0 is now available on Bioconda, so I am going to close this for now. Please feel free to reopen. Thank you very much for your feedback and suggestions!
