### ISSUE TITLE
[question] issue in setting up dataset 

### ISSUE THREAD

**Issue by kusandeep** [bactopia/bactopia#147]
Hi,
Thanks for the great work you guys are doing. I just found out about this program and try to explore.

I am running into an error while setting up dataset folder. 
I used 
bactopia datasets datasets/
line 78, in <module>
    from Bio import SeqIO
ModuleNotFoundError: No module named 'Bio'

Any help would be much appreciated.

Thanks,
Sandeep

**Comment by rpetit3** [comment]
Hmmm, let's see if we can figure this out.

What OS and environment are you using? Conda or a containter (Docker/Singularity)?

**Comment by kusandeep** [comment]
ohh that's lighting fast response..
I am using conda-envs/bactopia

**Comment by rpetit3** [comment]
What what the output for the following command: `which python` ?

**Comment by kusandeep** [comment]
I get this
/stash/miniconda3/bin/python

**Comment by rpetit3** [comment]
I think we are getting closer. Was a separate environment created for Bactopia (`conda create -n bactopia -c conda-forge -c bioconda bactopia`)?

**Comment by kusandeep** [comment]
Yes I had to put them other than my usual home directory so I used 
conda create -p /dataset/SK_PMI/itmp/conda-envs/bactopia -c conda-forge -c bioconda bactopia

**Comment by rpetit3** [comment]
I think our issue is that `/stash/miniconda3/bin/python` is being used instead of `/dataset/SK_PMI/itmp/conda-envs/bactopia/bin/python`

Is the Bactopia environment activated? Or is there something particular about our PATH that is putting `/stash/miniconda3/bin` in front?

**Comment by kusandeep** [comment]
It is activated, now u said it so seems like it using default python /stash/miniconda3/bin/python instead of /dataset/SK_PMI/itmp/conda-envs/bactopia/bin/python
however Bactopia environment activated is activated see below

(/dataset/SK_PMI/itmp/conda-envs/bactopia) grappler$ conda activate /dataset/SK_PMI/itmp/conda-envs/bactopia
(/dataset/SK_PMI/itmp/conda-envs/bactopia) grappler$ bactopia datasets datasets/
Traceback (most recent call last):
  File "/dataset/SK_PMI/itmp/conda-envs/bactopia/bin/bactopia-datasets.py", line 78, in <module>
    from Bio import SeqIO
ModuleNotFoundError: No module named 'Bio'
(/dataset/SK_PMI/itmp/conda-envs/bactopia) grappler$

**Comment by rpetit3** [comment]
Almost there, let's try deactivating everything, activate, then which pythons

```
conda deactivate
conda activate /dataset/SK_PMI/itmp/conda-envs/bactopia
which python
which python3
```

**Comment by rpetit3** [comment]
I'm reminded of this past issue related to python: https://github.com/bactopia/bactopia/issues/101#issuecomment-656397333

**Comment by kusandeep** [comment]
Here is the outcome.

(/dataset/SK_PMI/itmp/conda-envs/bactopia) grappler$ conda deactivate
grappler$ conda activate /dataset/SK_PMI/itmp/conda-envs/bactopia
(/dataset/SK_PMI/itmp/conda-envs/bactopia) grappler$ which python
/dataset/SK_PMI/itmp/conda-envs/bactopia/bin/python
(/dataset/SK_PMI/itmp/conda-envs/bactopia) grappler$ which python3
/dataset/SK_PMI/itmp/conda-envs/bactopia/bin/python3
(/dataset/SK_PMI/itmp/conda-envs/bactopia) grappler$

**Comment by kusandeep** [comment]
So should i try 
bactopia build /dataset/SK_PMI/itmp/conda-envs/bactopia/share/bactopia-1.4.x/conda/ /dataset/SK_PMI/itmp/conda-envs/bactopia/share/bactopia-1.4.x/conda/envs/
???

**Comment by rpetit3** [comment]
Great that looks good.

In that same environment
```
which pip
pip list

/dataset/SK_PMI/itmp/conda-envs/bactopia/bin/python3
from Bio import SeqIO
```

**Comment by kusandeep** [comment]
(/dataset/SK_PMI/itmp/conda-envs/bactopia) grappler$ which pip
/dataset/SK_PMI/itmp/conda-envs/bactopia/bin/pip
(/dataset/SK_PMI/itmp/conda-envs/bactopia) grappler$ pip list
Package                Version
---------------------- -------------------
appdirs                1.4.4
ariba                  2.14.6
beautifulsoup4         4.9.3
biopython              1.78
brotlipy               0.7.0
certifi                2020.6.20
cffi                   1.14.3
chardet                3.0.4
coloredlogs            14.0
conda                  4.9.0
conda-package-handling 1.7.2
cryptography           3.2.1
cycler                 0.10.0
DendroPy               4.5.1
executor               23.1
fasteners              0.14.1
humanfriendly          8.2
idna                   2.10
kiwisolver             1.3.1
lxml                   4.6.1
matplotlib             3.3.2
monotonic              1.5
ncbi-genome-download   0.3.0
numpy                  1.19.2
olefile                0.46
Pillow                 8.0.1
pip                    20.2.4
property-manager       3.0
pycosat                0.6.3
pycparser              2.20
pyfastaq               3.17.0
pymummer               0.10.3
pyOpenSSL              19.1.0
pyparsing              2.4.7
pysam                  0.16.0.1
PySocks                1.7.1
python-dateutil        2.8.1
requests               2.24.0
ruamel-yaml-conda      0.15.80
setuptools             49.6.0.post20201009
six                    1.15.0
soupsieve              2.0.1
tornado                6.1
tqdm                   4.51.0
urllib3                1.25.11
verboselogs            1.7
wheel                  0.35.1
(/dataset/SK_PMI/itmp/conda-envs/bactopia) grappler$/dataset/SK_PMI/itmp/conda-envs/bactopia/bin/python3
Python 3.6.11 | packaged by conda-forge | (default, Aug  5 2020, 20:09:42)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from Bio import SeqIO
>>>

**Comment by rpetit3** [comment]
All right, so it looks like Biopython is set up fine, but for some reason when you run `bactopia datasets` its not using the correct `python3`

Let's try, in the bactopia environment

```
/usr/bin/env python3 --versionE
/dataset/SK_PMI/itmp/conda-envs/bactopia/bin/python3 --version

bactopia datasets --version

/dataset/SK_PMI/itmp/conda-envs/bactopia/bin/python3 /dataset/SK_PMI/itmp/conda-envs/bactopia/bin/bactopia-datasets.py --version
```

**Comment by kusandeep** [comment]
Thanks here is the output

(/dataset/SK_PMI/itmp/conda-envs/bactopia) grappler$ /usr/bin/env python3 --version
Python 3.6.11
(/dataset/SK_PMI/itmp/conda-envs/bactopia) grappler$ /dataset/SK_PMI/itmp/conda-envs/bactopia/bin/python3 --version
Python 3.6.11
(/dataset/SK_PMI/itmp/conda-envs/bactopia) grappler$ bactopia datasets --version
bactopia datasets 1.4.11
(/dataset/SK_PMI/itmp/conda-envs/bactopia) grappler$

**Comment by kusandeep** [comment]
sorry here the last line and the output..

(/dataset/SK_PMI/itmp/conda-envs/bactopia) grappler$ /dataset/SK_PMI/itmp/conda-envs/bactopia/bin/python3 /dataset/SK_PMI/itmp/conda-envs/bactopia/bin/bactopia-datasets.py --version
bactopia datasets 1.4.11
(/dataset/SK_PMI/itmp/conda-envs/bactopia) grappler$

**Comment by rpetit3** [comment]
That's weird, I was expecting `bactopia datasets --version` to fail. Let's give it a go and see what happens!

```
bactopia datasets
```

The second `datasets/` is no longer needed. I added a parameter (`--outdir`) that defaults to `datasets/`. I need to update the docs (apologies!)

**Comment by kusandeep** [comment]
Now it seems to be working below is the output..
(/dataset/SK_PMI/itmp/conda-envs/bactopia) grappler$ bactopia datasets
usage: bactopia datasets [-h] [--outdir STR] [--skip_ariba] [--ariba STR]
                         [--species STR] [--skip_mlst] [--skip_prokka]
                         [--include_genus] [--limit INT] [--accessions STR]
                         [--identity FLOAT] [--overlap FLOAT]
                         [--max_memory INT] [--fast_cluster] [--skip_minmer]
                         [--skip_plsdb] [--prodigal_tf STR] [--reference STR]
                         [--mapping STR] [--genes STR] [--proteins STR]
                         [--primers STR] [--force_optional] [--cpus INT]
                         [--clear_cache] [--force] [--force_ariba]
                         [--force_mlst] [--force_prokka] [--force_minmer]
                         [--force_plsdb] [--keep_files] [--available_datasets]
                         [--depends] [--version] [--verbose] [--silent]
                         PUBMLST
.
.
.
.
example usage:
  bactopia datasets
  bactopia datasets --ariba 'vfdb_core'
  bactopia datasets --species 'Staphylococcus aureus' --include_genus

**Comment by rpetit3** [comment]
Well @kusandeep that's great to hear! Let's blame it on conda! I've had a few times where I had to deactivate and reactivate conda envs to get it to work.

Let me know if you run into any other issues!

**Comment by kusandeep** [comment]
Thanks heaps @rpetit3 much appreciated for help..
Great work
Regards
Sandeep

**Comment by rpetit3** [comment]
Thank you very much! Going to close this for now, please feel free to reopen,
