### ISSUE TITLE
[question] regarding the use of mash refseq

### ISSUE THREAD

**Issue by marcelladane** [bactopia/bactopia#153]
Hello, I was running some samples yesterday and this samples was tested for gram staining and pointed to be bacilli.
During the sequencing we have an automatic pipeline that does QC and uses kraken for classification ( we mostly run metagenomes, that is why we have this one automated) and my sample came out as L.crispatus. it's an automated processing, so all samples goes through it independently if it's wgs or metagenome.
When I ran the same sample in bactopia  I checked the output of this automated pipeline and bactopia and the outputs don't match. Bactopia classifies it as E. Faecalis.

I believe to be an issue with the mash refseq. 
Discussing with some bioinformaticians they mentioned that maybe I should try sendsketch from bbmap. 

What do you think?
And why did you choose mash refseq for this pipeline?

**Comment by rpetit3** [comment]
Those calls are pretty different (*E. faecalis* vs *L. crispatus*)! You can quickly compare the Mash results against a few other results: [CheckM](https://bactopia.github.io/output-overview/#quality-reports) (`SAMPLE_NAME/assembly/checkm/checkm-results.txt`) and [Sourmash](https://bactopia.github.io/output-overview/#minmers) (`SAMPLE_NAME/minmers/SAMPLE_NAME-genbank-k{2,3,5}1.txt`)?

CheckM uses single copy genes to make a taxonomic classification, and Sourmash is similar to Mash but uses GenBank. I chose each of these because the datasets could be downloaded locally and I wanted to have comparable results (e.g. did they all make the same call).

It might also be worth trying a few others:
- [GTDB](https://bactopia.github.io/bactopia-tools/gtdb/) - taxon classification against the [Genome Taxonomy Database](https://gtdb.ecogenomic.org/)
- [phyloFlash](https://bactopia.github.io/bactopia-tools/phyloflash/) - reconstruct 16S rRNA and see what it matches to
- [FastANI](https://bactopia.github.io/bactopia-tools/fastani/) - compare your sample to completed *E. faecalis* and *L. crispatus* genomes.

I am already using BBMap, so I don't think it would be a problem to add `sendsketch`. I would probably make it optional since it requires remote processing.

I'm curious does *E. faecalis* show up in the Kraken results, or does *L. cristpatus* show up in the Mash/Sourmash/CheckM results?

**Comment by marcelladane** [comment]
[image: res_Lgasseri.JPG]
Hey, it only shows up in the Mash.
Actually, I have another example that I was trying now (another sample),
where I got another type of lactobacillus (L.gasseri) in kraken and again a
E. faecalis in mash.
Then I ran it in sendsketch and got the correct L.gasseri.

**Comment by rpetit3** [comment]
The image didn't show up. Did the *L. gasseri* sample also look fine in Sourmash and CheckM?

I think an issue with Mash RefSeq is it uses 21-mers, where as Kraken most likely was 31-mers and Sourmash you get 21,31,51. CheckM isn't k-mer based.

**Comment by marcelladane** [comment]
Now the figure should open. Sorry that it didn't last time.

For checkM went as far as order and said to be lactobacillales. 
For sourmask 21,31,51 gave E.Faecalis.

**Comment by rpetit3** [comment]
At least it looks like CheckM was heading in the right direction.

I think the last thing I would check would be GTDB, but I assume it will give you Lactobacillus. It also has a ~30GB database to download, which might not be worth it to check a single sample.

Are these public samples (ENA/SRA), if not would you mind sharing the raw FASTQs for one of the samples? I would like to figure out what's happening with Mash and Sourmash.

Either way, I think you've convinced me to add `sendsketch`! Did you use the FASTQ reads or assembly for sendsketch?

**Comment by marcelladane** [comment]
It would be great if you would add sendsketch, but to be fair, I would like
to let you know 2 things about sendsketch:
1 - sendsketch.sh sends sketches to a remote server (at the JGI) for
comparison to a reference DB it introduces external dependencies that might
be hard to control.
2 - Updates to the BBMap package can break compatability with pinned
verisons in pipelines.

The upper side is that is quite good figuring out the spp. As you saw.

I can share the fastq file with you. That is ok. How should I do that?

=)

**Comment by rpetit3** [comment]
Yeah, that could be problematic, but agree seems like its worth it.

1) I think making sendsketch optional helps, but at this point I might opt for a `--disable_sendsketch` and have it used by default alongside Mash and Sourmash
2) I can add a check to CI that would help let us know if an update is needed.

Feel free to contact me at robbie.petit@gmail.com for sharing a sample, I can use Dropbox, Google Drive, One Drive or something that's easiest for you. Unfortunately, no SSH or FTP option at the moment on my end.

**Comment by marcelladane** [comment]
Hello, I will fix the data and share using drive then. Give me half an hour
or so. :)

And please let me know when I can use sendsketch in bactopia then.
That would be great. :)

**Comment by marcelladane** [comment]
Data is shared. Let me know if the sharing work, the email from work is a
bit annoying sometimes and doesn't share with ppl out from the
organisation. :)

**Comment by rpetit3** [comment]
Got the data, I'll update you when sendsketch its added

**Comment by rpetit3** [comment]
Alright @marcelladane I ran your samples through. Everything looks like what its expected to look like, at least based on the sample name. I also went ahead and ran `sendsketch` on the assembly for each and the results of `sendsketch` matched Mash and Sourmash.

Do you think there might have been a mix up at runtime?


### E. faecalis
```
(base) rpetit@staphopia:~/test/bactopia$ bactopia --R1 ../data_share/Faecalis_R1.fq.gz --R2 ../data_share/Faecalis_R2.fq.gz --sample faecalis --cpus 8 --condadir /data/storage/bactopia-ci/bactopia-envs --datasets ../datasets/

(base) rpetit@staphopia:~/test/bactopia$ head -n 6 faecalis/minmers/faecalis-genbank-k21.txt

overlap     p_query p_match
---------   ------- --------
2.8 Mbp      27.9%   88.6%      Enterococcus faecalis (** 1 equal matches)
220.0 kbp     2.2%   10.5%      Lactobacillus crispatus (** 2 equal matches)
120.0 kbp     1.2%    7.3%      Campylobacter coli (** 234 equal matches)

(base) rpetit@staphopia:~/test/bactopia$ head -n 6 faecalis/minmers/faecalis-refseq-k21.txt
identity        shared-hashes   median-multiplicity     p-value query-ID        query-comment
0.99781 955/1000        146     0       GCF_000395405.1_Ente_faec_5952_V1_genomic.fna.gz        [13 seqs] NZ_KB947497.1 Enterococcus faecalis 5952 genomic scaffold acEQc-supercont1.1, whole genome shotgun sequence [...]
0.982688        693/1000        667     0       GCF_001275495.1_ViralProj159663_genomic.fna.gz  NC_017732.1 Enterococcus phage EF62phi, complete genome
0.960714        431/1000        137     0       GCF_000884555.1_ViralProj42787_genomic.fna.gz   NC_013648.1 Enterococcus phage phiFL3A, complete genome
0.901381        113/1000        1       0       GCF_000176975.2_ASM17697v2_genomic.fna.gz       [70 seqs] NZ_GL877783.1 Lactobacillus crispatus SJ-3C-US genomic scaffold supercont1.1, whole genome shotgun sequence [...]
0.888234        83/1000 137     0       GCF_001931845.1_ASM193184v1_genomic.fna.gz      NZ_CP015998.1 Enterococcus faecalis strain AMB05 genome

(/data/storage/bactopia-ci/bactopia-envs/qc_reads-1.5.x) rpetit@staphopia:~/test/bactopia$ sendsketch.sh in=faecalis/assembly/faecalis.fna | head
Adding /data/storage/bactopia-ci/bactopia-envs/qc_reads-1.5.x/opt/bbmap-38.86-0/resources/blacklist_refseq_merged.sketch to blacklist.
0.008 seconds.
Loaded 1 sketch in 0.627 seconds.

Query: faecalis.fna     DB: RefSeq      SketchLen: 19273        Seqs: 33        Bases: 3024494  gSize: 3001876  GC: 0.372       File: faecalis.fna
WKID    KID     ANI     SSU     Complt  Contam  Matches Unique  TaxID   gSize   gSeqs   taxName
96.51%  95.51%  99.87%  .       96.77%  4.23%   18407   3       1158670 2972297 13      Enterococcus faecalis EnGen0283
77.21%  76.77%  99.08%  .       77.02%  22.54%  14778   0       1579344 3018615 157     Enterococcus sp. 255_ESPC
70.73%  66.46%  98.75%  .       71.01%  33.28%  12809   0       1739405 2821322 41      Enterococcus sp. HMSC073E09
72.61%  65.35%  98.84%  .       72.89%  34.39%  12595   0       1579349 2705945 75      Enterococcus sp. 1140_ESPC
64.65%  64.40%  98.47%  .       64.91%  35.34%  12411   0       1739314 2989429 81      Enterococcus sp. HMSC078F03
65.82%  63.47%  98.49%  .       66.09%  36.27%  12233   0       2315836 2899805 45      Enterococcus sp. N041.A-2
77.53%  5.77%   99.08%  .       5.79%   22.15%  2723    0       1352    40390K  246744  Enterococcus faecium
Total Time:     1.726 seconds.

```

### L. crispatus
```
(bactopia) rpetit@staphopia:~/test/bactopia$ bactopia --R1 ../data_share/Crispatus_R1.fq.gz --R2 ../data_share/Crispatus_R2.fq.gz --sample crispatus --cpus 8 --condadir /data/storage/bactopia-ci/bactopia-envs --datasets ../datasets/

(base) rpetit@staphopia:~/test/bactopia$ head -n 6 crispatus/minmers/crispatus-genbank-k21.txt

overlap     p_query p_match
---------   ------- --------
1.9 Mbp      24.4%   88.5%      Lactobacillus crispatus (** 1 equal matches)
150.0 kbp     2.0%    3.1%      Escherichia coli (** 32 equal matches)
130.0 kbp     1.7%    5.9%      Lactobacillus crispatus

(base) rpetit@staphopia:~/test/bactopia$ head -n 6 crispatus/minmers/crispatus-refseq-k21.txt
identity        shared-hashes   median-multiplicity     p-value query-ID        query-comment
0.997909        957/1000        113     0       GCF_000176975.2_ASM17697v2_genomic.fna.gz       [70 seqs] NZ_GL877783.1 Lactobacillus crispatus SJ-3C-US genomic scaffold supercont1.1, whole genome shotgun sequence [...]
0.86537 48/1000 111     1.69334e-194    GCF_000497065.1_L.crispatus1.0_genomic.fna.gz   [63 seqs] NZ_AXLM01000001.1 Lactobacillus crispatus EM-LC1 NODE_1, whole genome shotgun sequence [...]
0.85789 40/1000 83      3.93854e-159    GCF_001546015.1_ASM154601v1_genomic.fna.gz      [267 seqs] NZ_LJCZ01000001.1 Lactobacillus crispatus strain VMC1 VMC1_v1.0_contig_1, whole genome shotgun sequence [...]
0.852452        35/1000 1       2.20416e-137    GCF_000351145.1_Esch_coli_KTE210_V1_genomic.fna.gz      [15 seqs] NZ_KB732513.1 Escherichia coli KTE210 acEoo-supercont1.1, whole genome shotgun sequence [...]
0.843442        28/1000 100     1.75853e-107    GCF_001541515.1_ASM154151v1_genomic.fna.gz      [259 seqs] NZ_LJOK01000001.1 Lactobacillus crispatus strain VMC5 VMC5_v1.0_contig_1, whole genome shotgun sequence [...]

(/data/storage/bactopia-ci/bactopia-envs/qc_reads-1.5.x) rpetit@staphopia:~/test/bactopia$ sendsketch.sh in=crispatus/assembly/crispatus.fna | head
Adding /data/storage/bactopia-ci/bactopia-envs/qc_reads-1.5.x/opt/bbmap-38.86-0/resources/blacklist_refseq_merged.sketch to blacklist.
0.010 seconds.
Loaded 1 sketch in 0.538 seconds.

Query: crispatus.fna    DB: RefSeq      SketchLen: 17193        Seqs: 205       Bases: 2150311  gSize: 2134400  GC: 0.368       File: crispatus.fna
WKID    KID     ANI     SSU     Complt  Contam  Matches Unique  TaxID   gSize   gSeqs   taxName
94.11%  88.26%  99.78%  .       95.76%  10.19%  15175   1       575598  2000080 70      Lactobacillus crispatus SJ-3C-US
59.62%  56.56%  98.14%  .       61.25%  41.89%  9724    0       2042031 2022003 119     Lactobacillus sp. UMNPBX16
59.57%  56.51%  98.13%  .       61.20%  41.95%  9715    0       2042032 2022512 130     Lactobacillus sp. UMNPBX15
57.91%  56.78%  98.04%  .       59.49%  41.67%  9762    1       2042046 2089592 92      Lactobacillus sp. UMNPBX1
58.99%  56.42%  98.10%  .       60.61%  42.03%  9701    0       2042035 2040829 92      Lactobacillus sp. UMNPBX12
58.91%  56.41%  98.10%  .       60.52%  42.04%  9699    0       2042036 2043453 103     Lactobacillus sp. UMNPBX11
57.62%  56.78%  98.01%  .       59.19%  41.67%  9762    0       2042039 2102975 252     Lactobacillus sp. UMNPBX8
Total Time:     1.476 seconds.
```

### L. gasseri
```
(bactopia) rpetit@staphopia:~/test/bactopia$ bactopia --R1 ../data_share/Gasseri_R1.fq.gz --R2 ../data_share/Gasseri_R2.fq.gz --sample gasseri --cpus 8 --condadir /data/storage/bactopia-ci/bactopia-envs --datasets ../datasets/

(base) rpetit@staphopia:~/test/bactopia$ head -n 6 gasseri/minmers/gasseri-genbank-k21.txt

overlap     p_query p_match
---------   ------- --------
1.7 Mbp      23.6%   77.9%      Lactobacillus gasseri
220.0 kbp     3.1%    4.5%      Escherichia coli
150.0 kbp     2.1%    7.1%      Lactobacillus gasseri

(base) rpetit@staphopia:~/test/bactopia$ head -n 6 gasseri/minmers/gasseri-refseq-k21.txt
identity        shared-hashes   median-multiplicity     p-value query-ID        query-comment
0.985061        729/1000        163     0       GCF_002003555.1_ASM200355v1_genomic.fna.gz      [35 seqs] NZ_MUJA01000010.1 Lactobacillus gasseri strain AL5 scaffold10_size2407, whole genome shotgun sequence [...]
0.946334        314/1000        745     0       GCF_001507495.1_ViralProj249087_genomic.fna.gz  NC_024206.1 Lactobacillus phage phi jlb1, complete genome
0.920851        177/1000        150     0       GCF_000848805.1_ViralProj14588_genomic.fna.gz   NC_000896.1 Lactobacillus prophage phiadh, complete genome
0.900227        110/1000        920     0       GCF_000868065.1_ViralProj16663_genomic.fna.gz   NC_007924.1 Lactobacillus phage KC5a, complete genome
0.887722        82/1000 166     0       GCF_000406345.2_LK71.0_genomic.fna.gz   [8 seqs] NZ_KL402718.1 Lactobacillus gasseri K7 genomic scaffold LK7_scaffold1, whole genome shotgun sequence [...]

(/data/storage/bactopia-ci/bactopia-envs/qc_reads-1.5.x) rpetit@staphopia:~/test/bactopia$ sendsketch.sh in=gasseri/assembly/gasseri.fna | head
Adding /data/storage/bactopia-ci/bactopia-envs/qc_reads-1.5.x/opt/bbmap-38.86-0/resources/blacklist_refseq_merged.sketch to blacklist.
0.008 seconds.
Loaded 1 sketch in 0.578 seconds.

Query: gasseri.fna      DB: RefSeq      SketchLen: 16708        Seqs: 33        Bases: 1969236  gSize: 1953402  GC: 0.347       File: gasseri.fna
WKID    KID     ANI     SSU     Complt  Contam  Matches Unique  TaxID   gSize   gSeqs   taxName
68.05%  67.88%  98.64%  100.00% 79.36%  20.83%  11342   390     1334627 1948748 8       Lactobacillus paragasseri K7
96.36%  25.06%  99.86%  99.87%  25.93%  0.28%   6598    660     1596    7558042 1905    Lactobacillus gasseri
6.20%   5.88%   90.38%  99.62%  18.10%  82.84%  982     21      1423809 1857274 52      Lactobacillus taiwanensis DSM 21401
5.07%   4.67%   89.71%  99.56%  17.31%  84.04%  781     2       1408186 1802916 1       Lactobacillus johnsonii N6.2
4.74%   4.51%   89.50%  99.49%  16.62%  84.21%  753     0       2042028 1856744 180     Lactobacillus sp. UMNPBX19
12.39%  2.14%   92.69%  92.60%  2.74%   84.15%  649     0       47770   11314K  19892   Lactobacillus crispatus
32.24%  0.65%   95.96%  .       100.00% 88.07%  108     9       1416334 37489   1       Lactobacillus phage phi jlb1
Total Time:     1.467 seconds.
```

**Comment by marcelladane** [comment]
You are absolutely right. I apologize for my mistake and the time it took
for you troubleshooting to figure out the reason for the error.
As you can imagine, originally the samples were not named as I sent to you.
It was a very long sequencing of characters and letters and I believe you
may guess, I made typos while loading it since the FOFN file was giving me
an error.

Once again, I am sorry.

**Comment by rpetit3** [comment]
No worries! This is actually very good news, I thought an old bug had resurfaced (https://github.com/bactopia/bactopia/commit/5c1f6f2ebd776783eb92cab4721db0b12697fb12) that caused analyses to get mixed up.

I am interested in this though: _since the FOFN file was giving me an error._ Is there anything I can help with on that? I know sometimes the pattern matching can cause errors especially with the long names from sequencing centers.

**Comment by marcelladane** [comment]
Thanks for understanding.

Basically, I tried all possible versions of the word paired-end I could
think of: paired-end; paired_end; Paired-end; paired; pair end;
"paired-end"; "paired; "pair-end".
And every time I ran it, I get the following message:
*...*

*--species not given, skipping the following processes (analyses):*





*sequence_typecall_variantsprimer_queryIf something looks wrong, now's your
chance to back out (CTRL+C 3 times).Sleeping for 5 seconds...Invalid
run_type ${line.runtype} found, please correct to continue*

At the moment I have like 180 samples to run and I was trying to make it
work with the FOFN because it will take a lot of time to enter each
manually.

Another thing I notice since I am talking about the FOFN file is that if I
use special characters (* for example) to make pattern recognition for the
name of the samples (remember the names are long and not real words but a
seq of characters and numbers) I get the following:

*N E X T F L O W  ~  version 20.10.0*


*Launching
`/nfsstore/home/marcela.pereira/miniconda3/envs/bactopia/share/bactopia-1.5.x/main.nf
<http://main.nf>` [scruffy_curie] - revision: 23058d66b5Unknown method
invocation `exists` on LinkedList type*

I used exactly the same file, but changed a repetitive part of the name
with "*". So I believe it is related to the --fastqs.
It works to use "*" when calling sample by sample though.

**Comment by rpetit3** [comment]
Could you post the FOFN command you used and some of the output?

**Comment by marcelladane** [comment]
Alright, the command was like so:
bactopia --fastqs ValP/example.txt --skip_qc --cleanup_workdir --datasets bactopia/datasets/ --cpus 30 --outdir ./data/

The "example.txt" is the name of the FOFN in this example. And since I didn´t get any error on reading the samples, it should be ok. 

Actually, I did misspell one on purpose to see if I would get an error and I did, it was like this:
_Launching `/nfsstore/home/marcela.p/miniconda3/envs/bactopia/share/bactopia-1.5.x/main.nf` [stupefied_ramanujan] - revision: 23058d66b5
LINE 2:ERROR: Please verify /marcela.p/ValP/A11/ValP__A11__V335656851_L2_1_2.fq.gz  exists, and try again_

Then I corrected and was sure the sample name and location was fine. So I ran the same command and got the following error:
_Launching `/nfsstore/home/marcela.p/miniconda3/envs/bactopia/share/bactopia-1.5.x/main.nf` [voluminous_ritchie] - revision: 23058d66b5
bactopia - 1.5.2

Each task will use 30 CPUs out of the available 72 CPUs. At most 2.4 task(s) will be run at
a time, this can affect the efficiency of Bactopia.

Found 6 ARIBA datasets
/nfsstore/home/marcela.p/bactopia/datasets/ariba/card.tar.gz
/nfsstore/home/marcela.p/bactopia/datasets/ariba/megares.tar.gz
/nfsstore/home/marcela.p/bactopia/datasets/ariba/plasmidfinder.tar.gz
/nfsstore/home/marcela.p/bactopia/datasets/ariba/resfinder.tar.gz
/nfsstore/home/marcela.p/bactopia/datasets/ariba/srst2_argannot.tar.gz
...More than 5, truncating...
Found 3 PLSDB (plasmid) BLAST files
bactopia/datasets/plasmid/plsdb.fna.nhr
bactopia/datasets/plasmid/plsdb.fna.nin
bactopia/datasets/plasmid/plsdb.fna.nsq
Found 5 minmer sketches/signatures
/nfsstore/home/marcela.p/bactopia/datasets/minmer/genbank-k21.json.gz
/nfsstore/home/marcela.p/bactopia/datasets/minmer/genbank-k31.json.gz
/nfsstore/home/marcela.p/bactopia/datasets/minmer/genbank-k51.json.gz
/nfsstore/home/marcela.p/bactopia/datasets/minmer/refseq-k21-s1000.msh
/nfsstore/home/marcela.p/bactopia/datasets/plasmid/plsdb.msh
--species not given, skipping the following processes (analyses):
sequence_type
call_variants
primer_query
If something looks wrong, now's your chance to back out (CTRL+C 3 times).
Sleeping for 5 seconds...
Invalid run_type ${line.runtype} found, please correct to continue_

As for the FOFN file, I used the example provided and edited it accordingly. So it was a tab-delimited with the needed 5 columns (sample   runtype  r1  r2  extra)

**Comment by rpetit3** [comment]
Did you try `bactopia prepare` for generating the FOFN? If not, take a look at: https://bactopia.github.io/usage-basic/#generating-a-fofn

**Comment by marcelladane** [comment]
Actually I didn't.
I will take a look on it and let you know by Monday. :)

**Comment by rpetit3** [comment]
Sounds good!

Also I noticed:

```
bactopia --fastqs ValP/example.txt --skip_qc --cleanup_workdir --datasets bactopia/datasets/ --cpus 30 --outdir ./data/
...
Each task will use 30 CPUs out of the available 72 CPUs. At most 2.4 task(s) will be run at
a time, this can affect the efficiency of Bactopia.
```

If the goal was to only use a max of 30 cores out of the 72, you'll want to use the queue size parameter `-qs` (More info here: https://bactopia.github.io/usage-basic/#-qs)

```
bactopia --fastqs ValP/example.txt --skip_qc --cleanup_workdir --datasets bactopia/datasets/ --cpus 4 --outdir ./data/ -qs 30
```

Otherwise, if your ok using all 72 cores, I would suggest lowering `--cpus 30` to something like `--cpus 8` or `--cpus 4`. I make this suggestion based on how Nextflow's job scheduler works, more details here: https://bactopia.github.io/usage-basic/#-cpus

This will be really important when you run the 180 samples. 

Enjoy the weekend!

**Comment by marcelladane** [comment]
Thanks for the advice, you too.
I let you know if how it goes on Monday regarding the FOFN file. :)

**Comment by marcelladane** [comment]
I tried using the bactopia prepare and it worked now.

I noticed though that it works if the files are all together in a single
folder. If one has subfolders, "bactopia prepare" gives an error.

If you want advice (although the documentation is very clear and well
written...), I would also say that the way to run the FOFN could be a bit
more clear. Saying that -f and --fastq_pattern needs to be filled. Also,
just so people don´t spend time trying, mention to add a > "file_name.txt"

Just so people who are new to bioinformatics have an easier time. =)

**Comment by rpetit3** [comment]
That's a great idea! Thank you very much for the feedback.

I'll get more details added to the docs for `bactopia prepare` usage.

For this one: _If one has subfolders, "bactopia prepare" gives an error._

Do you think it would be useful to search all subdirectories of the given directory?

**Comment by marcelladane** [comment]
So, it all depends on how you get the output.
On my case where I had data preprocessed (did QC already and removed
adapters) it was in subfolders.

But my case is kinda the exception, not the rule. And the data from the
sequencer actually comes all together. It was more a thing that I noticed
and someone else might have the same situation.

An easy fix is just to let clear that all files should be in a single
folder. :)

**Comment by rpetit3** [comment]
Thanks again for the feedback! It's very useful to see how others are using it.

**Comment by rpetit3** [comment]
Hi @marcelladane 

Good news! `bactopia prepare` will now allow you to recursively search a directory.

Here's example:
```
test-fastqs/
├── run001
│   ├── sample001_R1.fastq.gz
│   ├── sample001_R2.fastq.gz
│   ├── sample002_R1.fastq.gz
│   └── sample002_R2.fastq.gz
└── run002
    ├── sample003_R1.fastq.gz
    ├── sample003_R2.fastq.gz
    ├── sample004_R1.fastq.gz
    └── sample004_R2.fastq.gz

python3 /data/apps/bactopia/bin/helpers/bactopia-prepare.py test-fastqs
... Nothing ...

python3 /data/apps/bactopia/bin/helpers/bactopia-prepare.py test-fastqs --recursive
sample  runtype r1      r2      extra
sample001       paired-end      /local/home/rpetit/test/test-fastqs/run001/sample001_R1.fastq.gz        /local/home/rpetit/test/test-fastqs/run001/sample001_R2.fastq.gz
sample002       paired-end      /local/home/rpetit/test/test-fastqs/run001/sample002_R1.fastq.gz        /local/home/rpetit/test/test-fastqs/run001/sample002_R2.fastq.gz
sample003       paired-end      /local/home/rpetit/test/test-fastqs/run002/sample003_R1.fastq.gz        /local/home/rpetit/test/test-fastqs/run002/sample003_R2.fastq.gz
sample004       paired-end      /local/home/rpetit/test/test-fastqs/run002/sample004_R1.fastq.gz        /local/home/rpetit/test/test-fastqs/run002/sample004_R2.fastq.gz
```

Thank you very much for this suggestion! It is going to be very useful!

This will be in the next version.

**Comment by rpetit3** [comment]
I've released v1.5.3 which includes the recursive search for `bactopia prepare`. It should be Bioconda soon.

Going to close this for now, please feel free to reopen. Thanks again for the feedback!

**Comment by marcelladane** [comment]
Hello, thank you for letting me know. I will test it.
Have been using bactopia a lot the past week. All my 180 samples are
processed and the results are quite interesting.

:)

**Comment by rpetit3** [comment]
That's exciting! If you have any feedback or suggestions, please feel free to share!

I'm going to be working on improving the summary tool to make easier to look at the results. So I might reach out for some testing if thats ok with you.

Thanks again!

**Comment by marcelladane** [comment]
Absolutely. I will gladly help out. Just let me know what you need! :)

Best regards
Marcela
