### ISSUE TITLE
bactopia datasets

### ISSUE THREAD

**Issue by haruosuz** [bactopia/bactopia#155]
https://bactopia.github.io/quick-start/
```
conda create -y -n bactopia -c conda-forge -c bioconda bactopia
conda activate bactopia
bactopia datasets
```
created the following folders instead of a folder `./datasets`:
```
$find . -maxdepth 2
.
./bactopia-info
./bactopia-info/bactopia-trace.txt
./.nextflow.log
./.nextflow
./.nextflow/history
./.nextflow/cache
./work
./work/bactopia
```

Re-running it did not generate any folder.

Run environment
```
$uname -a
Linux bias5-login 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 GNU/Linux
```

**Comment by rpetit3** [comment]
Which version are you using?

Did you get the help message when you ran `bactopia datasets`? I fixed a bug related to bactopia datasets (https://github.com/bactopia/bactopia/commit/829f536bc79ab13b86c71486e0b69c38f46ee2e4#diff-59e95d095501bc4060a247b03b939c7c0e10a4b4f614651e0c73601a20a4e930) but it was after the latest release.

If you got the help message, try : `bactopia datasets --outdir ./datasets`

**Comment by haruosuz** [comment]
Thank you for your reply.

I am using the following version.
```
N E X T F L O W  ~  version 20.10.0
bactopia v1.5.2
```

I got the help message using: `bactopia datasets`.
Therefore, I run:
```
$bactopia datasets --outdir ./datasets
2020-11-22 11:03:16:root:INFO - Setting up Ariba datasets
2020-11-22 11:03:16:root:INFO - Setting up vfdb_core Ariba dataset
2020-11-22 11:08:24:root:INFO - Setting up card Ariba dataset
2020-11-22 11:09:26:root:INFO - Setting up pre-computed Genbank/Refseq minmer datasets
2020-11-22 11:10:36:root:INFO - Setting up pre-computed PLSDB (plasmids) datasets
2020-11-22 11:11:31:root:INFO - No requests for an species, skipping
2020-11-22 11:11:31:root:INFO - Writing summary of available datasets
```

There are following files in the current directory:
```
$find . -maxdepth 1
.
./.nextflow.log.2
./bactopia-info
./.nextflow.log.1
./datasets
./.nextflow.log
./.nextflow
./work
```

**Comment by rpetit3** [comment]
Great! I think you should be good to continue now. (let me know if not!)

I'll get a version update pushed soon so this work-around isn't needed.

Thank you very much for catching that @haruosuz!

**Comment by rpetit3** [comment]
I've released v1.5.3 which fixes this issue, it should be Bioconda soon.

Going to close this for now, please feel free to reopen.

**Comment by haruosuz** [comment]
[6268884.zip](https://github.com/bactopia/bactopia/files/6187492/6268884.zip)


I'm attaching log files when Installation and Build Dataset was done using:
```
conda create -y -n bactopia -c conda-forge -c bioconda bactopia
conda activate bactopia

bactopia datasets
```

This created a folder ./datasets but did not build datasets such as `plasmid` and `minmer` as follows:
```
$find datasets
datasets
datasets/ariba
datasets/ariba/vfdb_core-updated.txt
datasets/ariba/vfdb_core.tar.gz
datasets/ariba/card-log.txt
datasets/ariba/card.download
datasets/ariba/card.download/card.tar.bz2
```

I checked versions as follows:
```
$bactopia datasets --version
bactopia datasets 1.6.2

$bactopia tools --h
N E X T F L O W  ~  version 20.10.0
Pulling nextflow-io/summary ...
WARN: Cannot read project manifest -- Cause: Remote resource not found: https://api.github.com/repos/nextflow-io/summary/contents/nextflow.config
Remote resource not found: https://api.github.com/repos/nextflow-io/summary/contents/main.nf
```

**Comment by rpetit3** [comment]
Your datasets command was affected by this https://github.com/bactopia/bactopia/issues/208 . What happened was conda selected an older version of Ariba that fails on downloads from CARD. I've updated the Bactopia recipe so that only the newest version of Ariba is always chosen. (https://github.com/bioconda/bioconda-recipes/pull/27511)

`bactopia tools --h`
I don't like the output of that. You asked for the usage `--h` , but it tried to run a tool. I think thats a bug and will fix in in the next version.

This should work for you `bactopia tools -h` or `bactopia tools --help`

**Comment by haruosuz** [comment]
Thank you for your advice. Installation was done again, then `bactopia datasets` built the following datasets:
```
$find datasets/
datasets/
datasets/ariba
datasets/ariba/vfdb_core-updated.txt
datasets/ariba/vfdb_core.tar.gz
datasets/ariba/card.tar.gz
datasets/ariba/card-updated.txt
datasets/plasmid
datasets/plasmid/plsdb.sim
datasets/plasmid/plsdb.fna.nin
datasets/plasmid/plsdb.tsv
datasets/plasmid/plsdb_changes.tsv
datasets/plasmid/plsdb-orginal-names.txt
datasets/plasmid/plsdb.msh
datasets/plasmid/README.md
datasets/plasmid/plsdb.fna.nhr
datasets/plasmid/plsdb.abr
datasets/plasmid/plsdb-updated.txt
datasets/plasmid/plsdb.fna.nsq
datasets/antimicrobial-resistance
datasets/antimicrobial-resistance/amrfinderdb.tar.gz
datasets/antimicrobial-resistance/amrfinderdb-updated.txt
datasets/minmer
datasets/minmer/genbank-k21.json.gz
datasets/minmer/minmer-updated.txt
datasets/minmer/genbank-k31.json.gz
datasets/minmer/refseq-k21-s1000.msh
datasets/minmer/genbank-k51.json.gz
datasets/summary.json
```
