### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by kusandeep** [bactopia/bactopia#160]
Hi,
I have five samples/assemblies that I want to run through bactopia. All assembly is in .fasta format. This is what I did.
1. ZIP them individualy to  .fasta.gz file
2. Create a FOFN file- see the picture below

sample	runtype	r1	r2	extra
FE1assembly	assembly/FE1.fasta.gz		
FE2	assembly	assembly/FE2.fasta.gz		
R17	assembly	assembly/R17.fasta.gz		
WTE2	assembly	assembly/WTE2.fasta.gz		
XBB3	assembly	assembly/XBB3.fasta.gz

3. Run the script like this      bactopia --fastqs fofn.txt --outdir run4 --cpus 15
Note: I am skipping the dataset option

And error I get is this 
--datasets not given, skipping the following processes (analyses):
sequence_type
ariba_analysis
minmer_query
plasmid_blast
call_variants
primer_query
If something looks wrong, now's your chance to back out (CTRL+C 3 times).
Sleeping for 5 seconds...
Argument of `file` function cannot be empty

Any suggestions?

**Comment by kusandeep** [comment]
sorted. I had to pest file location in extra column not in r1.

**Comment by rpetit3** [comment]
Hi @kusandeep 

Are you using `bactopia prepare` to make your FOFNs? If not for your assemblies you could have done this to make the FOFN.
```
bactopia prepare /path/to/assemblies --assembly_ext ".fasta.gz" --assembly_pattern "*.fasta.gz" > fofn.txt
cat fofn.txt
sample	runtype	r1	r2	extra
FE1	assembly			/path/to/assemblies/FE1.fasta.gz
FE2	assembly			/path/to/assemblies/FE2.fasta.gz
R17	assembly			/path/to/assemblies/R17.fasta.gz
WTE2	assembly			/path/to/assemblies/WTE2.fasta.gz
XBB3	assembly			/path/to/assemblies/XBB3.fasta.gz
```

**Comment by kusandeep** [comment]
I did it manually but good to know for next time.

**Comment by rpetit3** [comment]
Going to close this one since I think we're good, please feel free to reopen if not
