### ISSUE TITLE
[bug] outdir doesn't work when used in config file

### ISSUE THREAD

**Issue by simone-pignotti** [bactopia/bactopia#166]
**Description**
Setting `params.outdir` in the config file does not work, while setting the same value with the command-line parameter `--outdir` does.

**Steps to Reproduce**
```
bactopia --fastqs reads.txt --nfconfig test.nextflow.config
N E X T F L O W  ~  version 20.10.0
Launching `/home/[user]/.miniconda/envs/bactopia/share/bactopia-1.5.x/main.nf` [lethal_colden] - revision: 403ec4cd2e
Output directory (test) exists, Bactopia will not continue unless '--force' is used.
Cannot continue, please see --help for more information
```

**Expected Behavior**
Setting `params.outdir` in the config file should have the same effect as the respective command-line parameter, without requiring `--force`.

**Execution Environment**

- Bactopia Version: `1.5.3`
- OS: Debian 10
- Environment: conda

**Additional Information**
Tried to use `find` in a few directories to locate the `test` before and after bactopia fails, but couldn't find the directory.

**Comment by rpetit3** [comment]
Thanks for the info!

Did the `test` directory exist before running with `--nfconfig`? If not, its definitely a bug. If it did exist, then I think `force` is acting how it should.

If you are ok with overwriting, then setting `force = true` in the config file is the way to go.

**Comment by simone-pignotti** [comment]
No, the directory didn't exist in the current working directory (nor in the conda env's directory according to `find`). In any case using `force` works. What puzzles me is the different behavior for config file vs command-line!
Thanks

**Comment by rpetit3** [comment]
Do you think you could try it again in an empty directory? I haven't been able to replicate it. 

```
mkdir test-config
cd test-config
echo "outdir = 'bactopia-out'" > test-params.config
bactopia --accession SRX1390608 --nfconfig test-params.config

... OR for you I think ...
bactopia --fastqs ../reads.txt --nfconfig test-params.config
```

**Comment by simone-pignotti** [comment]
Ok that works in a fresh empty directory. It may have been the result of repeated failed executions in the same directory, although the outdir didn't exist.
I will close and re-open if I manage to reproduce this in a simpler context. In any case `--force` does its job, so it's not really an important issue. Thanks again!
