### ISSUE TITLE
[question] Cloud execution docs

### ISSUE THREAD

**Issue by simone-pignotti** [bactopia/bactopia#167]
First, thanks for describing your experience [using AWS Batch to process 67,000 genomes with Bactopia](https://read-lab-confederation.github.io/blog/posts/bactopia-aws-and-67000-genomes/) in such details.

By digging a bit in Bactopia's code I noticed that a lot of the AWS batch-specific code has been already implemented in the master branch (sample-based tags to run all the steps for a given sample in the same machine, nextflow profile, all the "Verify AWS files were staged" stuff...).
Does this mean that using Bactopia on AWS is (almost) as easy as using `-profile awsbatch -w s3://mybucket`? I am sure you have plans to include this in the docs, but if it's really that easy I may try this adventure without documentation :)

On the other hand, I am not personally familiar with AWS batch and have been trying to get Bactopia working with [Google Cloud Life Sciences](https://cloud.google.com/life-sciences) without success. On paper, it should be [pretty easy](https://www.nextflow.io/docs/latest/google.html#google-lifesciences) to execute nextflow workflows on G cloud, but my first attempt didn't work. Here are the config and log if you are interested in taking a look. Of course I used `-w gs://bactopia-test-1/bactopia` command-line option, and all the required files (reads, `reads.txt` and `datasets`) are in the bucket at the right place. Any suggestion is welcome!
[gcls.log](https://github.com/bactopia/bactopia/files/5683539/gcls.log)
[nextflow.config.txt](https://github.com/bactopia/bactopia/files/5683541/nextflow.config.txt)

**Comment by rpetit3** [comment]
Hi @simone-pignotti!


### AWS Batch
Thank you very much for taking a look at the blog post. So, yes, I think setting up Bactopia for AWS Batch would be straight forward. But I highly recommend you go with a wrapper around Bactopia (Phase 4 in my post).

Steps:
1. [Create AMI (link to instructions)](https://gist.github.com/rpetit3/01f27f52273104bbf609ed5acc9b63a9) 
2. [Grab the bactopia-wrapper](https://gist.github.com/rpetit3/fe1f5428be135852ec90bfb63aa32c93)
    - I randomly split outputs between two of our servers to help with download speeds, so you thill need to make edits
    - Adjust config to fit your needs: [L44-L71](https://gist.github.com/rpetit3/fe1f5428be135852ec90bfb63aa32c93#file-nextflow-config-L44-L71)

I think that is it (haha sure I missed something), either way happy to help out. If your inputs are on S3, you'll want to prefix the parameters with `s3://`

Example:
```
bactopia --R1 s3://my-bucket/fastqs/sample_R1.fastq.gz \
         --R2 s3://my-bucket/fastqs/sample_R2.fastq.gz \
         --datasets s3://my-bucket/datasets \
         --outdir s3://my-cucket/bactopia-runs
```


### GCS
Now, as for the GCS question, I have not tested Bactopia on GCS. I also agree it should work. You might want to check out [Nextflow's Google Cloud Docs](https://www.nextflow.io/docs/latest/google.html#) for getting setup. (If you haven't already).

I think this might be the issue:
```
Not a conda environment: /home/simone/.miniconda/envs/bactopia/share/bactopia-1.5.x/conda/envs/antimicrobial_resistance-1.5.x
```

(This is also kind of a bug to me, since you launch Bactopia with a docker containter, so downstream should also use containers. At least thats what I think)

In you nextflow.config. inside the `google` section you will need to add the following:

```
process {
    withName: 'annotate_genome|make_blastdb|blast_genes|blast_primers|blast_proteins|plasmid_blast' {
        container = "bactopia/annotate_genome:${container_version}"
    }
    withName: 'update_antimicrobial_resistance|antimicrobial_resistance' {
        container = "bactopia/antimicrobial_resistance:${container_version}"
    }
    withName: ariba_analysis {
        container = "bactopia/ariba_analysis:${container_version}"
    }
    withName: assemble_genome {
        container = "bactopia/assemble_genome:${container_version}"
    }
    withName: assembly_qc {
        container = "bactopia/assembly_qc:${container_version}"
    }
    withName: 'call_variants|call_variants_auto|mapping_query' {
        container = "bactopia/call_variants:${container_version}"
    }
    withName: count_31mers {
        container = "bactopia/count_31mers:${container_version}"
    }
    withName: download_references {
        container = "bactopia/download_references:${container_version}"
    }
    withName: 'estimate_genome_size|minmer_sketch|minmer_query' {
        container = "bactopia/minmers:${container_version}"
    }
    withName: 'gather_fastqs' {
        container = "bactopia/gather_fastqs:${container_version}"
    }
    withName: 'fastq_status|qc_reads|qc_original_summary|qc_final_summary' {
        container = "bactopia/qc_reads:${container_version}"
    }
    withName: sequence_type {
        container = "bactopia/sequence_type:${container_version}"
    }
}
```

I'll get a google section added to Bactopia's `profiles.conf` something like [this (awsbatch)](https://github.com/bactopia/bactopia/blob/master/conf/profiles.config#L19-L22), Because I think its best if you don't have to deal with the Docker bit, just your GCS specific settings.

I'll also see if I can round up some credits to give Bactopia a go on GCS.

**Comment by simone-pignotti** [comment]
Wow thanks a lot for all this precious information!

I will test the google version with the process-specific containers and the `--datasets gs://my-bucket/datasets --outdir gs://my-cucket/bactopia-runs --R1 gs://my-bucket/fastqs/sample_R1.fastq.gz --R2 gs://my-bucket/fastqs/sample_R2.fastq.gz`, although my understanding was that by using `-w gs://my-bucket/some-dir` (can't use the bucket without subdirectory according to Nextflow's docs) every other relative path should be prefixed automatically.

Will keep you posted, thanks again!

**Comment by rpetit3** [comment]
Give me ~20 minutes, I just noticed dockerhub doesn't have the 1.5.x containers

**Comment by rpetit3** [comment]
Had a bit of a DNS issue on my end, fixed it and am now actually building.

**Comment by rpetit3** [comment]
I think everything should be good now

**Comment by simone-pignotti** [comment]
Thanks again @rpetit3, finally I went the AWS road because I figured it would take me a while to port all your optimizations to GC.

It was all pretty straightforward, but my jobs are stuck in `RUNNABLE` state. I think this is a problem with the AMI, because using the default Amazon Linux 2 AMI with test jobs (using the exact same configuration and amount of resources as my bactopia AMI) works fine. The same test jobs, with the only difference being the underlying bactopia AMI, won't be scheduled. To be precise, the instances ARE created by AWS batch, but they are not detected and attached to the auto-scaling group, so I believe there is some aws component missing in the AMI.
I also checked all the common issues listed [here](https://aws.amazon.com/premiumsupport/knowledge-center/batch-job-stuck-runnable-status/).
I created the AMI starting from the ECS-optimized Amazon Linux 2 default image (the same which works with the test jobs), and only ran [your script](https://gist.github.com/rpetit3/01f27f52273104bbf609ed5acc9b63a9) before imaging the disk, so I don't see what I could have deactivated. Did you encounter similar issues, or have any advice about what to test?

And, another quick question :) what is the difference between the aws and the non-aws docker images? The aws ones are only available for version 1.4.x, so I was wondering whether I can replace them with the non-aws versions in the `awsbatch` profile.

PS: for future readers, when you create the instance to build your AMI, allow for 30GB storage to make sure all the environments and datasets will fit, and also so that the future instances created with the same AMI will have the same storage by default, allowing to store the temporary job results.

**Comment by rpetit3** [comment]
Yes, I should have mentioned the AMI should be based on an ECS-optimized Amazon Linux 2 AMI and a minimum space of 30-50gb. Good catch!

The AWS docker images are from my docker-within-docker attempts, and will be deleted. They are really small and only mount a directory from the instance that has the Conda environment.

If you are going to use Docker, use the [non-AWS versions](https://github.com/bactopia/bactopia/blob/master/conf/docker.config). Also, with Docker, you should be able to use the default ECS-Optimized AMI since the Docker containers have the Conda environments.

See if you can get Batch working with Docker containers. Once there, we can see about modifying the Bactopia AMI and [wrapper](https://gist.github.com/rpetit3/fe1f5428be135852ec90bfb63aa32c93) to fit your needs.

**Comment by simone-pignotti** [comment]
Thank you, I actually asked about Docker because the `nextflow.config` attached to your wrapper gist has the options `docker.enabled = true` and `process.container = "bactopia/aws-bactopia:1.4.x"`, so I figured that even with the conda version you somehow needed to use a container for AWS batch to schedule jobs, even on instances running the conda-based AMI. If that's not the case, can docker be completely avoided?

In any case I may have found the problem with my AMI: I had not stopped the ECS container agent (step 4 [here](https://docs.aws.amazon.com/batch/latest/userguide/create-batch-ami.html)). I am testing the new AMI and will let you know if that works!

I have also adapted the wrapper to work with --fastqs from S3 (first I manually added the S3 prefix to the output of `bactopia prepare`, I think it would be really useful to add an option like "alternative prefix" to this command which joins the prefix and the relative path, instead of always using the absolute path in the current machine!). I am attaching it here together with my custom config in case it is of help to someone else. Beware, quick and dirty solution!
[bactopia-aws-wrapper-fastqs.nf.txt](https://github.com/bactopia/bactopia/files/5696572/bactopia-aws-wrapper-fastqs.nf.txt)
[nextflow.config.txt](https://github.com/bactopia/bactopia/files/5696574/nextflow.config.txt)

**Comment by simone-pignotti** [comment]
Ok some progress here! I confirm the problem with the AMI was me forgetting to stop the ECS container agent. Now jobs get scheduled by AWS batch, but fail because it looks like the `bactopia/aws-bactopia:1.4.x` container can't copy stuff from S3:
```
2020-12-15T15:56:41.862+01:00 | download failed: s3://my-bucket/tmp/a9/6117b7157712dac1d195e94dae1de4/.command.run to - An error occurred (403) when calling the HeadObject operation: Forbidden
2020-12-15T15:56:42.284+01:00 | upload failed: ./.command.log to s3://my-bucket/tmp/a9/6117b7157712dac1d195e94dae1de4/.command.log An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
```
The `aws s3 cp` command works for the same file from an instance running the AMI. Here is the command I used:
```
nextflow run bactopia-aws-wrapper-fastqs.nf -c nextflow.config -bucket-dir s3://my-bucket/tmp -profile awsbatch --fastqs s3://my-bucket/reads.txt
```
Here's the container's volumes and entrypoint:
```
Volumes
=======
aws-cli | /home/ec2-user/miniconda3
vol-1   | /home/ec2-user/bactopia
vol-2   | /home/ec2-user/datasets
vol-3   | /home/ec2-user/bactopia-envs


Mount points
============
Container path               | Source volume | Read only
/home/ec2-user/miniconda3    | aws-cli       | True
/home/ec2-user/bactopia      | vol-1         | False
/home/ec2-user/datasets      | vol-2         | False
/home/ec2-user/bactopia-envs | vol-3         | False

Command
=======
["bash","-o","pipefail","-c","trap \"{ ret=$?; /home/ec2-user/miniconda3/bin/aws --region eu-west-3 s3 cp --only-show-errors .command.log s3://my-bucket/tmp/a9/6117b7157712dac1d195e94dae1de4/.command.log||true; exit $ret; }\" EXIT; /home/ec2-user/miniconda3/bin/aws --region eu-west-3 s3 cp --only-show-errors s3://my-bucket/tmp/a9/6117b7157712dac1d195e94dae1de4/.command.run - | bash 2>&1 | tee .command.log"]
```
I think the problem is that the container does not have access to `/home/ec2-user/.aws`, where config and credentials are stored. I also think that could be easily solved by passing the credentials as environment variables, although it's not the safest way. I will try to play around with AWS' secrets and see if I can get around that!

**Comment by rpetit3** [comment]
#### First comment

You figured correctly, Docker is required and cannot be avoided. 

I was mistaken on your earlier comment about the aws containers. The `aws-bactopia:1.4.x` will stay and the Dockerfile is [here](https://github.com/bactopia/bactopia/edit/master/.awsbatch.Dockerfile), this container is the one I used with the wrapper. Also, looking at the recipe, I didn't need to make it "1.4.x". There's nothing in it that's version dependent, so I will create a latest tag so it can be replaced with ``aws-bactopia`.

There are a bunch of other containers (e.g. aws-annotate_genome, aws-assemble_genome, etc...) which will be deleted.

Your suggestion for `bactopia prefare` is fantastic! I'm going to create a new issue for it.

One thing, I should mention was an issue I came across related to `uploadStorageClass`, Nextflow doesn't always honor it (See: https://github.com/nextflow-io/nextflow/issues/1762). Also, I wasn't aware, but the infrequent access storage classes have a fee if files are deleted within 30 days of creation. Haha I thought I was going to save lots of money, but ended up just paying fees.

#### Second comment
Progress! Yay!

For the AMI creation did, you run `aws configure` (https://gist.github.com/rpetit3/01f27f52273104bbf609ed5acc9b63a9#file-setup-bactopia-aws-sh-L28).

**Comment by simone-pignotti** [comment]
> I will create a latest tag so it can be replaced with `aws-bactopia`
Great, thanks a lot!
>Also, I wasn't aware, but the infrequent access storage classes have a fee if files are deleted within 30 days of creation. Haha I thought I was going to save lots of money, but ended up just paying fees.
Oups...that's a really good tip, thanks, I will change it immediately :)
>For the AMI creation did, you run `aws configure`
Yes I did, and `aws s3 cp` works if I run it from a fresh instance created from that AMI. I am pretty sure it's the lack of `/home/ec2-user/.aws` mount point that is problematic. I believe [this](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html) may be the best solution (according to this [old post](https://forums.aws.amazon.com/message.jspa?messageID=763613)).

**Comment by rpetit3** [comment]
This is uncharted grounds for me. Since I downloaded from SRA. But its definitely something I'm interested in. 

Do you think adding `/home/ec2-user/.aws` to `volumes = ['/home/ec2-user/bactopia', '/home/ec2-user/datasets', '/home/ec2-user/bactopia-envs']` in the config is worth a try?

I meet with my boss today and had planned on asking for the ok test Bactopia on GCS and AWS (through University). So I can help with this afterwards, haha but honestly you might have it all figured out by then!


Heads up, I'm testing out GitHub Discussions so I made a [post for your `bactopia prepare` suggestion](https://github.com/bactopia/bactopia/discussions/170). Please feel free to add any thoughts or details I missed

**Comment by rpetit3** [comment]
Just curious (for if I get ok to test), are launching the job from a local machine or another AWS instance?

**Comment by simone-pignotti** [comment]
From another AWS instance

**Comment by simone-pignotti** [comment]
Ok more progress! Using IAM task roles is definitely the way to go. It is not extremely intuitive but [this](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html) and [this](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html) helped. The first link explains how to assign IAM roles to task (in this case the role to access S3), while the second explains how to allow your user to pass roles to instances (which got me stuck for a while...).
On nextflow's side, you can specify the new role's ARN directly in the config:
```
aws.batch.jobRole = 'arn:aws:iam::123456789:role/yourRole'
```

Now I have a nextflow problem though :) I get the following error:
```
  Invalid input (--R1), please verify "001-r1" exists.
  Invalid input (--R2), please verify "001-r2" exists.
```
certainly due to my inexperience with nextflow. If you have a second to take a look to my [modified wrapper](https://github.com/bactopia/bactopia/files/5696572/bactopia-aws-wrapper-fastqs.nf.txt) from the previous comment (which should work with the `--fastqs` option) I would be extremely grateful! I just copy-pasted from the bactopia's `main.nf`, so I assumed the expansion would work. For the record, the reads are successfully downloaded to the work directory, and I encountered the error even with local execution...

**Comment by rpetit3** [comment]
Got the OK to test AWS and GCS. 

But first I'm going to try your wrapper locally, to see if its one of those Nextflow things.

**Comment by rpetit3** [comment]
Found the issue! 

```
    """
    mkdir !{sample}-run
    cd !{sample}-run  <--------------------------RIGHT HERE, We cd'd up a directory so --R1 and --R2 need a ../
    if nextflow run !{opts}; then
        # Everything finished, pack up the results and clean up
        mkdir complete/
        mv bactopia-info/ !{sample}/ complete/
        tar -cf - complete/ | pigz -n --best -p !{task.cpus} > !{sample}-complete.tar.gz
        mv !{sample}-complete.tar.gz ../
    else
        # Run failed
        if [[ "!{allow_failed}" == 'true' ]]; then
            # We've tried enough times, pack it up
            mkdir incomplete
            mv .nextflow* work/* bactopia-info/ !{sample}/ incomplete/
            tar -cf - incomplete/ | pigz -n --best -p !{task.cpus} > !{sample}-incomplete.tar.gz
            mv !{sample}-incomplete.tar.gz ../
	else
            rm -rf !{sample}-run
            exit 1
        fi
    fi
    cd ..
    rm -rf !{sample}-run
    """

```

Opts should look like this: (I also explicitly only use the first element of r1 and r2)
```
opts = "${bactopia}/main.nf -c ${bactopia}/nextflow.config --R1 ../${r1[0]} --R2 ../${r2[0]} --datasets ${datasets} --condadir ${conda} -qs ${task.cpus}"
```

**Comment by simone-pignotti** [comment]
Yay!!! Thank you SO much, it worked!
I mean, there was one last obstacle but I found a fix: for those who, like me, made the mistake of using a really small disk when they created the AMI, you can use a custom [launch template](https://aws.amazon.com/premiumsupport/knowledge-center/batch-ebs-volumes-launch-template/) in your compute environment to increase the volume size. Note that multiple jobs can still be scheduled on the same spot instance, even when using the wrapper, so I would allow for 100GB to be safe.
In any case the test jobs are running fine now, if they complete as they should...it's time to scale up :)

I hope someone else will find this helpful, so to recapitulate:
- Create an AMI based on ECS-optimized Amazon Linux 2 with sufficient disk space using [these instructions](https://gist.github.com/rpetit3/01f27f52273104bbf609ed5acc9b63a9) (stopped the ECS container agent - step 4 [here](https://docs.aws.amazon.com/batch/latest/userguide/create-batch-ami.html))
- Customize the [wrapper](https://gist.github.com/rpetit3/fe1f5428be135852ec90bfb63aa32c93) and the associated config file
- Use `bactopia prepare` to create the reads list and modify the file paths to look like `s3://your-bucket/reads/sample_R1.fastq.gz`
- Create an S3 bucket and upload the reads and the reads list to it
- Create an IAM role for tasks to access S3 (guidance [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html) and [here](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html)), then reference it in the nextflow config file: `aws.batch.jobRole = 'arn:aws:iam::123456789:role/yourRole'`
- Optionally, if the disk space is not enough, create a [launch template](https://aws.amazon.com/premiumsupport/knowledge-center/batch-ebs-volumes-launch-template/) to associate with the compute environment to increase the default volume for the instances based on your AMI
- Create an AWS batch compute environment (optionally with the custom launch template, or just by specifying the AMI if it has a big enough disk already) and a queue associated to it: the queue name will be referenced in the nextflow config (nf-batch-spot in the example)
- Run the wrapper using something like `nextflow run wrapper.nf -c nextflow.config -bucket-dir s3://your-bucket/tmp -profile awsbatch --fastqs s3://your-bucket/reads.txt ` (only tested from an AWS instance)

**Comment by rpetit3** [comment]
That's great to hear! Glad you were able to get it going!

**Comment by simone-pignotti** [comment]
Actually...one more question :) a considerable amount of time is spent in the `update_antimicrobial_resistance` process, for each job. Is it possible to skip this step? The dataset directory in my AMI already contains `datasets/ariba/card.tar.gz` and `datasets/ariba/vfdb_core.tar.gz`

**Comment by rpetit3** [comment]
`update_antimicrobial_resistance` is for AMRFinder+. I had to split AMRFinder+ into two steps `update_antimicrobial_resistance` and `antimicrobial_resistance` due to this issue https://github.com/ncbi/amr/issues/16.

But it's fixed now, so I can totally revisit and probably drop the `update_antimicrobial_resistance` step.
