### ISSUE TITLE
check_gtdb error[question]

### ISSUE THREAD

**Issue by kusandeep** [bactopia/bactopia#168]
Hi I am trying to run gtdb tool and getting the error below.
Any clue what I am doing wrong?
executor >  local (3)
[f5/66bc21] process > download_gtdb [100%] 1 of 1 ✔
[c9/e69ba7] process > check_gtdb    [100%] 2 of 2, failed: 2, retries: 1 ✘
[-        ] process > gtdb          -
[19/c0eba9] NOTE: Process `check_gtdb` terminated with an error exit status (127) -- Execution is retried (1)
Error executing process > 'check_gtdb'

Caused by:
  Process `check_gtdb` terminated with an error exit status (127)

Command executed:

  gtdbtk check_install && touch gtdb-passed.txt

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 2: gtdbtk: command not found

Work dir:
  /bifo/itmp/SK_PMI/bactopia_out/maze_runner/run1/work/c9/e69ba7ca46c26b12652ed3f870d87e

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

**Comment by rpetit3** [comment]
Well that's no good. I'm going to try an replicate locally. v1.5.0 had some changes made to how conda environments are handled for Bactopia Tools.

Are you running bactopia on a cluster or something with a job scheduler?

**Comment by kusandeep** [comment]
I am running it on a local server i assume u can call it a cluster?  Also, first I hought my gtdb databse is courrepted so I ran the whole thing with --download_gtdb option but got the error as below.

Command Line    : nextflow run /dataset/SK_PMI/itmp/conda-envs/bactopia//share/bactopia-1.4.x/tools/gtdb/main.nf --bactopia /bifo/itmp/SK_PMI//bactopia_out/maze_runner/run1/ --gtdb /dataset/datacache/scratch/bactopia/gtdb/ --download_gtdb /dataset/datacache/scratch/bactopia/gtdb/ --outdir /bifo/itmp/SK_PMI//bactopia_out/maze_runner/run1/ --include pseudomonas_only.txt --cpus 16 --force
    Resumed         : false
    Completed At    : 2020-12-15T08:32:14.685133+13:00
    Duration        : 11s
    Success         : false
executor >  local (2)
[6e/f32fe7] process > download_gtdb [100%] 2 of 2, failed: 2, retries: 1 ✘
[-        ] process > check_gtdb    -
[-        ] process > gtdb          -
[60/04c6d7] NOTE: Process `download_gtdb` terminated with an error exit status (127) -- Execution is retried (1)
Error executing process > 'download_gtdb'

Caused by:
  Process `download_gtdb` terminated with an error exit status (127)

Command executed:

  if [ "true" == "true" ]; then
      rm -rf /dataset/datacache/scratch/bactopia/gtdb//gtdbtk_data.tar.gz
      download-db.sh
  else
      echo "skipping GTDB database download"
  fi

  touch gtdb-downloaded.txt

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 4: download-db.sh: command not found

Work dir:
  /bifo/itmp/SK_PMI/bactopia_out/maze_runner/run1/work/6e/f32fe771cc7e836e753be748883f3b

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

**Comment by rpetit3** [comment]
Can definitely be run on both. I was curious because I've seen issues with using conda with job scheduler. Sometimes the job schedulers directories to the PATH that end up before conda  which cause problems.

Which version of bactopia are you using? (`bactopia --version`)

**Comment by kusandeep** [comment]
I am on bactopia 1.4.11

**Comment by rpetit3** [comment]
It almost seems like its not building the conda environment. 

Do you get something like the following when running the tool? 
```
Creating Conda env: /local/home/rpetit/miniconda3/envs/bactopia-1.4.11/share/bactopia-1.4.x/tools/gtdb/environment.yml [cache /local/home/rpetit/bactopia-dev/work/conda/bactopia-gtdb-1696650c68a6d4f33337c4e8e0528816]
```

**Comment by kusandeep** [comment]
No do not get this.  Below is the complete information

(/dataset/SK_PMI/itmp/conda-envs/bactopia) kumars@invbfopp10:/dataset/SK_PMI/itmp/bactopia_out/maze_runner/run1$ bactopia tools gtdb --bactopia /bifo/itmp/SK_PMI//bactopia_out/maze_runner/run1/ --gtdb /dataset/datacache/scratch/bactopia/gtdbtk/ --outdir /bifo/itmp/SK_PMI//bactopia_out/maze_runner/run1/ --include pseudomonas_only.txt --cpus 16 --force
N E X T F L O W  ~  version 20.07.1
Launching `/dataset/SK_PMI/itmp/conda-envs/bactopia/share/bactopia-1.4.x/tools/gtdb/main.nf` [sick_mestorf] - revision: f28d5690f5
bactopia tools gtdb - 1.4.11
Including 37 samples for analysis
Found 36 samples to process
If this looks wrong, now's your chance to back out (CTRL+C 3 times).
Sleeping for 5 seconds...
executor >  local (3)
[49/3c7355] process > download_gtdb [100%] 1 of 1 ✔
[04/f2d6c7] process > check_gtdb    [ 50%] 1 of 2, failed: 1, retries: 1
[-        ] process > gtdb          -
[e4/ddd568] NOTE: Process `check_gtdb` terminated with an error exit status (127) -- Execution is retried (1)
Error executing process > 'check_gtdb'

Caused by:
  Process `check_gtdb` terminated with an error exit status (127)

Command executed:

  gtdbtk check_install && touch gtdb-passed.txt

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 2: gtdbtk: command not found

Work dir:
  /bifo/itmp/SK_PMI/bactopia_out/maze_runner/run1/work/04/f2d6c7e606ce654f738be6937a3bb0

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

    Bactopia Tool 'gtdb' - Execution Summary
    ---------------------------
    Command Line    : nextflow run /dataset/SK_PMI/itmp/conda-envs/bactopia//share/bactopia-1.4.x/tools/gtdb/main.nf --bactopia /bifo/itmp/SK_PMI//bactopia_out/maze_runner/run1/ --gtdb /dataset/datacache/scratch/bactopia/gtdbtk/ --outdir /bifo/itmp/SK_PMI//bactopia_out/maze_runner/run1/ --include pseudomonas_only.txt --cpus 16 --force
    Resumed         : false
    Completed At    : 2020-12-15T10:42:57.060208+13:00
    Duration        : 11.9s
    Success         : false
executor >  local (3)
[49/3c7355] process > download_gtdb [100%] 1 of 1 ✔
[04/f2d6c7] process > check_gtdb    [100%] 2 of 2, failed: 2, retries: 1 ✘
[-        ] process > gtdb          -
[e4/ddd568] NOTE: Process `check_gtdb` terminated with an error exit status (127) -- Execution is retried (1)
Error executing process > 'check_gtdb'

Caused by:
  Process `check_gtdb` terminated with an error exit status (127)

Command executed:

  gtdbtk check_install && touch gtdb-passed.txt

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 2: gtdbtk: command not found

Work dir:
  /bifo/itmp/SK_PMI/bactopia_out/maze_runner/run1/work/04/f2d6c7e606ce654f738be6937a3bb0

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

(/dataset/SK_PMI/itmp/conda-envs/bactopia) kumars@invbfopp10:/dataset/SK_PMI/itmp/bactopia_out/maze_runner/run1$

**Comment by kusandeep** [comment]
I also tried deactivating conda and reactivating again, no luck. Do you recon I should update bactopia to 1.5, if so how..?

**Comment by rpetit3** [comment]
You could try deleting the `work` directory. If you don't want to delete it all, there might be something like this:
```
work/conda/bactopia-gtdb-*
```

Deleting this directory (if it exists) should force the env to be rebuilt.

Otherwise, I would suggest the bump up to 1.5. To do so, while in your bactopia environment run:

```
conda update -c conda-forge -c bioconda bactopia
```

**Comment by kusandeep** [comment]
so I deleted the whole work directory and updated the bactopia to 1.5, everything seems to be in order now and running smoothly.
Thank you very much for your
 help.

**Comment by rpetit3** [comment]
Glad to hear you're moving again!

**Comment by rpetit3** [comment]
Going to close this for now, please feel free to reopen
