### ISSUE TITLE
[question] Does bactopia build process use the proxy server in .condarc file?

### ISSUE THREAD

**Issue by koolape** [bactopia/bactopia#182]
I have set a proxy server in `.condarc` file. If I run `bactopia build --default`, will the build process use the proxy as well?

**Comment by rpetit3** [comment]
I'm not sure, here's the command (https://github.com/bactopia/bactopia/blob/master/bin/helpers/bactopia-build.py#L171) used to build the environments.

If .condarc is loaded automatically by Conda then it should work, but if its something that needs to be explicitly loaded, then it won't work currently.

The next version of Bactopia will no longer have a need to use my personal (rpetit3) conda channel.

**Comment by rpetit3** [comment]
Quick update, the next version of bactopia will no longer use packages from my personal channel.

**Comment by rpetit3** [comment]
I've release v1.5.5 (https://github.com/bactopia/bactopia/releases/tag/v1.5.5). My personal `rpetit3` channel will no longer be required, so I think you should be good to use mirrors.

Going to close this for now, please feel free to reopen!

**Comment by koolape** [comment]
Thanks for the change!
Btw, in my test a few days ago, I've alredy confugred anaconda to use my proxy and the bactopia build proces did follow the proxy setting. However, I also noticed that some files were downloaed by wget during build process, for which I have not configured wget to use proxy.

**Comment by rpetit3** [comment]
If there are steps in `bactopia build` that use wget I think that's conda related. Some tools (I think checkm us one) that will download a database post install.

On the other hand, I know for certain I use wget for downloading some datasets in `bactopia datasets`
