### ISSUE TITLE
Using Bactopia prepare with long fastq.gz file names[question]

### ISSUE THREAD

**Issue by zirbez** [bactopia/bactopia#192]
Hello,

I was wondering if there is a way to use Bactopia's prepare function on a directory full of fastq's that have long names containing numbers. They do follow a pattern, and some examples are provided below:

```
AF2001-IA-M05216-200813_S1_L001_R1_001.fastq.gz
AF2001-IA-M05216-200813_S1_L001_R1_001.fastq.gz
AF2002-IA-M05216-200826_S30_L001_R1_001.fastq.gz
AF2002-IA-M05216-200826_S30_L001_R2_001.fastq.gz
... (etc.)
AF2243-IA-M05216-200824_S11_L001_R1_001.fastq.gz
AF2243-IA-M05216-200824_S11_L001_R2_001.fastq.gz
... (etc.)
```

I tried using the following to prepare the FOFN:

```
(bactopia) [zirbez@argon-itf-login-3 pairedReads]$ bactopia prepare --pe1_pattern "L001_R1_001" --pe2_pattern "L001_ R2_001" ~/WGS_2018_Staph/pairedReads/ > WGS.txt
```

But was met with the following errors:

```
ERROR: Could not determine read set for "AF2243-IA-M05216-200824_S11_L001_R2_001".
ERROR: Found 001 expected (R1: L001_R1_001 or R2: L001_ R2_001)
ERROR: Please use --pe1_pattern and --pe2_pattern to correct and try again.
```
I have tried several variations of patterns, such as "R1"/"R2", "R1_001"/"R2_001", and "_L001_R1_001"/"_L001_R2_001"

Any help would be greatly appreciated! Thank you!

**Comment by rpetit3** [comment]
Hey! Hope all is well on your end @zirbez.

Since it looks like all the extensions are "_001.fastq.gz" you can try:
```
bactopia prepare ~/WGS_2018_Staph/pairedReads/  --fastq_ext "_001.fastq.gz"
```

**Comment by zirbez** [comment]
I am happy to report that upon moving my work to our cluster, I was able to smoothly progress through the rest of the tutorial and am looking forward to processing our sequences. I hope you are also doing well @rpetit3!

Your suggestion worked like a charm, thank you again for your help!
