### ISSUE TITLE
Unicycler for short reads only

### ISSUE THREAD

**Issue by haruosuz** [bactopia/bactopia#198]
Bactopia can run Unicycler even if I only have short reads?

I wonder how to run Bactopia to process multiple samples (paired-end reads only) using Unicycler?

References:
- https://bactopia.github.io/tutorial/#multiple-samples-fofn
- https://github.com/rrwick/Unicycler/blob/master/README.md#a-note-on-trycycler
If you only have short reads, use Unicycler (Trycycler does not do short-read assembly).

**Comment by rpetit3** [comment]
Hi @haruosuz!

At the moment, this is not possible. But, I think with a few tweaks I can make this happen. 

I'll update soon!
Robert

**Comment by rpetit3** [comment]
Hi @haruosuz 

I've added this in https://github.com/bactopia/bactopia/commit/82d0b57712847477ef5ea0335c13e28d51eddc9d and it will be in the next version.

You will be able to give `--assembler unicycler` to use Unicycler on Illumina only read sets.

**Comment by rpetit3** [comment]
I've released v1.6.2, which will allow you to use unicycler on Illumina reads only.

Please let me know if there are any issues. I'm going to close this for now. Thank you for your suggestion!

**Comment by haruosuz** [comment]
Thank you. To process multiple samples (only paired-end reads `_R1.fastq.gz` `_R2.fastq.gz` for each sample) using Unicycler, Could I run Bactopia as follows?
```
bactopia prepare fastqs/ > fastqs.txt

bactopia --fastqs fastqs.txt \
         --datasets datasets/ \
         --assembler unicycler \
         --outdir local-multiple-samples-paired-end
```

References
https://bactopia.github.io/tutorial/#local-samples
https://bactopia.github.io/tutorial/#paired-end
https://bactopia.github.io/tutorial/#multiple-samples-fofn
https://github.com/bactopia/bactopia/blob/master/README.md#quick-start

**Comment by rpetit3** [comment]
Yep! Once v1.6.2 is available on BioConda that should work.
