### ISSUE TITLE
[bug] create database

### ISSUE THREAD

**Issue by marcelladane** [bactopia/bactopia#199]
**Description**
Hello, me again, long time I dont bother you. =)
I needed to reinstall bactopia in the new server and it is failing to create the database. 

**Steps to Reproduce**
I installed the environment, but it found some issues to resolve the environment. After a while, it worked. Then I activated bactopia and tried to create the DB.
I used the following command:
```
Command:
bactopia datasets --outdir /ceph/db/bactopia/ --ariba "argannot, card, megares, plasmidfinder, srst2_argannot, vfdb_full, virulencefinder" --cpus 16

```
The error that shows is as follow:

ERROR: I tried to get the version of bowtie2 with: "/ceph/home/marcela.pereira/.conda/envs/bactopia/bin/bowtie2 --version" and the output didn't match this regular expression: ".*bowtie2.*version (.*)$"

Something wrong with at least one dependency. Please see the above error message(s)
ARIBA version: 2.14.6

External dependencies:
bowtie2 ERROR   /ceph/home/marcela.pereira/.conda/envs/bactopia/bin/bowtie2
cdhit   4.8.1   /ceph/home/marcela.pereira/.conda/envs/bactopia/bin/cd-hit-est
nucmer  3.1     /ceph/home/marcela.pereira/.conda/envs/bactopia/bin/nucmer

External dependencies OK: False

Python version:
3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37)
[GCC 9.3.0]
```

**Expected Behavior**
I was trying to create the database and got the following error

**Execution Environment**

- Bactopia Version: bactopia 1.6
- OS: remote server running linux
- Environment: conda
- 
- *Additional Information**
The part that is strange is that when I run "conda list -n bactopia" to see the pkg list, bowtie2 is there:
" bowtie2                   2.3.5.1          py37he513fc3_0    bioconda"

but this is the only pkg in the list that is in red. Have you ever faced this issue? 
Any idea on how to solve it?

Thx, Marcela

**Comment by rpetit3** [comment]
Hi @marcelladane!

Welcome back! This might be related to https://github.com/bioconda/bioconda-recipes/issues/22836. Could I get the output of `conda env export` for the bactopia environment?

Also was this built in a fresh environment?

Thanks!
Robert

**Comment by marcelladane** [comment]
Below you can find the output, exactly as its exported with color only for
bowtie2 version. And for your second question, this is build in a totally
fresh environment, since the old server is no longer running and we got a
new one, I am installing all over again.
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - alsa-lib=1.2.3=h516909a_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - ariba=2.14.6=py37hfa133b6_0
  - bactopia=1.6.1=0
  - bcftools=1.11=h7c999a4_0
  - beautifulsoup4=4.9.3=pyhb0f4dca_0
  - biopython=1.78=py37h5e8e339_2
  - blast=2.10.1=pl526he19e7b1_3
  - bowtie2=2.3.5.1=py37he513fc3_0
  - brotlipy=0.7.0=py37h5e8e339_1001
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.1=h36c2ea0_0
  - ca-certificates=2020.12.5=ha878542_0
  - cairo=1.16.0=h7979940_1007
  - capnproto=0.6.1=hfc679d8_1
  - cd-hit=4.8.1=h8b12597_3
  - certifi=2020.12.5=py37h89c1867_1
  - cffi=1.14.5=py37hc58025e_0
  - chardet=4.0.0=py37h89c1867_1
  - coloredlogs=15.0=py37h89c1867_0
  - conda=4.9.2=py37h89c1867_0
  - conda-package-handling=1.7.2=py37hb5d75c8_0
  - coreutils=8.31=h516909a_0
  - cryptography=3.4.4=py37hf1a17b8_0
  - curl=7.71.1=he644dc0_8
  - cycler=0.10.0=py_2
  - dendropy=4.5.2=pyh3252c3a_0
  - entrez-direct=13.9=pl526h375a9b1_1
  - enum34=1.1.10=py37hc8dfbb8_2
  - executor=23.2=pyhd3deb0d_0
  - expat=2.2.10=h9c3ff4c_0
  - fasteners=0.14.1=py_3
  - fontconfig=2.13.1=hba837de_1004
  - freetype=2.10.4=h0708190_1
  - gettext=0.19.8.1=h0b5b191_1005
  - giflib=5.2.1=h36c2ea0_2
  - graphite2=1.3.13=h58526e2_1001
  - gsl=2.6=he838d99_2
  - harfbuzz=2.7.4=h5cf4720_0
  - hmmer=3.3.2=he1b5a44_0
  - htslib=1.11=hd3b49d5_1
  - humanfriendly=9.1=py37h89c1867_0
  - icu=68.1=h58526e2_0
  - idna=2.10=pyh9f0ad1d_0
  - jpeg=9d=h36c2ea0_0
  - kiwisolver=1.3.1=py37h2527ec5_1
  - krb5=1.17.2=h926e7f8_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - libblas=3.9.0=8_openblas
  - libcblas=3.9.0=8_openblas
  - libcurl=7.71.1=hcdd3856_8
  - libdeflate=1.6=h516909a_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h2828fa1_18
  - libgfortran-ng=9.3.0=hff62375_18
  - libgfortran5=9.3.0=hff62375_18
  - libglib=2.66.7=h3e27bee_1
  - libgomp=9.3.0=h2828fa1_18
  - libiconv=1.16=h516909a_0
  - libidn2=2.3.0=h516909a_0
  - liblapack=3.9.0=8_openblas
  - libnghttp2=1.43.0=h812cca2_0
  - libopenblas=0.3.12=pthreads_h4812303_1
  - libpng=1.6.37=h21135ba_2
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-ng=9.3.0=h6de172a_18
  - libtiff=4.2.0=hdc55705_0
  - libunistring=0.9.10=h14c3975_0
  - libuuid=2.32.1=h7f98852_1000
  - libwebp-base=1.2.0=h7f98852_0
  - libxcb=1.13=h7f98852_1003
  - libxml2=2.9.10=h72842e0_3
  - libxslt=1.1.33=h15afd5d_2
  - llvm-meta=7.0.0=0
  - lxml=4.6.2=py37h77fd288_1
  - lz4-c=1.9.3=h9c3ff4c_0
  - mash=2.3=ha61e061_0
  - matplotlib-base=3.3.4=py37h0c9df89_0
  - monotonic=1.5=py_0
  - mummer=3.23=pl526he1b5a44_11
  - ncbi-amrfinderplus=3.10.1=h671e170_0
  - ncbi-genome-download=0.3.0=pyh864c0ab_1
  - ncurses=6.2=h58526e2_4
  - nextflow=20.10.0=hecda079_0
  - numpy=1.20.1=py37haa41c4c_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjdk=11.0.8=hacce0ff_0
  - openmp=7.0.0=h2d50403_0
  - openssl=1.1.1j=h7f98852_0
  - pcre=8.44=he1b5a44_0
  - perl=5.26.2=h36c2ea0_1008
  - perl-app-cpanminus=1.7044=pl526_1
  - perl-archive-tar=2.32=pl526_0
  - perl-base=2.23=pl526_1
  - perl-business-isbn=3.004=pl526_0
  - perl-business-isbn-data=20140910.003=pl526_0
  - perl-carp=1.38=pl526_3
  - perl-common-sense=3.74=pl526_2
  - perl-compress-raw-bzip2=2.087=pl526he1b5a44_0
  - perl-compress-raw-zlib=2.087=pl526hc9558a2_0
  - perl-constant=1.33=pl526_1
  - perl-data-dumper=2.173=pl526_0
  - perl-digest-hmac=1.03=pl526_3
  - perl-digest-md5=2.55=pl526_0
  - perl-encode=2.88=pl526_1
  - perl-encode-locale=1.05=pl526_6
  - perl-exporter=5.72=pl526_1
  - perl-exporter-tiny=1.002001=pl526_0
  - perl-extutils-makemaker=7.36=pl526_1
  - perl-file-listing=6.04=pl526_1
  - perl-file-path=2.16=pl526_0
  - perl-file-temp=0.2304=pl526_2
  - perl-html-parser=3.72=pl526h6bb024c_5
  - perl-html-tagset=3.20=pl526_3
  - perl-html-tree=5.07=pl526_1
  - perl-http-cookies=6.04=pl526_0
  - perl-http-daemon=6.01=pl526_1
  - perl-http-date=6.02=pl526_3
  - perl-http-message=6.18=pl526_0
  - perl-http-negotiate=6.01=pl526_3
  - perl-io-compress=2.087=pl526he1b5a44_0
  - perl-io-html=1.001=pl526_2
  - perl-io-socket-ssl=2.066=pl526_0
  - perl-io-zlib=1.10=pl526_2
  - perl-json=4.02=pl526_0
  - perl-json-xs=2.34=pl526h6bb024c_3
  - perl-libwww-perl=6.39=pl526_0
  - perl-list-moreutils=0.428=pl526_1
  - perl-list-moreutils-xs=0.428=pl526_0
  - perl-lwp-mediatypes=6.04=pl526_0
  - perl-lwp-protocol-https=6.07=pl526_4
  - perl-mime-base64=3.15=pl526_1
  - perl-mozilla-ca=20180117=pl526_1
  - perl-net-http=6.19=pl526_0
  - perl-net-ssleay=1.88=pl526h90d6eec_0
  - perl-ntlm=1.09=pl526_4
  - perl-parent=0.236=pl526_1
  - perl-pathtools=3.75=pl526h14c3975_1
  - perl-scalar-list-utils=1.52=pl526h516909a_0
  - perl-socket=2.027=pl526_1
  - perl-storable=3.15=pl526h14c3975_0
  - perl-test-requiresinternet=0.05=pl526_0
  - perl-time-local=1.28=pl526_1
  - perl-try-tiny=0.30=pl526_1
  - perl-types-serialiser=1.0=pl526_2
  - perl-uri=1.76=pl526_0
  - perl-www-robotrules=6.02=pl526_3
  - perl-xml-namespacesupport=1.12=pl526_0
  - perl-xml-parser=2.44_01=pl526ha1d75be_1002
  - perl-xml-sax=1.02=pl526_0
  - perl-xml-sax-base=1.09=pl526_0
  - perl-xml-sax-expat=0.51=pl526_3
  - perl-xml-simple=2.25=pl526_1
  - perl-xsloader=0.24=pl526_0
  - pillow=8.1.1=py37h4600e1f_0
  - pip=21.0.1=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - property-manager=3.0=py_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycosat=0.6.3=py37h5e8e339_1006
  - pycparser=2.20=pyh9f0ad1d_2
  - pyfastaq=3.17.0=py_2
  - pymummer=0.10.3=py_2
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pysam=0.16.0.1=py37hc334e0b_1
  - pysocks=1.7.1=py37h89c1867_3
  - python=3.7.10=hffdb5ce_100_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - readline=8.0=he28a2e2_2
  - requests=2.25.1=pyhd3deb0d_0
  - ruamel_yaml=0.15.80=py37h5e8e339_1004
  - samtools=1.11=h6270b1f_0
  - sed=4.8=he412f7d_0
  - setuptools=49.6.0=py37h89c1867_3
  - six=1.15.0=pyh9f0ad1d_0
  - soupsieve=2.0.1=py_1
  - spades=3.14.1=h2d02072_1
  - sqlite=3.34.0=h74cdb3f_0
  - tbb=2021.1.1=h4bd325d_0
  - tk=8.6.10=h21135ba_1
  - tornado=6.1=py37h5e8e339_1
  - tqdm=4.58.0=pyhd8ed1ab_0
  - unzip=6.0=h7f98852_2
  - urllib3=1.26.3=pyhd8ed1ab_0
  - verboselogs=1.7=py_0
  - wget=1.20.1=h22169c7_0
  - wheel=0.36.2=pyhd3deb0d_0
  - xorg-fixesproto=5.0=h14c3975_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxi=1.7.10=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxtst=1.2.3=h516909a_1002
  - xorg-recordproto=1.14.2=h516909a_1002
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.9=ha95c52a_0


=)

**Comment by rpetit3** [comment]
This all looks good! I'm going to see if I can replicate this and update soon.

Side-note: we've notices the conda installs (not just bactopia) taking much longer as well. I've started using [Mamba](https://github.com/mamba-org/mamba) more often, and might start recommending it to install Bactopia.

**Comment by rpetit3** [comment]
Oh! In the Bactopia environment, do you get this when trying `bowtie2 --version`?
```
(bactopia-test) rpetit@staphopia:~$ bowtie2 --version
/local/home/rpetit/miniconda3/envs/bactopia-test/bin/bowtie2-align-s: error while loading shared libraries: libtbb.so.2: cannot open shared object file: No such file or directory
(ERR): Description of arguments failed!
Exiting now ...
```

**Comment by marcelladane** [comment]
I actually didn't run that, but I tried to install another version of of
bowtie2. One before the 2.3.5 and it said all pkgs were already installed.

:)

**Comment by rpetit3** [comment]
It's looking like a new version of `tbb` is not working right with `bowtie2`

Let's try downgrading `tbb`:
```
conda install -y -c conda-forge 'tbb=2020.2'
```

Then try running `bowtie2 --version`:
```
bowtie2 --version
/local/home/rpetit/miniconda3/envs/bowtie2-latest/bin/bowtie2-align-s version 2.4.2
64-bit
Built on default-bf91a638-95fa-4b77-97c5-abccd9855c3e
Mon Nov  2 17:36:36 UTC 2020
Compiler: gcc version 7.5.0 (crosstool-NG 1.24.0.131_87df0e6_dirty)
Options: -O3 -msse2 -funroll-loops -g3 -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /local/home/rpetit/miniconda3/envs/bowtie2-latest/include -fdebug-prefix-map=/opt/conda/conda-bld/bowtie2_1604337828546/work=/usr/local/src/conda/bowtie2-2.4.2 -fdebug-prefix-map=/local/home/rpetit/miniconda3/envs/bowtie2-latest=/usr/local/src/conda-prefix -DPOPCNT_CAPABILITY -DWITH_TBB -std=c++11 -DNO_SPINLOCK -DWITH_QUEUELOCK=1
Sizeof {int, long, long long, void*, size_t, off_t}: {4, 8, 8, 8, 8, 8}
```

**Comment by marcelladane** [comment]
I will try that. :)

Thx a lot for the help. :)

**Comment by marcelladane** [comment]
Not it's working. :)
I also just answered your survey. Hope you like the idea. :)

And thx a lot for the help.

**Comment by rpetit3** [comment]
Great glad its working! And thank you very much for filling out the survey, it really means a lot! (Thank you!!)

I'll take a look.

I also submitted a PR (https://github.com/bioconda/bioconda-recipes/pull/27174) to bioconda to see about getting the bowtie recipe fixed.
