### ISSUE TITLE
bactopia bowtie2 ERROR

### ISSUE THREAD

**Issue by vertisAG** [bactopia/bactopia#200]
Hi,
I installed bactopia on my Linux system (Rhel 7)
In advance I have updated conda:
conda info
     active environment : bactopia
    active env location : /home/bcl2fastq/anaconda3/envs/bactopia
            shell level : 3
       user config file : /home/bcl2fastq/.condarc
 populated config files : /home/bcl2fastq/.condarc
          conda version : 4.9.2
    conda-build version : 3.20.5
         python version : 3.8.5.final.0
       virtual packages : __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/bcl2fastq/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/bcl2fastq/anaconda3/pkgs
                          /home/bcl2fastq/.conda/pkgs
       envs directories : /home/bcl2fastq/anaconda3/envs
                          /home/bcl2fastq/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Linux/3.10.0-1062.18.1.el7.x86_64 rhel/7.7.1908 glibc/2.17
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False

Then I wanted to build dataset
(bactopia) [bcl2fastq@LinuxWS ~]$ bactopia datasets
2021-03-05 11:06:52:root:INFO - Setting up Ariba datasets
2021-03-05 11:06:52:root:INFO - Setting up vfdb_core Ariba dataset
External command failed with exit code 1!

Command:
bash -c 'ariba prepareref -f ./datasets/ariba/vfdb_core.fa -m ./datasets/ariba/vfdb_core.tsv ./datasets/ariba/vfdb_core'

Standard error:
ERROR: I tried to get the version of bowtie2 with: "/home/bcl2fastq/anaconda3/envs/bactopia/bin/bowtie2 --version" and the output didn't match this regular expression: ".*bowtie2.*version (.*)$"

Something wrong with at least one dependency. Please see the above error message(s)
ARIBA version: 2.14.6

External dependencies:
bowtie2	ERROR	/home/bcl2fastq/anaconda3/envs/bactopia/bin/bowtie2
cdhit	4.8.1	/home/bcl2fastq/anaconda3/envs/bactopia/bin/cd-hit-est
nucmer	3.1	/home/bcl2fastq/anaconda3/envs/bactopia/bin/nucmer

External dependencies OK: False

Python version:
3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37) 
[GCC 9.3.0]

Python packages:
ariba	2.14.6	/home/bcl2fastq/anaconda3/envs/bactopia/lib/python3.7/site-packages/ariba/__init__.py
bs4	4.9.3	/home/bcl2fastq/anaconda3/envs/bactopia/lib/python3.7/site-packages/bs4/__init__.py
dendropy	4.5.2	/home/bcl2fastq/anaconda3/envs/bactopia/lib/python3.7/site-packages/dendropy/__init__.py
pyfastaq	3.17.0	/home/bcl2fastq/anaconda3/envs/bactopia/lib/python3.7/site-packages/pyfastaq/__init__.py
pymummer	0.10.3	/home/bcl2fastq/anaconda3/envs/bactopia/lib/python3.7/site-packages/pymummer/__init__.py
pysam	0.16.0.1	/home/bcl2fastq/anaconda3/envs/bactopia/lib/python3.7/site-packages/pysam/__init__.py

Python packages OK: True

Everything looks OK: False
Some dependencies not satisfied. Cannot continue.

Thank you for your help!

**Comment by rpetit3** [comment]
Hi @vertisAG 

There is currently and issue with Bowtie2 on Bioconda. The solution is to downgrade`tbb`. In your bactopia environment run the following:
```
conda install -y -c conda-forge **'tbb=2020.2'**
```

More details are avaialble here https://github.com/bactopia/bactopia/issues/199#issuecomment-790793213 and  https://github.com/bioconda/bioconda-recipes/pull/27174

Let me know if this doesn't work!

**Comment by vertisAG** [comment]
Dear @rpetit3 

Problem solved - many thanks!

**Comment by zephykoh** [comment]
I typed in:
(bactopia) zephykoh@dynamic-oit-vapornet100-10-8-22-104 ~ % bactopia datasets --species "Haemophilus influenzae,Staphylococcus aureus" --include_genus

and got back
Standard error:
WARNING: I tried to get the version of spades with: "/Users/zephykoh/opt/miniconda3/envs/bactopia/bin/spades.py --version" and the output didn't match this regular expression: "SPAdes\s+v([0-9.]+)"
ERROR: I tried to get the version of nucmer with: "/Users/zephykoh/opt/miniconda3/envs/bactopia/bin/nucmer --version" and the output didn't match this regular expression: "([0-9]+.[0-9.]+.*$)"

Something wrong with at least one dependency. Please see the above error message(s)
ARIBA version: 2.14.6

External dependencies:
bowtie2 2.3.5.1 /Users/zephykoh/opt/miniconda3/envs/bactopia/bin/bowtie2
cdhit 4.8.1 /Users/zephykoh/opt/miniconda3/envs/bactopia/bin/cd-hit-est
nucmer ERROR /Users/zephykoh/opt/miniconda3/envs/bactopia/bin/nucmer
spades ERROR /Users/zephykoh/opt/miniconda3/envs/bactopia/bin/spades.py

External dependencies OK: False
