### ISSUE TITLE
[bug] bactopia dataset bowtie2 error

### ISSUE THREAD

**Issue by rpetit3** [bactopia/bactopia#201]
There is currently and issue with Bowtie2 on Bioconda. The solution is to downgrade `tbb`. In your bactopia environment run the following:
```
conda install -y -c conda-forge 'tbb=2020.2'
```

More details are avaialble here https://github.com/bactopia/bactopia/issues/199#issuecomment-790793213 and  https://github.com/bioconda/bioconda-recipes/pull/27174

Let me know if this doesn't work!

**Comment by rpetit3** [comment]
This should no longer be an issue as of v1.6.3

**Comment by abhi18av** [comment]
Hey @rpetit3 , I saw that this issue is still pinned and since it has been resolved, we can allow this issue to be forgotten :)

**Comment by rpetit3** [comment]
Hi @abhi18av! You're right, thanks for reminding me!
