### ISSUE TITLE
Issue with nucmer dependency on Bactopia v1.6.5

### ISSUE THREAD

**Issue by jellyvanderwoude** [bactopia/bactopia#214]
I ran into an issue with creating the datasets on v.1.6.5 that I didn't have previously on v1.6.1. Looks like a similar error that some people have run into with bowtie2/ tbb in previous versions of Bactopia:

"(bactopia) bio-24046:bactopia-folder jvanderwoude3$ bactopia datasets
2021-04-14 10:11:33:root:INFO - Setting up Ariba datasets
2021-04-14 10:11:33:root:INFO - Setting up vfdb_core Ariba dataset
External command failed with exit code 1!

Command:
bash -c 'ariba prepareref -f ./datasets/ariba/vfdb_core.fa -m ./datasets/ariba/vfdb_core.tsv ./datasets/ariba/vfdb_core'

Standard error:
ERROR: I tried to get the version of nucmer with: "/Users/jvanderwoude3/miniconda3/envs/bactopia/bin/nucmer --version" and the output didn't match this regular expression: "([0-9]+\.[0-9\.]+.*$)"

Something wrong with at least one dependency. Please see the above error message(s)
ARIBA version: 2.14.6

External dependencies:
bowtie2	2.3.5.1	/Users/jvanderwoude3/miniconda3/envs/bactopia/bin/bowtie2
cdhit	4.8.1	/Users/jvanderwoude3/miniconda3/envs/bactopia/bin/cd-hit-est
nucmer	ERROR	/Users/jvanderwoude3/miniconda3/envs/bactopia/bin/nucmer

External dependencies OK: False

Python version:
3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 15:59:12) 
[Clang 11.0.1 ]

Python packages:
ariba	2.14.6	/Users/jvanderwoude3/miniconda3/envs/bactopia/lib/python3.7/site-packages/ariba/__init__.py
bs4	4.9.3	/Users/jvanderwoude3/miniconda3/envs/bactopia/lib/python3.7/site-packages/bs4/__init__.py
dendropy	4.5.2	/Users/jvanderwoude3/miniconda3/envs/bactopia/lib/python3.7/site-packages/dendropy/__init__.py
pyfastaq	3.17.0	/Users/jvanderwoude3/miniconda3/envs/bactopia/lib/python3.7/site-packages/pyfastaq/__init__.py
pymummer	0.10.3	/Users/jvanderwoude3/miniconda3/envs/bactopia/lib/python3.7/site-packages/pymummer/__init__.py
pysam	0.16.0.1	/Users/jvanderwoude3/miniconda3/envs/bactopia/lib/python3.7/site-packages/pysam/__init__.py

Python packages OK: True

Everything looks OK: False
Some dependencies not satisfied. Cannot continue."

**Comment by jellyvanderwoude** [comment]
It seems when I hunt down the nucmer file in miniconda>envs>bactopia>bin and open it, I get this in the Terminal:

/Users/jvanderwoude3/miniconda3/envs/bactopia/opt/mummer-3.23/nucmer ; exit;
(base) bio-24046:~ jvanderwoude3$ /Users/jvanderwoude3/miniconda3/envs/bactopia/opt/mummer-3.23/nucmer ; exit;
-bash: /Users/jvanderwoude3/miniconda3/envs/bactopia/opt/mummer-3.23/nucmer: /usr/local/bin/perl: bad interpreter: No such file or directory

**Comment by rpetit3** [comment]
Ah, well that's weird. What's the shebang line (`head -n 1 /Users/jvanderwoude3/miniconda3/envs/bactopia/opt/mummer-3.23/nucmer`), look like?

**Comment by jellyvanderwoude** [comment]
#!/usr/local/bin/perl

**Comment by jellyvanderwoude** [comment]
Not sure if this is helpful it's a bit above my head
https://stackoverflow.com/questions/17131249/how-to-solve-bad-interpreter-no-such-file-or-directory/17131267

**Comment by rpetit3** [comment]
I think this is something that needs to be fixed in the mummer bioconda recipe. It should use perl installed from conda.

You have to options: 1. skip ariba all together, or 2: edit the shebang line in nucmer

skip ariba:  
Just add `--skip_ariba` to the bactopia datasets command

Edit Nucmer shebang:  
Verify `/Users/jvanderwoude3/miniconda3/envs/bactopia/bin/perl` exists and if so replace `/usr/local/bin/perl` with `/Users/jvanderwoude3/miniconda3/envs/bactopia/bin/perl`

I'll submit an issue to Bioconda to get the mummer recipe fixed, if you want.

**Comment by jellyvanderwoude** [comment]
This seems to have done the trick, thanks!

**Comment by jellyvanderwoude** [comment]
Just so others know- there are multiple nucmer perl executable files in different folders corresponding to different tasks (sequence_type, ariba_analysis) and they will all have to be changed as above in order for the code to run

**Comment by rpetit3** [comment]
Curious, is perl installed on your system?

**Comment by jellyvanderwoude** [comment]
oh you know what, I'm using a brand new computer in the lab, so I don't believe so. That would probably explain why the perl doesn't run when it's linked outside Bactopia.
