### ISSUE TITLE
Error during process 'assemble_genome' - segmentation fault?

### ISSUE THREAD

**Issue by mdhfz89** [bactopia/bactopia#215]
Hi,

I am trying to use bactopia with 2 samples (i have qc-ed llumina and nanopore fastq so I am using the hybrid assembly option here) but keeps exiting with an error during the assembly step. The log file in the `work/bactopia/d9/a82e36c9e1ed96e708782365a3877f` folder shows this but I'm not too sure what the problem is either.

> /datadrive03/hafiz/data/kemin/bactopiaAnalysis/work/bactopia/d9/a82e36c9e1ed96e708782365a3877f/.command.sh: line 103: 53387 Segmentation fault      (core dumped) unicycler -1 CP51_R1.fastq.gz -2 CP51_R2.fastq.gz ${EXTRA} -o ${OUTDIR} --no_correct --min_fasta_length 500 --threads 9 --keep 1 --mode bold --min_polish_size 10000 --min_component_size 1000 --min_dead_end_size 1000 > ${LOG_DIR}/unicycler.out 2> ${LOG_DIR}/unicycler.err
/datadrive03/hafiz/data/kemin/bactopiaAnalysis/work/bactopia/d9/a82e36c9e1ed96e708782365a3877f/.command.sh: line 103: 53387 Segmentation fault      (core dumped) unicycler -1 CP51_R1.fastq.gz -2 CP51_R2.fastq.gz ${EXTRA} -o ${OUTDIR} --no_correct --min_fasta_length 500 --threads 9 --keep 1 --mode bold --min_polish_size 10000 --min_component_size 1000 --min_dead_end_size 1000 > ${LOG_DIR}/unicycler.out 2> ${LOG_DIR}/unicycler.err

I am running this on a server with bactopia installed as a conda environment and the command I used is this:

> #!/bin/sh
> #PBS -l nodes=1:ppn=24,mem=220g,walltime=600:00:00
> #PBS -q batch
> #PBS -M email@ntu.edu.sg
> #PBS -m abe
> #PBS -V
> 
> echo "running bactopia now"
> 
> bactopia --fastqs fastqs.txt \
>          --accessions ena-accessions.txt --use_ena \
>          --datasets datasets/ \
>          --species "Clostridium perfringens" \
>          --coverage 300 \
>          --genome_size 3260000 \
>          --max_memory 100\
>          --cpus 12 \
>          --max_time 6000 \
>          --outdir local-multiple-samples \
>          --skip_qc \
>          --unicycler_mode bold \
>          --compliant \
>          --centre 'SCELSE'
> 

I'm not too sure what other log files I should be providing here but will be glad to give them where needed.

Best regards.
Hafiz

**Comment by rpetit3** [comment]
Hi @mdhfz89 

Let's see if we can get this figured out. Is there anything in `/datadrive03/hafiz/data/kemin/bactopiaAnalysis/work/bactopia/d9/a82e36c9e1ed96e708782365a3877f/` we can use? There might be a folder `assemble_genome` or `logs` that might have log files in it.

**Comment by mdhfz89** [comment]
Hi,

I found 3 files in the assemble_genome folder but the unicycler.err file is empty. I can't upload the .err file since its empty and I had to append a .txt at the end to be able to upload these. Thank you for helping me figure out whats going on.

[assemble_genome.versions.txt](https://github.com/bactopia/bactopia/files/6395820/assemble_genome.versions.txt)
[unicycler.out.txt](https://github.com/bactopia/bactopia/files/6395821/unicycler.out.txt)

**Comment by rpetit3** [comment]
I think I have some illumina with matching nanopore data that I can test on my end. Hopefully this can help us narrow it down.

**Comment by rpetit3** [comment]
I was unable to replicate using my data

```
bactopia --R1 fastqs/GA81666_R1.fastq.gz --R2 fastqs/GA81666_R2.fastq.gz --SE fastqs/GA81666.fastq.gz --hybrid -profile slurm --cpus 20 --sample GA81666-bold --unicycler_mode bold --skip_qc
```

Do you think you could try running unicycler directly? Also, would you be up for trying the singularity images and maybe even creating a profile for your cluster? (I can help with that)

**Comment by mdhfz89** [comment]
Hi Robert,

I don't have sudo access in the server I'm in so I can't install either docker or singularity. I'll give running unicycler directly a shot. With regards to this, if I run bactopia using an assembly (the unicycler output), would the output be as complete as if I run bactopia with the fastq reads? Is it possible to run bactopia with an assembly and yet also provide the fastq reads as well? Looking at the workflow of bactopia, it seems like if I just use the assemblies only I'll be missing analysis like MLST or those run with Ariba. Do correct me if I'm wrong.

**Comment by rpetit3** [comment]
Apologies! Read this and forgot to follow up.

If you provide an assembly Bactopia will simulate FASTQ reads from the assembly in order to do the FASTQ based steps (e.g. Ariba's MLST and variant calling).

**Comment by mdhfz89** [comment]
Hi Robert,

I manged to get singularity 3.7 installed in the server. I got this message when I pulled the singularity image 

`singularity pull library://rpetit3/bactopia/bactopia`

> INFO:    Downloading library image
> 970.4MiB / 970.4MiB [==============================================================================] 100 % 6.5 MiB/s 0s
> WARNING: Directory mode (20000700) on /datadrive03/hafiz/.singularity/sypgp needs to be 700, fixing that...
> WARNING: integrity: signature not found for object group 1
> WARNING: Skipping container verification

I started the bactopia image using:

`singularity shell bactopia_latest.sif`


and tried running bactopia with this script:

```
bactopia --fastqs fastqs_ena.txt \
         --datasets datasets/ \
         --species "Clostridium perfringens" \
         --coverage 300 \
         --genome_size 3260000 \
         --max_memory 100\
         --cpus 12 \
         --max_time 6000 \
         --outdir local_ena-multiple-samples \
         --skip_qc \
         --unicycler_mode bold \
         --compliant \
         --centre 'SCELSE' \
         -qs 24
```

However I get this error:

> running bactopia now                                                                                                                                                                                        
> 2021-05-06 14:16:01:root:INFO - Found /opt/conda/envs/bactopia/share/bactopia-1.5.x/conda/linux/annotate_genome.yml (1 or 12), begin build to /opt/conda/envs/bactopia/share/bactopia-1.5.x/conda/envs/annot
> ate_genome-1.5.x                                                                                                                                                                                            
> Traceback (most recent call last):                                                                                                                                                                          
>   File "/opt/conda/envs/bactopia/bin/bactopia-build.py", line 171, in <module>                                                                                                                              
>     execute(f'conda env create -f {env_file} --prefix {prefix} {force}')                                                                                                                                    
>   File "/opt/conda/envs/bactopia/bin/bactopia-build.py", line 71, in execute                                                                                                                                
>     command.start()                                                                                                                                                                                         
>   File "/opt/conda/envs/bactopia/lib/python3.6/site-packages/executor/__init__.py", line 1441, in start                                                                                                     
>     self.start_once(**kw)                                                                                                                                                                                   
>   File "/opt/conda/envs/bactopia/lib/python3.6/site-packages/executor/__init__.py", line 1508, in start_once                                                                                                
>     self.wait(check=check)
>   File "/opt/conda/envs/bactopia/lib/python3.6/site-packages/executor/__init__.py", line 1551, in wait
>     self.check_errors(check=check)
>   File "/opt/conda/envs/bactopia/lib/python3.6/site-packages/executor/__init__.py", line 1673, in check_errors
>     raise self.error_type(self)
> executor.ExternalCommandFailed: External command failed with exit code 1!
> 
> Command:
> bash -c 'conda env create -f /opt/conda/envs/bactopia/share/bactopia-1.5.x/conda/linux/annotate_genome.yml --prefix /opt/conda/envs/bactopia/share/bactopia-1.5.x/conda/envs/annotate_genome-1.5.x --force'
> 
> Standard output:                                                                                                                                                                                    [70/159]
> EnvironmentSectionNotValid: The following section on '/opt/conda/envs/bactopia/share/bactopia-1.5.x/conda/linux/annotate_genome.yml' is invalid and will be ignored:                                        
>  - version                                                                                                                                                                                                  
>                                                                                                                                                                                                             
> Collecting package metadata (repodata.json): ...working... failed                                                                                                                                           
>                                                                                                                                                                                                             
> Standard error:
> NotWritableError: The current user does not have write permissions to a required path.
>   path: /opt/conda/envs/bactopia/pkgs/urls.txt
>   uid: 1007
>   gid: 1007
> 
> If you feel that permissions on this path are set incorrectly, you can manually
> change them by executing
> 
>   $ sudo chown 1007:1007 /opt/conda/envs/bactopia/pkgs/urls.txt
> 
> In general, it's not advisable to use 'sudo conda'.
> N E X T F L O W  ~  version 20.10.0
> Launching `/opt/conda/envs/bactopia/share/bactopia-1.5.x/main.nf` [sick_volta] - revision: 3f7e3dbaec
> WARN: Access to undefined parameter `ftp_only` -- Initialise it to a default value eg. `params.ftp_only = some_value`
> bactopia - 1.5.5
> 
> Each task will use 12 CPUs out of the available 72 CPUs. At most 6 task(s) will be run at                                                                                                                   
> a time, this can affect the efficiency of Bactopia.                                                                                                                                                         
>                                                                                                                                                                                                             
> Found 2 ARIBA datasets
> /datadrive03/hafiz/data/kemin/bactopiaAnalysis/datasets/ariba/card.tar.gz
> /datadrive03/hafiz/data/kemin/bactopiaAnalysis/datasets/ariba/vfdb_core.tar.gz
> Found 3 PLSDB (plasmid) BLAST files
> datasets/plasmid/plsdb.fna.nsq
> datasets/plasmid/plsdb.fna.nhr
> datasets/plasmid/plsdb.fna.nin
> Found 5 minmer sketches/signatures
> /datadrive03/hafiz/data/kemin/bactopiaAnalysis/datasets/minmer/genbank-k21.json.gz
> /datadrive03/hafiz/data/kemin/bactopiaAnalysis/datasets/minmer/genbank-k31.json.gz
> /datadrive03/hafiz/data/kemin/bactopiaAnalysis/datasets/minmer/genbank-k51.json.gz
> /datadrive03/hafiz/data/kemin/bactopiaAnalysis/datasets/minmer/refseq-k21-s1000.msh
> /datadrive03/hafiz/data/kemin/bactopiaAnalysis/datasets/plasmid/plsdb.msh
> Will use 3260000 bp for genome size
> Found Prokka proteins file
> /datadrive03/hafiz/data/kemin/bactopiaAnalysis/datasets/species-specific/clostridium-perfringens/annotation/proteins.faa
> Found Mash Sketch of RefSeq genomes
> /datadrive03/hafiz/data/kemin/bactopiaAnalysis/datasets/species-specific/clostridium-perfringens/minmer/refseq-genomes.msh
> If something looks wrong, now's your chance to back out (CTRL+C 3 times).
> Sleeping for 5 seconds...                                                                                                                                                                           [25/159]
> [-        ] process > gather_fastqs                   -                                                                                                                                                     
> [-        ] process > fastq_status                    -                                                                                                                                                     
> [-        ] process > estimate_genome_size            -                                                                                                                                                     
> [-        ] process > qc_reads                        -                                                                                                                                                     
> [-        ] process > qc_original_summary             -                                                                                                                                                     
> [-        ] process > gather_fastqs                   -                                                                                                                                                     
> [-        ] process > fastq_status                    -                                                                                                                                                     
> [-        ] process > estimate_genome_size            -                                                                                                                                                     
> [-        ] process > qc_reads                        -                                                                                                                                                     
> [-        ] process > qc_original_summary             -                                                                                                                                                     
> [-        ] process > qc_final_summary                -                                                                                                                                                     
> [-        ] process > assemble_genome                 -                                                                                                                                                     
> [-        ] process > assembly_qc                     -                                                                                                                                                     
> [-        ] process > make_blastdb                    -                                                                                                                                                     
> [-        ] process > annotate_genome                 -                                                                                                                                                     
> [-        ] process > count_31mers                    -                                                                                                                                                     
> [-        ] process > sequence_type                   -                                                                                                                                                     
> [-        ] process > ariba_analysis                  -                                                                                                                                                     
> [-        ] process > minmer_sketch                   -                                                                                                                                                     
> [-        ] process > minmer_query                    -                                                                                                                                                     
> [-        ] process > call_variants                   -                                                                                                                                                     
> [-        ] process > download_references             -                                                                                                                                                     
> [-        ] process > call_variants_auto              -                                                                                                                                                     
> [-        ] process > update_antimicrobial_resistance -
> [-        ] process > antimicrobial_resistance        -
> [-        ] process > plasmid_blast                   -
> [-        ] process > blast_genes                     -
> [-        ] process > blast_primers                   -
> [-        ] process > blast_proteins                  -
> [-        ] process > mapping_query                   -
> Error executing process > 'gather_fastqs (SRX2253983)'
> 
> Caused by:
>   Conda prefix path does not exist or it's not a directory: /opt/conda/envs/bactopia/share/bactopia-1.5.x/conda/envs/gather_fastqs-1.5.x


What I also noticed is that nextflow does not really limit the number of cores that I want it to use from the server. I want to run only 24 out of the 72 available cores but because it uses every available core. This happens in both the conda environment I was using before and also in the singularity image i pulled.

Do you have any idea what is happening? Or is the singularity image i pulled problematic? 

Thank you so much for your help.

**Comment by mdhfz89** [comment]
Hi Robert,

Just an update. I may have an inkling why bactopia was not working on either the server I had access to and on my local computer. I think it might have to do with how nextflow does not limit the number of cores that it can access using the `-qs` option. On the server, I wanted to use `--cpus 12 --max_memory 100 -qs 24` but because it still saw 72 cores, it ran 6 concurrent jobs which maxed out the available ram on the server. Something similar happened to my local computer where I think the memory was maxed out and therefore failed to run completely.

With that said, I reran using this command on my local computer (which has 12 cores and 32 gb memory) and it managed to complete. So I'm guessing it should have been the resource issue though I'm unsure why nextflow did not work for me.

```
bactopia --fastqs fastqs_ena.txt \
         --datasets datasets/ \
         --species "Clostridium perfringens" \
         --coverage 300 \
         --genome_size 3260000 \
	 --max_memory 31\
         --cpus 12 \
	 --max_time 60000 \
         --outdir local_ena-multiple-samples \
         --skip_qc \
         --unicycler_mode bold \
         --compliant \
         --centre 'SCELSE'
```

Best regards,
Hafiz

**Comment by mdhfz89** [comment]
Oh gosh my mistake. I somehow missed it before this and did not realise you had some guides on the visualisation. Anyway thanks for the help you've given.

Cheers,
Hafiz

**Comment by rpetit3** [comment]
Hi @mdhfz89 

I'm going to close this, please feel free to reopen. 

Don't hesitate to reach out with questions and feedback

Robert
