### ISSUE TITLE
error during assemble_genome

### ISSUE THREAD

**Issue by MHargita** [bactopia/bactopia#218]
Hey Robert,

I successfully created my datasets and then tried to run bactopia on one sample (paired end). I used the following

```
bactopia --R1 fastqs/172084_S11_L003_R1_001.fastq.gz \
               --R2 fastqs/172084_S11_L003_R2_001.fastq.gz \
               --sample 172084 \
               --datasets datasets/ \
               --species "Klebsiella pneumoniae" \
               --coverage 100 \
               --genome_size median \
               --cpus 4 \
               --outdir local-single-sample
```

While running the assemble_genome process usually gets to about [75%] 3 of 4 failed: 3, retries: 3

```
Error executing process > 'assemble_genome (172084)'
Caused by:
  Process `assemble_genome (172084)` terminated with an error exit status (1)

I checked the shoville.err I received

[shovill] Assembling reads with 'skesa'
[shovill] Running: skesa --gz  --fastq flash.extendedFrags.fastq.gz --fastq flash.notCombined_1.fastq.gz,flash.notCombined_2.fastq.gz --use_paired_ends --contigs_out skesa.fasta --min_contig 1 --memory 31 --cores 3 --vector_percent 1 2>&1 | sed 's/^/[skesa] /' | tee -a shovill.log
Illegal instruction
[shovill] Assembly failed - skesa.fasta has zero contigs!
```

Maybe I didn't run the bactopia command correctly, appreciate your help and feedback!

Thanks again!
Michelle

**Comment by rpetit3** [comment]
Hi Michelle!

Back in business on my end so I'm going to look into this on my end, I'll update soon.

Robert

**Comment by rpetit3** [comment]
Hi Michelle!

Do you think you could share what the FASTQ stats look like (https://bactopia.github.io/output-overview/#quality-control) should be the files that look like `${SAMPLE_NAME}(|_R1|_R2)-(original|final).json` 

I'm curious what the data looks like going into the assembly step

**Comment by MHargita** [comment]
Sure! I've included both _R1 and _R2

cat 172084_R1-original.json
{
    "qc_stats": {
        "total_bp": 365711128,
        "coverage": 64.8351,
        "read_total": 2421928,
        "read_min": 151,
        "read_mean": 151,
        "read_std": 0,
        "read_median": 151,
        "read_max": 151,
        "read_25th": 151,
        "read_75th": 151,
        "qual_min": 15,
        "qual_mean": 39.0091,
        "qual_std": 2.29216,
        "qual_max": 40,
        "qual_median": 40,
        "qual_25th": 39,
        "qual_75th": 40
    },
    "read_lengths": {
        "151": 2421928
    },
    "per_base_quality": {
        "1": 31.4678,        "2": 31.5826,        "3": 35.8685,        "4": 36.2868,        "5": 36.4753,
        "6": 40.0006,        "7": 40.1674,        "8": 40.2011,        "9": 40.2035,        "10": 40.1755,
        "11": 40.2233,        "12": 40.1971,        "13": 40.1534,        "14": 40.1594,        "15": 40.1069,
        "16": 40.1304,        "17": 40.0904,        "18": 40.1878,        "19": 40.1804,        "20": 40.138,
        "21": 40.0324,        "22": 40.0872,        "23": 40.095,        "24": 40.1317,        "25": 40.1282,
        "26": 40.1271,        "27": 40.1188,        "28": 40.0749,        "29": 39.9695,        "30": 40.0378,
        "31": 40.0815,        "32": 40.067,        "33": 40.0235,        "34": 40.0793,        "35": 40.0866,
        "36": 40.1118,        "37": 40.0345,        "38": 40.0678,        "39": 40.063,        "40": 40.0785,
        "41": 40.0889,        "42": 40.0267,        "43": 40.0637,        "44": 40.0955,        "45": 40.1079,
        "46": 40.1273,        "47": 40.1008,        "48": 40.1275,        "49": 40.0353,        "50": 40.0511,
        "51": 40.0258,        "52": 40.0746,        "53": 40.0394,        "54": 40.0659,        "55": 40.0656,
        "56": 40.066,        "57": 39.9978,        "58": 40.064,        "59": 40.0756,        "60": 40.0904,
        "61": 39.9177,        "62": 40.0182,        "63": 40.0541,        "64": 40.0628,        "65": 40.0305,
        "66": 40.0465,        "67": 39.9625,        "68": 39.9573,        "69": 39.9775,        "70": 39.9626,
        "71": 39.9886,        "72": 39.9645,        "73": 39.9843,        "74": 39.9545,        "75": 39.9718,
        "76": 39.2966,        "77": 39.7659,        "78": 39.923,        "79": 39.8846,        "80": 40.0009,
        "81": 40.0413,        "82": 40.0119,        "83": 40.0526,        "84": 40.0557,        "85": 40.0412,
        "86": 40.0011,        "87": 40.0212,        "88": 40.0352,        "89": 40.0214,        "90": 40.0269,
        "91": 40.0453,        "92": 39.9938,        "93": 39.9153,        "94": 39.9515,        "95": 39.8791,
        "96": 39.9485,        "97": 39.9807,        "98": 39.9823,        "99": 39.9613,        "100": 39.9572,
        "101": 39.9463,        "102": 39.872,        "103": 39.8786,        "104": 39.9031,        "105": 39.8509,
        "106": 39.8206,        "107": 39.7814,        "108": 39.804,        "109": 39.7994,        "110": 39.8131,
        "111": 39.7951,        "112": 39.7687,        "113": 39.7228,        "114": 39.6953,        "115": 39.6938,
        "116": 39.6822,        "117": 39.5492,        "118": 39.6,        "119": 39.5655,        "120": 39.5434,
        "121": 39.5421,        "122": 39.5225,        "123": 39.4339,        "124": 39.4154,        "125": 39.3695,
        "126": 39.2504,        "127": 39.3332,        "128": 39.3572,        "129": 39.3382,        "130": 39.2981,
        "131": 39.2611,        "132": 39.2383,        "133": 39.1815,        "134": 39.1964,        "135": 39.1255,
        "136": 39.1141,        "137": 39.091,        "138": 39.0504,        "139": 38.9958,        "140": 38.951,
        "141": 38.9013,        "142": 38.8712,        "143": 38.8373,        "144": 38.7124,        "145": 38.6659,
        "146": 38.6434,        "147": 38.6201,        "148": 38.614,        "149": 38.5863,        "150": 38.5332,
        "151": 36.6091
    }
}

cat 172084_R2-original.json
{
    "qc_stats": {
        "total_bp": 365711128,
        "coverage": 64.8351,
        "read_total": 2421928,
        "read_min": 151,
        "read_mean": 151,
        "read_std": 0,
        "read_median": 151,
        "read_max": 151,
        "read_25th": 151,
        "read_75th": 151,
        "qual_min": 12,
        "qual_mean": 37.5879,
        "qual_std": 4.35826,
        "qual_max": 40,
        "qual_median": 40,
        "qual_25th": 37,
        "qual_75th": 40
    },
    "read_lengths": {
        "151": 2421928
    },
    "per_base_quality": {
        "1": 30.9918,        "2": 31.1107,        "3": 34.8541,        "4": 35.4203,        "5": 35.6255,
        "6": 38.8573,        "7": 39.0428,        "8": 39.0446,        "9": 38.8938,        "10": 39.0481,
        "11": 39.0756,        "12": 39.1882,        "13": 39.1279,        "14": 39.2102,        "15": 39.1363,
        "16": 39.0317,        "17": 39.0372,        "18": 38.9222,        "19": 39.057,        "20": 39.0007,
        "21": 38.8948,        "22": 38.7851,        "23": 38.8352,        "24": 38.9553,        "25": 38.9192,
        "26": 38.9173,        "27": 38.863,        "28": 38.8144,        "29": 38.8473,        "30": 38.8805,
        "31": 38.8111,        "32": 38.8768,        "33": 38.7305,        "34": 38.8161,        "35": 38.8901,
        "36": 38.8764,        "37": 38.9198,        "38": 38.9091,        "39": 38.8728,        "40": 38.7469,
        "41": 38.8024,        "42": 38.8643,        "43": 38.8133,        "44": 38.7549,        "45": 38.8736,
        "46": 38.8519,        "47": 38.7956,        "48": 38.8619,        "49": 38.7808,        "50": 38.735,
        "51": 38.8148,        "52": 38.7394,        "53": 38.7866,        "54": 38.7041,        "55": 38.6478,
        "56": 38.5301,        "57": 38.6455,        "58": 38.6391,        "59": 38.608,        "60": 38.579,
        "61": 38.6074,        "62": 38.6282,        "63": 38.6963,        "64": 38.759,        "65": 38.8036,
        "66": 38.7967,        "67": 38.8135,        "68": 38.8071,        "69": 38.7154,        "70": 38.7578,
        "71": 38.7858,        "72": 38.7765,        "73": 38.7819,        "74": 38.7655,        "75": 38.6955,
        "76": 37.7819,        "77": 38.365,        "78": 38.6004,        "79": 38.7277,        "80": 38.7805,
        "81": 38.7979,        "82": 38.7757,        "83": 38.7804,        "84": 38.7826,        "85": 38.7968,
        "86": 38.7965,        "87": 38.7685,        "88": 38.7274,        "89": 38.7354,        "90": 38.6918,
        "91": 38.6848,        "92": 38.7021,        "93": 38.6504,        "94": 38.645,        "95": 38.6458,
        "96": 38.6151,        "97": 38.576,        "98": 38.5576,        "99": 38.5521,        "100": 38.5454,
        "101": 38.5006,        "102": 38.4307,        "103": 38.3491,        "104": 38.3758,        "105": 38.3854,
        "106": 38.3561,        "107": 38.3169,        "108": 38.2856,        "109": 38.2782,        "110": 38.2398,
        "111": 38.1814,        "112": 38.1594,        "113": 38.1565,        "114": 38.0885,        "115": 38.0369,
        "116": 38.0221,        "117": 37.9939,        "118": 37.9698,        "119": 37.9312,        "120": 37.8599,
        "121": 37.8147,        "122": 37.6831,        "123": 37.6429,        "124": 37.5741,        "125": 37.5651,
        "126": 37.5616,        "127": 37.5385,        "128": 37.4518,        "129": 37.3962,        "130": 37.365,
        "131": 37.2527,        "132": 37.2065,        "133": 37.1292,        "134": 37.124,        "135": 37.082,
        "136": 36.9875,        "137": 36.9235,        "138": 36.8599,        "139": 36.8019,        "140": 36.7171,
        "141": 36.6293,        "142": 36.507,        "143": 36.4691,        "144": 36.369,        "145": 36.2916,
        "146": 36.2229,        "147": 36.1025,        "148": 36.0716,        "149": 35.9308,        "150": 35.8199,
        "151": 32.0808
    }
}

**Comment by rpetit3** [comment]
Those look really good, how about the `final` ones?

**Comment by MHargita** [comment]
cat 172084_R1-final.json
{
    "qc_stats": {
        "total_bp": 282027269,
        "coverage": 49.9992,
        "read_total": 1965915,
        "read_min": 35,
        "read_mean": 143.459,
        "read_std": 20.042,
        "read_median": 150,
        "read_max": 150,
        "read_25th": 150,
        "read_75th": 150,
        "qual_min": 15,
        "qual_mean": 39.1919,
        "qual_std": 2.0422,
        "qual_max": 40,
        "qual_median": 40,
        "qual_25th": 40,
        "qual_75th": 40
    },
    "read_lengths": {

        "35": 1111,        "36": 1098,        "37": 1117,        "38": 1187,        "39": 1201,
        "40": 1135,        "41": 1204,        "42": 1328,        "43": 1245,        "44": 1357,
        "45": 1363,        "46": 1301,        "47": 1430,        "48": 1393,        "49": 1379,
        "50": 1486,        "51": 1462,        "52": 1450,        "53": 1496,        "54": 1507,
        "55": 1533,        "56": 1578,        "57": 1634,        "58": 1636,        "59": 1616,
        "60": 1645,        "61": 1714,        "62": 1758,        "63": 1692,        "64": 1704,
        "65": 1642,        "66": 1679,        "67": 1731,        "68": 1740,        "69": 1708,
        "70": 1870,        "71": 1819,        "72": 1792,        "73": 1891,        "74": 1943,
        "75": 1988,        "76": 1920,        "77": 1988,        "78": 1975,        "79": 1943,
        "80": 1989,        "81": 1959,        "82": 2029,        "83": 1944,        "84": 2081,
        "85": 2012,        "86": 2077,        "87": 2137,        "88": 2104,        "89": 2246,
        "90": 2226,        "91": 2246,        "92": 2184,        "93": 2232,        "94": 2222,
        "95": 2389,        "96": 2247,        "97": 2369,        "98": 2407,        "99": 2382,
        "100": 2524,        "101": 2421,        "102": 2442,        "103": 2524,        "104": 2657,
        "105": 2702,        "106": 2601,        "107": 2719,        "108": 2707,        "109": 2721,
        "110": 2842,        "111": 2832,        "112": 2877,        "113": 2989,        "114": 3075,
        "115": 3055,        "116": 3072,        "117": 3055,        "118": 3166,        "119": 3258,
        "120": 3213,        "121": 3279,        "122": 3311,        "123": 3447,        "124": 3466,
        "125": 3473,        "126": 3568,        "127": 3553,        "128": 126,        "129": 909,
        "130": 2765,        "131": 3411,        "132": 3604,        "133": 3774,        "134": 3942,
        "135": 3910,        "136": 4037,        "137": 4173,        "138": 4737,        "139": 5823,
        "140": 4138,        "141": 4259,        "142": 4519,        "143": 4471,        "144": 4498,
        "145": 4484,        "146": 4483,        "147": 4669,        "148": 6004,        "149": 13149,
        "150": 1672610
    },
    "per_base_quality": {
        "1": 31.617,        "2": 31.6031,        "3": 35.892,        "4": 36.2949,        "5": 36.4967,
        "6": 40.0054,        "7": 40.1735,        "8": 40.2044,        "9": 40.2066,        "10": 40.1787,
        "11": 40.2255,        "12": 40.1991,        "13": 40.1547,        "14": 40.1633,        "15": 40.1096,
        "16": 40.134,        "17": 40.0934,        "18": 40.1912,        "19": 40.1845,        "20": 40.1415,
        "21": 40.0355,        "22": 40.0902,        "23": 40.0976,        "24": 40.1357,        "25": 40.1296,
        "26": 40.1322,        "27": 40.1227,        "28": 40.0771,        "29": 39.975,        "30": 40.0401,
        "31": 40.086,        "32": 40.071,        "33": 40.0276,        "34": 40.0872,        "35": 40.0932,
        "36": 40.1179,        "37": 40.0402,        "38": 40.0701,        "39": 40.0667,        "40": 40.0833,
        "41": 40.0916,        "42": 40.0302,        "43": 40.0678,        "44": 40.1014,        "45": 40.1313,
        "46": 40.139,        "47": 40.1053,        "48": 40.1312,        "49": 40.0399,        "50": 40.054,
        "51": 40.0299,        "52": 40.0759,        "53": 40.0445,        "54": 40.07,        "55": 40.073,
        "56": 40.0686,        "57": 40.0013,        "58": 40.0677,        "59": 40.0779,        "60": 40.0912,
        "61": 39.9192,        "62": 40.019,        "63": 40.0548,        "64": 40.0643,        "65": 40.0298,
        "66": 40.0475,        "67": 39.9623,        "68": 39.9554,        "69": 39.9784,        "70": 39.9633,
        "71": 39.9951,        "72": 40.0249,        "73": 40.0448,        "74": 40.0141,        "75": 40.028,
        "76": 39.3551,        "77": 39.8268,        "78": 39.9828,        "79": 39.9454,        "80": 40.0642,
        "81": 40.1063,        "82": 40.0774,        "83": 40.1193,        "84": 40.1216,        "85": 40.1074,
        "86": 40.0697,        "87": 40.0901,        "88": 40.104,        "89": 40.09,        "90": 40.0957,
        "91": 40.1139,        "92": 40.0637,        "93": 39.9846,        "94": 40.0243,        "95": 39.9537,
        "96": 40.0229,        "97": 40.0565,        "98": 40.0578,        "99": 40.0429,        "100": 40.0445,
        "101": 40.0362,        "102": 39.9687,        "103": 39.9847,        "104": 40.0174,        "105": 39.9711,
        "106": 39.9516,        "107": 39.9235,        "108": 39.9572,        "109": 39.9669,        "110": 39.9942,
        "111": 39.987,        "112": 39.9738,        "113": 39.9437,        "114": 39.9303,        "115": 39.9437,
        "116": 39.9446,        "117": 39.8253,        "118": 39.8938,        "119": 39.8722,        "120": 39.8661,
        "121": 39.8808,        "122": 39.8795,        "123": 39.8078,        "124": 39.8067,        "125": 39.7794,
        "126": 39.6768,        "127": 39.7787,        "128": 39.8192,        "129": 39.8184,        "130": 39.7994,
        "131": 39.7813,        "132": 39.7766,        "133": 39.7432,        "134": 39.777,        "135": 39.7233,
        "136": 39.736,        "137": 39.7343,        "138": 39.7107,        "139": 39.6786,        "140": 39.6554,
        "141": 39.6247,        "142": 39.6164,        "143": 39.6025,        "144": 39.4973,        "145": 39.475,
        "146": 39.4712,        "147": 39.4693,        "148": 39.4912,        "149": 39.4923,        "150": 39.4691
    }
}

cat 172084_R2-final.json
{
    "qc_stats": {
        "total_bp": 282036584,
        "coverage": 50.0008,
        "read_total": 1965915,
        "read_min": 35,
        "read_mean": 143.463,
        "read_std": 20.0421,
        "read_median": 150,
        "read_max": 150,
        "read_25th": 150,
        "read_75th": 150,
        "qual_min": 12,
        "qual_mean": 37.8561,
        "qual_std": 4.23967,
        "qual_max": 40,
        "qual_median": 40,
        "qual_25th": 38,
        "qual_75th": 40
    },
    "read_lengths": {

        "35": 1102,        "36": 1097,        "37": 1125,        "38": 1185,        "39": 1198,
        "40": 1135,        "41": 1209,        "42": 1332,        "43": 1243,        "44": 1358,
        "45": 1356,        "46": 1301,        "47": 1429,        "48": 1394,        "49": 1384,
        "50": 1480,        "51": 1456,        "52": 1454,        "53": 1494,        "54": 1504,
        "55": 1537,        "56": 1586,        "57": 1623,        "58": 1640,        "59": 1620,
        "60": 1644,        "61": 1715,        "62": 1755,        "63": 1690,        "64": 1704,
        "65": 1641,        "66": 1687,        "67": 1725,        "68": 1746,        "69": 1703,
        "70": 1875,        "71": 1814,        "72": 1793,        "73": 1893,        "74": 1945,
        "75": 1987,        "76": 1924,        "77": 1979,        "78": 1975,        "79": 1944,
        "80": 1994,        "81": 1951,        "82": 2029,        "83": 1949,        "84": 2074,
        "85": 2007,        "86": 2091,        "87": 2141,        "88": 2109,        "89": 2236,
        "90": 2221,        "91": 2247,        "92": 2190,        "93": 2229,        "94": 2214,
        "95": 2395,        "96": 2246,        "97": 2365,        "98": 2404,        "99": 2391,
        "100": 2523,        "101": 2418,        "102": 2446,        "103": 2525,        "104": 2656,
        "105": 2704,        "106": 2597,        "107": 2722,        "108": 2704,        "109": 2720,
        "110": 2845,        "111": 2821,        "112": 2889,        "113": 2978,        "114": 3081,
        "115": 3055,        "116": 3072,        "117": 3052,        "118": 3165,        "119": 3248,
        "120": 3226,        "121": 3271,        "122": 3316,        "123": 3438,        "124": 3471,
        "125": 3483,        "126": 3560,        "127": 3572,        "128": 123,        "129": 903,
        "130": 2766,        "131": 3396,        "132": 3602,        "133": 3784,        "134": 3947,
        "135": 3902,        "136": 4028,        "137": 4172,        "138": 4754,        "139": 5824,
        "140": 4127,        "141": 4254,        "142": 4530,        "143": 4478,        "144": 4481,
        "145": 4536,        "146": 4483,        "147": 4657,        "148": 4864,        "149": 7027,
        "150": 1679855
    },
    "per_base_quality": {
        "1": 31.0304,        "2": 31.1132,        "3": 34.86,        "4": 35.4263,        "5": 35.6349,
        "6": 38.8609,        "7": 39.0485,        "8": 39.0477,        "9": 38.8994,        "10": 39.052,
        "11": 39.0786,        "12": 39.1906,        "13": 39.1323,        "14": 39.217,        "15": 39.1431,
        "16": 39.037,        "17": 39.0454,        "18": 38.9301,        "19": 39.0667,        "20": 39.0075,
        "21": 38.8976,        "22": 38.7885,        "23": 38.8391,        "24": 38.9659,        "25": 38.9269,
        "26": 38.9249,        "27": 38.8672,        "28": 38.818,        "29": 38.8522,        "30": 38.8856,
        "31": 38.8166,        "32": 38.8838,        "33": 38.7357,        "34": 38.8228,        "35": 38.8967,
        "36": 38.8796,        "37": 38.9244,        "38": 38.912,        "39": 38.8711,        "40": 38.746,
        "41": 38.8003,        "42": 38.8665,        "43": 38.8105,        "44": 38.7518,        "45": 38.8722,
        "46": 38.8479,        "47": 38.7902,        "48": 38.8561,        "49": 38.7729,        "50": 38.7265,
        "51": 38.8106,        "52": 38.7322,        "53": 38.7775,        "54": 38.6947,        "55": 38.6351,
        "56": 38.5164,        "57": 38.6312,        "58": 38.6204,        "59": 38.5879,        "60": 38.5591,
        "61": 38.5867,        "62": 38.6051,        "63": 38.6755,        "64": 38.788,        "65": 38.8364,
        "66": 38.8326,        "67": 38.8467,        "68": 38.841,        "69": 38.7449,        "70": 38.7842,
        "71": 38.8133,        "72": 38.8024,        "73": 38.81,        "74": 38.7907,        "75": 38.7174,
        "76": 37.7872,        "77": 38.3747,        "78": 38.6154,        "79": 38.7434,        "80": 38.7974,
        "81": 38.8128,        "82": 38.7914,        "83": 38.7931,        "84": 38.7942,        "85": 38.8081,
        "86": 38.8069,        "87": 38.7775,        "88": 38.7355,        "89": 38.7429,        "90": 38.7,
        "91": 38.6938,        "92": 38.7112,        "93": 38.6628,        "94": 38.6631,        "95": 38.6655,
        "96": 38.6416,        "97": 38.6095,        "98": 38.5959,        "99": 38.6006,        "100": 38.6035,
        "101": 38.569,        "102": 38.5079,        "103": 38.4387,        "104": 38.478,        "105": 38.4989,
        "106": 38.4834,        "107": 38.457,        "108": 38.4364,        "109": 38.442,        "110": 38.416,
        "111": 38.3723,        "112": 38.3612,        "113": 38.3762,        "114": 38.3188,        "115": 38.2816,
        "116": 38.284,        "117": 38.2668,        "118": 38.2629,        "119": 38.2407,        "120": 38.181,
        "121": 38.1483,        "122": 38.0297,        "123": 38.0043,        "124": 37.9525,        "125": 37.9622,
        "126": 37.9786,        "127": 37.9752,        "128": 37.9024,        "129": 37.8689,        "130": 37.8603,
        "131": 37.7631,        "132": 37.7323,        "133": 37.6676,        "134": 37.6885,        "135": 37.6633,
        "136": 37.5873,        "137": 37.5438,        "138": 37.502,        "139": 37.4649,        "140": 37.3939,
        "141": 37.3237,        "142": 37.2187,        "143": 37.2028,        "144": 37.1218,        "145": 37.0721,
        "146": 37.0293,        "147": 36.9243,        "148": 36.9132,        "149": 36.7974,        "150": 36.7012
    }
}

**Comment by rpetit3** [comment]
Well that looks great too! I'm going to hop onto ogston and see if I can figure this out

**Comment by rpetit3** [comment]
Hey Michelle!

I don't think you're going to like this, but I was able to assemble your sample. Did you run it on ogston with `-profile slurm`? I only ask because ogston has an older AMD CPU (~2009) and I've had some programs from Conda not work correctly.

Robert

**Comment by MHargita** [comment]
ah interesting, I've never heard of -profile slurm. Should I try and reinstall conda?

**Comment by rpetit3** [comment]
@MHargita I'm going to go ahead and close this, please feel free to reopen if using SLURM doesn't fix your problem.
