### ISSUE TITLE
Calculating Genome Coverage [question]

### ISSUE THREAD

**Issue by zirbez** [bactopia/bactopia#219]
Hello again rpetit3!

I was curious whether there is anywhere in the output that I could find the estimated base coverage across the genome. I looked through the output documentation, and though I do not have the mapping folder, I found that at the end of the shovill text file in the assembly folder there is the following line: 

```
Mean total coverage: 90 [shovill]
```

I was wondering whether this would be the genome coverage for the sample. I was intending to use this value in a GenBank submission.

Thank you!

**Comment by rpetit3** [comment]
Hi @zirbez 

Sorry for the delay in response. For the assembly coverage I think the contig header has a field `cov=xxx` that has the contig coverage.

If you are looking for the estimated sequence coverage, these files (https://bactopia.github.io/output-overview/#quality-control) will have that info.

Let me know if this helps!
Robert

**Comment by zirbez** [comment]
No worries! I was able to pull the length from the assembly/quast report, and then divided by the reference genome length to get the coverage!
