### ISSUE TITLE
[bug] Unable to build datasets

### ISSUE THREAD

**Issue by mboum** [bactopia/bactopia#220]
**Description**
Congrats for this new tool, curious to try out. 
While I successfully installed the bactopia conda environment on my mac, when trying to run the tutorial, at the build datasets step, I ran in the following error :

**Steps to Reproduce**
bactopia datasets
2021-05-20 10:30:48:root:INFO - Setting up Ariba datasets
2021-05-20 10:30:48:root:INFO - Setting up vfdb_core Ariba dataset
External command failed with exit code 1!

Command:
bash -c 'ariba prepareref -f ./datasets/ariba/vfdb_core.fa -m ./datasets/ariba/vfdb_core.tsv ./datasets/ariba/vfdb_core'

Standard error:
ERROR: I tried to get the version of nucmer with: "/Users/mbouma/anaconda2/envs/Bactopia/bin/nucmer --version" and the output didn't match this regular expression: "([0-9]+\.[0-9\.]+.*$)"

Something wrong with at least one dependency. Please see the above error message(s)
ARIBA version: 2.14.6

External dependencies:
bowtie2	2.3.5.1	/Users/mbouma/anaconda2/envs/Bactopia/bin/bowtie2
cdhit	4.8.1	/Users/mbouma/anaconda2/envs/Bactopia/bin/cd-hit-est
nucmer	ERROR	/Users/mbouma/anaconda2/envs/Bactopia/bin/nucmer

External dependencies OK: False

Python version:
3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 15:59:12) 
[Clang 11.0.1 ]

Python packages:
ariba	2.14.6	/Users/mbouma/anaconda2/envs/bactopia/lib/python3.7/site-packages/ariba/__init__.py
bs4	4.9.3	/Users/mbouma/anaconda2/envs/bactopia/lib/python3.7/site-packages/bs4/__init__.py
dendropy	4.5.2	/Users/mbouma/anaconda2/envs/bactopia/lib/python3.7/site-packages/dendropy/__init__.py
pyfastaq	3.17.0	/Users/mbouma/anaconda2/envs/bactopia/lib/python3.7/site-packages/pyfastaq/__init__.py
pymummer	0.10.3	/Users/mbouma/anaconda2/envs/bactopia/lib/python3.7/site-packages/pymummer/__init__.py
pysam	0.15.3	/Users/mbouma/anaconda2/envs/bactopia/lib/python3.7/site-packages/pysam/__init__.py

Python packages OK: True

Everything looks OK: False

**Execution Environment**

- Bactopia Version: 1.7.0
- OS: Mac
- Environment: conda

**Comment by mboum** [comment]
I should also add that 
/Users/mbouma/anaconda2/envs/Bactopia/bin/nucmer --version

gives 

-bash: /Users/mbouma/anaconda2/envs/Bactopia/bin/nucmer: /usr/local/bin/perl: bad interpreter: No such file or directory

**Comment by rpetit3** [comment]
Hello! 

Apologies for the delay in responding! I think the problem might be that nucmer is hard coded to look for Perl in `/usr/local/bin/perl`

An easy fix would be to add a symbolic link to your Perl path to `/usr/local/bin/perl`

Robert

**Comment by mboum** [comment]
Thank you for your answer. I tried the proposed solution, but this did not resolve my problem.

With $ which perl, I found my Perl path : /Users/mbouma/anaconda2/envs/bactopia/bin/perl

So, i added a symbolic link to it in /usr/local/bin/perl

Yet, I still get the same error when running $ bactopia datasets.

Now, /Users/mbouma/anaconda2/envs/Bactopia/bin/nucmer --version

gives:
-bash: /Users/mbouma/anaconda2/envs/Bactopia/bin/nucmer: /usr/local/bin/perl: bad interpreter: Permission denied

Thank you for your help!

Mathilde

**Comment by rpetit3** [comment]
Hi! 

Let's see if we can figure this out! It sounds like you did everything I would have, but can we double check?

What are the outputs of:
```
ls -lh /Users/mbouma/anaconda2/envs/bactopia/bin/perl

# and 
ls -lh /usr/local/bin/perl
```

Also, here's a solution that worked for a previous user: https://github.com/bactopia/bactopia/issues/214#issuecomment-819566584

**Comment by mboum** [comment]
So, ls -lh /Users/mbouma/anaconda2/envs/bactopia/bin/perl

gives

-rwxrwxr-x  2 mbouma  staff   1.9M Oct 28  2020 /Users/mbouma/anaconda2/envs/bactopia/bin/perl

and

ls -lh /usr/local/bin/perl

gives 

lrwxr-xr-x  1 mbouma  admin    46B Jun  3 17:16 perl -> /Users/mbouma/anaconda2/envs/bactopia/bin/perl

**Comment by rpetit3** [comment]
Thank you for doing that, I just wanted to double check.

I guess the nextstep is to install perl to `/usr/local/bin`, or find the nucmer related files and change the SHEBANG similar to https://github.com/bactopia/bactopia/issues/214#issuecomment-819566584 (not ideal, but an issue on nucmer's conda install)

**Comment by rpetit3** [comment]
Hi @mboum 

I'm going to close this for now, please feel to reopen if you think I can help with anything.
