### ISSUE TITLE
[feature] Custom additional steps at the end of the main workflow

### ISSUE THREAD

**Issue by simone-pignotti** [bactopia/bactopia#222]
**Related To**

- [x] Bactopia
- [ ] Bactopia Tools

**Is this related to a problem?**
Kind of: while downstream analysis of the main Bactopia pipeline is supposed to be carried out with Bactopia Tools, I am in a situation where I am using the cloud execution wrapper (see #167) to distribute the Bactopia pipeline on cloud instances, so that all the steps for a same sample are run by the same node.
It is quite tricky to do the same for Bactopia Tools, and while some of them require all the Bactopia outputs (e.g. roary), others are sample-specific and could actually be added as an additional step in Bactopia. Also, there are way too many tools out there for all of them to be integrated in Bactopia :) and I believe that modularity is a great feature for such a complete and fully automated pipeline.

**Is this something you would like to see added?**
The possibility to define custom additional steps for the main nextflow workflow.

**Describe the solution you'd like**
One solution could be the addition of a `.nf` nextflow file as command line parameter. This file would contain additional `process` blocks which could reference outputs of the other Bactopia workflow steps. These process blocks could be imported in `main.nf` to expand the default workflow.
One big problem is the availability of tools and databases in the environment: for this to work seamlessly and modularly, maybe there should be a way to also pass an extra conda env definition, that can be created and/or activated before running the custom step.

**Additional Information**
Of course this can be easily achieved by forking the repository and adding custom modules directly to `main.nf`. The problem with this is that it involves a great deal of maintenance and could be easily broken when merging future commits from the main Bactopia repo, which is in active development and has pretty frequent releases. It would also mean that one loses the capability to install from conda and use docker, limiting a lot the deployment options.

As an example of use case, I would love to add a prophage annotation step (e.g. [PhiSpy](https://github.com/linsalrob/PhiSpy)) that uses the prokka gbk as input.

**Comment by rpetit3** [comment]
Hi @simone-pignotti 

Great hearing from you again!  I've been thinking the same with regards to this.

I think Nextflow's DSL2 will probably take care of most of this for us by allowing the creation of modules. This would totally allow you to say "yeah use Bactopia, but also include this workflow (e.g. pirate)".

Let me look into this and I'll update soon
Robert

**Comment by simone-pignotti** [comment]
Great to hear that! Thanks a lot :)

**Comment by rpetit3** [comment]
@simone-pignotti looking for some feedback if you don't mind.

I'm working on v2, since you are primarily using the cloud for analyses. Do you prefer every task to be a single program or include multiple programs in a single task?

Example:
```
# Assembly process split into to tasks (two AWS batch submissions)
run shovill (use shovill container)
run assembly-scan (use assembly-scan)

# Current assembly process (single AWS batch submission)
run shovill and assembly-scan (use bactopia-assemble_genome container)
```

I guess, do you notice start/stop times of jobs ever being an issue for really small tasks on the cloud? I've always been in the camp of preferring to include a task that takes a few seconds (e.g. assembly-scan) in the longer task (e.g. assembling a genome)

**Comment by simone-pignotti** [comment]
Hello! I am on the same side: for the sake of performance, I'd rather pool short jobs with the "closest" long one (I do notice quite some overhead with AWS when spawning short jobs, although I can't really quantify that, sorry).
On the other hand, workflow definitions usually look clearer when each atomic task is defined separately.

Personally I love your idea of the nextflow-within-nextflow inception :) I have reused it for some other projects, I find it easily generalisable, reliable and efficient. The only problem is that it requires the creation of the custom AMI, which for some people could be a barrier to adoption.
If you were to maintain a public AMI and a [cloudformation](https://aws.amazon.com/cloudformation/) definition (for the compute environment and all its IAM permissions), we could use bactopia on AWS just as quickly as we would locally. This is probably a lot of work for you to maintain though, and if the databases are shipped with the AMI it's tricky to add custom ones.
For the first problem, you could check with AWS if they can provide support/funding for this; I have found their team to be very accommodating for this kind of requests, and they could use this for one of their tutorials (like [this](https://genomics-nf.workshop.aws/intro.html)).
For the second one, I believe it would be possible to add an optional parameter to the wrapper's configuration to get species-specific (or other custom) databases from S3.

I don't think nextflow supports this, but the best compromise would obviously be to have an option to pool processes together in the same AWS batch job, without the need for the nextflow-within-nextflow trick. This is possible in Snakemake (see [job grouping](https://snakemake.readthedocs.io/en/stable/executing/grouping.html) docs). It's probably worth opening a feature request in the nextflow repo.

My whole message was focused on AWS, but I guess Google and Azure don't differ so much. The problem is that each would require a considerable amount of work to achieve a good level of support (need to maintain different resources for each cloud provider...I wish they all agreed on some standards to make developers' life easier).
The other option is to write generic instructions for cloud execution in the docs, but personally it took me weeks to figure out how to make everything work. I didn't have much experience with AWS batch when I started, so this probably doesn't apply to everyone.

I went a bit off-topic but I hope you'll find this useful :) the short answer is, for lack of a better solution, I would group assembly and scan in the same process. Or, write some documentation and a solid wrapper for the nextflow inception.

**Comment by rpetit3** [comment]
This is very useful into Simone! I'm going to try and work some of this into v2. Thank you very much!

I really like Snakemake's job grouping. Looks like there might be a related feature request at https://github.com/nextflow-io/nextflow/issues/1822 I'm definitely going to keep my eye on it. Because like you suggest this would solve some of the issues when using the cloud.

**Comment by rpetit3** [comment]
Another question for you. 

I have this script `check-staging.py` that's included in each of the processes. It just makes sure the file has been staged on the instance. I ran into an issue with Batch, where sometimes Nextflow would start running a task before the inputs were staged. I'm wondering if I can drop these `check-staging` steps.

Have you experienced this type of behavior working with Batch? (In general, not just with Bactopia)

**Comment by simone-pignotti** [comment]
> Have you experienced this type of behavior working with Batch? (In general, not just with Bactopia)

I never did actually, at least not with nextflow versions >=20. It should be safe to drop them.

**Comment by rpetit3** [comment]
Great thanks for the info!

**Comment by rpetit3** [comment]
Hi @simone-pignotti been a while but I think I'm ready to tackle this! 

I'm curious to get your thoughts on how you would like to tell bactopia to run certain additional steps.

I'm wondering if it should be automated for some species specific tools (spatyper, kleborate, extyper, etc...) based on the value of `--species`, or if the user should provide a list of additional steps they would like to run.

**Comment by rpetit3** [comment]
@simone-pignotti I've release v2 (https://github.com/bactopia/bactopia/releases/tag/v2.0.0) which is now completely DSL2. This should give us a path to make your suggestion a reality!

Cheers!
Robert

**Comment by simone-pignotti** [comment]
Great work @rpetit3, I will try to add some custom steps as soon as I can!
I guess the only thing missing before closing this issue would be testing and adding a doc page with a simple example showing how to add a step at the end of the pipeline.
[ectyper](https://github.com/nf-core/modules/tree/master/modules/ectyper) may be a good candidate, since it's already wrapped in nf-core, what do you think?

**Comment by rpetit3** [comment]
Even better is I've already got it into Bactopia v2! https://github.com/bactopia/bactopia/tree/master/subworkflows/local/ectyper

So I think this would need to be added to the bactopia workflow

```
include { ECTYPER } from '../subworkflows/local/ectyper/main';
....
// ectyper
ECTYPER(ASSEMBLE_GENOME.out.fna_only)
```

I'm planning on revamping the docs, its partially there. So hopefully next few weeks

**Comment by simone-pignotti** [comment]
Wow, that's great!

**Comment by rpetit3** [comment]
@simone-pignotti in v2.0.1 I've added Merlin (https://github.com/bactopia/bactopia/blob/master/subworkflows/local/merlin/main.nf) which is a good example of an optional workflow for species specific tool selection. I think you might be able to use this as an example to implement custom workflows.

How it works is, if a user provides `--ask_merlin`, Bactopia will execute the Merlin. Merlin will then use the mash distance to determine which species specific tools to run.

I'm going to go ahead and close this issue for now. Please feel free to reopen or let me know if you have any feedback

Cheers,
Robert
