### ISSUE TITLE
[feature] Add Bactopia Tool for bactmap

### ISSUE THREAD

**Issue by rpetit3** [bactopia/bactopia#227]
**Related To**

- [X] Bactopia Tools

**Is this something you would like to see added?**
I would like to see a Bactopia Tool for bactmap (https://github.com/nf-core/bactmap) added

**Describe the solution you'd like**
Use the final FASTQs from bactopia to allow skipping trimming and down sampling.

**Comment by abhi18av** [comment]
We could also shrim/augment the code for fetching the samples using https://github.com/nf-core/fetchngs - what do you think?

**Comment by rpetit3** [comment]
Looking into this, it might be possible to feed the [pseudocontigs](https://bactopia.github.io/output-overview/#variants) produced during a Bactopia run into `bactmap`

Reached to bactmap folks to out to get an idea.
