### ISSUE TITLE
[question] gz error?

### ISSUE THREAD

**Issue by shlomobl** [bactopia/bactopia#229]
Hi,
Is is possible that fastq files need to be gz compressed?
I am getting the following error.
Any help highly appreciated :-)

[a7/93d307] NOTE: Process `fastq_status (2)` terminated with an error exit status (139) -- Execution is retried (1)

Bactopia Execution Summary
    ---------------------------
    Command Line    : nextflow run /media/shlomo/DATADRIVE0/conda/envs/bactopia//share/bactopia-1.7.x/main.nf -w /media/shlomo/DATADRIVE0/PmultB_2021/work/bactopia --fastqs fastqs.txt --species 'Pasteurella multocida' --outdir ./bactopia --assembler spades --centre KVI --datasets /media/shlomo/DATADRIVE0/conda/envs/bactopia/datasets
    Resumed         : false

    Completed At    : 2021-06-21T14:00:06.107243+03:00
    Duration        : 27.9s
    Success         : false
    Exit Code       : 139
    Error Report    : Error executing process > 'fastq_status (2)'

Caused by:
  Process `fastq_status (2)` terminated with an error exit status (139)

**Comment by rpetit3** [comment]
Hi @shlomobl, 

The FASTQ files should be gzipped. Although if you think its worthwhile I can add support for uncompressed FASTQs.

Cheers,
Robert

**Comment by shlomobl** [comment]
Hi,

Thanks for the prompt reply!

I can gzip the files then.

But it is worth mentioning in the guide that it works worth with gz only,
unless it is already there and I missed it.

The options when creating the fastqs.txt file gave me the impression that
you can use unzipped fastq.

Best,
Shlomo

**Comment by rpetit3** [comment]
Good call! Thank you very much for the feedback!

**Comment by rpetit3** [comment]
Going to close this one, feel free to reopen if gzipping the FASTQs doesn't solve the issue
