### ISSUE TITLE
[bug] cannot download references "terminated with an error exit status (1)

### ISSUE THREAD

**Issue by Steven-Kemp** [bactopia/bactopia#232]
**Description**
When executing the pipeline with command: 
bactopia --fastqs fastqs.txt --datasets datasets/ --species "Escherichia coli" --coverage 20 --outdir local_bactopia_farm --cpus 4

process seems to fail repeatedly on download references. Example error is 
[cf/eeb300] NOTE: Process `download_references (F11H3CX_S51 - 1 reference(s))` terminated with an error exit status (1) -- Execution is retried (1)

**Steps to Reproduce**
```
bactopia --fastqs fastqs.txt --datasets datasets/ --species "Escherichia coli" --coverage 20 --outdir local_bactopia_farm --cpus 4

Multi-sample local, fastqs.txt constructed with the bactopia MYFASTQs/ > fastqs.txt

**Expected Behavior**
Should download the references and continue working.

**Execution Environment**

Bactopia v1.7.1
OS: Linux HPC cluster (redhat enterprise)
Environment - fully contained conda environment according to installation instructions

**Additional Information**
Attached is the error log from the failure.
```
[erorr_message_refs.txt](https://github.com/bactopia/bactopia/files/6759989/erorr_message_refs.txt)

**Comment by rpetit3** [comment]
Hi @Steven-Kemp,

Looks like the issue (which you probably saw already) is with `rename`:
```
  rename: not enough arguments
  Try 'rename --help' for more information.
```

I'm wondering if your cluster is putting values at the front of the PATH (e.g. `PATH=/path/on/cluster/bin:/path/to/download_references/bin:....`), which might cause the non-Perl `rename` to be used.

Is it possible to use Singularity on your cluster and what is the queue system (SLURM, SGE, TORQUE, etc....) because we might be able to make a Nextflow profile to make use of your cluster's queue manager.

Either way, I'm going to see if I can replicate this on my end, since it has been a while since I tested the tutorial.

Cheers,
Robert

**Comment by rpetit3** [comment]
Hi @Steven-Kemp 

Can you provide details on your cluster? I've been unable to replicate locally.

Cheers,
Robert

**Comment by Steven-Kemp** [comment]
Hi @rpetit3 

Sorry, just seen this.

Despite it being a HPC, it doesn't have a queue system in place. As so few people use it, we run it directly. I can indeed use Singularity, yes. Would you advise trying that instead?

Best wishes,
Steve

**Comment by rpetit3** [comment]
Yeah, lets give that a go, see if we can replicate it. Keep me posted!

**Comment by Steven-Kemp** [comment]
Thanks - singularity gives an error: 

 "pull is only supported for shub URIs"

**Comment by rpetit3** [comment]
hmmm, that's a new one for me.

Try `bactopia pull --default` to see if that helps.

**Comment by Steven-Kemp** [comment]
Hi @rpetit3,

A little update - I couldn't get this to run with singularity, so I set up a local installation on my desktop - seems to be running smoothly at the moment however. It clearly didn't like my cluster environment I think.

**Comment by rpetit3** [comment]
Hi @Steven-Kemp,

Thank you for following up! Kind of glad it worked for you, but also bummed about the cluster environment.

Do you want to work together to see if we can get it working on your cluster? I would be happy to help out.

Robert

**Comment by rpetit3** [comment]
Hi @Steven-Kemp, 

I'm going to close this for now. If you want to work together on getting a profile created for your cluster, please feel free to reopen!

Robert
