### ISSUE TITLE
Rory with selected ref assemblies 

### ISSUE THREAD

**Issue by kusandeep** [bactopia/bactopia#235]
Hi @rpetit3,
Sorry, Here I am with another issue. It might just be me...

I am trying run Rory with list of assembly provided by --accession but it return with an error saying 

ERROR: No downloads matched your filter. Please check your options.

I am very sure I have provided the correct assembly name. So just checking if anyone else having the same issue...?

**Comment by rpetit3** [comment]
Let's see if we can get this figured out! What's the reference accession you've tried?

**Comment by kusandeep** [comment]
I have use the one below.
GCF_000341875.1
GCF_001593395.2
GCF_002968415.1
GCF_003073255.1
GCF_003285085.1
GCF_009738165.1
GCF_009789615.1
GCF_012647845.1
GCF_014495825.1
GCF_016415725.1
GCF_016834435.1

**Comment by rpetit3** [comment]
Ah! I apologize for the slow response.

Trying using `--accessions` instead of `--accession`

**Comment by kusandeep** [comment]
silly mistake. thanks for checking.
