### ISSUE TITLE
[question] Search for specific gene in all the analysed genome/isolates

### ISSUE THREAD

**Issue by kusandeep** [bactopia/bactopia#236]
Hi @rpetit3,

I was wondering what is the efficient way to search for specific genes and extract the sequences from all analysed samples? 

One way I could think of is to merge the databases from the blast folders and then and then conduct a search..? any suggestions?

Thanks,
Sandeep

**Comment by rpetit3** [comment]
Hi @kusandeep, 

This is definitely something I would like to add to v2. I think for the time being, like you suggest, building a blast database will all samples would be the way to go.

Something like might work for you to build a blast database with all samples

```
# If uncompressed (*.fna)
find <PATH_TO_BACTOPIA> -not -path "*work*" -path "*assembly*" -name "*.fna" | \
    xargs -I cat {} | \
    makeblastdb -dbtype "nucl" -title "All samples" -out <BLASTDB_OUTPUT_NAME>
    
# If compressed (*.fna.gz)
find <PATH_TO_BACTOPIA> -not -path "*work*" -path "*assembly*" -name "*.fna.gz" | \
    xargs -I zcat {} | \
    makeblastdb -dbtype "nucl" -title "All samples" -out <BLASTDB_OUTPUT_NAME>
```

**Comment by kusandeep** [comment]
Great thanks for the code. I will give this a go.

**Comment by rpetit3** [comment]
@kusandeep I'm going to go ahead and close this. I am planning in a future version to add a subworkflow for BLAST (e.g. `bactopia --wf blastn`) to allow this sort of thing.

**Comment by rpetit3** [comment]
Ah! Forgot to mention, please feel free to reopen! cheers
