### ISSUE TITLE
gtdb check_gtdb error[question]

### ISSUE THREAD

**Issue by kusandeep** [bactopia/bactopia#237]
Hi @rpetit3,

I am getting an error running gtdb on a group of my samples. the error from check_gtdb. see the error message below.

`Workflow` execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: 1.

The full error message was:

Error executing process > 'check_gtdb'

Caused by:
  Process `check_gtdb` terminated with an error exit status (1)

Command executed:

  gtdbtk check_install && touch gtdb-passed.txt

Command exit status:
  1

[2021-09-06 21:00:22] INFO:          |-- fastani          HASH MISMATCH 6a3555bb61d9cc3163c26e65772b96b8f58a2d84

  [/dataset/datacache/scratch/bactopia/gtdbtk/mrca_red/]
  [/dataset/datacache/scratch/bactopia/gtdbtk/mrca_red/] - 0/2 files (0.0%)
  [/dataset/datacache/scratch/bactopia/gtdbtk/mrca_red/] - 1/2 files (50.0%)

  [2021-09-06 21:00:22] INFO:          |-- mrca_red         HASH MISMATCH 6f661eef8e172a8a7e78af2a74fe4d079a3f5b0f
  [2021-09-06 21:00:22] ERROR: Unexpected files were seen, or the reference package is corrupt.
  [2021-09-06 21:00:22] ERROR: Controlled exit resulting from an unrecoverable error or warning.

Work dir:
  `/dataset/SK_PMI/................./run2/work/gtdb/15/6b66e947e96a83d558732904357c81`

**Comment by rpetit3** [comment]
Hi @kusandeep 

Is the is fresh GTDB database download or an older one?

**Comment by kusandeep** [comment]
It's old one. 
downloaded on 26/11/2020

**Comment by kusandeep** [comment]
Is there any way to check the integrity of the database..?

**Comment by rpetit3** [comment]
Its not you, the issue here is in v1.5.0 of GTDB they dropped backwards compatibility with previous database versions. (Release notes: https://github.com/Ecogenomics/GTDBTk/releases/tag/1.5.0)

So unfortunately, you'll have to download the latest version.

**Comment by kusandeep** [comment]
Hmm, Interesting. In this case, could y please check the command below? to replace the old one with new    

`bactopia tools gtdb --bactopia /bifo/itmp/SK_PMI/bactopia_out/amy/run2/ --gtdb /dataset/datacache/scratch/bactopia/gtdbtk/ --download_gtdb /dataset/datacache/scratch/bactopia/gtdbtk/ --outdir /bifo/itmp/SK_PMI/bactopia_out/amy/run2/ --cpus 16 --cleanup_workdir --force`

**Comment by rpetit3** [comment]
Looks good to me, is it giving you issues?

**Comment by kusandeep** [comment]
Thanks looking good so far. will have to see when it get to the check_gtdb step (will take some time, I guess). I will close this issue if it runs normally.
Thanks again for the quick response.

**Comment by kusandeep** [comment]
I am getting the same error again after running this command which seems to be working on 
--download_gtdb /dataset/datacache/scratch/bactopia/gtdbtk/ step but not on check_gtdb.

Do you think instead of overwriting I should create a new folder with this new dataset?

**Comment by kusandeep** [comment]
database issue solved, but I have new error no.  at pplacer step.

executor >  local (4)
[9c/b02e78] process > download_gtdb [100%] 1 of 1 ✔
[d7/5ab967] process > check_gtdb    [100%] 1 of 1 ✔
[93/b7b430] process > gtdb          [ 50%] 1 of 2, failed: 1, retries: 1
[9b/78ff08] NOTE: Process `gtdb` terminated with an error exit status (1) -- Execution is retried (1)

================================================================================
  EXCEPTION: PplacerException
    MESSAGE: An error was encountered while running pplacer.

**Comment by rpetit3** [comment]
Going to see if I can replicate this locally

**Comment by rpetit3** [comment]
OK! I'm getting an error too, although its not very helpful.

```
  ==> Step 5 of 9: Caching likelihood information on reference tree (99.58/227.81 GB, 43.71%).
  ==> Step 5 of 9: Caching likelihood information on reference tree.
  ==> Step 5 of 9: Caching likelihood information on reference tree.
  ==> Step 6 of 9: Pulling exponents.                               Process Process-10:
  Traceback (most recent call last):
    File "/home/robert_petit/miniconda3/envs/bactopia-1.7.1/share/bactopia-1.7.x/conda/envs/tools-gtdb-1.7.x/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
      self.run()
    File "/home/robert_petit/miniconda3/envs/bactopia-1.7.1/share/bactopia-1.7.x/conda/envs/tools-gtdb-1.7.x/lib/python3.8/multiprocessing/process.py", line 108, in run
      self._target(*self._args, **self._kwargs)
    File "/home/robert_petit/miniconda3/envs/bactopia-1.7.1/share/bactopia-1.7.x/conda/envs/tools-gtdb-1.7.x/lib/python3.8/site-packages/gtdbtk/external/pplacer.py", line 124, in _worker
      raise PplacerException('An error was encountered while '
  gtdbtk.exceptions.PplacerException: An error was encountered while running pplacer, check the log file: classify/classify/intermediate_results/pplacer/pplacer.bac120.out
  ```
  
  ```
  cat /home/robert_petit/test/bactopia/work/gtdb/31/ef807949ccd1dffaff0ad6b80cba6e/classify/classify/intermediate_results/pplacer/pplacer.bac120.out
Running pplacer v1.1.alpha19-0-g807f6f3 analysis on classify/align/gtdb.bac120.user_msa.fasta...
Didn't find any reference sequences in given alignment file. Using supplied reference alignment.
Pre-masking sequences... sequence length cut from 5037 to 4987.
Determining figs... figs disabled.
Allocating memory for internal nodes... done.
Caching likelihood information on reference tree...
```

I'm going to see if I can figure out what's happening

**Comment by rpetit3** [comment]
@kusandeep It looks like I ran out of memory.

**Comment by kusandeep** [comment]
In my case

**Comment by rpetit3** [comment]
I get to the third step as well. 

Just curious how much memory does your machine have?

**Comment by kusandeep** [comment]
Our system is very resourceful but needs to check the load though. I think I should run the job in Slurm where I can specify the no of CPU and memory...
What do you recommend for 30 genome queries with  GTDB?

**Comment by rpetit3** [comment]
I'd recommend a node with atleast 64GB of memory, and whatever you can get CPU wise.

**Comment by kusandeep** [comment]
And It worked . Thanks.

**Comment by rpetit3** [comment]
Look at that! Glad it worked for you! Cheers @kusandeep
