### ISSUE TITLE
[question]gather_fastqs 

### ISSUE THREAD

**Issue by kusandeep** [bactopia/bactopia#239]
HI @rpetit3, 

I am trying to run some assemblies files but getting a funny error, see below.
the input fastaqs.txt file

![image](https://user-images.githubusercontent.com/38409245/133351136-4cb6c03d-463d-416b-b2f9-ddc3f633c264.png)

`Error executing process > 'gather_fastqs (CE046.fasta)'

Caused by:
  /dataset/SK_PMI/itmp/bactopia_out/nanopore/amy_run2/CE046.fasta/logs: Not a directory`

**Comment by rpetit3** [comment]
Was your fastqs.txt created using `bactopia prepare`?

**Comment by kusandeep** [comment]
Thanks, @rpetit3 
I was always using .txt but I figured out that the issue was the sample name column where I had extention peasted as well.  Now everything runnuig fine now. Also could you please write me an example code to generate the fastqs.txt from the folder location below.

`kumars@invbfopp10:/dataset/SK_PMI/itmp/bactopia_out/nanopore/amy_run2/assemblies$ ls -l
total 50521
-rw-rw-r-- 1 kumars bacteria_users 4118008 Aug 16 11:26 CE046_C.fna
-rw-rw-r-- 1 kumars bacteria_users 4062913 Sep 15 11:36 CE046.fna
-rw-rw-r-- 1 kumars bacteria_users 4058865 Dec  5  2020 CE229.fna
-rw-rw-r-- 1 kumars bacteria_users 4062451 Dec  4  2020 CE230.fna
-rw-rw-r-- 1 kumars bacteria_users 4119317 Aug 16 11:27 CE232_C.fna
-rw-rw-r-- 1 kumars bacteria_users 4059661 Dec  5  2020 CE232.fna
-rw-rw-r-- 1 kumars bacteria_users 4118003 Aug 16 11:29 CE235_C.fna
-rw-rw-r-- 1 kumars bacteria_users 4062050 Dec  4  2020 CE235.fna
-rw-rw-r-- 1 kumars bacteria_users 4119317 Aug 16 11:30 CE241_C.fna
-rw-rw-r-- 1 kumars bacteria_users 4062935 Dec  4  2020 CE241.fna
-rw-rw-r-- 1 kumars bacteria_users 4116393 Aug 16 11:32 CE280_C.fna
-rw-rw-r-- 1 kumars bacteria_users 4059380 Dec  5  2020 CE280.fna
-rw-rw-r-- 1 kumars bacteria_users 4063322 Dec  4  2020 CE281.fna
-rw-rw-r-- 1 kumars bacteria_users 4063122 Dec  4  2020 CE287.fna
-rw-rw-r-- 1 kumars bacteria_users 4062627 Dec  5  2020 CE312.fna
`

**Comment by rpetit3** [comment]
Hey! Looks like you found a bug. The glob statement isn't working for assemblies. I'm going to rewrite it and have it fixed in the next version


It's not ideal, but this should work
```
bactopia prepare  assemblies/ --fastq_ext .fna --fastq_pattern *.fna | sed 's/single-end/assembly/'
```

Here's my example:
```
bactopia prepare  test_fna/ --fastq_ext .fna --fastq_pattern *.fna | sed 's/single-end/assembly/'
sample  runtype r1      r2      extra
1       assembly        /home/robert_petit/bactopia/test_fna/1.fna
10      assembly        /home/robert_petit/bactopia/test_fna/10.fna
2       assembly        /home/robert_petit/bactopia/test_fna/2.fna
3       assembly        /home/robert_petit/bactopia/test_fna/3.fna
4       assembly        /home/robert_petit/bactopia/test_fna/4.fna
5       assembly        /home/robert_petit/bactopia/test_fna/5.fna
6       assembly        /home/robert_petit/bactopia/test_fna/6.fna
7       assembly        /home/robert_petit/bactopia/test_fna/7.fna
8       assembly        /home/robert_petit/bactopia/test_fna/8.fna
9       assembly        /home/robert_petit/bactopia/test_fna/9.fna
```

**Comment by kusandeep** [comment]
Thanks, @rpetit3

**Comment by rpetit3** [comment]
No problem! Fixed submitted for next version: https://github.com/bactopia/bactopia/commit/ad3dcea896bf6ed1bf57de4f48367c09837bf904
