### ISSUE TITLE
ANI tool error

### ISSUE THREAD

**Issue by kusandeep** [bactopia/bactopia#243]
Hi @rpetit3, I am getting an error running ANI. See the error below. Could you please run some samples at your end and see if everything is alright?

` bactopia tools fastani --bactopia /bifo/itmp/SK_PMI/bactopia_out/ --cpus 4 --outdir /bifo/itmp/SK_PMI/bactopia_out/ --force`

`Error executing process > 'calculate_ani'

Caused by:
  No such property: local_reference for class: ScriptEF490762C6FF1287261B30D94B1FB406
`

**Comment by rpetit3** [comment]
Going to look into this today.

Are you in a rush to get this fixed? If yes, I'll get a small patch fix released instead of waiting until v2

**Comment by rpetit3** [comment]
I get this error, going to see about getting a fix put in place for you

V2, will include tests to help capture these types of "robert made a change and broke something" instances!

**Comment by kusandeep** [comment]
Thanks @rpetit3 not in a rush, but would be good to get this fix. Indeed looking forward to V2 for sure. Also would be great if you could have a look on #237

**Comment by rpetit3** [comment]
This is fixed now, https://github.com/bactopia/bactopia/commit/fa6b7220b5d337e703b960a38c184a5fa6c7b046

I'll try to get v1.7.2 pushed in the next day or so.

**Comment by rpetit3** [comment]
We can try a quick and dirty approach if you'd rather not wait

Basically we're downloading the latest workflow and replacing your current one with it
```
FASTANI_DIR=$(which bactopia | sed 's=bin/bactopia=share/bactopia-1.7.x/tools/fastani/=')
mv $FASTANI_DIR/main.nf $FASTANI_DIR/main.old
wget https://github.com/bactopia/bactopia/raw/master/tools/fastani/main.nf
mv main.nf $FASTANI_DIR/main.nf
```

**Comment by kusandeep** [comment]
work like a charm. Thanks.

**Comment by rpetit3** [comment]
Awesome! I'll hold off on v1.7.2 for now

working on GTDB, but as you know it takes forever to download the initial db
