### ISSUE TITLE
[bug] download_references fails when the reference genome has been removed

### ISSUE THREAD

**Issue by embatty** [bactopia/bactopia#245]
I found an edge case where the auto variant calling chooses the nearest reference based on a minmer sketch but the
reference genome has been removed/superseded in RefSeq and the sketch hasn't been updated yet. 
This was tested with datasets downloaded on 29/09/2021.
To reproduce use this accession:
```
bactopia --accession ERX4021268 --species "Klebsiella pneumoniae"
```
This tries to download reference GCA_002257935.3, but this has been replaced with GCA_002257935.4. It fails at the download_references step and the error file ncbi-genome-download.err contains "ERROR: No downloads matched your filter. Please check your options."

I've disabled auto variant calling to get round this, I've only run into this for one sample so I think it will be a rare event.

**Comment by rpetit3** [comment]
Thank you for posting this @embatty !

I thought I had this figured out with a quick check to see if the version had been updated. Going to look into why this accession fails that update.

Oh! I also wonder if this might be related to ncbi-genome-download caching. Will update soon!

Thanks again!

**Comment by rpetit3** [comment]
@embatty ! Good news, I have fixed this and it'll be in v2. The `select-references` script checked if the accession had been supressed but not if it had been updated.

It will now check if its updated and report the change.

```
GCA_002257935.3 0.01    GCF_002257935.4 GCA_002257935.3 replaced with GCF_002257935.4
Skipping GCF_000017125.1, it no longer in RefSeq or suppressed. Reason: "suppressed_refseq" or "supressed" found in "PropertyList"
GCF_000009645.1 0.0418234       GCF_000009645.1 no change in assembly version
GCF_000025145.1 0.0418234       GCF_000025145.1 no change in assembly version
```

**Comment by rpetit3** [comment]
Hi @embatty 

I've release v2 (https://github.com/bactopia/bactopia/releases/tag/v2.0.0) and this should now be fixed.  Please feel free to reopen if not.

Cheers!
Robert
