### ISSUE TITLE
[bug] path with spaces cause problems with "datasets"

### ISSUE THREAD

**Issue by telatin** [bactopia/bactopia#249]
**Description**
I try to avoid like plague paths with spaces, but sometimes they slip through.

**Steps to Reproduce**
Steps to reproduce the behaviour:
```
bactopia datasets
[...]
Downloading "http://www.mgc.ac.cn/VFs/Down/VFDB_setA_nt.fas.gz" and saving as "/.../shared drive/datasets/ariba/vfdb_core.tmp.download/VFDB_setA_nt.fas.gz"

gzip: drive/datasets/ariba/vfdb_core.tmp.download/VFDB_setA_nt.fas.gz: No such file or directory
       ^^^^ (truncated path)
```

**Expected Behavior**
Download of the datasets

**Execution Environment**

- Bactopia Version: 1.7.1
- OS: ubuntu
- Environment: conda

**Additional Information**
Any other information you think might be helpful in squashing this bug.

**Comment by rpetit3** [comment]
Hi @telatin 

Haha I'm going through the archives and cleaning up! This should no longer be an issue in v3 of Bactopia, so I'm going to go ahead and close this issue (_haha and make myself feel a little better about the total number of open issues going down!_)

On another note! I've put together a long overdue survey that would be super useful for getting feedback and helping guide future directions of Bactopia. If you have time, I would be super thankful is you completed my [2024 Bactopia Usage Survey](https://forms.gle/BA2BDHRQvZtpVcD38)!

Thank you so much!
Robert

**Comment by telatin** [comment]
Thanks for the spring cleaning and I will definitely complete the survey :)

**Comment by rpetit3** [comment]
Thank you very much @telatin !
