### ISSUE TITLE
Off line bactopia crushs

### ISSUE THREAD

**Issue by Najmabms** [bactopia/bactopia#253]
Hi 
I am using bactopia off line. I have my fastq folder ready and prepared. However, whenever I run the multiple samples FOFN command, it crushes. I am new to all this. I hope someone can help. below is the command used and the error generated. Thanks

COMMAND: bactopia --fastqs test-samples --datasets datasets/ --coverage 100 --cpus 2 --outdir local-multiple-samples

ERROR:

Traceback (most recent call last):
  File "/home/najmabms/anaconda3/envs/bactopia/bin/bactopia-build.py", line 212, in <module>
    execute(f'touch {install_path}/envs-built-{CONTAINER_VERSION}.txt')
  File "/home/najmabms/anaconda3/envs/bactopia/bin/bactopia-build.py", line 106, in execute
    from executor import ExternalCommand, ExternalCommandFailed
ModuleNotFoundError: No module named 'executor'
N E X T F L O W  ~  version 21.10.0
Launching `/home/najmabms/anaconda3/envs/bactopia/share/bactopia-1.7.x/main.nf` [wise_jepsen] - revision: e0e3135d71
bactopia - 1.7.1

Each task will use 2 CPUs out of the available 40 CPUs. At most 20 task(s) will be run at 
a time, this can affect the efficiency of Bactopia.

Found 1 Antimicrobial resistance datasets
	/home/najmabms/bactopia/fastqs/datasets/antimicrobial-resistance/amrfinderdb.tar.gz
Found 2 ARIBA datasets
	/home/najmabms/bactopia/fastqs/datasets/ariba/card.tar.gz
	/home/najmabms/bactopia/fastqs/datasets/ariba/vfdb_core.tar.gz
WARN: Warning: datasets//plasmid/null does not exist and will not be used for analysis.
Found 4 minmer sketches/signatures
	/home/najmabms/bactopia/fastqs/datasets/minmer/genbank-k21.json.gz
	/home/najmabms/bactopia/fastqs/datasets/minmer/genbank-k31.json.gz
	/home/najmabms/bactopia/fastqs/datasets/minmer/genbank-k51.json.gz
	/home/najmabms/bactopia/fastqs/datasets/minmer/refseq-k21-s1000.msh
--species not given, skipping the following processes (analyses):
	sequence_type
	call_variants
	primer_query

If something looks wrong, now's your chance to back out (CTRL+C 3 times). 
Sleeping for 5 seconds...
executor >  local (27)
[fe/156c9b] process > gather_fastqs (SRX7032024)        [100%] 5 of 5 ✔
[3c/15cdd1] process > fastq_status (4)                  [100%] 5 of 5 ✔
[1a/67b2b7] process > estimate_genome_size (SRX7032021) [ 60%] 3 of 5
[84/e98935] process > qc_reads (SRX7032021)             [ 40%] 2 of 5, failed: 2, retries: 2
[6b/d5b53b] process > qc_original_summary (SRX7032024)  [ 57%] 4 of 7, failed: 4, retries: 4
[-        ] process > qc_final_summary                  -
[-        ] process > assemble_genome                   -
[-        ] process > assembly_qc                       -
[-        ] process > make_blastdb                      -
[-        ] process > annotate_genome                   -
[-        ] process > count_31mers                      -
[-        ] process > sequence_type                     -
[-        ] process > ariba_analysis                    -
[-        ] process > minmer_sketch                     -
[-        ] process > minmer_query                      -
[-        ] process > call_variants                     -
[-        ] process > download_references               -
[-        ] process > call_variants_auto                -
[-        ] process > antimicrobial_resistance          -
[-        ] process > blast_primers                     -
[-        ] process > blast_proteins                    -
[-        ] process > mapping_query                     -
[35/77b8cc] NOTE: Process `qc_original_summary (SRX7032022)` terminated with an error exit status (1) -- Execution is retried (1)
[d7/39c2be] NOTE: Process `qc_reads (SRX7032022)` terminated with an error exit status (1) -- Execution is retried (1)
[ae/8c596c] NOTE: Process `qc_original_summary (SRX7032022)` terminated with an error exit status (1) -- Execution is retried (2)
[20/cf1d90] NOTE: Process `qc_reads (SRX7032022)` terminated with an error exit status (1) -- Execution is retried (2)
[39/354174] NOTE: Process `qc_original_summary (SRX7032022)` terminated with an error exit status (1) -- Execution is retried (3)
[d3/344a14] NOTE: Process `qc_original_summary (SRX7032024)` terminated with an error exit status (1) -- Execution is retried (1)
Error executing process > 'qc_original_summary (SRX7032022)'

Caused by:
  Process `qc_original_summary (SRX7032022)` terminated with an error exit status (1)

Command executed [/home/najmabms/anaconda3/envs/bactopia/share/bactopia-1.7.x/templates/qc_original_summary.sh]:

  #!/bin/bash
  set -e
  set -u
  LOG_DIR="qc_original_summary"
  mkdir -p ${LOG_DIR}
  echo "# Timestamp" > ${LOG_DIR}/qc_original_summary.versions
  date --iso-8601=seconds >> ${LOG_DIR}/qc_original_summary.versions
  
  echo "# FastQC Version" >> ${LOG_DIR}/qc_original_summary.versions
  fastqc -version>> ${LOG_DIR}/qc_original_summary.versions 2>&1
  
  echo "# fastq-scan Version" >> ${LOG_DIR}/qc_original_summary.versions
executor >  local (27)
[fe/156c9b] process > gather_fastqs (SRX7032024)        [100%] 5 of 5 ✔
[3c/15cdd1] process > fastq_status (4)                  [100%] 5 of 5 ✔
[1a/67b2b7] process > estimate_genome_size (SRX7032021) [ 60%] 3 of 5
[84/e98935] process > qc_reads (SRX7032021)             [ 40%] 2 of 5, failed: 2, retries: 2
[47/c066af] process > qc_original_summary (SRX7032022)  [ 71%] 5 of 7, failed: 5, retries: 4
[-        ] process > qc_final_summary                  -
[-        ] process > assemble_genome                   -
[-        ] process > assembly_qc                       -
[-        ] process > make_blastdb                      -
[-        ] process > annotate_genome                   -
[-        ] process > count_31mers                      -
[-        ] process > sequence_type                     -
[-        ] process > ariba_analysis                    -
[-        ] process > minmer_sketch                     -
[-        ] process > minmer_query                      -
[-        ] process > call_variants                     -
[-        ] process > download_references               -
[-        ] process > call_variants_auto                -
[-        ] process > antimicrobial_resistance          -
[-        ] process > blast_primers                     -
[-        ] process > blast_proteins                    -
[-        ] process > mapping_query                     -
[35/77b8cc] NOTE: Process `qc_original_summary (SRX7032022)` terminated with an error exit status (1) -- Execution is retried (1)
[d7/39c2be] NOTE: Process `qc_reads (SRX7032022)` terminated with an error exit status (1) -- Execution is retried (1)
[ae/8c596c] NOTE: Process `qc_original_summary (SRX7032022)` terminated with an error exit status (1) -- Execution is retried (2)
[20/cf1d90] NOTE: Process `qc_reads (SRX7032022)` terminated with an error exit status (1) -- Execution is retried (2)
[39/354174] NOTE: Process `qc_original_summary (SRX7032022)` terminated with an error exit status (1) -- Execution is retried (3)
[d3/344a14] NOTE: Process `qc_original_summary (SRX7032024)` terminated with an error exit status (1) -- Execution is retried (1)
Error executing process > 'qc_original_summary (SRX7032022)'

Caused by:
  Process `qc_original_summary (SRX7032022)` terminated with an error exit status (1)

Command executed [/home/najmabms/anaconda3/envs/bactopia/share/bactopia-1.7.x/templates/qc_original_summary.sh]:

  #!/bin/bash
  set -e
  set -u
  LOG_DIR="qc_original_summary"
  mkdir -p ${LOG_DIR}
  echo "# Timestamp" > ${LOG_DIR}/qc_original_summary.versions
  date --iso-8601=seconds >> ${LOG_DIR}/qc_original_summary.versions
  
  echo "# FastQC Version" >> ${LOG_DIR}/qc_original_summary.versions
  fastqc -version>> ${LOG_DIR}/qc_original_summary.versions 2>&1
  
  echo "# fastq-scan Version" >> ${LOG_DIR}/qc_original_summary.versions
  fastq-scan -v >> ${LOG_DIR}/qc_original_summary.versions 2>&1
  
  # Verify AWS files were staged
  if [[ ! -L "SRX7032022_R1.fastq.gz" ]]; then
      if [ "false" == "true" ]; then
          check-staging.py --fq1 SRX7032022_R1.fastq.gz --extra empty.fna.gz --genome_size SRX7032022-genome-size.txt --is_single
      else
          check-staging.py --fq1 SRX7032022_R1.fastq.gz --fq2 SRX7032022_R2.fastq.gz --extra empty.fna.gz --genome_size SRX7032022-genome-size.txt
      fi
  fi
  
  GENOME_SIZE=`head -n 1 SRX7032022-genome-size.txt`
  if [ "false" == "false" ]; then
      # Paired-End Reads
      gzip -cd SRX7032022_R1.fastq.gz | fastq-scan -g ${GENOME_SIZE} > SRX7032022_R1-original.json
      gzip -cd SRX7032022_R2.fastq.gz | fastq-scan -g ${GENOME_SIZE} > SRX7032022_R2-original.json
      ln -s SRX7032022_R1.fastq.gz SRX7032022_R1-original.fastq.gz
      ln -s SRX7032022_R2.fastq.gz SRX7032022_R2-original.fastq.gz
      fastqc --noextract -f fastq -t 1 SRX7032022_R1-original.fastq.gz SRX7032022_R2-original.fastq.gz
  else
      # Single-End Reads
      gzip -cd SRX7032022_R1.fastq.gz | fastq-scan -g ${GENOME_SIZE} > SRX7032022-original.json
      ln -s SRX7032022_R1.fastq.gz SRX7032022-original.fastq.gz
      fastqc --noextract -f fastq -t 1 SRX7032022-original.fastq.gz
  fi
  
  mkdir -p quality-control/summary-original
  mv *.json  quality-control/summary-original
  mv *fastqc.html quality-control/summary-original
  mv *fastqc.zip quality-control/summary-original
  
  if [ "false" == "false" ]; then 
      cp .command.err ${LOG_DIR}/qc_original_summary.err
      cp .command.out ${LOG_DIR}/qc_original_summary.out
      cp .command.sh ${LOG_DIR}/qc_original_summary.sh || :
      cp .command.trace ${LOG_DIR}/qc_original_summary.trace || :
  else
      rm -rf ${LOG_DIR}/
  fi

Command exit status:
  1

Command output:
  (empty)

Work dir:
  /home/najmabms/bactopia/fastqs/work/bactopia/47/c066aff7f4bc63e07ce2d2eee0d5b5

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

    Bactopia Execution Summary
    ---------------------------
    Command Line    : nextflow run /home/najmabms/anaconda3/envs/bactopia//share/bactopia-1.7.x/main.nf -w /home/najmabms/bactopia/fastqs/work/bactopia --fastqs test-samples --datasets datasets/ --coverage 100 --cpus 2 --outdir local-multiple-samples
    Resumed         : false

    Completed At    : 2021-11-30T12:05:08.020695+04:00
    Duration        : 37.8s
    Success         : false
    Exit Code       : 1
    Error Report    : Error executing process > 'qc_original_summary (SRX7032022)'

Caused by:
  Process `qc_original_summary (SRX7032022)` terminated with an error exit status (1)

Command executed [/home/najmabms/anaconda3/envs/bactopia/share/bactopia-1.7.x/templates/qc_original_summary.sh]:

  #!/bin/bash
  set -e
  set -u
  LOG_DIR="qc_original_summary"
  mkdir -p ${LOG_DIR}
  echo "# Timestamp" > ${LOG_DIR}/qc_original_summary.versions
  date --iso-8601=seconds >> ${LOG_DIR}/qc_original_summary.versions
  
  echo "# FastQC Version" >> ${LOG_DIR}/qc_original_summary.versions
  fastqc -version>> ${LOG_DIR}/qc_original_summary.versions 2>&1
  
  echo "# fastq-scan Version" >> ${LOG_DIR}/qc_original_summary.versions
  fastq-scan -v >> ${LOG_DIR}/qc_original_summary.versions 2>&1
  
  # Verify AWS files were staged
  if [[ ! -L "SRX7032022_R1.fastq.gz" ]]; then
      if [ "false" == "true" ]; then
          check-staging.py --fq1 SRX7032022_R1.fastq.gz --extra empty.fna.gz --genome_size SRX7032022-genome-size.txt --is_single
      else
          check-staging.py --fq1 SRX7032022_R1.fastq.gz --fq2 SRX7032022_R2.fastq.gz --extra empty.fna.gz --genome_size SRX7032022-genome-size.txt
      fi
  fi
  
  GENOME_SIZE=`head -n 1 SRX7032022-genome-size.txt`
  if [ "false" == "false" ]; then
      # Paired-End Reads
      gzip -cd SRX7032022_R1.fastq.gz | fastq-scan -g ${GENOME_SIZE} > SRX7032022_R1-original.json
      gzip -cd SRX7032022_R2.fastq.gz | fastq-scan -g ${GENOME_SIZE} > SRX7032022_R2-original.json
      ln -s SRX7032022_R1.fastq.gz SRX7032022_R1-original.fastq.gz
      ln -s SRX7032022_R2.fastq.gz SRX7032022_R2-original.fastq.gz
      fastqc --noextract -f fastq -t 1 SRX7032022_R1-original.fastq.gz SRX7032022_R2-original.fastq.gz
  else
      # Single-End Reads
      gzip -cd SRX7032022_R1.fastq.gz | fastq-scan -g ${GENOME_SIZE} > SRX7032022-original.json
      ln -s SRX7032022_R1.fastq.gz SRX7032022-original.fastq.gz
      fastqc --noextract -f fastq -t 1 SRX7032022-original.fastq.gz
  fi
  
  mkdir -p quality-control/summary-original
  mv *.json  quality-control/summary-original
  mv *fastqc.html quality-control/summary-original
  mv *fastqc.zip quality-control/summary-original
  
  if [ "false" == "false" ]; then 
      cp .command.err ${LOG_DIR}/qc_original_summary.err
      cp .command.out ${LOG_DIR}/qc_original_summary.out
      cp .command.sh ${LOG_DIR}/qc_original_summary.sh || :
      cp .command.trace ${LOG_DIR}/qc_original_summary.trace || :
  else
      rm -rf ${LOG_DIR}/
  fi

Command exit status:
  1

Command output:
  (empty)

Work dir:
  /home/najmabms/bactopia/fastqs/work/bactopia/47/c066aff7f4bc63e07ce2d2eee0d5b5

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

    Launch Dir      : /home/najmabms/bactopia/fastqs
    Working Dir     : /home/najmabms/bactopia/fastqs/work/bactopia (Total Size: 32.085G)
    Working Dir Size: 32.085G

    
WARN: Killing pending tasks (7)

**Comment by rpetit3** [comment]
Hi @Najmabms 

Let's see if we can get this figured out!

Do you think you can post the contents of: 
```
/home/najmabms/bactopia/fastqs/work/bactopia/47/c066aff7f4bc63e07ce2d2eee0d5b5/.command.err 
/home/najmabms/bactopia/fastqs/work/bactopia/47/c066aff7f4bc63e07ce2d2eee0d5b5/.command.log
/home/najmabms/bactopia/fastqs/work/bactopia/47/c066aff7f4bc63e07ce2d2eee0d5b5/.command.out
```

I'm wondering if a program is trying to use internet for some reason (maybe analytics?)

**Comment by Najmabms** [comment]
all the files (.command.err, .command.log, .command.out) are emptey.

**Comment by rpetit3** [comment]
Hmmm, are there any other files in that directory?

**Comment by Najmabms** [comment]
Hi, Sorry for the delay. I was unable to enter the server for a while and check the files.
I tried applying this tip that appeared at the end of the error. 

Tip: you can replicate the issue by changing to the process work dir and entering the command bash 

and after doing do the files (.command.err, .command.log, .command.out)  disappeared and the followings were created:
SRX7032022-genome-size.txt  
SRX7032022_R1.fastq.gz  
SRX7032022_R2.fastq.gz  
empty.fna.gz  qc_
original_summary/

the last one is a directory that has only one file:
original_summary/qc_original_summary.versions

**Comment by Najmabms** [comment]
This is what I get during the run:
If something looks wrong, now's your chance to back out (CTRL+C 3 times). 
Sleeping for 5 seconds...
executor >  local (21)
executor >  local (22)
[b3/b15679] process > gather_fastqs (SRX7032024)        [100%] 5 of 5 ✔
executor >  local (22)
[b3/b15679] process > gather_fastqs (SRX7032024)        [100%] 5 of 5 ✔
executor >  local (24)
[b3/b15679] process > gather_fastqs (SRX7032024)        [100%] 5 of 5 ✔
executor >  local (26)
[b3/b15679] process > gather_fastqs (SRX7032024)        [100%] 5 of 5 ✔
executor >  local (27)
[b3/b15679] process > gather_fastqs (SRX7032024)        [100%] 5 of 5 ✔
[4e/397751] process > fastq_status (4)                  [100%] 5 of 5 ✔
executor >  local (27)
[b3/b15679] process > gather_fastqs (SRX7032024)        [100%] 5 of 5 ✔
[4e/397751] process > fastq_status (4)                  [100%] 5 of 5 ✔
executor >  local (27)
[b3/b15679] process > gather_fastqs (SRX7032024)        [100%] 5 of 5 ✔
[4e/397751] process > fastq_status (4)                  [100%] 5 of 5 ✔
[77/55c52f] process > estimate_genome_size (SRX7032021) [ 60%] 3 of 5
[07/d2d458] process > qc_reads (SRX7032022)             [ 50%] 3 of 6, failed: 3, retries: 3
[99/cb2a56] process > qc_original_summary (SRX7032021)  [ 50%] 3 of 6, failed: 3, retries: 3
[-        ] process > qc_final_summary                  -
[-        ] process > assemble_genome                   -
[-        ] process > assembly_qc                       -
[-        ] process > make_blastdb                      -
[-        ] process > annotate_genome                   -
[-        ] process > count_31mers                      -
[-        ] process > sequence_type                     -
[-        ] process > ariba_analysis                    -
[-        ] process > minmer_sketch                     -
[-        ] process > minmer_query                      -
[-        ] process > call_variants                     -
[-        ] process > download_references               -
[-        ] process > call_variants_auto                -
[-        ] process > antimicrobial_resistance          -
[-        ] process > blast_primers                     -
[-        ] process > blast_proteins                    -
[-        ] process > mapping_query                     -
[e1/a54760] NOTE: Process `qc_original_summary (SRX7032022)` terminated with an error exit status (1) -- Execution is retried (1)
[bc/e017d3] NOTE: Process `qc_reads (SRX7032022)` terminated with an error exit status (1) -- Execution is retried (1)
[14/614f02] NOTE: Process `qc_original_summary (SRX7032022)` terminated with an error exit status (1) -- Execution is retried (2)
[4a/52aebd] NOTE: Process `qc_reads (SRX7032022)` terminated with an error exit status (1) -- Execution is retried (2)
[8a/a81ff2] NOTE: Process `qc_original_summary (SRX7032022)` terminated with an error exit status (1) -- Execution is retried (3)
[dc/4c30f0] NOTE: Process `qc_reads (SRX7032022)` terminated with an error exit status (1) -- Execution is retried (3)

**Comment by rpetit3** [comment]
This is actually very useful. These two processes only call two programs: fastqc and fastq-scan. 

What does the content of `original_summary/qc_original_summary.versions`  look like. I think that will be helpful.

**Comment by Najmabms** [comment]
this is the content of the file:

Timestamp
2021-11-30T12:13:26+04:00
# FastQC Version
Error: Could not find or load main class uk.ac.babraham.FastQC.FastQCApplication
Caused by: java.lang.ClassNotFoundException: uk.ac.babraham.FastQC.FastQCApplication
