### ISSUE TITLE
--skipp_plsdb

### ISSUE THREAD

**Issue by shlomobl** [bactopia/bactopia#257]
Hi,

The datasets command seem not to be recognizing the "--skip_plsdb" option.

Worth taking a look at it :-)

Thanks!

**Comment by rpetit3** [comment]
Hi @shlomobl, 

Did I have this in the docs somewhere? (I need to update docs!) I removed `PLDB` from Bactopia Datasets a few versions back, so its always skipped now.

Cheers,
Robert

**Comment by shlomobl** [comment]
I got an error message that it does not recognize it as a bactopia
parameter.

Also, the --update_amr parameter is giving the same error.

Both are described in the docs.

Best,
Shlomo

**Comment by rpetit3** [comment]
Okie doke! Thank you for this info, I'm in the process of updating the docs for v2, fill get these removed

**Comment by rpetit3** [comment]
Ok, removed this in the docs. Thank you for pointing them out. I'll slowly be working my way through.

Let me know if you have any suggestions!

Thanks agian,
Robert
