### ISSUE TITLE
[bug] Failed to launch the Java virtual machine

### ISSUE THREAD

**Issue by brross60** [bactopia/bactopia#260]
Trying to run the pangenome tool and can't seem to get it to work. Help would be amazing !!!!

Code:
bactopia --wf pangenome --bactopia /xxx/scratch/WGS/Illumina.Reads/bactopia --use-roary --include genomes.txt --traits traits.csv
Error: 
Failed to launch the Java virtual machine
NOTE: Nextflow is trying to use the Java VM defined by the following environment variables:
 JAVA_CMD: xxxx/.conda/envs/bactopia/bin/java
 NXF_OPTS:

Bactopia Version 2.0.0
conda 4.10.1
Python 3.8.12

**Comment by rpetit3** [comment]
Hi @brross60 

Let's see if we can get this figured out! What kind of system are you running this on? (local, cluster cloud?)

**Comment by brross60** [comment]
I am on a cluster. I am guessing it's an issue with the conda environment but not sure how to address a java issue. this is what i get for java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment Zulu10.3+5 (build 10.0.2+13)
OpenJDK 64-Bit Server VM Zulu10.3+5 (build 10.0.2+13, mixed mode)

**Comment by rpetit3** [comment]
Do you by chance have access to docker or Singularity on you cluster? And do you know the scheduler (e.g slurm, sge, etc...)?

**Comment by brross60** [comment]
Figure it out. The computing core changed our anaconda3 default version. I got to start working.

**Comment by rpetit3** [comment]
Great! going to close this for now please feel free to reopen
