### ISSUE TITLE
How to run bactopia tools pirate v2.0.0 with local assemblies

### ISSUE THREAD

**Issue by haruosuz** [bactopia/bactopia#261]
I run bactopia tools pirate - 1.6.5 with local assemblies (*.fna of completed genomes) using:
```
bactopia tools pirate --only_completed --assembly ./data/fna/ --assembly_pattern *.fna --skip_clonalframe
```

I would be grateful if you could provide the corresponding command to run bactopia tools pirate v2.0.0 with local assemblies.

I installed Bactopia v2 using:
```
mamba create -n bactopia2 -c conda-forge -c bioconda bactopia --yes
```

**Comment by rpetit3** [comment]
Great idea @haruosuz , thank you very much. I'll work on getting this added to the docs

**Comment by rpetit3** [comment]
Hi @haruosuz 

This is an old one! You could likely get away with this using `bactopia atb-formatter` which will format assemblies to allow usage of bactopia tools.

I'm thinking
```
bactopia atb-formatter  --path assemblies/ --recursive
bactopia --wf prokka --bactopia bactopia/
bactopia --wf pangenome --bactopia bactopia/
```

Here's more details about doing this: https://bactopia.github.io/latest/blog/2024/bactopia-allthebacteria-tutorial/

Cheers,
Robert
