### ISSUE TITLE
WARN: The operator `first` is useless when applied to a value channel which returns a single value by definition

### ISSUE THREAD

**Issue by brross60** [bactopia/bactopia#265]
Started getting this error last night. Previously I had gotten it to work without the --species. @rpetit3 can you help?

Input (note I change personal IDs to xxx in the paths):
module load anaconda3/2020.11
module load python/2.7.16
conda activate bactopia
bactopia --wf pangenome --bactopia /storage/home/xxx/scratch/WGS/Illumina.Reads/bactopia/xxx --include xxx_genomes.txt --species "Mycobacteroides abscessus"

 Output:
Core Nextflow options
  runName          : modest_lamarck
  launchDir        : /storage/scratch1/xxx/WGS/Illumina.Reads/bactopia/xxx
  workDir          : /storage/home/xxx/scratch/WGS/Illumina.Reads/bactopia/xxx/work/pangenome
  projectDir       : /storage/home/xxx/.conda/envs/bactopia/share/bactopia-2.0.x
  userName         : xxx
  profile          : standard
  configFiles      : /storage/home/xxx/.conda/envs/bactopia/share/bactopia-2.0.x/nextflow.config

Required Parameters
  bactopia         : /storage/home/xxx/scratch/WGS/Illumina.Reads/bactopia/xxx

Filtering Parameters
  include          : xxx_genomes.txt

NCBI Genome Download Parameters
  species          : Mycobacteroides abscessus

Optional Parameters
  outdir           : /storage/home/xxx/scratch/WGS/Illumina.Reads/bactopia/xx
  run_name         : pangenome

Nextflow Profile Parameters
  condadir         : /storage/home/hcoda1/9/xxx/.conda/envs/bactopia/share/bactopia-2.0.x/conda/envs
  singularity_cache: /storage/home/xxx/.bactopia/singularity

Helpful Parameters
  wf               : pangenome

!! Only displaying parameters that differ from the pipeline defaults !!
--------------------------------------------------------------------
If you use bactopia for your analysis please cite:

* Bactopia
  https://doi.org/10.1128/mSystems.00190-20

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

* Software dependencies
  https://bactopia.github.io/acknowledgements/
--------------------------------------------------------------------
WARN: 
WARN: Conda Disclaimer
WARN: 
WARN: If you have access to Docker or Singularity, please consider
WARN: running Bactopia using containers. The containers are less
WARN: susceptible to Conda environment related issues (e.g. version
WARN: conflicts) and errors caused by creation of conda environments
WARN: in parallel (use '--max_cpus 1' to over come this error).
WARN: 
WARN: To use containers, you can use the profile parameter
WARN:     Docker: -profile docker
WARN:     Singularity: -profile singularity
WARN: 
--------------------------------------------------------------------

Each task will use 4 CPUs out of the available 4 CPUs. At most 
1 task(s) will be run at a time, this can affect the efficiency 
of Bactopia. You can use the '-qs' parameter to alter the number of 
tasks to run at a time (e.g. '-qs 2', means only 2 tasks or a maximum 
of 8 CPUs will be used at once)

Including 56 samples for analysis
Found 56 samples to process

If this looks wrong, now's your chance to back out (CTRL+C 3 times).
Sleeping for 5 seconds...
--------------------------------------------------------------------
executor >  local (1)
[3d/e1aeee] process > BACTOPIATOOLS:NCBIGENOMEDOWNLOAD:NCBIGENOMEDOWNLOAD_MODULE () [  0%] 0 of 1
[-        ] process > BACTOPIATOOLS:PROKKA:PROKKA_MODULE                            -
[-        ] process > BACTOPIATOOLS:PANGENOME:PG_TOOL:PIRATE_MODULE                 -
[-        ] process > BACTOPIATOOLS:PANGENOME:SNPDISTS                              -
[-        ] process > BACTOPIATOOLS:PANGENOME:CLONALFRAMEML:IQTREE                  -
[-        ] process > BACTOPIATOOLS:PANGENOME:CLONALFRAMEML:CLONALFRAME             -
[-        ] process > BACTOPIATOOLS:PANGENOME:FINAL_TREE:IQTREE_MODULE              -
[-        ] process > BACTOPIATOOLS:CUSTOM_DUMPSOFTWAREVERSIONS                     -
WARN: The operator `first` is useless when applied to a value channel which returns a single value by definition
WARN: The operator `first` is useless when applied to a value channel which returns a single value by definition
WARN: The operator `first` is useless when applied to a value channel which returns a single value by definition
WARN: The operator `first` is useless when applied to a value channel which returns a single value by definition
Unknown method invocation `getFileSystem` on ArrayList type

 -- Check script '/storage/home/xxx/.conda/envs/bactopia/share/bactopia-2.0.x/./workflows/../subworkflows/local/ncbigenomedownload/main.
nf' at line: 31 or see '.nextflow.log' file for more details

    Bactopia Tools: `pangenome Execution Summary
    ---------------------------
    Bactopia Version : 2.0.0
    Nextflow Version : 21.10.0
    Command Line     : nextflow run /storage/home/xxx/.conda/envs/bactopia//share/bactopia-2.0.x/main.nf -w /storage/scratch1/xxx/
WGS/Illumina.Reads/bactopia/xxx/work/pangenome --wf pangenome --bactopia /storage/home/xxx/scratch/WGS/Illumina.Reads
/bactopia/xxx --include xxx_genomes.txt --species 'Mycobacteroides abscessus' --max_time 300
    Resumed          : false
    Completed At     : 2021-12-21T10:10:23.787830-05:00
    Duration         : 22.8s
    Success          : false
    Exit Code        : null
    Error Report     : No signature of method: java.util.ArrayList.getFileSystem() is applicable for argument types: () values: []
    Launch Dir       : /storage/scratch1/xxx/Illumina.Reads/bactopia/xxx
    

executor >  local (1)
[4e/a97e55] process > BACTOPIATOOLS:NCBIGENOMEDOW... [100%] 1 of 1 ✔
[-        ] process > BACTOPIATOOLS:PROKKA:PROKKA... -
[-        ] process > BACTOPIATOOLS:PANGENOME:PG_... -
[-        ] process > BACTOPIATOOLS:PANGENOME:SNP... -
[-        ] process > BACTOPIATOOLS:PANGENOME:CLO... -
[-        ] process > BACTOPIATOOLS:PANGENOME:CLO... -
[-        ] process > BACTOPIATOOLS:PANGENOME:FIN... -
[-        ] process > BACTOPIATOOLS:CUSTOM_DUMPSO... -
WARN: The operator `first` is useless when applied to a value channel which returns a single value by definition
WARN: The operator `first` is useless when applied to a value channel which returns a single value by definition
WARN: The operator `first` is useless when applied to a value channel which returns a single value by definition
WARN: The operator `first` is useless when applied to a value channel which returns a single value by definition
Unknown method invocation `getFileSystem` on ArrayList type

 -- Check script '/storage/home/xxx/.conda/envs/bactopia/share/bactopia-2.0.x/./workflows/../subworkflows/local/ncbigenomedownload/main.nf' at line: 31 or see '.nextflow.log' file for more details

**Comment by rpetit3** [comment]
Going to look into this shortly. Will update soon. Thank you for posting!

**Comment by rpetit3** [comment]
Good news, think I fixed this one: https://github.com/bactopia/bactopia/commit/2fb59142747dec471282d7ddb3ddc35dfa0557be 

It'll be in the next version, in the meantime if you want to test it out I've pushed this fix to my personal conda channel

```
conda create -n temp-bactopia -c rpetit3 -c conda-forge -c bioconda bactopia
```

**Comment by brross60** [comment]
Got it, thank you.  It made it through grabbing the NCBI genomes but it failed to do Prokka because it could not find the command. Prokka is in the pkg folder in the environment but when I tried to call it, it is not found. I reinstalled Prokka 1.14.6 but get the same error. 

Example of the output while it ran and what was at the bottom of the report.
executor >  local (5)
[78/87bc9b] process > BACTOPIATOOLS:NCBIGENOMEDOW... [100%] 1 of 1 ✔
[2d/0d5c5a] process > BACTOPIATOOLS:PROKKA:PROKKA... [  2%] 2 of 69, failed: ...
[-        ] process > BACTOPIATOOLS:PANGENOME:PG_... -
[-        ] process > BACTOPIATOOLS:PANGENOME:SNP... -
[-        ] process > BACTOPIATOOLS:PANGENOME:CLO... -
[-        ] process > BACTOPIATOOLS:PANGENOME:CLO... -
[-        ] process > BACTOPIATOOLS:PANGENOME:FIN... -
[-        ] process > BACTOPIATOOLS:CUSTOM_DUMPSO... -
WARN: The operator `first` is useless when applied to a value channel which returns a single value by definition
WARN: The operator `first` is useless when applied to a value channel which returns a single value by definition
WARN: The operator `first` is useless when applied to a value channel which returns a single value by definition
[78/9cd9aa] NOTE: Process `BACTOPIATOOLS:PROKKA:PROKKA_MODULE (GCF_000445035)` terminated with an error exit status (127) -- Execution is retried (1)
[d3/fe1926] NOTE: Process `BACTOPIATOOLS:PROKKA:PROKKA_MODULE (GCF_000277775)` terminated with an error exit status (127) -- Execution is retried (1)

.....


Caused by:
  Process `BACTOPIATOOLS:PROKKA:PROKKA_MODULE (GCF_000277775)` terminated with an error exit status (127)

Command executed:

  if [ "true" == "true" ]; then
      gzip -c -d GCF_000277775.2_ASM27777v2_genomic.fna.gz > GCF_000277775.2_ASM27777v2_genomic.fna
  fi
  
 prokka \
      --evalue 1e-09 --coverage 80 \
      --cpus 4 \
      --prefix GCF_000277775 \
       \
       \
      GCF_000277775.2_ASM27777v2_genomic.fna
  
  if [[ "false" == "false" ]]; then
      gzip GCF_000277775/*.gff
      gzip GCF_000277775/*.gbk
      gzip GCF_000277775/*.fna
      gzip GCF_000277775/*.faa
      gzip GCF_000277775/*.ffn
      gzip GCF_000277775/*.sqn
      gzip GCF_000277775/*.fsa
      gzip GCF_000277775/*.tbl
  fi
  
  cat <<-END_VERSIONS > versions.yml
  prokka:prokka: $( echo $(prokka --version 2>&1) | sed 's/^.*prokka //')
  END_VERSIONS

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 7: prokka: command not found

Work dir:
  /storage/scratch1/9/bross60/WGS/Illumina.Reads/bactopia/EMORY/Emory_NCBI_roary/work/pangenome/de/7aa28b0dbb49a8386903d3bf4f1b4e

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`


WARN: To render the execution DAG in the required format it is required to install Graphviz -- See http://www.graphviz.org for more info.

**Comment by rpetit3** [comment]
Hmmm, do you by chance have access to Docker or Singularity?

**Comment by brross60** [comment]
I suspect you are right and it's the conda environment. We have anaconda hosted on the servers. I completely deleted conda and reinstalled it but that didn't seem to help.  I have tried the singularity but I found out I don't have permission to path singularities can be run from. I'll keep trying to get it to work.


singularity pull library://rpetit3/bactopia/bactopia
INFO:    Using cached image
WARNING: integrity: signature not found for object group 1
WARNING: Skipping container verification

# have a file bactopia_latest.sif now

singularity exec bactopia_latest.sif bactopia --wf pangenome -resume --bactopia /storage/home/xxx/scratch/WGS/Illumina.Reads/bactopia/xxx_NCBI_roary --include xxx_genomes.txt --species "Mycobacteroides abscessus"

FATAL:   singularity image is not in an allowed configured path
grep '^limit container paths' /etc/singularity/singularity.conf
limit container paths = /usr/local/pace-apps/manual/packages/singularity_images, /usr/local/pace-apps/manual/packages/singularity_images/group-restricted/p-ag5

**Comment by rpetit3** [comment]
You can run bactopia as normal through conda, just add a `-profile singularity`

```
bactopia --wf pangenome \
    --bactopia /storage/home/xxx/scratch/WGS/Illumina.Reads/bactopia/xxx \
    --include xxx_genomes.txt \
    --species "Mycobacteroides abscessus" \
    -profile singularity
```

Also, by chance are running this on a cluster with a scheduler (e.g. SLURM, SGE, etc...)?

**Comment by brross60** [comment]
I'll try that now. Our cluster uses a Moab scheduler.

**Comment by rpetit3** [comment]
No problem! Keep me posted.

Looks like Nextflow has experimental support for MOAB: https://www.nextflow.io/docs/latest/executor.html#moab We could potentially create a config to queue the jobs for you

**Comment by rpetit3** [comment]
@brross60 let me know if I can help with anything

**Comment by rpetit3** [comment]
@brross60 I'm going to go ahead and close this issue, please feel free to reopen! Cheers!

**Comment by brross60** [comment]
Follow up, for others out there. I kept having issues with java and could not use the docker on our server. It turned out that permissions and conda on the server were causing problems. I downloaded Bactopia on our labs in houses computer that has enhancements for analysis like bactopia and it worked!!!! Thank you @rpetit3 rpetit3 for all the help.
