### ISSUE TITLE
[bug] Erro from Bio.Alphabet while building the datasets

### ISSUE THREAD

**Issue by alarawms** [bactopia/bactopia#267]
**Description**
While building the datasets I get an error 

**Steps to Reproduce**
```
 srun bactopia datasets --ariba "vfdb_core,argannot,card,ncbi,megares,plasmidfinder,resfinder,srst2_argannot,vfdb_core,virulencefinde" --species "Staphylococcus aureus" --include_genus --cpus 64 

!!ERROR!!
```

**Expected Behavior**
"Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information."
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.

**Execution Environment**

- Bactopia Version: [2]
- OS: [centos7.5]
- Environment: [e.g. conda, using slurm]

**Additional Information**
Any other information you think might be helpful in squashing this bug.

**Comment by rpetit3** [comment]
Hmmm, I'm wondering if this is related to Ariba.

What does your bactopia conda environment look like?

**Comment by rpetit3** [comment]
I've submitted a few PRs (https://github.com/bioconda/bioconda-recipes/pull/32258 and https://github.com/sanger-pathogens/ariba/pull/319) to hopefully fix this.

Related issues on Ariba are here https://github.com/sanger-pathogens/ariba/issues/317 https://github.com/sanger-pathogens/ariba/issues/307

**Comment by alarawms** [comment]
solved. now. I don't know what changed, but I pulled the recent changed version.

**Comment by rpetit3** [comment]
Great! I patched the bioconda install for Ariba. Glad it worked for you!
