### ISSUE TITLE
Does bactopia analyzes bacteriophages?

### ISSUE THREAD

**Issue by marwa38** [bactopia/bactopia#269]
Hello 
Does bactopia analyzes bacteriophages? as I want to reproduce this study: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4429339/
Thanks 
Marwa

**Comment by rpetit3** [comment]
Hi @marwa38 

I've never actually tried! I don't think it'll hurt to give it a go. Let me know, if there's anything I can help with!

Robert

**Comment by rpetit3** [comment]
@marwa38 I'm going to go ahead and close this, please feel free to reopen!
