### ISSUE TITLE
How to run Bactopia to get minmers

### ISSUE THREAD

**Issue by rpetit3** [bactopia/bactopia#279]
Hi Robert,
I've been running bactopia on some sra (multiple) samples to check out species identification .  I used the command with no --species option like: 
```
for my_sample in $(cat sample_list.txt);do
    bactopia --sample $my-sample --R1 /path/to/$my-sample_R1.fastq.gz --R2 /path/to/$my-sample_R2.fastq.gz --outdir\ my_outdir
done
```

When a sample doesn't meet the default genome size, the minmer subdirectory isn't generated, therefore no sampleID-mash-refseq-k21.txt and  sampleID-sourmash-genbank-k21.txt files (need those for the species name).  And I get the file SRR11086695-genome-size-error.txt.  When I add the `--genome-size  62200000` (for example), the same issue arises for other samples. However,  choosing `--genome-size` max, min, or median will require the option `--species`.  How to I address this?
Thanks,
TJ

_Originally posted by @tbazilegith in https://github.com/bactopia/bactopia/issues/100#issuecomment-1035199086_

**Comment by rpetit3** [comment]
Also, I wonder if this might help you? https://bactopia.github.io/tutorial/#multiple-samples-fofn

**Comment by tbazilegith** [comment]
Yeah,
The --datasets option is there in script, forgot to include it the issue
I  also I a script wherein I use the file of file name (fofn). I a have the same issue with a particular sample. It seems like there is a cutoff on the genome size (the allowed size is 1804066). I have 4 samples whose genome sizes scaled: 5065800 - 61139700. The thing is if choose min max I have to add --species option.

**Comment by tbazilegith** [comment]
Thanks,
 I am going ahead and try with --max_genome_size. 
the SRR11086695    Candidatus Udaeobacter  sp. Isolate AEW3 (think this name isn't definitive) - After a bactopia run, the file genome-size error displayds this estimated size 61,139,700. Thus cannot identify it

**Comment by rpetit3** [comment]
I think it might be worth looking into why the estimated genome size is 61Mbp (total reads, coverage etc...)

**Comment by tbazilegith** [comment]
It worked! 
Thanks a lot

**Comment by rpetit3** [comment]
great! going to go ahead and close this one

**Comment by rpetit3** [comment]
If you have a moment, could you take a few minutes to fill out a [Bactopia Usage Survey](https://forms.gle/PTgUxEBwCsCdbQjr7)? It really helps me direct the direction of Bactopia's development! Thanks!
