### ISSUE TITLE
mkdir: cannot create directory ‘species-specific/.DS_Store’: Not a directory

### ISSUE THREAD

**Issue by jellyvanderwoude** [bactopia/bactopia#280]
Downloaded the newest version of Bactopia v2 on my computer and I'm setting up the datasets from scratch. When I create the general datasets, it runs fine. When I try to create the Pseudomonas aeruginosa specific datasets, I get this error:

> (bactopia) bio-24046:bactopia-folder jvanderwoude3$ bactopia datasets --species "Pseudomonas aeruginosa" --include_genus
> 2022-02-15 12:58:29:root:INFO - Pseudomonas aeruginosa verified in ENA Taxonomy database
> 2022-02-15 12:58:29:root:INFO - Setting up Ariba datasets
> 2022-02-15 12:58:29:root:INFO - vfdb_core (./datasets/ariba/vfdb_core) exists, skipping
> 2022-02-15 12:58:29:root:INFO - card (./datasets/ariba/card) exists, skipping
> 2022-02-15 12:58:29:root:INFO - Setting up pre-computed Genbank/Refseq minmer datasets
> 2022-02-15 12:58:29:root:INFO - ./datasets/minmer/sourmash-genbank-k21.json.gz exists, skipping
> 2022-02-15 12:58:29:root:INFO - ./datasets/minmer/sourmash-genbank-k31.json.gz exists, skipping
> 2022-02-15 12:58:29:root:INFO - ./datasets/minmer/sourmash-genbank-k51.json.gz exists, skipping
> 2022-02-15 12:58:29:root:INFO - ./datasets/minmer/mash-refseq-k21.msh exists, skipping
> 2022-02-15 12:58:29:root:INFO - Setting up antimicrobial resistance datasets
> 2022-02-15 12:58:29:root:INFO - Setting up latest AMRFinder+ database
> 2022-02-15 12:58:55:root:INFO - AMRFinder+ database saved to ./datasets/antimicrobial-resistance/amrfinderdb.tar.gz
> 2022-02-15 12:58:55:root:INFO - Setting up MLST datasets
> 2022-02-15 12:58:55:root:INFO - Setting up default MLST schema for Pseudomonas aeruginosa
> 2022-02-15 12:58:55:root:INFO - Creating Ariba MLST dataset
> 2022-02-15 12:59:31:root:INFO - Creating BLAST MLST dataset
> 2022-02-15 12:59:33:root:INFO - Setting up custom Prokka proteins
> 2022-02-15 12:59:33:root:INFO - Setting up custom Prokka proteins for Pseudomonas aeruginosa
> 2022-02-15 12:59:33:root:INFO - Downloading genomes (assembly level: complete)
> 2022-02-15 12:59:37:root:INFO - There are less available genomes than the given limit (1000), downloading all.
> 2022-02-15 13:14:05:root:INFO - Processing 988 Genbank files
> 2022-02-15 13:28:57:root:INFO - Median genome size: 6734601 (n=389)
> 2022-02-15 13:28:57:root:INFO - Running CD-HIT on 5580546 proteins
> External command failed with exit code 1!
> 
> Command:
> bash -c 'mkdir -p species-specific/.DS_Store/optional/blast'
> 
> Standard error:
> mkdir: cannot create directory ‘species-specific/.DS_Store’: Not a directory

I am deleting the .DS_Store file and proceeding, but I wanted to raise this issue in case it's a bug that needs to be fixed.

**Comment by rpetit3** [comment]
Oh this is interesting! Not sure why its trying to write to `.DS_Store`. Let me see if I can get my hands on a Mac and replicate this

**Comment by rpetit3** [comment]
Found it! https://github.com/bactopia/bactopia/blob/master/bin/bactopia/bactopia-datasets.py#L843

I'll add a fix to this to ignore folders starting with a `.`

**Comment by rpetit3** [comment]
I've released v2.0.2 (https://github.com/bactopia/bactopia/releases/tag/v2.0.2) which should fix this, let me know if not!

Thanks for the help finding this! Going to close for now
