### ISSUE TITLE
[bug] Failed to build the pre-computed Genbank/Refseq minmer datasets

### ISSUE THREAD

**Issue by llk578496** [bactopia/bactopia#285]
**Description**
Failed to build the pre-computed Genbank/Refseq minmer datasets. External command failed with exit code 4!

**Steps to Reproduce**

> $bactopia datasets --ariba 'card, resfinder'
> 2022-02-24 00:28:56:root:INFO - Setting up Ariba datasets
> 2022-02-24 00:28:56:root:INFO - Setting up card Ariba dataset
> 2022-02-24 00:31:34:root:INFO - Setting up resfinder Ariba dataset
> 2022-02-24 00:31:49:root:INFO - Setting up pre-computed Genbank/Refseq minmer datasets
> External command failed with exit code 4!
> Command:
> bash -c 'wget --quiet -O mash-refseq-k21.msh https://gembox.cbcb.umd.edu/mash/refseq.genomes.k21s1000.msh'

```
bactopia datasets
```

**Expected Behavior**
It should builds datasets normally.

**Execution Environment**

- Bactopia Version: 2.0.2
- OS: Ubuntu
- Environment: conda

**Comment by rpetit3** [comment]
Can you verify https://gembox.cbcb.umd.edu/mash/refseq.genomes.k21s1000.msh is working for you?

**Comment by llk578496** [comment]
Yes, I could download it, but it said it needs 10 hours. I have been building the datasets normally before.

**Comment by rpetit3** [comment]
Ok downloaded in ~2min for me here on west coast of the US. 

I wonder if it might be worthwhile to put this on a mirror somewhere

**Comment by llk578496** [comment]
Thanks a lot! 
I will try to build the datasets later and will keep update here!

**Comment by rpetit3** [comment]
Hi @llk578496 

I think we might be all set here. Hopefully it was just an intermittent connection issue!

Please feel free to reopen if the issue persists!
Robert
