### ISSUE TITLE
[feature] add custom reference genome to call variant

### ISSUE THREAD

**Issue by fabgenomics** [bactopia/bactopia#287]
**Related To**

- [x] Bactopia
- [ ] Bactopia Tools

**Is this something you would like to see added?**

Hi,
I would like to know if it's possible to add an option to set a custom reference genome for the variant calling step using snippy instead of the nearest reference ?
I saw the --disable_auto_variants option for the Nearest Neighbor Reference Genomes but I don't know how to provide mine.
Maybe it exist and I didn't find it.
Have a nice day,
Fabien

**Comment by rpetit3** [comment]
Hi @fabgenomics,

You can add your own reference after building datasets via this method: https://bactopia.github.io/datasets/#reference-genomes

During the `bactopia datasets` step you can use `--reference` to put the file in the right location. 

Do you think it would be useful to also be able to give `--reference` when running the Bactopia pipeline?

Cheers,
Robert

**Comment by fabgenomics** [comment]
Hi Robert,

Thanks for your quick answer. I missed that parameter in the +100 parameters :)
Here is my command :
`bactopia datasets --species "Escherichia coli" --reference /home/XX/Documents/ref.gbk --force_optional`

Nothing goes to the optional/reference-genomes folder !

Then I putted it manually and it works.

For my point of view it could be a good parameter to add directly --reference in the bactopia pipeline but as you explained me how to do it I'll not need it anymore.

Cheers,
Fabien

**Comment by rpetit3** [comment]
so! funny story.

Looks like I started the whole `bactopia datasets --species "XYZ" --reference YOUR_REFERENCE" but never actually completed it. So, that explains why it does work! 

I'll work on getting this added to both `bactopia datasets` and `bactopia`

**Comment by rpetit3** [comment]
Hi @fabgenomics 

Happy to report the follow parameters are now implemented in `bactopia datasets`

```
Optional User Provided Datasets:
  --prodigal_tf STR     A pre-built Prodigal training file to add to the species annotation
                        folder. Requires a single species (--species) and will replace
                        existing training files.
  --reference STR       A reference genome (FASTA/GenBank (preferred)) file or directory to be
                        added to the optional folder for variant calling. Requires a single
                        species (--species).
  --mapping STR         A reference sequence (FASTA) file or directory to be added to the
                        optional folder for mapping. Requires a single species (--species).
  --genes STR           A gene sequence (FASTA) file or directory to be added to the optional
                        folder for BLAST. Requires a single species (--species).
  --proteins STR        A protein sequence (FASTA) file or directory to be added to the
                        optional folder for BLAST. Requires a single species (--species).
  --primers STR         A primer sequence (FASTA) file or directory to be added to the
                        optional folder for BLAST. Requires a single species (--species).
  --force_optional      Overwrite any existing files in the optional folders
```

If you want to give it a go, its available in my dev build

```
mamba create -n bactopia-dev -c rpetit3 -c conda-forge -c bioconda bactopia
```

Thanks for reporting this!
Robert
