### ISSUE TITLE
Should we still use the Nextflow wrapper for AWS?

### ISSUE THREAD

**Issue by habibdanesh** [bactopia/bactopia#292]
Hi, I came across your blog "[Using AWS Batch to process 67,000 genomes with Bactopia](https://emergent.emory.edu/blog/posts/bactopia-aws-and-67000-genomes/)". Awesome speedup!

I'm trying to run Bactopia on AWS. My main objective is to be able to run Bactopia on a large number of genomes as quickly as possible. I have a few questions:

1) Should I still use [this script](https://gist.github.com/rpetit3/01f27f52273104bbf609ed5acc9b63a9) for setup, and the [wrapper here](https://gist.github.com/rpetit3/fe1f5428be135852ec90bfb63aa32c93)? Or Bactopia has now all the required AWS settings built-in?

2) If yes to 1), could you point me to the main parts of the wrapper that need to be customized?

Thank you!

**Comment by rpetit3** [comment]
Hi @habibdanesh!

Great timing! I was planning to get the AWS config updated. So, the blog post was for v1 of Bactopia, and may or may not work with v2 of Bactopia. (Might not even need them!) I think I'll need to update the settings in AWS for bactopia. I've tried it on GCP, but haven't got the credits to get them updated on AWS.

I can see about trying some small datasets. But, would you like to work together on getting this up and running?

Are you planning to run from NF-Tower, EC2 instance, or locally?

Cheers,
Robert

**Comment by habibdanesh** [comment]
Fantastic! Yes, let's work on it. I'm all in!

I'm planning to run from an EC2 instance.

Thanks,
Habib

**Comment by rpetit3** [comment]
Ok here's what I have for `-profile aws`

```
bactopia --help_all -profile

AWS Batch Profile (-profile awsbatch) Parameters
  --aws_region                        [string]  AWS Region to be used by Nextflow [default: us-east-1]
  --aws_queue                         [string]  Name of queue to use for AWS Batch
  --aws_volumes                       [string]  Volumes to be mounted from the EC2 instance to the Docker container [default: /opt/conda:/mnt/conda]
  --aws_cli_path                      [string]  Path to the AWS CLI for Nextflow to use. [default: /home/ec2-user/conda/bin/aws]
  --aws_upload_storage_class          [string]  The S3 storage slass to use for storing files on S3 [default: STANDARD]
  --aws_max_parallel_transfers        [integer] The number of parallele transfers between EC2 and S3 [default: 8]
  --aws_delay_between_attempts        [integer] The duration of sleep (in seconds) between each transfer between EC2 and S3 [default: 15]
  --aws_max_transfer_attempts         [integer] The maximum number of times to retry transferring a file between EC2 and S3 [default: 3]
  --aws_max_retry                     [integer] The maximum number of times to retry a process on AWS Batch [default: 4]

```

I think you you will want to change `--aws_queue` to your AWS Batch queue name.

I think let's try just a single sample using something like:

```
bactopia --accession SRX1390609 --genome_size 300000 -profile aws --aws_queue <YOUR_BATCH_QUEUE>
```

**Comment by habibdanesh** [comment]
Ok first, I need to properly set up my AWS Batch. Is [Nextfow documentation](https://www.nextflow.io/docs/latest/awscloud.html#aws-batch) a good place to start?

**Comment by rpetit3** [comment]
I think it should be, I used these, which might be easier to get through.

https://antunderwood.gitlab.io/bioinformant-blog/posts/running_nextflow_on_aws_batch/
https://t-neumann.github.io/pipelines/AWS-pipeline/

**Comment by rpetit3** [comment]
@habibdanesh This might be of interest to you: https://seqera.io/blog/tower-batch-forge/

**Comment by rpetit3** [comment]
Hi @habibdanesh 

Checking to see if you were able to get going on AWS.

Cheers,
Robert

**Comment by rpetit3** [comment]
Hi @habibdanesh 

I'm going to go ahead and close this issue, please feel free to reopen.

Cheers,
Robert
