### ISSUE TITLE
Spades-> Roary Pangenome Gunzip error 

### ISSUE THREAD

**Issue by brross60** [bactopia/bactopia#295]
**Description**
With spades assemblies i get an error about the gunzip function w/ roary. when i look in the work folder temp-gff  the files are symlinks. In the gff folder they are regular files. 

**Steps to Reproduce**
spades assemblies-> roary pangenome

```
!!ERROR!!
Error executing process > 'BACTOPIATOOLS:PANGENOME:PG_TOOL:ROARY_MODULE (roary)'

Caused by:
  Process `BACTOPIATOOLS:PANGENOME:PG_TOOL:ROARY_MODULE (roary)` terminated with an error exit status (123)

Command executed:

  mkdir gff
  cp -L gff-tmp/* gff/
  find gff/ -name "*.gff.gz" | xargs gunzip
  roary \
      -e -n -g 50000 -i 95 -cd 99 -iv 1.5 \
      -p 4 \
      -f results/ \
      gff/*.gff
  
  gzip results/*.aln
  gzip results/*.fa
  
  cat <<-END_VERSIONS > versions.yml
  "BACTOPIATOOLS:PANGENOME:PG_TOOL:ROARY_MODULE":
      roary: $( roary --version )
  END_VERSIONS

Command exit status:
  123

Command output:
  (empty)

Command error:
  gunzip: invalid magic

Work dir:
  /home/xxx/Desktop/new_bac/work/96/2a5f72ad47ff99e44d03ff3050ff56

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
```

- Bactopia Version: 2.0.1
Ubuntu
- Environment: conda

**Comment by rpetit3** [comment]
If you don't mind checking, does the same happen with PIRATE?

**Comment by brross60** [comment]
So far it looks like pirate is OK with spades files. Right now its working but no errors.
If this looks wrong, now's your chance to back out (CTRL+C 3 times).
Sleeping for 5 seconds...
--------------------------------------------------------------------
executor >  local (1)
[-        ] process > BACTOPIATOOLS:PROKKA:PROKKA_MODULE                     -
[c9/1c817f] process > BACTOPIATOOLS:PANGENOME:PG_TOOL:PIRATE_MODULE (pirate) [  0%] 0 of 1
[-        ] process > BACTOPIATOOLS:PANGENOME:SNPDISTS                       -
[-        ] process > BACTOPIATOOLS:PANGENOME:CLONALFRAMEML:IQTREE           -
[-        ] process > BACTOPIATOOLS:PANGENOME:CLONALFRAMEML:CLONALFRAME      -
[-        ] process > BACTOPIATOOLS:PANGENOME:FINAL_TREE:IQTREE_MODULE       -
[-        ] process > BACTOPIATOOLS:PANGENOME:SCOARY:SCOARY_MODULE           -
[-        ] process > BACTOPIATOOLS:CUSTOM_DUMPSOFTWAREVERSIONS              -
WARN: The operator `first` is useless when applied to a value channel which returns a single value by definition

**Comment by rpetit3** [comment]
Thank you! that's very helpful, I'm wondering if this has to do with the gzip version included with Roary.

Some of the biocontainers come with BusyBox xargs/gzip that behaves differently. I'll get a fix and dev build for you here shortly

**Comment by rpetit3** [comment]
Oh wait this is conda, let me see what's happening here

**Comment by rpetit3** [comment]
What's ` /home/xxx/Desktop/new_bac/work/96/2a5f72ad47ff99e44d03ff3050ff56/gff` look like?

**Comment by brross60** [comment]
Yep its conda. 
Gffs look fine there. Their property type is below.
/home/xxx/Desktop/new_bac/work/96/2a5f72ad47ff99e44d03ff3050ff56/gff: gffs present and type is "MATLAB file (text/x-matlab)"
/home/xxx/Desktop/new_bac/work/96/2a5f72ad47ff99e44d03ff3050ff56/gff-tmp:all gffs present and type is "link to MATLAB file (text/x-matlab)"

**Comment by rpetit3** [comment]
OK, I've tried to reproduce this on my end. So far I've been unsuccessful.

Going to try a few more things.

Do you by chance have access to docker or singularity?

**Comment by brross60** [comment]
Weird. I am pulling from the docker. 
 This is the command I am using:
bactopia --wf pangenome --bactopia /home/xxx/Desktop/new_bac/ --include /home/xxx/Desktop/new_bac/geneomes.txt --condadir /home/xxx/Desktop/new_bac/packages/ --outdir /home/xxx/Desktop/new_bac/spades_roary/ --use_roary True --traits traits.csv --max_time 1000 -profile docker
