### ISSUE TITLE
How to update bactopia

### ISSUE THREAD

**Issue by plasminogene** [bactopia/bactopia#296]
Hi，

I  found several updates today ，such as ”add more documentation to meta YAMLs“，How to update bactopia 。

 I try ”bactopia update“，it did not work.

Thanks

Haitao

**Comment by rpetit3** [comment]
Hi @plasminogene 

The updates over the weekend were minor and mostly related to documentation. But I have a dev build with the latest changes that can be installed like so:

```
conda create -n bactopia-dev -c rpetit3 -c conda-forge -c bioconda rpetit3::bactopia
```

Cheers,
Robert

**Comment by plasminogene** [comment]
Thanks for your excellent work!!!

**Comment by rpetit3** [comment]
No problem! Let me know if you have any feedback! 

Going to close this, please feel free to reopen

Cheers
