### ISSUE TITLE
[question]  How to use --download_gtdb commands to build a database

### ISSUE THREAD

**Issue by plasminogene** [bactopia/bactopia#297]
Hi，

 I tried the following command and reported an error.

Thanks

Haitao

(bactopia-dev) lh@ubuntu:~$ bactopia datasets --species "Mycoplasma gallisepticum" --include_genus  --skip_ariba  --skip_amr --keep_file  --download_gtdb

(bactopia-dev) lh@ubuntu:~$ bactopia datasets --species "Mycoplasma gallisepticum"  --skip_ariba  --skip_amr --keep_file  --download_gtdb

bactopia datasets: error: unrecognized arguments: --download_gtdb
(bactopia-dev) lh@ubuntu:~$ bactopia datasets --species "Mycoplasma gallisepticum" --include_genus  --skip_ariba  --skip_amr  --download_gtdb

bactopia datasets: error: unrecognized arguments: --download_gtdb
(bactopia-dev) lh@ubuntu:~$ bactopia datasets --species "Mycoplasma gallisepticum"   --skip_ariba  --skip_amr --keep_file  --download_gtdb

bactopia datasets: error: unrecognized arguments: --download_gtdb
(bactopia-dev) lh@ubuntu:~$ bactopia datasets --species "Mycoplasma gallisepticum"   --skip_ariba  --skip_amr  --download_gtdb

bactopia datasets: error: unrecognized arguments: --download_gtdb
(bactopia-dev) lh@ubuntu:~$ bactopia datasets --species "Mycoplasma gallisepticum"   --skip_ariba  --skip_amr  --download_gtdb

bactopia datasets: error: unrecognized arguments: --download_gtdb
(bactopia-dev) lh@ubuntu:~$ bactopia datasets --species "Mycoplasma gallisepticum"  --download_gtdb

bactopia datasets: error: unrecognized arguments: --download_gtdb
(bactopia-dev) lh@ubuntu:~$ bactopia datasets  --download_gtdb

bactopia datasets: error: unrecognized arguments: --download_gtdb

**Comment by rpetit3** [comment]
Hi @plasminogene 

You will give it when you execute the `gtdb` subworkflow. More details here: https://bactopia.github.io/bactopia-tools/gtdb/#gtdb-setup-parameters

But here's an example:

```
bactopia --wf gtdb \
    --bactopia /path/to/bactopia/outputs  
    --gtdb /path/to/gtdb \
    --download_gtdb
```

This will tell Bactopia to download the GTDB databases to the path given by `--gtdb`.

Let me know if this doesn't help!
Robert

**Comment by plasminogene** [comment]
Yes ，thanks.  This command -"(bactopia) prp27@ubuntu:~$ bactopia --wf gtdb  --bactopia OUTDIR5   --gtdb NO.3-scaffolds.fasta     --download_gtdb" is worked.

**Comment by rpetit3** [comment]
Hi @plasminogene 

I think we are all good here, so I'm going to go ahead and close this issue.

Please feel free to reopen, and I really appreciate your feedback!
Robert
