### ISSUE TITLE
Local assemblies not producing outputs

### ISSUE THREAD

**Issue by rpetit3** [bactopia/bactopia#303]
Hi Robert,
Is there any update about running bactopia on assembly files? I ran bactopia to process some local .fasta files, but had no output. The error log file is empty though.  
Here is the command:
```
for s in $(cat samples.txt);do
    bactopia --sample ${s}  --assembly assemblies_zipped/${s}.fasta.gz --assembly_pattern *.fasta.gz --datasets /color/my_directory/datasets/ --outdir ${today}bactopia_output --max_cpus $SLURM_CPUS_PER_TASK --cle\
anup_workdir
done
```
Thanks!
TJ

_Originally posted by @tbazilegith in https://github.com/bactopia/bactopia/issues/259#issuecomment-1082305731_

**Comment by rpetit3** [comment]
Hi @tbazilegith,

Thought it might be best to create a new issue for this one. I'm looking into what you aren't getting outputs.

But I think its also worth pointing out you can use `bactopia prepare` with the `--assembly_pattern` parameter to create an FOFN to use with `--fastqs`.

More details available here: https://bactopia.github.io/usage-basic/#generating-a-fofn

Will update soon, 
Robert

**Comment by rpetit3** [comment]
Could you by chance share one of your assemblies? I'm unable to reproduce on my end

```
    Bactopia Execution Summary
    ---------------------------
    Bactopia Version : 2.0.3
    Nextflow Version : 21.10.6
    Command Line     : nextflow run /home/robert_petit/miniconda3/envs/bactopia-dev//share/bactopia-2.0.x/main.nf -w /home/robert_petit/temp/work/work/ --assembly /home/robert_petit/repos/bactopia-tests/data/species/portiera/genome/GCF_000292685.fna.gz --sample porteria -profile docker --outdir test
    Resumed          : false
    Completed At     : 2022-03-30T03:44:01.483433Z
    Duration         : 1m 37s
    Success          : true
    Exit Code        : 0
    Error Report     : -
    Launch Dir       : /home/robert_petit/temp/work
```

**Comment by tbazilegith** [comment]
I mean
bactopia prepare path_to_fasta/ --assembly_pattern > fastas.txt
bactopia --fastqs fastas.txt

**Comment by tbazilegith** [comment]
I can share an assembly file. How do we do that?

**Comment by tbazilegith** [comment]
[CFI20000592.fasta.gz](https://github.com/bactopia/bactopia/files/8382138/CFI20000592.fasta.gz)
I have attached the above file.
Thanks!,
TJ

**Comment by rpetit3** [comment]
Yeah, the `--fastqs` is a bit misleading and I need to rename it. Originally when it was made assemblies were not supported.

**Comment by rpetit3** [comment]
OK! I tried your assembly and it worked

```
    Bactopia Execution Summary
    ---------------------------
    Bactopia Version : 2.0.3
    Nextflow Version : 21.10.6
    Command Line     : nextflow run /home/robert_petit/miniconda3/envs/bactopia-dev//share/bactopia-2.0.x/main.nf -w /home/robert_petit/temp/work/work/ --assembly CFI20000592.fasta.gz --outdir test_fasta --sample CFI20000592 -profile docker
    Resumed          : false
    Completed At     : 2022-03-30T16:32:21.897485Z
    Duration         : 7m 23s
    Success          : true
    Exit Code        : 0
    Error Report     : -
    Launch Dir       : /home/robert_petit/temp/work
```

**Comment by tbazilegith** [comment]
My I see what your output directory(ries) look(s) like?

**Comment by tbazilegith** [comment]
* May I see...

**Comment by rpetit3** [comment]
Here you go!

```
.
├── CFI20000592
│   ├── CFI20000592-genome-size.txt
│   ├── annotation
│   │   ├── CFI20000592.faa.gz
│   │   ├── CFI20000592.ffn.gz
│   │   ├── CFI20000592.fna.gz
│   │   ├── CFI20000592.fsa.gz
│   │   ├── CFI20000592.gbk.gz
│   │   ├── CFI20000592.gff.gz
│   │   ├── CFI20000592.sqn.gz
│   │   ├── CFI20000592.tbl.gz
│   │   ├── CFI20000592.tsv
│   │   └── CFI20000592.txt
│   ├── assembly
│   │   ├── CFI20000592.fna.gz
│   │   ├── CFI20000592.json
│   │   ├── checkm
│   │   │   └── checkm-was-skipped.txt
│   │   └── quast
│   │       ├── basic_stats
│   │       │   ├── CFI20000592_GC_content_plot.pdf
│   │       │   ├── GC_content_plot.pdf
│   │       │   ├── NGx_plot.pdf
│   │       │   ├── Nx_plot.pdf
│   │       │   └── cumulative_plot.pdf
│   │       ├── icarus.html
│   │       ├── icarus_viewers
│   │       │   └── contig_size_viewer.html
│   │       ├── predicted_genes
│   │       │   ├── CFI20000592_glimmer.stderr
│   │       │   └── CFI20000592_glimmer_genes.gff.gz
│   │       ├── report.html
│   │       ├── report.pdf
│   │       ├── report.tex
│   │       ├── report.tsv
│   │       ├── report.txt
│   │       ├── transposed_report.tex
│   │       ├── transposed_report.tsv
│   │       └── transposed_report.txt
│   ├── blast
│   │   └── blastdb
│   │       ├── CFI20000592.ndb
│   │       ├── CFI20000592.nhr
│   │       ├── CFI20000592.nin
│   │       ├── CFI20000592.not
│   │       ├── CFI20000592.nsq
│   │       ├── CFI20000592.ntf
│   │       └── CFI20000592.nto
│   ├── logs
│   │   ├── annotate_genome
│   │   │   ├── CFI20000592.err
│   │   │   ├── CFI20000592.log
│   │   │   ├── nf-annotate_genome.begin
│   │   │   ├── nf-annotate_genome.err
│   │   │   ├── nf-annotate_genome.log
│   │   │   ├── nf-annotate_genome.out
│   │   │   ├── nf-annotate_genome.run
│   │   │   ├── nf-annotate_genome.sh
│   │   │   ├── nf-annotate_genome.trace
│   │   │   └── versions.yml
│   │   ├── assemble_genome
│   │   │   ├── nf-assemble_genome.begin
│   │   │   ├── nf-assemble_genome.err
│   │   │   ├── nf-assemble_genome.log
│   │   │   ├── nf-assemble_genome.out
│   │   │   ├── nf-assemble_genome.run
│   │   │   ├── nf-assemble_genome.sh
│   │   │   ├── nf-assemble_genome.trace
│   │   │   └── versions.yml
│   │   ├── assembly_qc
│   │   │   ├── nf-assembly_qc.begin
│   │   │   ├── nf-assembly_qc.err
│   │   │   ├── nf-assembly_qc.log
│   │   │   ├── nf-assembly_qc.out
│   │   │   ├── nf-assembly_qc.run
│   │   │   ├── nf-assembly_qc.sh
│   │   │   ├── nf-assembly_qc.trace
│   │   │   ├── quast.log
│   │   │   └── versions.yml
│   │   ├── gather_samples
│   │   │   ├── nf-gather_samples.begin
│   │   │   ├── nf-gather_samples.err
│   │   │   ├── nf-gather_samples.log
│   │   │   ├── nf-gather_samples.out
│   │   │   ├── nf-gather_samples.run
│   │   │   ├── nf-gather_samples.sh
│   │   │   ├── nf-gather_samples.trace
│   │   │   └── versions.yml
│   │   ├── minmer_sketch
│   │   │   ├── nf-minmer_sketch.begin
│   │   │   ├── nf-minmer_sketch.err
│   │   │   ├── nf-minmer_sketch.log
│   │   │   ├── nf-minmer_sketch.out
│   │   │   ├── nf-minmer_sketch.run
│   │   │   ├── nf-minmer_sketch.sh
│   │   │   ├── nf-minmer_sketch.trace
│   │   │   └── versions.yml
│   │   └── qc_reads
│   │       ├── nf-qc_reads.begin
│   │       ├── nf-qc_reads.err
│   │       ├── nf-qc_reads.log
│   │       ├── nf-qc_reads.out
│   │       ├── nf-qc_reads.run
│   │       ├── nf-qc_reads.sh
│   │       ├── nf-qc_reads.trace
│   │       └── versions.yml
│   ├── minmers
│   │   ├── CFI20000592-k21.msh
│   │   ├── CFI20000592-k31.msh
│   │   └── CFI20000592.sig
│   └── quality-control
│       ├── CFI20000592_R1.fastq.gz
│       ├── CFI20000592_R2.fastq.gz
│       ├── reads-simulated-from-assembly.txt
│       └── summary
│           ├── CFI20000592_R1-final.json
│           ├── CFI20000592_R1-final_fastqc.html
│           ├── CFI20000592_R1-final_fastqc.zip
│           ├── CFI20000592_R1-original.json
│           ├── CFI20000592_R1-original_fastqc.html
│           ├── CFI20000592_R1-original_fastqc.zip
│           ├── CFI20000592_R2-final.json
│           ├── CFI20000592_R2-final_fastqc.html
│           ├── CFI20000592_R2-final_fastqc.zip
│           ├── CFI20000592_R2-original.json
│           ├── CFI20000592_R2-original_fastqc.html
│           └── CFI20000592_R2-original_fastqc.zip
├── bactopia
│   └── nf-reports
│       ├── bactopia-dag.dot
│       ├── bactopia-report.html
│       ├── bactopia-timeline.html
│       ├── bactopia-trace.txt
│       └── bactopia-trace.txt.1
├── logs
│   └── custom_dumpsoftwareversions
│       ├── nf-custom_dumpsoftwareversions.begin
│       ├── nf-custom_dumpsoftwareversions.err
│       ├── nf-custom_dumpsoftwareversions.log
│       ├── nf-custom_dumpsoftwareversions.out
│       ├── nf-custom_dumpsoftwareversions.run
│       ├── nf-custom_dumpsoftwareversions.sh
│       ├── nf-custom_dumpsoftwareversions.trace
│       └── versions.yml
├── software_versions.yml
└── software_versions_mqc.yml

24 directories, 122 files
```

**Comment by tbazilegith** [comment]
Hi Robert,
I gave these commands, there is still no output:
#Processing Muliple Samples
bactopia prepare assemblies-zipped/ --assembly_pattern *.fasta.gz > cfi_fastas.txt
 
bactopia --assembly cfi_fastas.txt --datasets /color/mydir/datasets/ --outdir bactopia_outputAssbl --cpus $SLURM_CPUS_PER_TASK --cleanup_workdir

Is there something extra or missing?

**Comment by rpetit3** [comment]
Is there a `.nextflow.log` file in that directory?

Also, you would use `--fastqs` with the file-of-filenames (I should really go ahead and rename it to `--fofn`)

**Comment by tbazilegith** [comment]
No, there isn't a .nextflow.log file in the directory. Is it required? Normally, what does the output directory look like after processing an assembly? Does it look like the same (in terms of content) as the fastq output?
Thanks!

**Comment by rpetit3** [comment]
The `.nextflow.log` file is created when Nextflow executes, so that suggests to me Nextflow (e.g. Bactopia) is never starting.

Can you do me a favor and try just one assembly?

```
bactopia \
    --assembly CFI20000592.fasta.gz \
    --datasets /color/mydir/datasets/ \
    --outdir bactopia_outputAssbl \
    --cpus $SLURM_CPUS_PER_TASK \
    --cleanup_workdir
```

**Comment by rpetit3** [comment]
Great so we know its working, can you post a few lines from cfi_fastas.txt?

also this one should be:
```
bactopia \
    --fastqs cfi_fastas.txt \
    --datasets /color/mydir/datasets/ \
    --outdir bactopia_outputAssbl \
    --cpus $SLURM_CPUS_PER_TASK \
    --cleanup_workdir
```

It had an extra `--assembly` in it. Also if your using slurm, you might want to consider using `-profile slurm` then tweaking `--slurm_queue` and `--slurm_opts`

**Comment by tbazilegith** [comment]
Another question about the long-read version of the sample CFI20000592 fastq.  (My 1st goal is to process it hybrid along with the short-read version but it triggered genome_size_error, thus I inspected it by running bactopia on it alone). When I run bactopia on it, the only output I have  is JBI20000592-genome-size.txt  logs  minmers  quality-control (1 file and 3 directories). 
The normal output should be:
annotation  antimicrobial-resistance  ariba  assembly  blast  CFI20000592-genome-size.txt  logs  minmers  quality-control
- The genome size seems to be 999491700 bp, and I added max_genome_size 99500700, but I got the incomplete output
- Any thought?
Sorry for so many issues, but I like bactopia!
Thanks

>

**Comment by tbazilegith** [comment]
> -profile slurm
Here is a few lines from cfi_fastas.txt
sample  runtype r1      r2      extra
CFI20000447.fasta.gz    assembly                        /color/my_dir/my_project/assemblies-zipped/CFI20000447.fasta.gz
CFI20000519.fasta.gz    assembly                        /color/my_dir/my_project/assemblies-zipped/CFI20000519.fasta.gz

**Comment by tbazilegith** [comment]
> 

Here is the command to process that ONT long-read sample:
bactopia --SE LRfastqs/JBI20000592.fastq.gz --sample JBI20000592 --ont --datasets /color/my_dir/datasets/ --outdir ${today}bactopia_output1Samp --max_genome_size 99950800 --max_cpus $SLURM_CPUS_PER_TASK --c\
leanup_workdir

**Comment by rpetit3** [comment]
Oh this is interesting, an estimated genome size of `999,491,700`  or 1GBp? That seems wrong, is it a metagenomic sample?

**Comment by tbazilegith** [comment]
The genome size file indicates 99,941,700 when I run it with other samples. It's a bacterial sample. 
- Its bactopia output
JBI20000592-genome-size.txt  logs  minmers  quality-control
-Here is the content of the txt file

99941700
JBI20000592-genome-size.txt (END)

Is the size out of range for bactopia to process?

**Comment by rpetit3** [comment]
I think you are going to want to look into that sample. 99MBp is way outside the largest know bacterial genome size is 16Mbp.

I'm wondering if it is either a eukaryote, metagenomic, or contaminated.

**Comment by tbazilegith** [comment]
Possibly contaminated- we are investigating... I think it's an unknown bacterial species (which I'll confirm with the lab) we're trying to identify through genomic data.

**Comment by rpetit3** [comment]
Also is this a FASTQ file that is given the 99Mb prediction?

**Comment by tbazilegith** [comment]
Right! JBI20000592.fastq.gz

**Comment by rpetit3** [comment]
If you have an idea of the genome size you can give it like `--genome_size 5000000` 

This would bypass the estimate and let you get some results that might help figure out what's happening

**Comment by rpetit3** [comment]
Hi @tbazilegith 

Just checking to see if you were able to get going.

Cheers,
Robert

**Comment by tbazilegith** [comment]
Hi Robert,
I couldn't go any further with this sample JBI20000592.fastq.gz. It is an isolate we're seeking to identify. I have no idea about the genome size. I'm unable to generate assembly for it either by itself or hybrid. I tried to assemble it with both bactopia (SR-LR) and dragonflye (LR-SR). But its sequencing throughput is outstanding 2,994,408,369 pb, and longQC metrics look good. I temporarily left aside it so they can resequence it. Oh, Perhaps I may use the species identified from the short-read sequences to find a genome size from NCBI.
Thanks for checking,
TJ

**Comment by rpetit3** [comment]
Hi @tbazilegith 

I think we might be about as close to a solution as we can get with this one. I'm going to go ahead and close this issue, please feel free to reopen.

Cheers,
Robert
