### ISSUE TITLE
How can I use the bactopia tools?

### ISSUE THREAD

**Issue by lingbingzeng1985** [bactopia/bactopia#308]
Hi, I followed the script that you published on mSphere, like "bactopia tools summary --bactopia ~/KP_annotation/bactopia/ --prefix klebsiella". However, it errors like this: 
WARN: Found unexpected parameters:
* --prefix: klebsiella
* --bactopia: /home/lingbing/study/KP_annotation/bactopia/
- Ignore this warning: params.schema_ignore_params = "prefix,bactopia" 
- ERROR: Validation of pipeline parameters failed!
Please correct to continue

So how I could use the bactopia tools? Thanks.

**Comment by lingbingzeng1985** [comment]
Yes. It is cool. I followed the protocol of bactopia in your paper, and had a good result. But I cannot take the access to the tools. Could you provide any protocols of the tools? Thanks.

**Comment by rpetit3** [comment]
Hi @lingbingzeng1985 

I'm going to go ahead and close this issue, please feel free to reopen.

Cheers,
Robert
