### ISSUE TITLE
Error in documentation (cpus)

### ISSUE THREAD

**Issue by lfenske-93** [bactopia/bactopia#315]
Hi 😄 

I have found an error in the documentation. Under Complete Usage the runtime parameters are listed. The command `--cpus` is mentioned, but it should be `--max_cpus`.
I just tried `--cpus `and was confused why it is not recognized as a parameter. 
I'm also not quite sure if `-qs` works, as it doesn't show me on the parameters that differ from the pipeline default.

Greetings,
Linda

**Comment by rpetit3** [comment]
Okie doke! I've brought the complete usage docs to v2 https://bactopia.github.io/usage-complete/

There's still more I want to do on this page, but at least it now reflects parameter names in v2

**Comment by rpetit3** [comment]
@lfenske-93 I'm going to go ahead and close this issue, please feel free to reopen!
