### ISSUE TITLE
Spades assembly failing, extra non-integer argument in "-k"

### ISSUE THREAD

**Issue by creamerk** [bactopia/bactopia#317]
Hi, thanks for this fantastic tool! 

I'm trying to assemble some bacterial genomes using spades and I've run into this error twice now where I think there's a bug in shovill calling spades.

**Steps to Reproduce**
My submitted bactopia job: 
```
bactopia --R1 ../fastqs/Sample055test_S16_L001_R1_001.fastq.gz \
--R2 ../fastqs/Sample055test_S16_L001_R2_001.fastq.gz \
--sample Sample055test --datasets datasets/ --genome_size 5790000 --cpus 8 --outdir $OUTDIRN \
--coverage 300 --minlength 35 --shovill_assembler spades --shovill_opts "--isolate" --compliant \
--datasets datasets/ --run_checkm
```

The job fails on the "`Process BACTOPIA:ASSEMBLE_GENOME (Sample055test) terminated with an error exit status (1)`" 

I'm happy to provide in any of the other traceback information/version info saved from the error, but what I noticed was both samples I tried that returned the same error had this in common: 

```
    Bactopia Execution Summary
    ---------------------------
    Bactopia Version : 2.0.3
    Nextflow Version : 22.04.0
    Command Line     : nextflow run /home/kcreamer/miniconda3/envs/bactopia2//share/bactopia-2.0.x/main.nf -w /oasis/tscc/scratch/kcreamer/assembly_bactopia/work/ --R1 ../fastqs/Sample055test_S16_L001_R1_001.fastq.gz --R2 ../fastqs/Sample055test_S16_L001_R2_001.fastq.gz --sample Sample055test --datasets datasets/ --genome_size 5790000 --cpus 8 --outdir Sample055test --coverage 300 --minlength 35 --shovill_assembler spades --shovill_opts --isolate --compliant --datasets datasets/ --run_checkm
    Resumed          : false
    Completed At     : 2022-05-11T19:43:02.770678-07:00
    Duration         : 24m 25s
    Success          : false
    Exit Code        : 1
    Error Report     : Error executing process > 'BACTOPIA:ASSEMBLE_GENOME (Sample055test)'

Caused by:
  Process `BACTOPIA:ASSEMBLE_GENOME (Sample055test)` terminated with an error exit status (1)
```

- I noticed above is that "--shovill_opts" is listed but "--isolate" is no longer in quotes, is that okay?  
The report continues: 

Command executed: 
```
  OUTDIR=results
  GENOME_SIZE=`head -n 1 Sample055test-genome-size.txt`
  if [ "null" == "true" ]; then
      mkdir ${OUTDIR}
      gzip -cd empty.fna.gz > ${OUTDIR}Sample055test.fna
  elif [[ "paired-end" == "hybrid"  || "false" == "true" ]]; then
      unicycler -1 Sample055test_R1.fastq.gz -2 Sample055test_R2.fastq.gz -o ${OUTDIR}/ --no_correct             --min_fasta_length 500             --threads 3             --mode normal             --min_polish_size 10000             --min_component_size 1000             --min_dead_end_size 1000     --keep 1
      sed -r 's/^>([0-9]+)(.*)/>Sample055test_\1\2/' ${OUTDIR}/assembly.fasta > ${OUTDIR}/Sample055test.fna
      mv ${OUTDIR}/assembly.gfa ${OUTDIR}/unicycler.gfa
  else
      # Shovill or Dragonflye
      shovill --R1 Sample055test_R1.fastq.gz --R2 Sample055test_R2.fastq.gz  --gsize ${GENOME_SIZE}             --outdir ${OUTDIR}             --force             --minlen 500             --mincov 2             --namefmt "Sample055test_%05d"             --keepfiles             --cpus 3             --ram 31 --assembler spades --depth 0 --noreadcorr --opts 'true'  
      mv ${OUTDIR}/contigs.fa ${OUTDIR}/Sample055test.fna
  
      # Rename Graphs
      if [ "shovill" == "shovill" ]; then 
          if [ -f "${OUTDIR}/contigs.gfa" ]; then
              mv ${OUTDIR}/contigs.gfa ${OUTDIR}/spades-unpolished.gfa
          elif [ -f "${OUTDIR}/contigs.fastg" ]; then
              mv ${OUTDIR}/contigs.fastg ${OUTDIR}/spades-unpolished.gfa
          elif [ -f "${OUTDIR}/contigs.LastGraph" ]; then
              mv ${OUTDIR}/contigs.LastGraph ${OUTDIR}/spades-unpolished.gfa
          fi
      fi
  
      if [ -f "${OUTDIR}/flye-info.txt" ]; then
          mv ${OUTDIR}/flye-info.txt ${OUTDIR}/flye.log
      fi
  fi


etc 
```

Command output: 
(..everything above this looks correct..)
```
  [FLASH] FLASH v1.2.11 complete!
  [FLASH] 26.605 seconds elapsed
  [spades] SPAdes genome assembler v3.15.3
  [spades] 
  [spades] Usage: spades.py [options] -o <output_dir>
  [spades] spades.py: error: argument -k: invalid kmers value: 'true'
```
and looking where that "true" showed up (the command should be -k integer,integer,etc) 

```
[shovill] Average read length looks like 296 bp
  [shovill] Setting k-mer range to (31 .. 127)
  [shovill] Estimated K-mers: 31 55 79 103 127 [kn=5, ks=24, kmin=31, kmax=127]
  [shovill] Using kmers: 31,55,79,103,127
  [shovill] Enabled --noreadcorr, so no read correction will be performed
  [shovill] Overlapping/stitching PE reads with 'FLASH'
  [shovill] Running: flash -m 20 -M 300 -d . -o flash -z -t 3 R1.fq.gz R2.fq.gz 2>&1 | sed 's/^//' | tee -a shovill.log
  [shovill] Assembling reads with 'spades'
  [shovill] Running: spades.py -1 flash.notCombined_1.fastq.gz -2 flash.notCombined_2.fastq.gz --isolate --threads 3 --memory 31 -o spades --tmp-dir /scratch/kcreamer/29036845.tscc-mgr7.local -k 31,55,79,103,127 true --merged flash.extendedFrags.fastq.gz 2>&1 | sed 's/^/[spades] /' | tee -a shovill.log
  [shovill] Assembly failed - spades.fasta has zero contigs!
```

I'm not sure where that "true" came from, and is it something that can be removed? I think that it's the cause of the failure as each time Nextflow tried to run it again (4 times), the same "true" error was returned. 

I was looking for other warnings that might relate to "true"; I found at the top of the Nextflow launch: 
WARN: Found unexpected parameters:
```
* --isolate: true
* --cpus: 8
- Ignore this warning: params.schema_ignore_params = "isolate,cpus" 
```

It looks like to me that perhaps 1) the true is coming from the single quote 'true' used in the call for shovill -opts 'true' where perhaps instead it should be -opts "true" ?  or 2) something else ? Happy to provide any other details of the error, I didn't want to be overzealous with copy-paste. 
 
**Execution Environment**

- Bactopia Version: bactopia 2.0.3
- OS: Linux
- Environment: conda env on SDSC cluster

Thank you in advance for your help!

**Comment by rpetit3** [comment]
Hi @creamerk,

Looks like Nextflow doesn't like `--shovill_opts "--isolate"`, but it does like `--shovill_opt="--isolate"`. A heads up, as of Shovill v1.1.0, `--isolate` is used by default. So the `--shovill_opt="--isolate"` is redundant, but it is very nice to learn for these "opts" parameters a `=` is needed otherwise Nextflow interprets them.


Another thing you'll want to switch is `--cpus` to `--max_cpus`.

Here's a revised command, let me know if it works for you:

```
bactopia \
    --R1 ../fastqs/Sample055test_S16_L001_R1_001.fastq.gz \
    --R2 ../fastqs/Sample055test_S16_L001_R2_001.fastq.gz \
    --sample Sample055test \
    --datasets datasets/ \
    --genome_size 5790000 \
    --max_cpus 8 \
    --outdir $OUTDIRN \
    --coverage 300 \
    --minlength 35 \
    --shovill_assembler spades \
    --shovill_opts="--isolate" \
    --compliant \
    --run_checkm
```

**Comment by creamerk** [comment]
Thanks so much for the super speedy reply-- great to know that "--isolate" is the default, I must have missed that! 

To test this fix (which it also worked when I removed --shovill_opts altogether), I instead replaced --shovill_opts="--isolate"  with --shovill_opts="--careful" , the other option I'd like to toggle on (and toggle off --isolate). This didn't seem to work-- relevant error codes are copied below, both --isolate and --careful can't be run at the same time. Is it possible to run a Spades with --careful in this workflow? 

Command error:
```
  [shovill] Assembling reads with 'spades'
  [shovill] Running: spades.py -1 flash.notCombined_1.fastq.gz -2 flash.notCombined_2.fastq.gz --isolate --threads 6 --memory 31 -o spades --tmp-dir /scratch/kcreamer/29037543.tscc-mgr7.local -k 31,51,71,91 --careful --merged flash.extendedFrags.fastq.gz 2>&1 | sed 's/^/[spades] /' | tee -a shovill.log
  [shovill] Assembly failed - spades.fasta has zero contigs!
```

Command executed:
```
  [spades] == Error ==  you cannot specify --mismatch-correction or --careful in isolate mode!
  [spades] 
  [spades] In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
  [spades] or report an issue on our GitHub repository github.com/ablab/spades
  [spades] Please provide us with params.txt and spades.log files from the output directory.
```

Thank you!

**Comment by rpetit3** [comment]
Looks like you are not going to be able to run spades with `--careful` because `--isolate` is hardcoded in Shovill: https://github.com/tseemann/shovill/blob/master/bin/shovill#L108

**Comment by creamerk** [comment]
Ah, that makes sense-- especially since the Shovill spades assembly workflow is followed by bwa+samtools & pilon, which seems redundant to the `--careful` flag. Thanks for looking into that; I still get great assemblies-- I was only curious about testing it because my coverage wasn't as "high" as indicated best for `--isolate` mode in the Spades documentation, but it seems to work just fine.
Thanks again @rpetit3 !

**Comment by rpetit3** [comment]
No problem, let me know if there's anything I can help with!

If you have any feedback, please feel free to complete my little survey: https://forms.gle/PTgUxEBwCsCdbQjr7
