### ISSUE TITLE
Bactopia tools summary leads to: One or more required parameters are missing, please check and try again.

### ISSUE THREAD

**Issue by KarimAI7** [bactopia/bactopia#318]
Hello, I created a .txt with all my .fastq files and analyzed them using:
`bactopia --fastqs R_fastqFOFN.txt --datasets /home/elliston/Documents/karim/bactopia/R_fastq_bactopia/datasets/
`
This ran well andoutputted a directory of directories with all the analyzed files individually.
Then I tried to run: 
`bactopia tools summary --bactopia ~/bactopia --prefix Lpn` to get a summary report (I got this from https://journals.asm.org/doi/10.1128/mSystems.00190-20) but it keeps saying: 
`One or more required parameters are missing, please check and try again.

Required Parameters
  ### For Procesessing Multiple Samples
  --fastqs                            [string]  A FOFN with sample names and paths to FASTQ/FASTAs to process

  ### For Processing A Single Sample
  --R1                                [string]  First set of compressed (gzip) paired-end FASTQ reads (requires --R2 and --sample)
  --R2                                [string]  Second set of compressed (gzip) paired-end FASTQ reads (requires --R1 and --sample)
  --SE                                [string]  Compressed (gzip) single-end FASTQ reads  (requires --sample)
  --ont                               [boolean] Treat `--SE` as long reads for analysis. (requires --sample)
  --hybrid                            [boolean] Treat `--SE` as long reads for hybrid assembly.  (requires --R1, --R2, --SE and --sample)
  --sample                            [string]  Sample name to use for the input sequences

  ### For Downloading from SRA/ENA or NCBI Assembly
  **Note: Downloaded assemblies will have error free Illumina reads simulated for processing.**
  --accessions                        [string]  A file containing ENA/SRA Experiment accessions or NCBI Assembly accessions to processed
  --accession                         [string]  Sample name to use for the input sequences

  ### For Processing an Assembly
  **Note: Assemblies will have error free Illumina reads simulated for processing.**
  --assembly                          [string]  A assembled genome in compressed FASTA format. (requires --sample)

--------------------------------------------------------------------
ERROR: Validation of pipeline parameters failed!
Please correct to continue
`
Shouldnt the directories containing the analyses for each .fastq file be used to generate the summary file?

**Comment by rpetit3** [comment]
Hi @KarimAI7,

The `summary` tool was lost in version 2, and I'm slowly bringing it back. I have development build of Bactopia with it, if you are interested in trying it.

```
mamba install -n bactopia-dev -c rpetit3 -c conda-forge -c bioconda bactopia
conda activate bactopia-dev
bactopia-summary --help
```

Let me know if this doesn't work for you!
Cheers,
Robert

**Comment by KarimAI7** [comment]
Will do, I tried skipping over this step and running:
`bactopia tools phyloflash --phyloflash /home/elliston/Documents/karim/bactopia/R_fastq_bactopia/datasets/16s/138 --bactopia ~/bactopia` (also from: https://journals.asm.org/doi/10.1128/mSystems.00190-20) 
I got the same error:
`One or more required parameters are missing, please check and try again.


Required Parameters
  ### For Procesessing Multiple Samples
  --fastqs                            [string]  A FOFN with sample names and paths to FASTQ/FASTAs to process

  ### For Processing A Single Sample
  --R1                                [string]  First set of compressed (gzip) paired-end FASTQ reads (requires --R2 and --sample)
  --R2                                [string]  Second set of compressed (gzip) paired-end FASTQ reads (requires --R1 and --sample)
  --SE                                [string]  Compressed (gzip) single-end FASTQ reads  (requires --sample)
  --ont                               [boolean] Treat `--SE` as long reads for analysis. (requires --sample)
  --hybrid                            [boolean] Treat `--SE` as long reads for hybrid assembly.  (requires --R1, --R2, --SE and --sample)
  --sample                            [string]  Sample name to use for the input sequences

  ### For Downloading from SRA/ENA or NCBI Assembly
  **Note: Downloaded assemblies will have error free Illumina reads simulated for processing.**
  --accessions                        [string]  A file containing ENA/SRA Experiment accessions or NCBI Assembly accessions to processed
  --accession                         [string]  Sample name to use for the input sequences

  ### For Processing an Assembly
  **Note: Assemblies will have error free Illumina reads simulated for processing.**
  --assembly                          [string]  A assembled genome in compressed FASTA format. (requires --sample)

--------------------------------------------------------------------
ERROR: Validation of pipeline parameters failed!
Please correct to continue
`
I am not sure why it cant detect the directories with the analyzed .fastq data. Or is this also a tool that is not working anymore? I am following the originally published paper to get the scripts.

**Comment by KarimAI7** [comment]
Hello,
The Bactopia Tools link worked great! pangenome ran well.
I tried running the developer link you provided: `mamba install -n bactopia-dev -c rpetit3 -c conda-forge -c bioconda bactopia`
I got the following error `EnvironmentLocationNotFound: Not a conda environment: /home/elliston/miniconda3/envs/bactopia-dev
`

**Comment by rpetit3** [comment]
Glad it worked! The dev didn't work because I told you the wrong thing! You will need `create` instead of `install`

```
mamba create -n bactopia-dev -c rpetit3 -c conda-forge -c bioconda bactopia
``

**Comment by KarimAI7** [comment]
It worked and I was able to activate the bactopia-dev environment using `conda activate bactopia-dev`
I then tried running `bactopia-summary --help` as stated but I got `bactopia-summary: command not found
`
How should I proceed?

**Comment by rpetit3** [comment]
Can you post the output of `conda env export` while in your bactopia dev environment?

**Comment by rpetit3** [comment]
Hi @KarimAI7 ,

Is this still an issue you would like to fix?

Cheers,
Robert

**Comment by rpetit3** [comment]
Hi @KarimAI7 

This should all be sorted out via `bactopia summary` in v3 of Bactopia. 

I will go ahead and close this issue. Please feel free to reach out if you have any issues!

Cheers,
Robert
