### ISSUE TITLE
[question] Can someone help me on --coverage and the discrepancy in output?

### ISSUE THREAD

**Issue by JordyCoolen** [bactopia/bactopia#321]
Dear,

I have noticed that with setting --coverage 120 the quality_control results report 120 coverage on R1 and on R2,
however, the results of the assembly in the contigs indicate around cov=60.

Can someone help me how --coverage is calculating and limiting the coverage and what the natural and best coverage is to report.

Kind regards,

Jordy

**Comment by rpetit3** [comment]
Hi @JordyCoolen 

Did you use SKESA or SPAdes for assembly? I'm guessing the the coverage for the contigs is the k-mer coverage which is expected to lower than the estimated coverage. Here's some info from SPAdes documentation: https://github.com/ablab/spades#contigs-and-scaffolds-format

`--coverage` is using the genome size to estimate the number of base pairs needed for 'X' coverage. Example being for 100X of Staphylococcus aureus (genome size 2,800,000 bp), a total of 280,000,000 base pairs would be randomly subsampled. This comes out to be.

Cheers,
Robert

**Comment by rpetit3** [comment]
Hi @JordyCoolen,

I'm going to go ahead and close this issue, please feel free to reopen if you have any questions!

Cheers,
Robert
