### ISSUE TITLE
[feature] Report

### ISSUE THREAD

**Issue by shlomobl** [bactopia/bactopia#323]
Hi,

Is there already a way to wrap the results of different analysis into one report or file? 

Preferably csv, but also a html or similar report for visualization would be great!

I mean per analysis, but as I write, I think the option of a report with multiple analysis would be also very nice to have (table of AMR, MLST, VGs etc.).

If not, does someone suggest a script to gather the results together?

**Comment by rpetit3** [comment]
Hi @shlomobl

It's a work in progress, but take a look at this issue: https://github.com/bactopia/bactopia/issues/318

You can use `bactopia-summary` (only in my dev build at the moment) to get a table with some of these fields

Cheers,
Robert

**Comment by rpetit3** [comment]
Hi @shlomobl 

This sis now apart of v3. In the future I will be adding HTML reports (think multiqc)

I will go ahead and close this,
Robert
