### ISSUE TITLE
 pangenome pirate - ERROR: extract_feature_sequences.pl failed

### ISSUE THREAD

**Issue by jellyvanderwoude** [bactopia/bactopia#329]
(bactopia) bio-24046:bactopia-folder jvanderwoude3$ bactopia --wf pangenome --bactopia /Volumes/JellyExternal/bactopia-folder --include include130.txt --outdir 130_pirate
Traceback (most recent call last):
  File "/Users/jvanderwoude3/miniconda3/envs/bactopia/bin/bactopia-download.py", line 515, in <module>
    workflow_modules = parse_workflows(bactopia_path, include_merlin=include_merlin, build_all=args.build_all)
  File "/Users/jvanderwoude3/miniconda3/envs/bactopia/bin/bactopia-download.py", line 146, in parse_workflows
    nf_config, stderr = execute(f'nextflow config -flat {bactopia_path}/main.nf', capture=True)
  File "/Users/jvanderwoude3/miniconda3/envs/bactopia/bin/bactopia-download.py", line 80, in execute
    from executor import ExternalCommand, ExternalCommandFailed
ModuleNotFoundError: No module named 'executor'
N E X T F L O W  ~  version 22.04.0
Launching `/Users/jvanderwoude3/miniconda3/envs/bactopia/share/bactopia-2.0.x/main.nf` [prickly_colden] DSL2 - revision: bd75c553f9

--------------------------------------------------------------------
   _                _              _         _              _              
  | |__   __ _  ___| |_ ___  _ __ (_) __ _  | |_ ___   ___ | |___          
  | '_ \ / _` |/ __| __/ _ \| '_ \| |/ _` | | __/ _ \ / _ \| / __|    
  | |_) | (_| | (__| || (_) | |_) | | (_| | | || (_) | (_) | \__ \        
  |_.__/ \__,_|\___|\__\___/| .__/|_|\__,_|  \__\___/ \___/|_|___/ 
                            |_|                                            
  bactopia tools pangenome v2.0.3
  Pangenome analysis with optional core-genome phylogeny 
--------------------------------------------------------------------
Core Nextflow options
  runName          : prickly_colden
  launchDir        : /Volumes/JellyExternal/bactopia-folder
  workDir          : /Volumes/JellyExternal/bactopia-folder/work
  projectDir       : /Users/jvanderwoude3/miniconda3/envs/bactopia/share/bactopia-2.0.x
  userName         : jvanderwoude3
  profile          : standard
  configFiles      : /Users/jvanderwoude3/miniconda3/envs/bactopia/share/bactopia-2.0.x/nextflow.config

Required Parameters
  bactopia         : /Volumes/JellyExternal/bactopia-folder

Filtering Parameters
  include          : include130.txt

Optional Parameters
  outdir           : 130_pirate
  run_name         : pangenome

Nextflow Profile Parameters
  condadir         : /Users/jvanderwoude3/miniconda3/envs/bactopia/share/bactopia-2.0.x/conda/envs
  registry         : quay
  singularity_cache: /Users/jvanderwoude3/.bactopia/singularity

Helpful Parameters
  wf               : pangenome

!! Only displaying parameters that differ from the pipeline defaults !!
--------------------------------------------------------------------
If you use bactopia for your analysis please cite:

* Bactopia
  https://doi.org/10.1128/mSystems.00190-20

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

* Software dependencies
  https://bactopia.github.io/acknowledgements/
--------------------------------------------------------------------
WARN: 
WARN: Conda Disclaimer
WARN: 
WARN: If you have access to Docker or Singularity, please consider
WARN: running Bactopia using containers. The containers are less
WARN: susceptible to Conda environment related issues (e.g. version
WARN: conflicts) and errors caused by creation of conda environments
WARN: in parallel (use '--max_cpus 1' to over come this error).
WARN: 
WARN: To use containers, you can use the profile parameter
WARN:     Docker: -profile docker
WARN:     Singularity: -profile singularity
WARN: 
--------------------------------------------------------------------

Each task will use 4 CPUs out of the available 28 CPUs. At most 
7 task(s) will be run at a time, this can affect the efficiency 
of Bactopia. You can use the '-qs' parameter to alter the number of 
tasks to run at a time (e.g. '-qs 2', means only 2 tasks or a maximum 
of 8 CPUs will be used at once)

Including 75 samples for analysis
Found 75 samples to process

If this looks wrong, now's your chance to back out (CTRL+C 3 times).
Sleeping for 5 seconds...
--------------------------------------------------------------------
[-        ] process > BACTOPIATOOLS:PROKKA:PROKKA... -
[-        ] process > BACTOPIATOOLS:PROKKA:PROKKA... -
[-        ] process > BACTOPIATOOLS:PANGENOME:PG_... -
[-        ] process > BACTOPIATOOLS:PANGENOME:SNP... -
[-        ] process > BACTOPIATOOLS:PROKKA:PROKKA... -
executor >  local (1)
executor >  local (1)
[-        ] process > BACTOPIATOOLS:PROKKA:PROKKA... -
executor >  local (2)
[-        ] process > BACTOPIATOOLS:PROKKA:PROKKA... -
executor >  local (3)
[-        ] process > BACTOPIATOOLS:PROKKA:PROKKA... -
executor >  local (3)
[-        ] process > BACTOPIATOOLS:PROKKA:PROKKA... -
executor >  local (4)
[-        ] process > BACTOPIATOOLS:PROKKA:PROKKA... -
[f0/346027] process > BACTOPIATOOLS:PANGENOME:PG_... [ 75%] 3 of 4, failed: 3..
executor >  local (4)
[-        ] process > BACTOPIATOOLS:PROKKA:PROKKA... -
[f0/346027] process > BACTOPIATOOLS:PANGENOME:PG_... [ 75%] 3 of 4, failed: 3..
[-        ] process > BACTOPIATOOLS:PANGENOME:SNP... -
[-        ] process > BACTOPIATOOLS:PANGENOME:CLO... -
[-        ] process > BACTOPIATOOLS:PANGENOME:CLO... -
[-        ] process > BACTOPIATOOLS:PANGENOME:FIN... -
[-        ] process > BACTOPIATOOLS:CUSTOM_DUMPSO... -
[84/3bc632] NOTE: Process `BACTOPIATOOLS:PANGENOME:PG_TOOL:PIRATE_MODULE (pirate)` terminated with an error exit status (2) -- Execution is retried (3)
WARN: Task runtime metrics are not reported when using macOS without a container engine

Error executing process > 'BACTOPIATOOLS:PANGENOME:PG_TOOL:PIRATE_MODULE (pirate)'

Caused by:
  Process `BACTOPIATOOLS:PANGENOME:PG_TOOL:PIRATE_MODULE (pirate)` terminated with an error exit status (2)

Command executed:

  find . -name "*.gff.gz" | sed 's/.gz//' | xargs -I {} bash -c 'gzip -cdf {}.gz > {}'
  
  PIRATE \
      --steps 50,60,70,80,90,95,98 --features CDS \
      --align \
      --threads 4 \
      --input ./ \
      --output results/
  PIRATE_to_roary.pl -i results/PIRATE.*.tsv -o results/gene_presence_absence.csv
  find . -name "*.fasta" | xargs -I {} -P 4 -n 1 gzip {}
  
  # Only copy files if they exist
  if [[ -f "results/core_alignment.fasta.gz" ]]; then
      cp results/core_alignment.fasta.gz ./core-genome.aln.gz
  fi
  
  cat <<-END_VERSIONS > versions.yml
  "BACTOPIATOOLS:PANGENOME:PG_TOOL:PIRATE_MODULE":
      pirate: $( echo $( PIRATE --version 2>&1) | sed 's/PIRATE //' )
  END_VERSIONS

Command exit status:
  2

Command output:
  
  -------------------------------
  
  PIRATE input options:
  
   - Input Directory = /Volumes/JellyExternal/bactopia-folder/work/f0/346027c3737af4abc8bddc20f43150
   - Output directory = results
   - PIRATE will run using 4 cores
   - 75 files in input directory.
   - PIRATE will be run on 50,60,70,80,90,95,98 amino acid % identity thresholds.
   - PIRATE will be run on features annotated as CDS
  
  -------------------------------
  
  Standardising and checking input files:
  
   - 75 gff files passed QC and will be analysed by PIRATE - completed in: 14s
  
  -------------------------------
  
   - creating co-ordinate files - completed in: 3s
   - creating genome loci list: - completed in: 1s
  
  -------------------------------
  
  Extracting pangenome sequences:

Command error:
   - ERROR: extract_feature_sequences.pl failed
  No such file or directory at /Users/jvanderwoude3/miniconda3/envs/bactopia/share/bactopia-2.0.x/conda/envs/env-16bdc2e458233f53f9e47dc3671faf52/bin/PIRATE_to_roary.pl line 48.

Work dir:
  /Volumes/JellyExternal/bactopia-folder/work/f0/346027c3737af4abc8bddc20f43150

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

    Bactopia Tools: `pangenome Execution Summary
    ---------------------------
    Bactopia Version : 2.0.3
    Nextflow Version : 22.04.0
    Command Line     : nextflow run /Users/jvanderwoude3/miniconda3/envs/bactopia//share/bactopia-2.0.x/main.nf -w /Volumes/JellyExternal/bactopia-folder/work/ --wf pangenome --bactopia /Volumes/JellyExternal/bactopia-folder --include include130.txt --outdir 130_pirate
    Resumed          : false
    Completed At     : 2022-06-03T15:49:06.485574-04:00
    Duration         : 4m 40s
    Success          : false
    Exit Code        : 2
    Error Report     : Error executing process > 'BACTOPIATOOLS:PANGENOME:PG_TOOL:PIRATE_MODULE (pirate)'

Caused by:
  Process `BACTOPIATOOLS:PANGENOME:PG_TOOL:PIRATE_MODULE (pirate)` terminated with an error exit status (2)

Command executed:

  find . -name "*.gff.gz" | sed 's/.gz//' | xargs -I {} bash -c 'gzip -cdf {}.gz > {}'
  
  PIRATE \
      --steps 50,60,70,80,90,95,98 --features CDS \
      --align \
      --threads 4 \
      --input ./ \
      --output results/
  PIRATE_to_roary.pl -i results/PIRATE.*.tsv -o results/gene_presence_absence.csv
  find . -name "*.fasta" | xargs -I {} -P 4 -n 1 gzip {}
  
  # Only copy files if they exist
  if [[ -f "results/core_alignment.fasta.gz" ]]; then
      cp results/core_alignment.fasta.gz ./core-genome.aln.gz
  fi
  
  cat <<-END_VERSIONS > versions.yml
  "BACTOPIATOOLS:PANGENOME:PG_TOOL:PIRATE_MODULE":
      pirate: $( echo $( PIRATE --version 2>&1) | sed 's/PIRATE //' )
  END_VERSIONS

Command exit status:
  2

Command output:
  
  -------------------------------
  
  PIRATE input options:
  
   - Input Directory = /Volumes/JellyExternal/bactopia-folder/work/f0/346027c3737af4abc8bddc20f43150
   - Output directory = results
   - PIRATE will run using 4 cores
   - 75 files in input directory.
   - PIRATE will be run on 50,60,70,80,90,95,98 amino acid % identity thresholds.
   - PIRATE will be run on features annotated as CDS
  
  -------------------------------
  
  Standardising and checking input files:
  
   - 75 gff files passed QC and will be analysed by PIRATE - completed in: 14s
  
executor >  local (4)
[-        ] process > BACTOPIATOOLS:PROKKA:PROKKA... -
[f0/346027] process > BACTOPIATOOLS:PANGENOME:PG_... [100%] 4 of 4, failed: 4..
[-        ] process > BACTOPIATOOLS:PANGENOME:SNP... -
[-        ] process > BACTOPIATOOLS:PANGENOME:CLO... -
[-        ] process > BACTOPIATOOLS:PANGENOME:CLO... -
[-        ] process > BACTOPIATOOLS:PANGENOME:FIN... -
[-        ] process > BACTOPIATOOLS:CUSTOM_DUMPSO... -
[84/3bc632] NOTE: Process `BACTOPIATOOLS:PANGENOME:PG_TOOL:PIRATE_MODULE (pirate)` terminated with an error exit status (2) -- Execution is retried (3)
WARN: Task runtime metrics are not reported when using macOS without a container engine
Error executing process > 'BACTOPIATOOLS:PANGENOME:PG_TOOL:PIRATE_MODULE (pirate)'

Caused by:
  Process `BACTOPIATOOLS:PANGENOME:PG_TOOL:PIRATE_MODULE (pirate)` terminated with an error exit status (2)

Command executed:

  find . -name "*.gff.gz" | sed 's/.gz//' | xargs -I {} bash -c 'gzip -cdf {}.gz > {}'
  
  PIRATE \
      --steps 50,60,70,80,90,95,98 --features CDS \
      --align \
      --threads 4 \
      --input ./ \
      --output results/
  PIRATE_to_roary.pl -i results/PIRATE.*.tsv -o results/gene_presence_absence.csv
  find . -name "*.fasta" | xargs -I {} -P 4 -n 1 gzip {}
  
  # Only copy files if they exist
  if [[ -f "results/core_alignment.fasta.gz" ]]; then
      cp results/core_alignment.fasta.gz ./core-genome.aln.gz
  fi
  
  cat <<-END_VERSIONS > versions.yml
  "BACTOPIATOOLS:PANGENOME:PG_TOOL:PIRATE_MODULE":
      pirate: $( echo $( PIRATE --version 2>&1) | sed 's/PIRATE //' )
  END_VERSIONS

Command exit status:
  2

Command output:
  
  -------------------------------
  
  PIRATE input options:
  
   - Input Directory = /Volumes/JellyExternal/bactopia-folder/work/f0/346027c3737af4abc8bddc20f43150
   - Output directory = results
   - PIRATE will run using 4 cores
   - 75 files in input directory.
   - PIRATE will be run on 50,60,70,80,90,95,98 amino acid % identity thresholds.
   - PIRATE will be run on features annotated as CDS
  
  -------------------------------
  
  Standardising and checking input files:
  
   - 75 gff files passed QC and will be analysed by PIRATE - completed in: 14s
  
  -------------------------------
  
   - creating co-ordinate files - completed in: 3s
   - creating genome loci list: - completed in: 1s
  
  -------------------------------
  
  Extracting pangenome sequences:

Command error:
   - ERROR: extract_feature_sequences.pl failed
  No such file or directory at /Users/jvanderwoude3/miniconda3/envs/bactopia/share/bactopia-2.0.x/conda/envs/env-16bdc2e458233f53f9e47dc3671faf52/bin/PIRATE_to_roary.pl line 48.

Work dir:
  /Volumes/JellyExternal/bactopia-folder/work/f0/346027c3737af4abc8bddc20f43150

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

WARN: To render the execution DAG in the required format it is required to install Graphviz -- See http://www.graphviz.org for more info.

**Comment by rpetit3** [comment]
Bummer, I bet I know what's happening here.

I added a build of PIRATE to Bioconda (https://github.com/bioconda/bioconda-recipes/pull/31629) that included `PIRATE_to_roary.pl`. This would be Build 2 of PIRATE v1.0.4 on BioConda. I think when you are running the `pangenome` tool Conda is pulling Build 1 or Build 0 of PIRATE, which are missing this script.

Let me see if I can force the build for you. Otherwise if its possible to use Docker or Singularity I would recommend those over Conda. 

I'll update soon!

Robert

**Comment by rpetit3** [comment]
Hi @jellyvanderwoude 

I released v2.1.0 (https://github.com/bactopia/bactopia/releases/tag/v2.1.0) which should fix this for you! I updated the PIRATE step to use the specific build with the necessary scripts. The new version should be available on Bioconda today or tomorrow. If your problem persists, please feel free to reopen this issue!

If you have some time to spare, please consider filling out my Bactopia survey.  I use the feedback to direct the future developments of Bactopia. (_If you've already filled it out, thank you so much!_)

https://forms.gle/PTgUxEBwCsCdbQjr7

Cheers,
Robert
