### ISSUE TITLE
macOS: Bactopia refused to continue after S. aureus dataset was created

### ISSUE THREAD

**Issue by phanhung2** [bactopia/bactopia#334]
**Description**
Using an M1 Pro MacBook, I encountered this error while using Bactopia to run the tutorial from the Sequence Read Archive (SRA). The result indicated that the ARIBA dependency was not working properly. I tried using  `pip install ariba` to resolve this issue but I encountered it again using the same commands. The dataset folder was created but bactopia refused to continue. 

**Steps to Reproduce**
```
bactopia datasets \
    --species "Staphylococcus aureus" \
    --include_genus \
    --limit 100 \
    --cpus 8
```

**Expected Behavior**
Bactopia should create a dataset the /dataset folder in the bactopia environment. 

**Execution Environment**

- Bactopia Version: 2.1.0
- OS: macOS 12.4
- Environment: conda 4.12.0

**Additional Information**
Output by Bactopia:

`2022-06-14 11:26:13:root:INFO - Staphylococcus aureus verified in ENA Taxonomy database
2022-06-14 11:26:13:root:INFO - Setting up pre-computed Genbank/Refseq minmer datasets
2022-06-14 11:26:13:root:INFO - ./datasets/minmer/sourmash-genbank-k21.json.gz exists, skipping
2022-06-14 11:26:13:root:INFO - ./datasets/minmer/sourmash-genbank-k31.json.gz exists, skipping
2022-06-14 11:26:13:root:INFO - ./datasets/minmer/sourmash-genbank-k51.json.gz exists, skipping
2022-06-14 11:26:13:root:INFO - ./datasets/minmer/mash-refseq-k21.msh exists, skipping
2022-06-14 11:26:13:root:INFO - Setting up antimicrobial resistance datasets
2022-06-14 11:26:13:root:INFO - Setting up latest AMRFinder+ database
2022-06-14 11:27:09:root:INFO - AMRFinder+ database saved to ./datasets/antimicrobial-resistance/amrfinderdb.tar.gz
2022-06-14 11:27:09:root:INFO - Setting up MLST datasets
2022-06-14 11:27:09:root:INFO - Setting up default MLST schema for Staphylococcus aureus
External command failed with exit code 1!

Command:
bash -c 'ariba pubmlstget "Staphylococcus aureus" ./datasets/species-specific/staphylococcus-aureus/mlst/default/ariba'

Standard error:
WARNING: I tried to get the version of spades with: "/Users/phanhung2/miniconda3/envs/bactopia/bin/spades.py --version" and the output didn't match this regular expression: "SPAdes\s+v([0-9\.]+)"
ERROR: I tried to get the version of nucmer with: "/Users/phanhung2/miniconda3/envs/bactopia/bin/nucmer --version" and the output didn't match this regular expression: "([0-9]+\.[0-9\.]+.*$)"

Something wrong with at least one dependency. Please see the above error message(s)
ARIBA version: 2.14.6

External dependencies:
bowtie2	2.3.5.1	/Users/phanhung2/miniconda3/envs/bactopia/bin/bowtie2
cdhit	4.8.1	/Users/phanhung2/miniconda3/envs/bactopia/bin/cd-hit-est
nucmer	ERROR	/Users/phanhung2/miniconda3/envs/bactopia/bin/nucmer
spades	ERROR	/Users/phanhung2/miniconda3/envs/bactopia/bin/spades.py

External dependencies OK: False

Python version:
3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 05:57:50)
[Clang 11.1.0 ]

Python packages:
ariba	2.14.6	/Users/phanhung2/miniconda3/envs/bactopia/lib/python3.7/site-packages/ariba/__init__.py
bs4	4.11.1	/Users/phanhung2/miniconda3/envs/bactopia/lib/python3.7/site-packages/bs4/__init__.py
dendropy	4.5.2	/Users/phanhung2/miniconda3/envs/bactopia/lib/python3.7/site-packages/dendropy/__init__.py
pyfastaq	3.17.0	/Users/phanhung2/miniconda3/envs/bactopia/lib/python3.7/site-packages/pyfastaq/__init__.py
pymummer	0.10.3	/Users/phanhung2/miniconda3/envs/bactopia/lib/python3.7/site-packages/pymummer/__init__.py
pysam	0.18.0	/Users/phanhung2/miniconda3/envs/bactopia/lib/python3.7/site-packages/pysam/__init__.py

Python packages OK: True

Everything looks OK: False
Some dependencies not satisfied. Cannot continue.`

**Comment by phanhung2** [comment]
Hello Robert,

Thank you for getting back to me. I have Perl installed on my MacBook, v5.30.3.

**Comment by rpetit3** [comment]
What's the output of `which perl`? 

I'm asking because `nucmer` has the perl path hard coded to `/usr/local/bin/perl`

**Comment by phanhung2** [comment]
`/usr/bin/perl`

**Comment by rpetit3** [comment]
Yep, that's going to be the issue. You can try:

```
sudo ln -s /usr/bin/perl /usr/local/bin/perl
```

Head's up I'm not sure how well things are going to work related to Biconda and the M1 chip.

**Comment by phanhung2** [comment]
Hello Robert,

I notice that Bioconda and M1 still have some compatibility issues as of this post: https://github.com/conda/conda/issues/11216

Thank you very much for helping me. Have a nice day.

**Comment by phanhung2** [comment]
Hello Robert,

After a while of trying, I decided to uninstall and reinstall again. But now, it is giving me this error after I ran this prompt:

`(bactopia) Hungs-MacBook-Pro:~ phanhung2$ conda install -c conda-forge -c bioconda bactopia
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - bactopia

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/osx-arm64/osx-64
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/r/osx-64

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.`

Could you help me with this? Thanks!

**Comment by phanhung2** [comment]
So I got it to work, but the output was 
`

**Comment by rpetit3** [comment]
Hi @phanhung2,

Apologies for the delay in responding. By chance do you have Docker or Singularity available to use?

Cheers,
Robert

**Comment by valery-shap** [comment]
Hello,

@phanhung2 have you solved the problem with 
`Solving environment: failed with initial frozen solve. Retrying with flexible solve.`
?
I had the same message on linux server when tried to install Bactopia.

Best regards,
Valery

**Comment by rpetit3** [comment]
Hi @valery-shap,

What does your `base` environment look like? Also, if you have docker or Singularity available on your Linux server, I would recommend those over conda.

Cheers,
Robert

**Comment by valery-shap** [comment]
Firstly, I've created empty env for Bactopia
`conda create -n bactopia`
then 
`conda activate bactopia `
`conda install -c bioconda bactopia`
error with frozen solve

conda info output:

     active environment : bactopia
    active env location : /home/vshapovalova/miniconda3/envs/bactopia
            shell level : 2
       user config file : /home/vshapovalova/.condarc
 populated config files : /home/vshapovalova/.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.8.3.final.0
       virtual packages : __linux=4.18.0=0
                          __glibc=2.28=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/vshapovalova/miniconda3  (writable)
      conda av data dir : /home/vshapovalova/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/vshapovalova/miniconda3/pkgs
                          /home/vshapovalova/.conda/pkgs
       envs directories : /home/vshapovalova/miniconda3/envs
                          /home/vshapovalova/.conda/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.23.0 CPython/3.8.3 Linux/4.18.0-193.el8.x86_64 centos/8.2.2004 glibc/2.28
                UID:GID : 1011:1011
             netrc file : None
           offline mode : False

**Comment by valery-shap** [comment]
```
channels:
  - conda-forge
  - bioconda
  - defaults
```

**Comment by rpetit3** [comment]
Hi @phanhung2 

I'm cleaning up old issues and since this is related to v2, I'm going to go ahead and close this with the recommendation to give v3 a try.

Please reach out if you have any questions or issues!

Cheers,
Robert
