### ISSUE TITLE
[bug] output in json format only

### ISSUE THREAD

**Issue by shlomobl** [bactopia/bactopia#336]
Hi,
After updating to the last version of Bactopia, most output files are in json format. For example, BLAST, MLST, AMR... no txt files, only json.
Any ideas what could be causing/how to solve this?
Thanks!

**Comment by rpetit3** [comment]
There was an issue with the Ariba recipe which forced me to removed it temporarily.

I've since fixed the recipe (https://github.com/bioconda/bioconda-recipes/pull/35383) and will look to adding it back. Although I might have to move to strictly a Bactopia Tool due to it no longer being maintained.

**Comment by rpetit3** [comment]
Hi @shlomobl 

I've released [v2.2.0](https://github.com/bactopia/bactopia/releases/tag/v2.2.0), there is now an alternate [mlst tool](https://bactopia.github.io/v2.2.0/bactopia-tools/mlst/) available. I'm going to go ahead and close this.

Cheers,
Robert
