### ISSUE TITLE
[bug] pipeline failing when supplied ONT reads

### ISSUE THREAD

**Issue by bernadettecy** [bactopia/bactopia#338]
**Description**
Attempting to pipeline ONT reads (using a single specified reference) 

but bactopia: QC_reads fails

executor >  local (27)
[cf/a28af4] process > BACTOPIA:GATHER_SAMPLES (E20544088)  [100%] 15 of 15 ✔
[19/30dba9] process > BACTOPIA:QC_READS (E20581978)        [ 35%] 7 of 20, failed: 5, retries: 5
[-        ] process > BACTOPIA:ASSEMBLE_GENOME             [  0%] 0 of 2
[-        ] process > BACTOPIA:ASSEMBLY_QC                 -
[-        ] process > BACTOPIA:ANNOTATE_GENOME             -
[-        ] process > BACTOPIA:MINMER_SKETCH               [  0%] 0 of 2
[-        ] process > BACTOPIA:ANTIMICROBIAL_RESISTANCE    -
[-        ] process > BACTOPIA:MINMER_QUERY                -
[-        ] process > BACTOPIA:BLAST                       -
[-        ] process > BACTOPIA:CALL_VARIANTS               -
[-        ] process > BACTOPIA:MAPPING_QUERY               -
[-        ] process > BACTOPIA:SEQUENCE_TYPE               -
[-        ] process > BACTOPIA:CUSTOM_DUMPSOFTWAREVERSIONS -

Can't find any error reports related to QC_reads on samples which have failed, but lines in the bactopia-trace.txt file look like this
16      9d/e48e8c       52124   BACTOPIA:QC_READS       E20766313       BACTOPIA:QC_READS (E20766313)   COMPLETED       0       -       -       4       1h      -       4 GB    1       2022-06-15 21:16:49.700 2022-06-15 22:05:58.890 49m 9s  49m 8s  -       351.1%  1.3%    2.6 GB  5.6 GB
17      7a/5e5ff0       61554   BACTOPIA:QC_READS       E20581978       BACTOPIA:QC_READS (E20581978)   FAILED  -       -       -       4       1h      -       4 GB    1       2022-06-15 21:18:45.316 2022-06-15 22:18:45.364 1h      1h      -       -       -       -       -

**Steps to Reproduce**
```
bactopia --samples ~/SCAP/NBICU_MRSA/ONT_MRSA_FOFN.txt --datasets /home/ndm.local/bernadette/datasets/ --disable_auto_variants TRUE --species 'Staphylococcus aureus'  --outdir /home/ndm.local/bernadette/SCAP/NBICU_MRSA/ONT_fastq_analysis -qs 12 --available_datasets

```

**Expected Behavior**
A description of what is expected to happen.

**Execution Environment**

- Bactopia Version: bactopia 2.1.0
- OS: Ubuntu 16.04.2 LTS
- Environment: conda
-
**Additional Information**
FOFN was prepared using bactopia prepare
Same samples have been passed through a local mapping pipeline and given expected outputs
Also tried to run a single sample with Illumina + ONT sequence reads for the same sample, and this failed on the assembly step (but using same reads was able to create hybrid assembly in unicycler)

**Comment by bernadettecy** [comment]
Thanks!
I've uploaded the FOFN
In the directory I ran bactopia I have folders for all the isolates, one called bactopia and one called work, but no log files (in the base directory) - the program aborted after lots of errors/re-tries, don't know if that affected log files?


[ONT_MRSA_FOFN.txt](https://github.com/bactopia/bactopia/files/8941775/ONT_MRSA_FOFN.txt)

**Comment by bernadettecy** [comment]
Actually they are fairly large - between 500MB and 1.2 GB. Thanks, will try the max time

**Comment by rpetit3** [comment]
Keep me posted on if `--max_time` works. Could also toss more cpus at it with `--max_cpus` 

I'll also see about finding a large ONT dataset to test on my end. If you know one on SRA/ENA, please feel free to share!

**Comment by bernadettecy** [comment]
This has solved it, thank you! Got some beautifully circularised assemblies.

**Comment by rpetit3** [comment]
Awesome! Glad you were able to get some good data! 

Don't hesitate to reach out if you run into any more issues or have any feedback (e.g. improvements, or tools to include)
