### ISSUE TITLE
[feature] Call variant without network accessing

### ISSUE THREAD

**Issue by alienzj** [bactopia/bactopia#340]
**Related To**

- [x] Bactopia
- [ ] Bactopia Tools

**Is this related to a problem?**
Every time I run bactopia on an HPC slurm system, when run to the **call variant** step, bactopia will prompt that the network is not accessible. 

**Is this something you would like to see added?**
Is there a way to use bactopia without internet, knowing what the species I'm studying is.
I have configured the conda environment with `bactopia download --build_all` in advance in an environment with a network.

**Describe the solution you'd like**
As we know which bacterial we are studying, so can we prepare genomes for it, and when run the pipeline, we don't need to prepare it again when network is not accesible.

**Additional Information**
Most of HPC have not accessible network at compute node.

**Comment by rpetit3** [comment]
Hi @alienzj 

Try running with `--disable_auto_variants`, this shod disable the minmer assisted reference selection.

Have you tried using singularity with your HPC? Also, if you are interested we can set up a config file similar to this one https://github.com/bactopia/bactopia/blob/master/conf/profiles/arcc.config for your SLURM cluster.

Cheers,
Robert
