### ISSUE TITLE
[question] Setting Up Latest AMRFinder+ Database failed... 

### ISSUE THREAD

**Issue by erin-thei** [bactopia/bactopia#343]
<img width="1438" alt="Screen Shot 2022-06-30 at 11 02 49 AM" src="https://user-images.githubusercontent.com/108017953/176711150-76b9c455-0100-424d-a94a-82a99aa50ce2.png">

Hi all,

I'm new to bioinformatics so not sure what to do here. Trying to run the command 'bactopia datasets' but got this issue. Can someone help explain this to me to understand it better and to also help me resolve it? 

Thanks so much!
Erin

**Comment by rpetit3** [comment]
Hi @erin-thei 

Let's see if we can get this figured out. Are you by chance running this on a cluster? I ask because the $PATH looks like some things are added before the bactopia env. 

I'm wondering if its pulling a different `makeblastdb`

Cheers,
Robert

**Comment by erin-thei** [comment]
Thanks for the quick reply! @rpetit3 

Yes, I am running this on a cluster. I do see what you're talking about in terms of the $PATH. Is there a way a change this? 

In addition to being new to bioinformatics, I am new to programming too (if it wasn't already obvious :-) ). Very much learning as I go so your help is greatly appreciated!

**Comment by rpetit3** [comment]
To solve the initial issue, this was run on the login node?

If so we'll need to update your path to put the conda env first. Mind posting the output of `echo $PATH` as text here?

**Comment by erin-thei** [comment]
Yes, this was run on the login node. Here's the output: 

(bactopia) [theillere@reslnvvhpc0135 marc_genomics]$ echo $PATH
/cm/local/apps/environment-modules/4.5.3/bin:/home/theillere/miniconda3/envs/bactopia/bin:/home/theillere/miniconda3/condabin:/home/theillere/.local/bin:/home/theillere/bin:/cm/shared/apps/slurm/current/sbin:/cm/shared/apps/slurm/current/bin:/cm/local/apps/environment-modules/4.5.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/sbin:/usr/sbin:/cm/local/apps/environment-modules/4.5.3/bin:/opt/puppetlabs/bin

**Comment by rpetit3** [comment]
Just to test if its the things early in the path you can try the following, then try rerunning `bactopia datasets`
```
export PATH=/home/theillere/miniconda3/envs/bactopia/bin:$PATH
```

This will only last while you are logged in, when you relog the changes will go away.

**Comment by erin-thei** [comment]
<img width="1440" alt="Screen Shot 2022-06-30 at 4 05 51 PM" src="https://user-images.githubusercontent.com/108017953/176768257-db67647c-b8c1-4db3-9039-ac2981472be2.png">

I tried that command, and then re-ran bactopia datasets, however I ran into the same problem. I ran the echo $PATH command again also. It seems like the $PATH in the error message differs than that from when I run echo $PATH... not sure if that matters. 

Any insight as to what I should try to do? 

Thanks as always!

**Comment by rpetit3** [comment]
I wonder if this is related to the tmp directory https://github.com/ncbi/amr/wiki/Running-AMRFinderPlus#temporary-files

Just as a test you could try
```
mkdir /home/theillere/test_tmp
export TMPDIR=/home/theillere/test_tmp
```

Then try rerunning `bactopia datasets`. Otherwise if all else fails you can run with `--skip_amr`

**Comment by erin-thei** [comment]
<img width="1244" alt="Screen Shot 2022-06-30 at 7 33 53 PM" src="https://user-images.githubusercontent.com/108017953/176795316-435394d5-001f-4c93-8647-d20538380d6c.png">

After running the above commands, and re-running bactopia datasets, still ran into that same error message. I was able to use --skip_amr.

Then I ran the following command:
<img width="1235" alt="Screen Shot 2022-06-30 at 7 39 50 PM" src="https://user-images.githubusercontent.com/108017953/176799737-a3821e4c-da0c-4065-b230-dcce894a82dc.png">

Which resulted in this message: 
<img width="1245" alt="Screen Shot 2022-06-30 at 8 29 56 PM" src="https://user-images.githubusercontent.com/108017953/176799773-40ffd95a-0180-4472-b238-70d432868dee.png">

Should I not be using --species "Staph aureus" when running the command since I didn't create a species-specific database? Just trying to understand what's meant by that error message... 

Thanks again!

**Comment by rpetit3** [comment]
Hmmm, the amrfinder issue is problematic, but we can fix it later! 

You are correct, if there is no species-specific database then leave the `--species` off.

**Comment by erin-thei** [comment]
Hmm seemed to have run into another error while trying to run the command bactopia --samples fastq.txts --datasets datasets/ --species "Staphylococcus aureus" --coverage 100 --genome_size median --outdir multiple-samples-test
<img width="868" alt="Screen Shot 2022-07-01 at 7 28 13 PM" src="https://user-images.githubusercontent.com/108017953/176977695-6da51cdf-8d8b-4a5e-a343-ae7cae54384e.png">

It look like it got to 3 of 6, but then got an error message, updated and installed a bunch of specs and then finally ended with this message: 
<img width="861" alt="Screen Shot 2022-07-01 at 7 31 39 PM" src="https://user-images.githubusercontent.com/108017953/176977764-f02aa729-ebc0-4295-a168-cc1b7d4f9d67.png">


<img width="868" alt="Screen Shot 2022-07-01 at 7 31 53 PM" src="https://user-images.githubusercontent.com/108017953/176977767-9797529a-63ad-4101-8944-4e42f2026ecb.png">

Would you know what this error message is saying?

Thanks!

**Comment by rpetit3** [comment]
@erin-thei  apologies! Thought I responded to this!

Looks like conda failed for some reason (maybe intermittent connection issue). Easiest thing to do is try again, otherwise I would consider using Docker or Singularity as they are a bit less error-prone.

Again, happy to help set a config for your cluster

**Comment by erin-thei** [comment]
No worries @rpetit3 ! 
I actually was able to get it working. I had some conflicts involving conda so un-installing/re-installing conda resolved those, enabling it to successfully run. I also got the config file from one of the senior bioinformaticians who works on the cluster, so I'm all set there. Thanks again for your responsiveness and help!

**Comment by rpetit3** [comment]
Awesome! I'm going to go ahead and close this. 

Please feel free to reach out if you have questions, issues, or feedback!
