### ISSUE TITLE
[question] SPAdes version in Bactopia v2.1.1.

### ISSUE THREAD

**Issue by ingridvanw** [bactopia/bactopia#346]
Hi @rpetit3,

After updating to the last version of Bactopia (v2.1.1) we noticed that SPAdes version is v3.13.0 (spades.py --version).
In an earlier version of Bactopia (2.0.3) the version of SPAdes is v3.15.3.
Can you confirm the downgrade of SPAdes. Can you explain why this is done?

Thanks!

Cheers,
Ingrid

**Comment by ingridvanw** [comment]
Thank you for your answer!

**Comment by rpetit3** [comment]
No problem, I'm going to go ahead and close this. Feel free to reopen or reach out if you have more questions or feedback
