### ISSUE TITLE
[feature] Add option --nanohq in assembly when using bactopia with ONT reads

### ISSUE THREAD

**Issue by llk578496** [bactopia/bactopia#347]
Hi @rpetit3 

**Is this something you would like to see added?**
It will be great to have the option `--nanohq` when performing de novo assembly in `bactopia`, just like you did in `dragonflye`! 

Thank you very much!

Eddie

**Comment by rpetit3** [comment]
Sure thing, I'll get a dev build with this option soon

**Comment by llk578496** [comment]
Thank you very much!

**Comment by rpetit3** [comment]
OK I think I got this in the dev build. I added a parameter `--dragonflye_opts` that should allow you to do this:

 `--dragonflye_opts "--nanohq"`

```
mamba create -n bactopia-dev -c rpetit3 -c conda-forge -c bioconda bactopia
mamba activate bactopia-dev
```

**Comment by rpetit3** [comment]
Hi @llk578496 

I've released [v2.2.0](https://github.com/bactopia/bactopia/releases/tag/v2.2.0), which includes `--dragonflye_opts`. I'm going to go ahead and close this.

Cheers,
Robert

**Comment by llk578496** [comment]
Hi @rpetit3 

Thank you so much for adding the `--dragonflye_opts`!

We just tried to use it with the command below:
`bactopia --ont --SE /mnt/data2/Food/REAL/02_fastq/Batch041_C_02_NS_XLDTT_01_Sub_01_Sub.fastq.gz --sample Batch041_C_02_NS_XLDTT_01_Sub_01_Sub --datasets /mnt/data2/Food/REAL/datasets --outdir /mnt/data2/Food/REAL/04_bactopia/04.1_tmp/Batch041_C_02_NS_XLDTT_01_Sub_01_Sub -profile docker --max_cpus 10 --max_memory 110 --max_time 360 --dragonflye_opts "--nanohq" --medaka_model r941_min_sup_g507 --genome_size 5000000 --min_coverage 25 --medaka_steps 1 --cleanup_workdir`

but we got the following warning:
> (bactopia) gilmansiu3@gilmansiu3-Z490-AORUS-ULTRA:/mnt/data2/Food/REAL$ bactopia --ont --SE /mnt/data2/Food/REAL/02_fastq/Batch041_C_02_NS_XLDTT_01_Sub_01_Sub.fastq.gz --sample Batch041_C_02_NS_XLDTT_01_Sub_01_Sub --datasets /mnt/data2/Food/REAL/datasets --outdir /mnt/data2/Food/REAL/04_bactopia/04.1_tmp/Batch041_C_02_NS_XLDTT_01_Sub_01_Sub -profile docker --max_cpus 10 --max_memory 110 --max_time 360 --dragonflye_opts "--nanohq" --medaka_model r941_min_sup_g507 --genome_size 5000000 --min_coverage 25 --medaka_steps 1 --cleanup_workdir
> 2022-11-29 18:42:56:root:INFO - Checking if environment pre-builds are needed, use --verbose to see full details.
> N E X T F L O W  ~  version 22.10.1
> Launching `/home/gilmansiu3/miniconda3/envs/bactopia/share/bactopia-2.2.x/main.nf` [sick_lichterman] DSL2 - revision: 145bb11899
> 
> WARN: Found unexpected parameters:
> * --nanohq: true
> - Ignore this warning: params.schema_ignore_params = "nanohq" 
> 
> 
> 
> ---------------------------------------------
>    _                _              _             
>   | |__   __ _  ___| |_ ___  _ __ (_) __ _       
>   | '_ \ / _` |/ __| __/ _ \| '_ \| |/ _` |   
>   | |_) | (_| | (__| || (_) | |_) | | (_| |      
>   |_.__/ \__,_|\___|\__\___/| .__/|_|\__,_| 
>                             |_|                  
>   bactopia v2.2.0
>   Bactopia is a flexible pipeline for complete analysis of bacterial genomes. 
> ---------------------------------------------
> Core Nextflow options
>   runName          : sick_lichterman
>   containerEngine  : docker
>   container        : quay.io/bactopia/bactopia:2.2.0
>   launchDir        : /mnt/data2/Food/REAL
>   workDir          : /mnt/data2/Food/REAL/work
>   projectDir       : /home/gilmansiu3/miniconda3/envs/bactopia/share/bactopia-2.2.x
>   userName         : gilmansiu3
>   profile          : docker
>   configFiles      : /home/gilmansiu3/miniconda3/envs/bactopia/share/bactopia-2.2.x/nextflow.config
> 
> Required Parameters
>   SE               : /mnt/data2/Food/REAL/02_fastq/Batch041_C_02_NS_XLDTT_01_Sub_01_Sub.fastq.gz
>   ont              : true
>   sample           : Batch041_C_02_NS_XLDTT_01_Sub_01_Sub
> 
> Dataset Parameters
>   datasets         : /mnt/data2/Food/REAL/datasets
>   genome_size      : 5000000
> 
> Gather Samples Parameters
>   min_coverage     : 25
> 
> Assemble Genome Parameters
>   dragonflye_opts  : true
>   medaka_model     : r941_min_sup_g507
>   medaka_steps     : 1
> 
> Optional Parameters
>   outdir           : /mnt/data2/Food/REAL/04_bactopia/04.1_tmp/Batch041_C_02_NS_XLDTT_01_Sub_01_Sub
> 
> Max Job Request Parameters
>   max_cpus         : 10
>   max_memory       : 110
>   max_time         : 360
> 
> Nextflow Configuration Parameters
>   cleanup_workdir  : true
> 
> Nextflow Profile Parameters
>   condadir         : /home/gilmansiu3/miniconda3/envs/bactopia/share/bactopia-2.2.x/conda/envs
>   registry         : quay
>   singularity_cache: /home/gilmansiu3/.bactopia/singularity
> 
> !! Only displaying parameters that differ from the pipeline defaults !!
> --------------------------------------------------------------------
> If you use bactopia for your analysis please cite:
> 
> * Bactopia
>   https://doi.org/10.1128/mSystems.00190-20
> 
> * The nf-core framework
>   https://doi.org/10.1038/s41587-020-0439-x
> 
> * Software dependencies
>   https://bactopia.github.io/acknowledgements/
> --------------------------------------------------------------------
> 
> Each task will use 10 CPUs out of the available 20 CPUs. At most 
> 2 task(s) will be run at a time, this can affect the efficiency 
> of Bactopia. You can use the '-qs' parameter to alter the number of 
> tasks to run at a time (e.g. '-qs 2', means only 2 tasks or a maximum 
> of 20 CPUs will be used at once)
> 
> 
> Found 1 Antimicrobial resistance datasets
> 	/mnt/data2/Food/REAL/datasets/antimicrobial-resistance/amrfinderdb.tar.gz
> Found 3 ARIBA datasets
> 	/mnt/data2/Food/REAL/datasets/ariba/card.tar.gz
> 	/mnt/data2/Food/REAL/datasets/ariba/resfinder.tar.gz
> 	/mnt/data2/Food/REAL/datasets/ariba/vfdb_core.tar.gz
> Found 4 minmer sketches/signatures
> 	/mnt/data2/Food/REAL/datasets/minmer/mash-refseq-k21.msh
> 	/mnt/data2/Food/REAL/datasets/minmer/sourmash-genbank-k21.json.gz
> 	/mnt/data2/Food/REAL/datasets/minmer/sourmash-genbank-k31.json.gz
> 	/mnt/data2/Food/REAL/datasets/minmer/sourmash-genbank-k51.json.gz
> --species not given, skipping the following processes (analyses):
> 	blast (genes, proteins, primers)
> 	call_variants
> 	mapping_query
> 	sequence_type
> Will use 5000000 bp for genome size
> 
> If something looks wrong, now's your chance to back out (CTRL+C 3 times). 
> Sleeping for 5 seconds...
> --------------------------------------------------------------------
> executor >  local (12)
> [01/ca0fc0] process > BACTOPIA:GATHER_SAMPLES (Batch041_C_02_NS_XLDTT_01_Sub_01_Sub)                      [100%] 1 of 1 ✔
> executor >  local (12)
> [01/ca0fc0] process > BACTOPIA:GATHER_SAMPLES (Batch041_C_02_NS_XLDTT_01_Sub_01_Sub)                      [100%] 1 of 1 ✔
> [2b/cc8253] process > BACTOPIA:QC_READS (Batch041_C_02_NS_XLDTT_01_Sub_01_Sub)                            [100%] 1 of 1 ✔
> [11/9f2bbb] process > BACTOPIA:ASSEMBLE_GENOME (Batch041_C_02_NS_XLDTT_01_Sub_01_Sub)                     [100%] 1 of 1 ✔
> [3f/9f1c0c] process > BACTOPIA:ASSEMBLY_QC (Batch041_C_02_NS_XLDTT_01_Sub_01_Sub)                         [100%] 1 of 1 ✔
> [9d/a6e11b] process > BACTOPIA:ANNOTATE_GENOME (Batch041_C_02_NS_XLDTT_01_Sub_01_Sub)                     [100%] 1 of 1 ✔
> [b0/569e6a] process > BACTOPIA:MINMER_SKETCH (Batch041_C_02_NS_XLDTT_01_Sub_01_Sub)                       [100%] 1 of 1 ✔
> [ab/e2357e] process > BACTOPIA:ANTIMICROBIAL_RESISTANCE (Batch041_C_02_NS_XLDTT_01_Sub_01_Sub)            [100%] 1 of 1 ✔
> [8e/9a3c22] process > BACTOPIA:MINMER_QUERY (Batch041_C_02_NS_XLDTT_01_Sub_01_Sub - sourmash-genbank-k51) [100%] 4 of 4 ✔
> [-        ] process > BACTOPIA:BLAST                                                                      -
> [-        ] process > BACTOPIA:CALL_VARIANTS                                                              -
> [-        ] process > BACTOPIA:MAPPING_QUERY                                                              -
> [-        ] process > BACTOPIA:SEQUENCE_TYPE                                                              -
> [07/3a7ec9] process > BACTOPIA:CUSTOM_DUMPSOFTWAREVERSIONS (1)                                            [100%] 1 of 1 ✔
> 
>     Bactopia Execution Summary
>     ---------------------------
>     Bactopia Version : 2.2.0
>     Nextflow Version : 22.10.1
>     Command Line     : nextflow run /home/gilmansiu3/miniconda3/envs/bactopia//share/bactopia-2.2.x/main.nf -w /mnt/data2/Food/REAL/work/ --ont --SE /mnt/data2/Food/REAL/02_fastq/Batch041_C_02_NS_XLDTT_01_Sub_01_Sub.fastq.gz --sample Batch041_C_02_NS_XLDTT_01_Sub_01_Sub --datasets /mnt/data2/Food/REAL/datasets --outdir /mnt/data2/Food/REAL/04_bactopia/04.1_tmp/Batch041_C_02_NS_XLDTT_01_Sub_01_Sub -profile docker --max_cpus 10 --max_memory 110 --max_time 360 --dragonflye_opts --nanohq --medaka_model r941_min_sup_g507 --genome_size 5000000 --min_coverage 25 --medaka_steps 1 --cleanup_workdir
>     Resumed          : false
>     Completed At     : 2022-11-29T18:52:55.115582882+08:00
>     Duration         : 9m 45s
>     Success          : true
>     Exit Code        : 0
>     Error Report     : -
>     Launch Dir       : /mnt/data2/Food/REAL
>     
> Completed at: 29-Nov-2022 18:52:55
> Duration    : 9m 45s
> CPU hours   : 1.8
> Succeeded   : 12
> 
> 
> Bactopia finished successfully! Found '--cleanup_workdir' removing '/mnt/data2/Food/REAL/work/'

**Comment by rpetit3** [comment]
Try this with an equals. I wonder if Nextflow is trying to interpret nanohq as a separate parameter

```
--dragonflye_opts="--nanohq"
```

**Comment by llk578496** [comment]
It works! 
Thank you so much for your help!
