### ISSUE TITLE
[bactopia-tool]  Panaroo

### ISSUE THREAD

**Issue by themudo** [bactopia/bactopia#348]
In order for a tool to be added to [Bactopia Tools](https://bactopia.github.io//bactopia-tools/#available-bactopia-tools), it must be available on  [Bioconda](https://bioconda.github.io/) and [nf-core/modules](https://github.com/nf-core/modules). __But!!__ Don't let that stop you from suggesting a tool! Time permitting and depending on the feasibility I can help you get a tool on Bioconda and/or nf-core/modules.

_So! Suggest away!_

Tool Name: Panaroo

Tool Link: https://github.com/gtonkinhill/panaroo

Available on [Bioconda](https://bioconda.github.io/)? Yes

Available on [nf-core/modules](https://github.com/nf-core/modules)?No

**Comment by rpetit3** [comment]
Hi @themudo 

Panaroo is available as of v2.1.1. In the workflow `--wf panagenome` you will want to use `--use_panaroo`. More details here: https://bactopia.github.io/bactopia-tools/pangenome/#panaroo-parameters

Let me know if you have questions and feedback.

Cheers,
Robert

**Comment by themudo** [comment]
Thank you! Don't know how I missed that.

Cheers,
Gonçalo

**Comment by rpetit3** [comment]
No worries! Very curious how it goes for you.

**Comment by rpetit3** [comment]
Hi @themudo,

I've released [v2.2.0](https://github.com/bactopia/bactopia/releases/tag/v2.2.0), going to go ahead and close this.

Cheers,
Robert
