### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by sekhwal** [bactopia/bactopia#349]
I am trying bactopia with only one sample but it is taking so long (around 2-3 hours) and still running. Is there any error in the command?

bactopia --R1 bactopia_fastqs/1-Ent_R1.fastq.gz --R2 bactopia_fastqs/1-Ent_R2.fastq.gz --sample 1-N2122099 --datasets datasets/ --outdir bactopia_output/

**Comment by rpetit3** [comment]
Looks fine, how big are the fastqs?

**Comment by sekhwal** [comment]
R1 is 55.4 MB and R2 is 56.6 MB.

**Comment by rpetit3** [comment]
oh definitely should take that long!

Did the pipeline actually start, or is it still building conda environments?

**Comment by sekhwal** [comment]
It runs and stops here,

2022-07-22 13:31:19:root:INFO - Checking if environment pre-builds are needed, use --verbose to see full details.
2022-07-22 13:31:19:root:INFO - Found /home/anaconda3/envs/bactopia/share/bactopia-2.1.x/conda/linux/gather_samples.yml (5 of 6), begin build to /home/anaconda3/envs/bactopia/share/bactopia-2.1.x/conda/envs/gather_samples-2.1.x

**Comment by rpetit3** [comment]
Do you by chance have access to Docker or Singularity on this system?

**Comment by sekhwal** [comment]
It seems, it extended the process with the following warnings.

Software dependencies
  https://bactopia.github.io/acknowledgements/
--------------------------------------------------------------------
WARN: 
WARN: Conda Disclaimer
WARN: 
WARN: If you have access to Docker or Singularity, please consider
WARN: running Bactopia using containers. The containers are less
WARN: susceptible to Conda environment related issues (e.g. version
WARN: conflicts) and errors caused by creation of conda environments
WARN: in parallel (use '--max_cpus 1' to over come this error).
WARN: 
WARN: To use containers, you can use the profile parameter
WARN:     Docker: -profile docker
WARN:     Singularity: -profile singularity
WARN:

**Comment by sekhwal** [comment]
Do I need to install docker in this environment? I think I have docker in the system.

**Comment by rpetit3** [comment]
We can find out real quick by adding a `-profile docker` to the end of your command

```
bactopia --R1 bactopia_fastqs/1-Ent_R1.fastq.gz --R2 bactopia_fastqs/1-Ent_R2.fastq.gz --sample 1-N2122099 --datasets datasets/ --outdir bactopia_output/ -profile docker
```

**Comment by sekhwal** [comment]
The pipeline is done with --max_cpus 40. I used without the -profile docker since it was showing an error. Can you please suggest which output files I should use to make a phylogenetic tree as similar as it is indicated in the paper "Bactopia: a Flexible Pipeline for Complete Analysis of Bacterial Genomes".

**Comment by rpetit3** [comment]
You can use the `pangenome` Bactopia Tool to generate a tree from your samples. Here's more details: https://bactopia.github.io/bactopia-tools/pangenome/

Also, the `--max_cpus` is likely going to slow things down. If you are trying to limit the pipeline to only use 40 cpus total, you'll want to use `-qs 40`. More details about `--max_cpus` vs `-qs` is available here: https://bactopia.github.io/usage-basic/#-max_cpus

**Comment by sekhwal** [comment]
I ran the pipeline with the following command. It seems not generating the output files. I suppose --include "file name" contains input multiple files?

bactopia --wf pangenome --bactopia bactopia_output/ --include fastqs.txt

fastqs.txt
sample	runtype	r1	r2	extra
N2122099	paired-end	/bactopia_fastqs/N2122099_R1.fastq.gz	/bactopia_fastqs/N2122099_R2.fastq.gz	
N2122225	paired-end	/bactopia_fastqs/N2122225_R1.fastq.gz	/bactopia_fastqs/N2122225_R2.fastq.gz

**Comment by sekhwal** [comment]
Also, it is showing an warning at the end.

WARN: The operator `first` is useless when applied to a value channel which returns a single value by definition

**Comment by rpetit3** [comment]
You are going to need more samples for the `pangenome` tool. 

You can ignore the `first` warning, it happens with only one sample

**Comment by sekhwal** [comment]
Hi, 
I noticed that in the datasets, it contains only "antimicrobial-resistance",  "minmer" but not CARD, VFDB etc. I used the command  "bactopia datasets" to make the dataset.
I am using the following command for the 245 samples, the pipeline still running for so long.

bactopia --wf pangenome --bactopia bactopia_output --include includes.txt

**Comment by rpetit3** [comment]
If you want to use CARD/VFDB you'll want to use the Ariba Bactopia Tool (`--wf ariba`) I had to remove ariba from the main bactopia workflow (including datasets) at v2.1.0

The pangenome step is likely to take a while. You might be able to speed it up with `--max_cpus`

**Comment by sekhwal** [comment]
Sounds good. Can you please let me know how to add more features on the tree such as ANI, Genus, Taxon etc?
It seems, pipeline generates a directory "work" and is storing the results of pangenome analysis.

**Comment by rpetit3** [comment]
I usually us something like iTOL (https://itol.embl.de/) to annotate the tree. 

The `work` directory is used by Nextflow to run things in isolated directories. On successfully pipeline completion you can delete the `work` directory.

**Comment by sekhwal** [comment]
It is running with the following steps for more than 48 hours..

executor >  local (7)
[-        ] process > BACTOPIATOOLS:PROKKA:PROKKA_MODULE                         -
[bf/4f5956] process > BACTOPIATOOLS:PANGENOME:PG_TOOL:PIRATE_MODULE (pirate)     [100%] 1 of 1 ✔
[ef/c68f05] process > BACTOPIATOOLS:PANGENOME:SNPDISTS (pirate)                  [100%] 1 of 1 ✔
[5b/207621] process > BACTOPIATOOLS:PANGENOME:CLONALFRAMEML:IQTREE (start-tree)  [100%] 1 of 1 ✔
[68/7e6b6d] process > BACTOPIATOOLS:PANGENOME:CLONALFRAMEML:CLONALFRAME (pirate) [ 75%] 3 of 4, failed: 3, retries: 3
[-        ] process > BACTOPIATOOLS:PANGENOME:FINAL_TREE:IQTREE_MODULE           -
[-        ] process > BACTOPIATOOLS:CUSTOM_DUMPSOFTWAREVERSIONS                  -
[f8/33dbfb] NOTE: Process `BACTOPIATOOLS:PANGENOME:CLONALFRAMEML:CLONALFRAME (pirate)` failed -- Execution is retried (3)

**Comment by sekhwal** [comment]
work directory has many folders, please let me know where I can find the tree file and its annotation files such as ANI, Genus, Taxon.
Thanks!

**Comment by rpetit3** [comment]
You might need to increase `--max_time` or rerun with `--skip_recombination -resume`

Once completed the output files are described here: https://bactopia.github.io/bactopia-tools/pangenome/#output-overview

**Comment by sekhwal** [comment]
Yes, I terminated the pipeline and re-ran with the --force, it is running again. Mostly, it takes time at "pirate" step.  

bactopia --wf pangenome --bactopia bactopia_output --include includes.txt --max_cpus 50 --max_time 200 --skip_recombination

**Comment by rpetit3** [comment]
Sounds good, next time instead of `--force` try `-resume` so it won't start over

**Comment by sekhwal** [comment]
It seems, the pipeline is done and I have results in pangenome folder. Can you please let me know how to annotate the tree such as ANI, Genus, Taxon. Do I need to run any other tools at bactopia?

**Comment by rpetit3** [comment]
I usually us something like iTOL (https://itol.embl.de/) to annotate the tree. 

A description of output files are available here: https://bactopia.github.io/bactopia-tools/pangenome/#output-overview

**Comment by sekhwal** [comment]
Thank you for your help. I am using iTOL. I generated the tree using iTOL and added some meta data of my datasets. I am looking to add Genus, Taxon information also.
In addition, is there any tool at bactopia to add population clustering?

**Comment by sekhwal** [comment]
Can you please tell me the tool name to add Genus and taxon on the tree?

**Comment by rpetit3** [comment]
For kraken you will also need to provide a kraken database.

For taxonomic classification, you can try the GTDB bactopia tool, but I'll warn you it requires a large input database and ~60GB of memory

**Comment by sekhwal** [comment]
Do I need to download kraken database separately or through bactopia? I have enough memory in my system, it has 120 GB.

**Comment by rpetit3** [comment]
Here's a link to download pre-build databases: https://benlangmead.github.io/aws-indexes/k2

**Comment by sekhwal** [comment]
Hi,
I have one more question. I am trying to run bactopia at 40 samples (R1 and R2) with 10 references genomes (.fasta) files. I am wondering if I can add these fasta files in the folder with input files (R1 and R2) and run following command. Please let me know if I can run the pipeline with more than one references.

bactopia --samples fastqs.txt --datasets datasets --outdir OUTDIR

**Comment by rpetit3** [comment]
This is possible with the `bactopia prepare` command. You will need to compress your assemblies then play around with the `--assembly_pattern` parameter.

More details here: https://bactopia.github.io/usage-basic/#generating-a-fofn

**Comment by rpetit3** [comment]
Hi @sekhwal 

I'm going to go ahead and close this issue, please feel free to reopen.

Cheers,
Robert
