### ISSUE TITLE
Installing bactopia

### ISSUE THREAD

**Issue by tbazilegith** [bactopia/bactopia#351]
Hello Robert,
In installing bactopia, is there any step that precedes the databases downloading?
Actually, after 
conda activate bactopia
---?
bactopia datasets (isn't moving any further)

Thanks!
TJ

**Comment by rpetit3** [comment]
Hi TJ,

Can you verify you get output with `bactopia --version`?

Cheers,
Robert

**Comment by tbazilegith** [comment]
Hey Robert,
bactopia --version
bactopia 2.1.1
It has worked then! Prior to running bactopia datasets, I ran this
 conda install -c conda-forge -c bioconda bactopia
Thanks!

**Comment by rpetit3** [comment]
Any output from `bactopia datasets --help`?

**Comment by tbazilegith** [comment]
Here is a piece of the output
usage: bactopia datasets [-h] [--outdir STR] [--species STR] [--skip_mlst]
My database directory's contents:
antimicrobial-resistance minmer  summary.json
Thanks

**Comment by rpetit3** [comment]
Looks like the `bactopia datasets` command ran fine

**Comment by tbazilegith** [comment]
Hello Robert,
I reinstalled bactobia, 
bactopia --version gave
bactopia 2.2.0
However the help gave
bactopia -h
bactopia download [-h] [--envtype STR] [--wf STR] [--use_defaults] [--build_all] [--build_nfcore] [--registry STR] .....
Couldn't process any sample
bactopia --sample brucey_v2 --assembly brucey_v2.fa.gz --datasets datasets
I got this
Could not solve for environment specs
Encountered problems while solving:
  - package libdeflate-1.14-h166bdaf_0 is excluded by strict repo priority
  - package perl-algorithm-diff-1.201-pl5321hd8ed1ab_0 is excluded by strict repo priority
  - package perl-carp-1.50-pl5321hd8ed1ab_0 is excluded by strict repo priority
  - package perl-compress-raw-zlib-2.202-pl5321h166bdaf_0 is excluded by strict repo priority
Any thoughts?
Thanks!
TJ

**Comment by rpetit3** [comment]
Hi TJ,

Is this in a fresh environment? Also how does your `base` environment look?

Haha final question, by chance is docker or singularity an option?

**Comment by tbazilegith** [comment]
Yeah it's a fresh environment. Do you refer to this one
user/conda/envs/bactopia/
bin  cmake  compiler_compat  condabin  conda-meta  etc  fonts  include  lib  libexec  man  pkgs  sbin  share  shell  ssl  var  x86_64-conda_cos6-linux-gnu  x86_64-conda-linux-gnu
Thanks

**Comment by tbazilegith** [comment]
Error executing process > 'BACTOPIA:GATHER_SAMPLES (brucey_v2)'

Caused by:
  Conda prefix path does not exist or is not a directory: /color/user/conda/envs/bactopia/share/bactopia-2.2.x/conda/envs/gather_samples-2.2.x

**Comment by rpetit3** [comment]
Are you running on a cluster or single server? I think we should explore the Singularity route

**Comment by tbazilegith** [comment]
- I am on server
- As I explored singularity I got this
bactopia_latest.sif
How does it look? 
I also got this while downdloading the image
INFO:    Downloading library image
970.4MiB / 970.4MiB [==============================================================================================================] 100 % 53.4 MiB/s 0s
WARNING: integrity: signature not found for object group 1
WARNING: Skipping container verification

**Comment by tbazilegith** [comment]
Robert,
Assuming the image is ok. Is there any steps before running bactopia?
Thanks

**Comment by rpetit3** [comment]
Haha this might be confusing. We're still going to use Conda, but just for Bactopia, and Nextflow will use Singularity, by adding `-profile singularity` to the command

So something like this:
```
conda activate bactopia
bactopia datasets ...
bactopia ...<options>... -profile singularity
```

A good test would be this command:
```
bactopia -profile test,singularity
```

This is run bactopia with a small test dataset using Singularity

**Comment by tbazilegith** [comment]
Thanks, Robert!
It worked
TJ

**Comment by rpetit3** [comment]
Hi @tbazilegith 

I'm cleaning up old issues and since this is related to v2, I'm going to go ahead and close this. Although it looks like we resolved it, but I'll recommend to give v3 a try.

Please reach out if you have any questions or issues!

Cheers,
Robert
