### ISSUE TITLE
[question] How to set up a copy of Bactopia for development

### ISSUE THREAD

**Issue by zachary-foster** [bactopia/bactopia#353]
Our lab is looking to adapt Bactopia for automated pathogen DNA analysis for our University's plant clinic. As part of this, we would like to use the variant caller graphtyper. Since it does not appear to be in Bactopia or nf-core, we thought we should write a module to run it and then modify the appropriate workflow to make it available as one of the options for variant callers, alongside things like snippy.

We are having trouble setting up a clone of this repository that we can edit and running Bactopia from it rather than from a conda/docker installation. We tried using the conda environment to install the required dependencies (in hopes of avoiding installing each dependency manually) and changing the $PATH to point to the git repo clone of bactopia instead of the executable installed by conda, but we are running into path-related errors and I am thinking there must be a better way.

Do you have any suggestions for how to set up and run a version of bactopia optimized for development?  Such a description might be helpful to put in the documentation if it isn't already. Its possible we might be missing some fundamental concepts regarding nextflow/conda development and that might be the root of the problem, but we do have a basic understanding of those tools. If we are missing something basic, could you just point us in the right direction (i.e. what to type into Google to find tutorials/info)? 

If we can get a graphtyper module to work, we would be happy to submit a PR to have added to Bactopia if you are interested.

Thanks for developing such a useful set of tools! 

@phanhung2 @grunwald

**Comment by rpetit3** [comment]
Hi @zachary-foster @phanhung2 @grunwald

Very cool! Happy to help where I can help! Here's my process for working with the dev. It basically boils down to not using the wrappers I've created and executing things directly.

1. Install and activate dev build
    - `mamba create -n bactopia-dev -c rpetit3 -c conda-forge -c bioconda bactopia`
    - I maintain a dev build on my personal conda channel (reason for the `-c rpetit3`)
    - This at least gets us the dependencies 
2. Ignore all `bactopia` subcommands and point directly to the scripts
    - e.g. `bactopia prepare` --> `/PATH/TO/BACTOPIA_REPO/bin/bactopia/bactopia-prepare.py`
3. Ignore `bactopia` command and use `nextflow run`
    - e.g. `bactopia --samples fofn.txt` --> `nextflow run /PATH/TO/BACTOPIA_REPO/main.nf --wf bactopia --samples fofn.txt`
    
I think this should get you started, let me know if not!
    
### Inclusion of `graphtyper`

We can totally do this. I noticed it was available on Bioconda which is the hardest part. The next step would be to add it to [nf-core/modules](https://github.com/nf-core/modules/). 

Would you like to work on getting this added to nf-core/modules, or want me to take a crack at it? Once its on nf-core/modules we're basically all set to use it in Bactopia.


Super excited to see how you manipulate Bactopia to meet your needs! Please don't hesitate to reach out and let me know if I can help anyway. Also please feel free to contact me through email!

Cheers,
Robert

**Comment by zachary-foster** [comment]
Thanks for your quick and helpful reply! 

> It basically boils down to not using the wrappers I've created and executing things directly.

We will give that a try, thanks!

> Would you like to work on getting this added to nf-core/modules, or want me to take a crack at it? 

That would be great if its not too much trouble for you. We also have no problem doing this, since we will want to learn how to do it anyway. So, if you have the time and inclination to add graphtyper to nf-core we would be grateful, but we are happy to do it as well and let you know if we run into problems.

> Super excited to see how you manipulate Bactopia to meet your needs! Please don't hesitate to reach out and let me know if I can help anyway. Also please feel free to contact me through email!

Thanks! I really appreciate you willingness to help. We will be in contact via email for any questions specific to our project and use Github issues for any problems that might be relevant to other users.

**Comment by rpetit3** [comment]
Hi @zachary-foster 

Time flies, and it looks like ya'll went the route of https://github.com/nf-core/pathogensurveillance

I'm going to go ahead and close this issue, good luck with `pathogensurveillance`!

Cheers,
Robert
