### ISSUE TITLE
Bactopia tool summary and Kraken2

### ISSUE THREAD

**Issue by Clr27** [bactopia/bactopia#354]
Hello, I am a bioinformatics novice and completely new to bactopia.  I have found all the guidance and tutorials super helpful. I can run BaP and most tools, but having trouble with the summary tool and Kraken2.  Are these two tools still available and if yes do you have any advice on how to get them to work? Best.

**Comment by rpetit3** [comment]
Apologies for the slow response! The summary tool is available from my dev branch, let me know if you would like details on how to make use of it.

Kraken2 is still available and details are available here: https://bactopia.github.io/bactopia-tools/kraken2/

Let me know how this works for you. I think I might need to update the docs some, would be very interested to get your feedback!

**Comment by Clr27** [comment]
Thanks for getting back to me. I have found the documentation clear and the tutorials particularly useful. We plan to use bactopia for routine sequencing analysis so the next step will be setting up easy extraction of the data, so the summary tool could be useful and I would be interested to try it via dev branch. For Kraken2, daft question, do you need to specify database location?  Best

**Comment by Clr27** [comment]
Thanks for getting back to me. I have found the documentation clear and the tutorials particularly useful. We plan to use bactopia for routine sequencing analysis so the next step will be setting up easy extraction of the data, therefore the summary tool could be useful and I would be interested to try it via dev branch. For Kraken2, daft question, do you need to specify database location?  Best

**Comment by rpetit3** [comment]
Saw this an forgot to respond.

Yes you will need to specify the path to your kraken2 database

**Comment by Clr27** [comment]
Hello again, I have tried setting up the summary tool from your dev branch using the commands you gave in #318. I can activate bactopia-dev and also obtain help using  'bactopia tools summary --help'; however, I am failing to get the tool to work and keep getting -Process 'summary' terminated with an error exit status (1).  Is there an obvious fix for this I am missing? Best

**Comment by Clr27** [comment]
Hi, bactopia-summary comes back with command not found.

**Comment by rpetit3** [comment]
hmmm, what does `conda env export | grep bactopia` look like?

**Comment by Clr27** [comment]
name: bactopia-dev
  - bactopia=1.4.0=0
prefix: /home/wgs/miniconda3/envs/bactopia-dev

**Comment by rpetit3** [comment]
Oh wow, that installed an old version of bactopia.

maybe lets try forcing it to the latest
```
mamba create -n bactopia-dev -c rpetit3 -c conda-forge -c bioconda 'rpetit3::bactopia>=2.1.1'
```

**Comment by Clr27** [comment]
That worked!!!! Thank you!

**Comment by Clr27** [comment]
Will do, if I think of anything. Currently happy this version is now working. Thanks again.

**Comment by Clr27** [comment]
Sorry me again.  Just to let you know that I ran some Strep pneumos through and all worked well except the seroba.tsv file only contains a single serotype (ran 75). I can get the serotypes from the individual folders, but thought worth letting you know.

**Comment by rpetit3** [comment]
Thank you so much for bringing this to my attention. I'll look into and hopefully update soon!

**Comment by rpetit3** [comment]
Hi @Clr27 

I'm cleaning up old issues and since this is related to v2, I'm going to go ahead and close this with the recommendation to give v3 a try.

In v3, I added merged reports for tools similar to seroba that produce CSV/TSV files.

Please reach out if you have any questions or issues!

Cheers,
Robert

**Comment by Clr27** [comment]
Hi @rpetit3, great thank you.  I am already using v3.  Best wishes.

**Comment by rpetit3** [comment]
Great glad to hear! If you have some time and you don't mind filling our a servey, I could use some feedback! Here's the link: https://forms.gle/BA2BDHRQvZtpVcD38
