### ISSUE TITLE
Conda create argument runs for hours

### ISSUE THREAD

**Issue by mbyott** [bactopia/bactopia#357]
Hi, 

`conda create -n bactopia -c conda-forge -c bioconda bactopia`

runs for hours and hours, tried it on 2 different computers.

However the mamba version works in a few minutes:

`mamba create -y -n bactopia -c conda-forge -c bioconda bactopia`

**Comment by rpetit3** [comment]
Thanks for bringing this to my attention! I'm in the process of simplifying some things in the recipe so that there isn't this difference in `conda` and `mamba` (since most people will default to `conda`).

Curious, are you using micromamba or anaconda?

**Comment by mbyott** [comment]
I use conda from miniconda3, but when the conda version of this wouldnt finish I tried mamba for existing conda users with:

`conda install mamba -n base -c conda-forge`

**Comment by rpetit3** [comment]
Hi @mbyott,

I've released [v2.2.0](https://github.com/bactopia/bactopia/releases/tag/v2.2.0), going to go ahead and close this.

Cheers,
Robert
