### ISSUE TITLE
[bug] Process failed: execution is retried

### ISSUE THREAD

**Issue by baileybowcutt** [bactopia/bactopia#358]
**Description**
Apologies that I am here again. I really appreciate all the help so far. I have a dataset of ~260 _E.coli_ samples to run, and am trying to turn them around by Thursday. I decided to cut them into 13 jobs of 20 samples to run on our cluster quickly. Interestingly enough, I had 4 jobs finish within 12 hours with no problems, and the remaining are still running (hitting 36 hours).

I've peeked into the slurm output of the ones still running, and I'm noticing a trend. They all seem to be stuck on some process that gives the error Process (name of process) failed -- Execution is retried (1). 

Most of them seem to be hitting this wall with antimicrobial resistance, while another one hit it at Assembly QC. I don't really mind about the resistance right now, but it would be good to have. The assembly files are important to me though, so I thought I'd share. 

**Steps to Reproduce*
This is on a cluster. Each job is exactly identical except for the job title and samples. 

I used a bactopia miniconda environment to do the bactopia search 

```
(for index in {2..13}
do 
        cd /mnt/gs21/scratch/bowcuttb/mamba_bact/"SRR_20_"$index
        bactopia search "SRR_20_"$index".txt"
done 
```
This was fine. The following is an example of the code I submitted for one of the 13 jobs. Things wouldn't run right so I ended up using my profile -singularity :

```
#!/bin/bash --login

#######Resources Needed with SBATCH Lines ##########
#SBATCH --time=100:00:00		
#SBATCH --ntasks=1		    
#SBATCH --cpus-per-task=4	
#SBATCH --mem=80G     		
#SBATCH --job-name=SRR_20_8	
#SBATCH --account=(removed for privacy sake, but I ran this on a buyin node associated with my lab)
########## Modules to Load ##########

module load Conda/3

########## Code to Run ###########

cd /mnt/gs21/scratch/bowcuttb/mamba_bact/SRR_20_8
conda activate bactopia 
bactopia --accessions ena-accessions.txt \
         --datasets /mnt/gs21/scratch/bowcuttb/mamba_bact/datasets \
         --species "Escherichia coli" \
         --coverage 100 \
         --genome_size median \
         --outdir ena-multiple-samples \
         --max_cpus 4 \
	 -profile singularity
```

Error:

<img width="837" alt="image" src="https://user-images.githubusercontent.com/72410151/192187446-7c459217-a626-4972-8e32-b30cbbd006fc.png">

<img width="837" alt="image" src="https://user-images.githubusercontent.com/72410151/192188263-0dbfe204-2784-4ce5-a2cc-781376914d47.png">

Maybe this is an issue with me running files simultaneously using that -profile singularity? Not quite sure. Thank you for all of the help with running things so far!! I really appreciate it.

**Comment by rpetit3** [comment]
Can you by chance take a look into the `work` directory? Something like `work/6a/8519bd...` there should be some files named `.command.log`, `.command.err`, etc...

We might be able to find something in there for us to use.

Also, if you are interested in letting Nextflow handle the `sbatch` scripting, we can make a SLURM profile for you

**Comment by baileybowcutt** [comment]
I appreciate the quick response. Found the work directory, got to where you mentioned, but no command files there.
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/72410151/192189451-bd6f39cd-affc-4f9a-a4ee-0c016bd8c3d3.png">

Also, not quite sure what you mean by letting nextflow handle the sbatch scripting? Or what a slurm profile means. Apologies, I'm still pretty new.

**Comment by rpetit3** [comment]
That's the right directory, how the hidden files `ls -lha` and you should see the `.command` files.

If you are interested, Nextflow can write the following for you:
```
#######Resources Needed with SBATCH Lines ##########
#SBATCH --time=100:00:00		
#SBATCH --ntasks=1		    
#SBATCH --cpus-per-task=4	
#SBATCH --mem=80G     		
#SBATCH --job-name=SRR_20_8	
#SBATCH --account=(removed for privacy sake, but I ran this on a buyin node associated with my lab)
########## Modules to Load ##########
```

Except it will do it per-process, making things much more efficient because instead of reserving a large job (100 hours, 80GB, etc...), Nextflow will submit jobs with specific requirements for each task.

My chance do you know the partition or queue you submit jobs to on your SLURM cluster?

**Comment by baileybowcutt** [comment]
yes, the queue is my mortal enemy because it took about an hour to accept these jobs even with our buyin node. That SLURM profile is sounding really great right now. Let me know how to get that done and I can talk to our cluster folks about it tomorrow. 

less .command.err 
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/72410151/192190263-280c55ad-3d9e-4c4b-a6ec-568c9dbea26b.png">

less .command.log 
```
amrfinderdb/AMR_DNA-Neisseria
amrfinderdb/AMR_CDS.ntf
amrfinderdb/AMR_DNA-Escherichia.nto
amrfinderdb/AMR_DNA-Enterococcus_faecium.tab
amrfinderdb/AMR_CDS.nhr
amrfinderdb/AMR.LIB
amrfinderdb/AMRProt.pot
amrfinderdb/AMR_DNA-Escherichia.tab
amrfinderdb/AMR_DNA-Streptococcus_pneumoniae.not
amrfinderdb/AMR_DNA-Clostridioides_difficile.nhr
amrfinderdb/AMR_DNA-Staphylococcus_aureus.nsq
amrfinderdb/AMRProt.pdb
amrfinderdb/AMR_DNA-Enterococcus_faecium.nhr
amrfinderdb/AMR.LIB.h3p
amrfinderdb/AMRProt-susceptible.tab
amrfinderdb/AMR_DNA-Enterococcus_faecalis.ndb
amrfinderdb/AMR_DNA-Clostridioides_difficile.njs
amrfinderdb/AMR_DNA-Salmonella.nhr
amrfinderdb/AMR_DNA-Clostridioides_difficile.tab
amrfinderdb/AMR_DNA-Streptococcus_pneumoniae.nin
amrfinderdb/taxgroup.tab
amrfinderdb/AMR_DNA-Neisseria.nto
amrfinderdb/AMR_DNA-Escherichia
amrfinderdb/AMR_DNA-Escherichia.nsq
amrfinderdb/AMR_DNA-Campylobacter.ntf
amrfinderdb/AMR_DNA-Neisseria.nhr
amrfinderdb/changes.txt
amrfinderdb/AMR_DNA-Clostridioides_difficile.ntf
amrfinderdb/AMR_DNA-Salmonella.njs
amrfinderdb/AMR_DNA-Escherichia.njs
amrfinderdb/AMR_DNA-Neisseria.ndb
amrfinderdb/AMR_DNA-Clostridioides_difficile.nto
amrfinderdb/AMR_DNA-Escherichia.ntf
amrfinderdb/AMR_DNA-Campylobacter
amrfinderdb/version.txt
amrfinderdb/AMR_DNA-Streptococcus_pneumoniae.ntf
amrfinderdb/AMR_DNA-Enterococcus_faecalis
amrfinderdb/AMR_DNA-Salmonella.tab
amrfinderdb/AMR_DNA-Neisseria.ntf
amrfinderdb/AMR_DNA-Campylobacter.nto
amrfinderdb/AMR_DNA-Enterococcus_faecium.nto
amrfinderdb/AMR_DNA-Salmonella.not
amrfinderdb/AMRProt.pin
amrfinderdb/AMR_DNA-Staphylococcus_aureus.nin
amrfinderdb/AMR_DNA-Neisseria.njs
amrfinderdb/AMR_DNA-Staphylococcus_aureus.not
amrfinderdb/AMRProt.pto
amrfinderdb/AMR_DNA-Streptococcus_pneumoniae.nsq
amrfinderdb/AMR_DNA-Staphylococcus_aureus.njs
amrfinderdb/AMR_DNA-Campylobacter.nsq
amrfinderdb/AMRProt.psq
Running: amrfinder -n SRX3536181.ffn -d amrfinderdb/ -o SRX3536181-gene-report.txt --ident_min -1 --coverage_min 0.5 --translation_table 11 --threads 4
Software directory: '/opt/conda/envs/bactopia-annotate_genome/bin/'
Software version: 3.10.30
```

**Comment by rpetit3** [comment]
Anything useful in the `.command.err` file? (I'm guessing not, since it should have also been captured in `.command.log`)

I think another one we can look at is the `.nextflow.log`, which is in the directory you launched the workflow from. If you don't want to post that here you can email it to me at robbie.petit@gmail.com

**Comment by baileybowcutt** [comment]
That was it for the .command.err earlier. Pretty short. 

Shoot, I launched all 13 jobs from the same directory, so it probably overwrites the .nextflow.log each time. Sorry I didn't realize that would be a problem! I'll email you what I have, but I'm not sure how to tell which of the 13 jobs it is associated with. I can cancel these jobs and rerun them overnight each in new directories if that would be helpful. That will probably get us to about the point where they got stuck again by tomorrow noon.

**Comment by rpetit3** [comment]
Ok sounds good, I'll look for the email. I have an idea to make sure you have everything you need by Thursday!

**Comment by baileybowcutt** [comment]
Email sent! Would you like me to go ahead and cancel/rerun these jobs?

**Comment by rpetit3** [comment]
I say let them run, call it a night, see what happens by the morning

**Comment by baileybowcutt** [comment]
Update: it looks like that error code isn't anything important. When I allowed the code to run longer, things resolved themselves and it appears that everything populated correctly! Thanks again for all the quick responses.
