### ISSUE TITLE
[bug] Issue with Mash / Minimers workflow

### ISSUE THREAD

**Issue by dankein** [bactopia/bactopia#360]
Bactopia was failing for me on the minimer step and mash is producing the error
`mash: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory`

Command:
`bactopia --accessions ena-accessions.txt --datasets ./datasets --coverage 125 --outdir Sequences --species "Mycobacterium tuberculosis" --genome size median`

Bactopia 2.1.1

**Additional Information**
I was able to resolve this by activating the minimer environment inside of the bactopia conda environment and downgrading mash to version 2.2.2 from 2.2.3

**Comment by rpetit3** [comment]
Hi @dankein 

I'm happy to report I have [released version 3 of Bactopia](https://github.com/bactopia/bactopia/releases/tag/v3.0.0). With this release, your issue should now be taken care of. 

If not please feel free to reopen this issue or create a new one.

Thanks for using Bactopia!
Robert
