### ISSUE TITLE
[question] Issue running Bactopia script in updated version

### ISSUE THREAD

**Issue by jjhill4796** [bactopia/bactopia#376]
Hello,

I'm fairly new to bactopia and I'm currently trying to submit a .job file that seems to be failing in the updated version of bactopia.

This .job file was successful when it was ran by the previous researcher in my position, however he had not updated bactopia. I've placed the .job file below as well as the error code I'm receiving when I run it. I'm currently troubleshooting this but I thought I would ask on here as well in case I'm missing something obvious.

The researcher in this position before me commonly posted on this message board for help with bactopia issues, so hopefully this .job file looks familiar. 

Thanks!

bactopia_FOFN.job
```
#!/bin/sh
# This script should submit the fastq.gz's in this directory as a FOFN to Bactopia
#$ -q CCOM 
#$ -N JH_Test
#$ -pe smp 56
#$ -l h_rt=24:0:0
#$ -l high_mem
#$ -o JH_Test_11_22_22FOFNCCOM.log
#$ -M jared-hill@uiowa.edu
#$ -m bes
#$ -cwd
##### Putting the commands run into here so they may be printed to the .log output file
start=`date +%s`
CMD="
##$ -q CCOM
##$ -N Apr13_22FOFN
##$ -pe smp 56
##$ -l h_rt=8:0:0
##$ -l high_mem
##$ -o Apr13_22FOFNCCOM.log
##$ -M alexis-rozen@uiowa.edu
##$ -m bes
##$ -cwd
cd /Users/jhill7/BactopiaRuns/JHTest_11_17_22
conda activate bactopia
bactopia --fastqs testFOFN.txt \
	 --datasets ~/BactopiaRuns/datasets/ \
      	 --species “Staphylococcus aureus” (<- enclosed in quotes) \
         --coverage 100 \
         --genome_size median \
         --cpus 2 \
	 --max_memory 8 \
         --outdir Bactopia_Output_Apr13_22
"
#### The below commands prints the text you
#### assigned to the CMD variable to the log
echo "**************************************"
echo "commands=$CMD"
echo "**************************************" 
cd /Users/jhill7/BactopiaRuns/JHTest_11_17_22
conda activate bactopia
bactopia --fastqs testFOFN.txt \
	 --datasets ~/datasets/ \
	 --species "Staphylococcus aureus" \
	 --coverage 100 \
	 --genome_size median \
	 --cpus 2 \
	 --max_memory 8 \
	 --outdir BactopiaRuns_JHTest_11_17_22


Error Code (JH_Test.e9352189)

Traceback (most recent call last):
  File "/Users/jhill7/miniconda3/envs/bactopia/bin/bactopia-download.py", line 535, in <module>
    workflow_modules = parse_workflows(bactopia_path, include_merlin=include_merlin, build_all=args.build_all)
  File "/Users/jhill7/miniconda3/envs/bactopia/bin/bactopia-download.py", line 150, in parse_workflows
    nf_config, stderr = execute(f'nextflow config -flat {bactopia_path}/main.nf', capture=True)
  File "/Users/jhill7/miniconda3/envs/bactopia/bin/bactopia-download.py", line 84, in execute
    from executor import ExternalCommand, ExternalCommandFailed
ModuleNotFoundError: No module named 'executor'
tput: unknown terminal "xterm-256color"
tput: unknown terminal "xterm-256color"
tput: unknown terminal "xterm-256color"
tput: unknown terminal "xterm-256color"
tput: unknown terminal "xterm-256color"
curl: (77) error setting certificate verify locations:  CAfile: /Users/jhill7/miniconda3/envs/bactopia/ssl/cacert.pem CApath: none
ERROR: Cannot download nextflow required file -- make sure you can connect to the internet
```
Thank you!!

**Comment by rpetit3** [comment]
Hi @jjhill4796,

Let's see if we can get this figured out. 

What's the executor? (local, SGE, SLURM, etc...)
Can you use docker or singularity?
Can you add a `env` command in your script?

I'm curious what your PYTHONPATH looks like since its not finding executor.

Cheers,
Robert

**Comment by jjhill4796** [comment]
Hey Robert,

The job is running in a cloud computing cluster at the university, we believe it's using SGE.

We believe there is confusion on where bactopia is searching for the executor. I've included the following to help trace the location of executor.  


(bactopia) [jhill7@argon-login-1 bin]$ ls ~/miniconda3/bin/*executor*
ls: cannot access '/Users/jhill7/miniconda3/bin/*executor*': No such file or directory
(bactopia) [jhill7@argon-login-1 bin]$ ls ~/miniconda3/envs/bactopia/bin/*executor*
/Users/jhill7/miniconda3/envs/bactopia/bin/executor
(bactopia) [jhill7@argon-login-1 bin]$ echo $PATH
/Users/jhill7/miniconda3/envs/bactopia/bin:/Users/jhill7/miniconda3/condabin:/opt/sge/bin:/opt/sge/bin/lx-amd64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/Users/jhill7/.local/bin:/Users/jhill7/bin:/Users/jhill7/miniconda3/bin
(bactopia) [jhill7@argon-login-1 bin]$ which conda
~/miniconda3/envs/bactopia/bin/conda
(bactopia) [jhill7@argon-login-1 bin]$ 

Thanks!

**Comment by rpetit3** [comment]
In this case `executor` is a python package, so try adding a `which python` to your script.

Do you know if you can use Docker or Singularity containers on this cluster? If there are publicly available docs for the cluster I might be able to help you set up a config profile.

**Comment by jjhill4796** [comment]
Hey Robert,

After working on our script a bit and reading some of the similar errors that users have encountered, I believe we've fixed our executor error. See below for our new set of errors from the code. Any thoughts on what may be causing this?

Traceback (most recent call last):
  File "/Users/jhill7/miniconda3/envs/bactopia/bin/bactopia-download.py", line 535, in <module>
    workflow_modules = parse_workflows(bactopia_path, include_merlin=include_merlin, build_all=args.build_all)
  File "/Users/jhill7/miniconda3/envs/bactopia/bin/bactopia-download.py", line 150, in parse_workflows
    nf_config, stderr = execute(f'nextflow config -flat {bactopia_path}/main.nf', capture=True)
TypeError: cannot unpack non-iterable NoneType object
tput: unknown terminal "xterm-256color"
tput: unknown terminal "xterm-256color"
tput: unknown terminal "xterm-256color"
tput: unknown terminal "xterm-256color"
tput: unknown terminal "xterm-256color"
Cannot find script file: /Users/jhill7/miniconda3/envs/bactopia//share/bactopia-2.1.x/main.nf

Thanks!

**Comment by rpetit3** [comment]
Do you know if you can use Docker or Singularity containers on this cluster?

**Comment by jjhill4796** [comment]
I just looked up the info sheets on our cluster and I believe we can not use Docker/Singularity on it. 

I'm basing this on the following statement from this site "Docker is not suitable for HPC applications due to needing root level access"

https://wiki.uiowa.edu/display/hpcdocs/Singularity+Containers

**Comment by rpetit3** [comment]
Thank you for sharing this link, looks like Singularity is available. I'm going to look it this link more to see if we can maybe create a config file for you

**Comment by jjhill4796** [comment]
Thank you, that would be a huge help!

**Comment by rpetit3** [comment]
When you log into the cluster, can you use Conda? We're not trying to run jobs at this point, just curious if you are allowed to `conda activate bactopia` outside of your job script

**Comment by rpetit3** [comment]
If you can run bactopia via conda on the head node, we can try and let Nextflow submit the jobs:

```
bactopia -profile test,sge \
    --sge_penv "smp 56" \
    --sge_queue "CCOM" \
    --sge_opts="-cwd -m bes -M jared-hill@uiowa.edu"
```

**Comment by rpetit3** [comment]
Hi @jjhill4796 

Were you able to get this figured out?

Cheers,
Robert

**Comment by jhill4796** [comment]
Hey Robert,

Sorry for not getting back to you sooner. It looks like the problem was in our .job file that we were submitting to the argon cluster. The document had been edited in windows and therefore carried over invisible characters with it. All we had to do was run dos2unix "XX.job" and get rid of all those extra characters and it ran fine. 

Thanks for all your help!

**Comment by rpetit3** [comment]
Glad you were able to get this figured out!
