### ISSUE TITLE
libgsl.so.25: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by MalcolmorianVII** [bactopia/bactopia#378]
**Description**

I have bactopia installed in a **bactopia-dev conda env**.  I have observed the error arising when I run bactopia on my data.My investigation has revealed this affects the following bactopia steps & their associated conda envs:**gather_samples,call_variant,minmers**

**Example**
Running bactopia as follows:
`bactopia --samples fastqs.txt –species “Salmonella enterica” --datasets datasets --outdir bactopiaResults`

**Output**
```
Error executing process > 'BACTOPIA:MINMER_SKETCH (CQJ19G)'

Caused by:
  Process `BACTOPIA:MINMER_SKETCH (CQJ19G)` terminated with an error exit status (127)

Command error:
  mash: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
```

**What I have done**
Using the command `mamba install -c conda-forge gsl=2.6` I have downgraded gsl which has cleared the above error and bactopia seems to run fine.

**Additional Information**
Bactopia has finished processing all the samples in my dataset. I am looking forward for the official fix!

**Comment by rpetit3** [comment]
Hi @MalcolmorianVII 

Thank you for bringing this up! I'll get this fixed and tested on my dev build. Looking like a patch release might be coming soon.

Thanks again, and let me know if you have any questions!
Robert

**Comment by rpetit3** [comment]
Hi @MalcolmorianVII 

I'm happy to report I have [released version 3 of Bactopia](https://github.com/bactopia/bactopia/releases/tag/v3.0.0). With this release, your issue should now be taken care of. 

If not please feel free to reopen this issue or create a new one.

Thanks for using Bactopia!
Robert
