### ISSUE TITLE
[question] Command Error: cp: cannot create regular file

### ISSUE THREAD

**Issue by erin-thei** [bactopia/bactopia#379]
Finally circling back to Bactopia, and I'm determined to get it up and running correctly! 

I'm using version 2.2.0. I ran the command: bactopia --R1 /path/to/A_R1.fastq.gz --R2 /path/to/A_R2.fastq.gz --sample A2001 --outdir A2001 --datasets datasets/ -profile respublica --nfconfig bactopia_respublica.config 

It failed on the Gather Samples step: "Command error: cp: cannot create regular file 'fastqs/A20001_R1.fastq.gz/001-r1': No such file or directory"

Would you be able to help resolve this? Thanks.

<img width="706" alt="Screen Shot 2022-12-05 at 7 41 58 PM" src="https://user-images.githubusercontent.com/108017953/205778278-6ace4011-b5e5-410e-a0d3-50cded358e31.png">

<img width="1437" alt="Screen Shot 2022-12-05 at 7 43 12 PM" src="https://user-images.githubusercontent.com/108017953/205778343-bafac103-485f-4736-ba0a-b06b309e2366.png">

Side note, I had issues with AMRFinder+, but skipped it using --skip_amr. I noticed that others were having similar issues as well.

**Comment by rpetit3** [comment]
Hi @erin-thei,

Let's see if we can figure this out. Just to verify, is `/mnt/isilon/marc_genomics` available on the worker nodes?

Also, in the second image there is a "Work dir" `work/f8/a5...`. Are the FASTQ files in there?

**Comment by rpetit3** [comment]
progress! Are you using conda, docker or singularity?

**Comment by erin-thei** [comment]
i'm using conda

**Comment by rpetit3** [comment]
OK, this makes me wonder if the conda env isn't built or not available on the worker node.

Can you by chance use singularity?

**Comment by erin-thei** [comment]
Let me try. I have never used Singularity before so I will update you once I try!

**Comment by erin-thei** [comment]
After doing some reading, I tried running bactopia using singularity with the following commands: 
Module load singularity
singularity pull library://rpetit3/bactopia/bactopia
singularity exec bactopia_latest.sif bactopia --R1 A_R1.fastq.gz --R2 A_R2.fastq.gz --sample A2001 --outdir a2001_outdir --datasets datasets/ -profile singularity 

<img width="1435" alt="Screen Shot 2022-12-07 at 4 04 49 PM" src="https://user-images.githubusercontent.com/108017953/206295818-819bce0a-e7ba-40d6-8b51-585cf9ea38f4.png">

I got this error. Going to read up about it, but figured I would post it to see if you had any insights, especially since I'm not too familiar with singularity. 

Thanks as always for your help!

**Comment by rpetit3** [comment]
Can you by chance share the contents of `bactopia_respublica.config`?

If necessary, you can send it to my email robbie.petit@gmail.com

**Comment by erin-thei** [comment]
<img width="483" alt="Screen Shot 2022-12-08 at 4 17 20 PM" src="https://user-images.githubusercontent.com/108017953/206569419-92ff4a5d-5f7e-47f6-80a0-66b143c24e7f.png">

This is what the config file looks like

**Comment by erin-thei** [comment]
Hey Rob, any further insight to what I should try? I've been trying to work through it as well, but to no avail so far.

**Comment by rpetit3** [comment]
Looking into our previous conversations, let's give this command a try: 

```
bactopia -profile test,slurm -qs 20 --max_cpus 8 --max_ram 16 --slurm_queue defq
```

**Comment by erin-thei** [comment]
Thanks for getting back to me. I tried to run the above command, but received the following error: 
<img width="1437" alt="Screen Shot 2022-12-19 at 2 57 27 PM" src="https://user-images.githubusercontent.com/108017953/208510692-3de53f0b-7c53-4960-8bea-6f312f51ce95.png">

Additionally, I changed to the process work dir noted in the error message. This was what was in the dir:
<img width="1435" alt="Screen Shot 2022-12-19 at 3 02 00 PM" src="https://user-images.githubusercontent.com/108017953/208510884-5616cb24-ee20-4443-b830-edf1dea64c7a.png">

I tried to execute "cat .command.out" but there was nothing in that file.

**Comment by rpetit3** [comment]
By chance do you have to do something like: `module load singularity`

**Comment by erin-thei** [comment]
After I loaded the singularity module, I ran the same command. It looks like it got further, but failed at the assemble genome step:
<img width="1408" alt="Screen Shot 2022-12-19 at 5 03 50 PM" src="https://user-images.githubusercontent.com/108017953/208534230-c8977d81-b61f-448e-b5ce-a6a9dbf80d66.png">
<img width="1419" alt="Screen Shot 2022-12-19 at 5 04 09 PM" src="https://user-images.githubusercontent.com/108017953/208534238-4b93efda-ffc2-487e-8ee4-a3665e034aa0.png">

**Comment by rpetit3** [comment]
I feel a little deja vu here, I think we got to this point last time.

How much space do you have to work with here? We might have to change things from `/tmp`

**Comment by rpetit3** [comment]
Also, looks like just jobs were submitted to the SLURM cluster too! So all we have left to figure out is the space issue

**Comment by erin-thei** [comment]
I did notice that the jobs were submitted to SLURM, which is exciting -- feels like we are making some progress. In terms of the space I have to work with, I am working on the scratch directory, which has unlimited space (which I'm not sure makes sense if it's saying I'm running out)..

**Comment by rpetit3** [comment]
It looks like it might be related to the `/tmp` dir. Do you have a directory you know there shouldn't be a space issue with?

**Comment by erin-thei** [comment]
Hm, the directory that I'm working in currently is the one that I've been told to work in because it has unlimited space.

**Comment by rpetit3** [comment]
Let's try something, in the current directory, let's make a folder called `singularity`.  Looking at the picture above maybe this one? `/scr1/users/theillere/`

So let's try this:
```
# Make directories for new singularity cache
mkdir -p /scr1/users/theillere/singularity/images
mkdir -p /scr1/users/theillere/singularity/tmp

# export environment variables
export SINGULARITY_CACHE=/scr1/users/theillere/singularity/images
export SINGULARITY_TMPDIR=/scr1/users/theillere/singularity/tmp
export NXF_SINGULARITY_CACHEDIR=/scr1/users/theillere/singularity

# test bactopia
module load singularity
bactopia \
    -profile test,slurm \
    -qs 20 \
    --max_cpus 8 \
    --max_ram 16 \
    --slurm_queue defq \
    --singularity_cache /scr1/users/theillere/singularity/images
```

**Comment by erin-thei** [comment]
Hey Rob, sorry for the delay in response. Thanks for this information. I'll give it a try. Before I do that, since I'm not too familiar with singularity, do I need to pull the container (i.e.  singularity pull library://rpetit3/bactopia/bactopia)? and is there any specific way to run the bactopia command you provided above (i.e. singularity exec or singularity run, etc.). thanks for your help!

**Comment by rpetit3** [comment]
Hi @erin-thei 

This got completely lost to me! I apologize. 

Do you still want help with this one? Or were you able to get it figured out?

Robert

**Comment by rpetit3** [comment]
Hi @erin-thei 

I'm happy to report I have [released version 3 of Bactopia](https://github.com/bactopia/bactopia/releases/tag/v3.0.0). With this release, your issue should now be taken care of. 

If not please feel free to reopen this issue or create a new one.

Thanks for using Bactopia!
Robert
