### ISSUE TITLE
Species 'Staphylococcus aureus' not available

### ISSUE THREAD

**Issue by AroobAlhumaidy** [bactopia/bactopia#380]
Hello everyone, 

I'm using the tutorial mentioned here and https://bactopia.github.io/v2.2.0/tutorial/ and facing the following error: 
`Species 'Staphylococcus aureus' not available, please check spelling or use '--available_datasets' to verify the dataset has been set up. Exiting`

commands used: 
```
bactopia --accessions ena-accessions.txt \
         --datasets ../bactopia-tutorial3/datasets/ \
         --species "Staphylococcus aureus" \
         --coverage 100 \
         --genome_size median \
         --outdir ena-multiple-samples \
         --max_cpus 60
```

this is the dataset directory content: 
```
$ ls
antimicrobial-resistance  minmer  species-specific  summary.json
```
This is the summary.jason content: 
```
{
    "antimicrobial-resistance": [
        {
            "name": "amrfinderdb.tar.gz",
            "last_update": "2022-10-24T06:13:23Z"
        }
    ],
    "minmer": {
        "sketches": [
            "mash-refseq-k21.msh",
            "sourmash-genbank-k21.json.gz",
            "sourmash-genbank-k31.json.gz",
            "sourmash-genbank-k51.json.gz"
        ],
        "last_update": "2022-10-24T06:06:52Z"
    },
    "plasmid": {
        "sketches": null,
        "blastdb": null,
        "last_update": null
    }
}
```

Execution Environment

    Bactopia Version: bactopia 2.2.0
    OS: Ubuntu
    Environment: conda

can anyone help? 

Thanks

**Comment by rpetit3** [comment]
Hi @AroobAlhumaidy 

Based on the `summary.json` file above you will need to build datasets for S. aureus:

```
bactopia datasets \
    --species "Staphylococcus aureus" \
    --include_genus \
    --limit 100 \
    --cpus 4
```

**Comment by AroobAlhumaidy** [comment]
Thanks a lot for your response, I will try it out and let you know 

Best,
Aroob

**Comment by rpetit3** [comment]
Hi @AroobAlhumaidy 

Following up to see if you ever got this working.

Cheers,
Robert

**Comment by rpetit3** [comment]
Hi @AroobAlhumaidy 

I'm happy to report I have [released version 3 of Bactopia](https://github.com/bactopia/bactopia/releases/tag/v3.0.0). With this release, your issue should now be taken care of. 

If not please feel free to reopen this issue or create a new one.

Thanks for using Bactopia!
Robert
