### ISSUE TITLE
[question] Defining .bactopia / .cache env variables with conda install

### ISSUE THREAD

**Issue by aforestsomewhere** [bactopia/bactopia#389]
Hi Robert,

Thank you for the awesome tool and the ongoing support and development!

I have encountered the below problem, mainly (I think) because I am limited to a conda install of the latest Bactopia release on the computing cluster at my institute.

I managed to get the first few steps (bactopia prepare, bactopia --samples) to run by providing a hard path to the conda environment where Bactopia is installed in my SLURM submission script, as below 

```
NXF_HOME=/data/.../Katie_F/conda
export NXF_HOME
```

However I am stuck with running bactopia datasets, as it seems to be trying to create a .bactopia cache in my home folder, which is does not have enough space.

```
`External command failed with exit code 1!

Command:
bash -c 'mkdir -p /home/katie.fala/.bactopia'

Standard error:
mkdir: cannot create directory ‘/home/katie.fala/.bactopia’: Disk quota exceeded
`
```

 Would you have any tips how to proceed, or if I can modify environmental variables to force it to write all intermediate/cache/work files to my working directory (on the data partition)? I (most likely crudely) tried to force the CACHE_DIR variable in my script too, but it hasn't helped matters.

`CACHE_DIR=/data/.../WD
export CACHE_DIR`

Thanks a million!

Katie

**Comment by rpetit3** [comment]
Hi Katie!

I didn't think that cache dir through, looks like there is currently no parameter to change

For running on SLURM, do you have access to singularity?

Cheers,
Robert

**Comment by aforestsomewhere** [comment]
Thanks for coming back so quickly!

No worries, I realise the conda workaround for HPC is fairly hacky, was happy to get the first few steps running at least.

I can check out Singularity again, it is available as a module but as far as I recall it is not straightforward for users without root access to setup.

**Comment by rpetit3** [comment]
In the next version I'm dropping the need for `bactopia datasets`, so this will fix your cache issue.

But I think ideally on your cluster, running bactopia would happen like this:

```
conda activate bactopia
bactopia --samples katies-samples.txt -profile katiescluster
```

Since this would allow Nextflow to submit jobs to the cluster for you. If you think there's interest, I'd be happy to help create a config file. 

Here's an example for a university cluster using SLURM: https://github.com/bactopia/bactopia/blob/master/conf/profiles/arcc.config

With this, users can just do the following: `bactopia --samples samples.txt -profile arcc` and Nextflow handles the rest (e.g. sbatch scripts)


But! None of this solves your current issue. As a temporary band-aid, I can build the datasets and share them for you. Or you can download this file: https://github.com/bactopia/bactopia/blob/master/bin/bactopia/bactopia-datasets.py change the line 15 to a path that works for you

**Comment by aforestsomewhere** [comment]
We do have a module to load Bactopia, which I think is set up with the Singularity workflow and config by our admin as you outlined. Problem is its an older version, and there was a definite reason why I needed 2.2.0 for this analysis (compatibility with the workflows I think, although it escapes me right now!).

Thank you, I am hesitant to ask for you to build the databases for me as my use case seems isolated; have changed the file path for CACHE_DIR, it is at least starting now (yay!) but is throwing an error for the pubmlst.json paths also. I will have a further bash at this and can reach out again if I can't resolve.

**Comment by rpetit3** [comment]
Easiest might be a 
```
git clone https://github.com/bactopia/bactopia.git
path/to/edited/bactopia-datasets.py bactopia/
```

That should get you those files needed

**Comment by aforestsomewhere** [comment]
Thank you for this! This got at least through the minmers but I am getting an error for AMRFinder+, I think as seen in [this issue](https://github.com/bactopia/bactopia/issues/373)

Sorry for the hassle!

`External command failed with exit code 1!

Command:
bash -c 'mv 2022-10-11.2/* amrfinderdb/'

Standard error:
mv: cannot stat '2022-10-11.2/*': No such file or directory
`

**Comment by rpetit3** [comment]
Exactly! Here's a comment with a solution: https://github.com/bactopia/bactopia/issues/377#issuecomment-1385578774

This is another one that will be fixed in the next version

**Comment by aforestsomewhere** [comment]
Sorted! Really appreciate your help (esp on a Friday evening) and looking forward to the next release of Baktopia :)

**Comment by rpetit3** [comment]
No problem! Reach out if you think I might be able to help!
