### ISSUE TITLE
[question] genome size = 1bp?

### ISSUE THREAD

**Issue by Svnipni** [bactopia/bactopia#391]
I tested and ran bactopia on the same paired-end files in WSL2, which gave some nice results.
So I moved to set it up on my Ubuntu machine but every attempt ends within minutes on the GATHER_SAMPLES and returns a genome size of 1bp. Is something off with Mash on my env? Should I just try --genome_size? I mostly confused why it worked fine on WSL but it cant seem to pass the first step in a pure Ubuntu environment.

Any help would be greatly appreciated.

**Comment by rpetit3** [comment]
@Svnipni thats awesome it worked on WSL for you! On the Ubunut side, I think its an issue with the `gsl` version in the env that is affecting Mash.

Easiest way to keep moving would be as you suggest, provide a genome size if you know it. I think there were a few other steps affected by this `gsl` issue.

I'm currently in the process of getting these all fixed and hope that will be soon!

**Comment by Svnipni** [comment]
@rpetit3 thank you! Glad to hear the issue is not on my end. The pipeline runs fine with --genome_size but I have a few samples that came from unknown isolates, so I'll have little to go on regarding the expected genome size. Is there a way I can use a range for the genome size? It can either be Comamonas sp or another Pseudomonas sp, so that put its genome size anywhere between 3 and 6 Mbp.

**Comment by rpetit3** [comment]
If you don't provide a genome size it will be estimated using mash
