### ISSUE TITLE
[question] ariba can't find samples

### ISSUE THREAD

**Issue by Svnipni** [bactopia/bactopia#392]
I'm trying to run ariba on my samples after having already run the basic pipeline for assembly.

```
bactopia --R1 SEQS_R1.fastq.gz \
         --R2 SEQS_R2.fastq.gz \
         --sample SAMPLE_NAME \
         --datasets datasets/ \
         --outdir OUTDIR
```
then 

```
bactopia --wf ariba \
  --bactopia /path/to/your/bactopia/results \ 
  --ariba_dir ariba_dir
  --ariba_db CARD
```
`Found 0 samples to process`

Seems pointing it to the OUTDIR is not the right approach?

**Comment by rpetit3** [comment]
Hi @Svnipni 

What does `ls ${OUTDIR}` look like?

**Comment by Svnipni** [comment]
`ls` looks like this
`annotation                blast                      minmers          variants
antimicrobial-resistance  logs                       mlst
assembly                  MEGIC_246-genome-size.txt  quality-control
`

**Comment by rpetit3** [comment]
You'll want to step back a directory, in the `--bactopia`  option

**Comment by Svnipni** [comment]
Ah ok! 
Darn I might have to rerun a few samples then. I had to offload these individual folders to an external drive and only kept the individual sample folders. I'll try to run it on a recent sample that still has the `bactopia/` `logs/` and .yml files.

**Comment by rpetit3** [comment]
Hold off on rerunning. As long as it looks something like this, it should work:

```
<FOLDER>
     <SAMPLE1>
          annotation
          blast
          ...
          quality-control
         -genome-size.txt
     <SAMPLE2>
          annotation
          blast
          ...
          quality-control
         -genome-size.txt 
```

You can  use `--bactopia  /path/to/<FOLDER>`. For something like `ariba` you can move the <SAMPLE> folders on and off the external drive. 

For something like the `pangenome` tool, you'll need them all in one location.

**Comment by Svnipni** [comment]
Oh that's awesome! I feared it needed the trace files in bactopia/
I'll give it a go!
