### ISSUE TITLE
[bug] Singularity container link not reachable?

### ISSUE THREAD

**Issue by uloeber** [bactopia/bactopia#393]
**Description**
Unable to fetch singularity container

**Steps to Reproduce**
```
singularity pull library://rpetit3/bactopia/bactopia
FATAL:   Unable to get library client configuration: remote has no library client
```

**Expected Behavior**
Download singularity container

**Execution Environment**

Linux 3.10.0-1160.76.1.el7.x86_64 #1 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64 GNU/Linux
singularity --version
apptainer version 1.1.5-2.el7
**Additional Information**
Hi Robert, I try to run the pangenome workflow, however, something is going wrong setting up pirate and panroo at least. I installed bactopia via conda and after some days of trying to fix it, I decided to try using a singularity container. I get the error posted above. Is this a problem on our end or is the path the wrong one?
Thanks in advance!
Ulrike

**Comment by rpetit3** [comment]
Here's a link to a singularity image that should work better for you: https://depot.galaxyproject.org/singularity/bactopia%3A2.2.0--hdfd78af_0

What was the error message coming out of `pnagenome`?

**Comment by uloeber** [comment]
Thank you, I will try. 
```
[54/4cb036] NOTE: Process `BACTOPIATOOLS:PANGENOME:PG_TOOL:PIRATE_MODULE (pirate)` terminated with an error exit status (127) -- Execution is retried (1)
[22/33e504] NOTE: Process `BACTOPIATOOLS:PANGENOME:PG_TOOL:PIRATE_MODULE (pirate)` terminated with an error exit status (127) -- Execution is retried (2)
[55/0ce3b0] NOTE: Process `BACTOPIATOOLS:PANGENOME:PG_TOOL:PIRATE_MODULE (pirate)` terminated with an error exit status (127) -- Execution is retried (3)
Error executing process > 'BACTOPIATOOLS:PANGENOME:PG_TOOL:PIRATE_MODULE (pirate)'

Caused by:
  Process `BACTOPIATOOLS:PANGENOME:PG_TOOL:PIRATE_MODULE (pirate)` terminated with an error exit status (127)

Command executed:

  find . -name "*.gff.gz" | sed 's/.gz//' | xargs -I {} bash -c 'gzip -cdf {}.gz > {}'
  
  PIRATE \
      --steps 50,60,70,80,90,95,98 --features CDS \
      --align \
      --threads 2 \
      --input ./ \
      --output results/
  PIRATE_to_roary.pl -i results/PIRATE.*.tsv -o results/gene_presence_absence.csv
  find . -name "*.fasta" | xargs -I {} -P 2 -n 1 gzip {}
  
  # Only copy files if they exist
  if [[ -f "results/core_alignment.fasta.gz" ]]; then
      cp results/core_alignment.fasta.gz ./core-genome.aln.gz
  fi
  
  cat <<-END_VERSIONS > versions.yml
  "BACTOPIATOOLS:PANGENOME:PG_TOOL:PIRATE_MODULE":
      pirate: $( echo $( PIRATE --version 2>&1) | sed 's/PIRATE //' )
  END_VERSIONS

Command exit status:
  127
```

**Comment by rpetit3** [comment]
Apologies for the slow response here. One thing I want to tackle with v3, is making sure the Docker and Singularity containers work just the same as the Conda install

I will look into this further

**Comment by rpetit3** [comment]
Hi @uloeber 

I'm cleaning up old issues and since this is related to v2, I'm going to go ahead and close this with the recommendation to give v3 a try.

Please reach out if you have any questions or issues!

Cheers,
Robert
