### ISSUE TITLE
[bug] Sequence_type

### ISSUE THREAD

**Issue by MartinVad** [bactopia/bactopia#396]
**Description**
Unable to run ´sequence_type´ successfully when working directly on cifs share

**Steps to Reproduce**

!NOTE! It is when working directly on cifs share. Locally it works perfectly.

```
bactopia --use_ena --accession SRX4563634 --datasets datasets/ --species "Staphylococcus aureus" --coverage 100 --genome_size median --outdir ena-single-sample --max_cpus 32 --verbose
```
After most of the tasks have been completed, and it reaches  `BACTOPIA:SEQUENCE_TYPE` it fails with the following error for each of the tar it tries to perform:
```
...
Cannot utime: ... : Operation not permitted
...
```
See log for more information:
[nextflow.log](https://github.com/bactopia/bactopia/files/10880975/nextflow.log)

**Expected Behavior**
Expect to run the bactopia successfully

**Execution Environment**

- Bactopia Version: bactopia 2.2.0
- OS: Ubuntu
- Environment: Conda

**Additional Information**
Hi. Just got introduced to bactopia, and I try to get familiar with it. 
I ran the tutorial step directly on our application share (cifs) and encountered this issue when it tries to extract files from a compressed tar archive under bactopia/share/bactopia-2.2.x/modules/local/bactopia/sequence_type/main.nf

To circumvent this, I just added the flag `--touch` to the tar command:
```
...
    tar --touch -xvzf !{dataset_tarball}
...
```
Runs smoothly now :-)

Sorry if I've missed some essential details. 
Hope to hear from you

Regards
Martin

**Comment by rpetit3** [comment]
Thank you @MartinVad  for finding a bug and fixing it! 

Fortunately, this will be fixed in v3!

**Comment by rpetit3** [comment]
Hi @MartinVad 

I'm happy to report I have [released version 3 of Bactopia](https://github.com/bactopia/bactopia/releases/tag/v3.0.0). With this release, your issue should now be taken care of. 

If not please feel free to reopen this issue or create a new one.

Thanks for using Bactopia!
Robert
