### ISSUE TITLE
Error for Mac

### ISSUE THREAD

**Issue by lingbingzeng1985** [bactopia/bactopia#398]
Hello Robert,
When I used the bacteria on Mac, I found a problem. When I use " bactopia --R1 /Users/cenglingbing/Desktop/Bioinformatics_analysis/Genomes/MCR_Genomes/K75_HQ_R1.fq.gz --R2 /Users/cenglingbing/Desktop/Bioinformatics_analysis/Genomes/MCR_Genomes/K75_HQ_R2.fq.gz --sample K75 --datasets /Users/cenglingbing/Desktop/Bioinformatics_analysis/bactopia/database --outdir /Users/cenglingbing/Desktop/Bioinformatics_analysis/Genomes/MCR_Results --species "Klebsiella pneumoniae" --coverage 100 --genome_size median --max_cpus 2 --force", and the report like this:

**Error executing process > 'BACTOPIA:MINMER_QUERY (K75 - wget-log)'**

Caused by:
  Index 2 out of bounds for length 2 -- Check script 'miniconda3/envs/bactopia/share/bactopia-2.2.x/./workflows/../modules/local/bactopia/minmer_query/main.nf' at line: 35

Source block:
  dataset_basename = dataset.getSimpleName()
  dataset_info = dataset_basename.split("-")
  program = dataset_info[0]
  database = dataset_info[1]
  kmer = dataset_info[2]
  mash_w = params.no_winner_take_all ? "" : "-w"
  fastq = meta.single_end ? "${fq[0]}" : "${fq[0]} ${fq[1]}"
  '''
      OUTPUT="!{meta.id}-!{program}-!{database}-!{kmer}.txt"
      if [ "!{program}" == "mash" ]; then
          echo "identity<TAB>shared-hashes<TAB>median-multiplicity<TAB>p-value<TAB>query-ID<TAB>query-comment" | sed 's/<TAB>/\t/g' > ${OUTPUT}
          gzip -cd !{fastq} | \
              mash screen !{mash_w} -i !{params.screen_i} -p !{task.cpus} !{dataset} - | \
              sort -gr >> ${OUTPUT}
      elif [ "!{program}" == "sourmash" ]; then
          sourmash lca classify --query !{sourmash} --db !{dataset} > ${OUTPUT}
      fi
  
      # Capture versions
      cat <<-END_VERSIONS > versions.yml
      "!{task.process}":
          mash: $(echo $(mash 2>&1) | sed 's/^.*Mash version //;s/ .*$//')
          sourmash: $(echo $(sourmash --version 2>&1) | sed 's/sourmash //;')
      END_VERSIONS
      '''

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

WARN: Graphviz is required to render the execution DAG in the given format -- See http://www.graphviz.org for more info.

**Comment by rpetit3** [comment]
Hi @lingbingzeng1985 

Can you confirm `bactopia -profile test` works for you?

Thank you,
Robert

**Comment by rpetit3** [comment]
Hi @lingbingzeng1985 

I'm cleaning up old issues and since this is related to v2, I'm going to go ahead and close this with the recommendation to give v3 a try.

Please reach out if you have any questions or issues!

Cheers,
Robert
