### ISSUE TITLE
[bug] Unable to install on SLURM cluster through Singularity

### ISSUE THREAD

**Issue by Svnipni** [bactopia/bactopia#402]
On a slurm cluster I tried setting up bactopia through conda. Installation seemed to run just fine but any and all runs on reads or samples fails with exit code 1, 2 or 127

Tried to set it up through singularity but this ends with 
`while building SIF from layers: while creating squashfs: create command failed: signal: killed:`

**Comment by rpetit3** [comment]
I would suggest trying to run it like so:

```
conda activate bactopia
bactopia -profile test,slurm --slurm_queue <YOUR_QUEUES> --slurm_opts='<SLURM_OPTIONS>'
```

Here are optiions for slurm:
```
SLURM Profile (-profile slurm) Parameters
  --slurm_queue                       [string]  Comma-separated name of the queue(s) to be used by SLURM [default: general,high-memory]
  --slurm_opts                        [string]  Additional options to pass to SLURM. (e.g. '--account=my_acct_name')
  --slurm_use_scratch                 [boolean] All intermediate files will stay on the on worker nodes.
```

The goal here being, use conda to load bactopia, but tell Nextflow to submit jobs to the SLURM queue. 

Here's a profile for a SLURM cluster I have access to: https://github.com/bactopia/bactopia/blob/master/conf/profiles/arcc.config

The main benefit is I only need to add `-profile arcc` and Nextflow takes care of the rest with SLURM. I can help set up a profile if you are interested. 

Let me know how things go!
Robert

**Comment by Svnipni** [comment]
Thanks! I can try singularity but last time I try to run it, it still ends with exit status 1. Also, I'd need it to stay out of $HOME and stick to $SCRATCH.

**Comment by Svnipni** [comment]
Quick update.
running a `--wf abricate` seems to now work on slurm after rebuilding bactopia conda env and datasets. `--pangenome` still doesn't unfortunately.  Running this with `--verbose` seems like it's stuck with 

```
2023-03-31 18:23:34:executor.process:DEBUG - Got return code 127 from synchronous process (bash -c 'singularity build  /marconi/home/userexternal/afranzet/.bactopia/singularity/quay.io-bactopia-bactopia-2.0.1.img docker://quay.io/bactopia/bactopia:2.0.1').
2023-03-31 18:23:34:root:STDERR - Error creating image, retrying after short sleep.
```

**Comment by Svnipni** [comment]
Quick update before closing:

Was able to set up the conda env on SLURM . Seems a few variables and packages were not properly in place previously. I would still like to be able to run `-wf pangenome` but I might have to cut my losses and accept my isolates may have been too contaminated.

Thanks for your help so far :)
