### ISSUE TITLE
Erro: unable to open summary.json 

### ISSUE THREAD

**Issue by shafi-OZ** [bactopia/bactopia#404]
Hi 
I have gone through other related posts and still cannot find the solution https://github.com/bactopia/bactopia/issues/137
I have tried many times to provide the location in different ways, but I get this error message every time. 
Also, I follow the tutorial, and it fails to download the entire dataset. Would that be a reason for not finding summary.jason

Command:
bash -c 'mv 2022-10-11.2/* amrfinderdb/'

Standard error:
mv: cannot stat '2022-10-11.2/*': No such file or directory

Regards
Shafi

**Comment by rpetit3** [comment]
Hi @shafi-OZ 

Check out this one: https://github.com/bactopia/bactopia/issues/377#issuecomment-1385578774

Or you can try a preview of version 3 here: https://github.com/bactopia/bactopia/issues/394

let me know if these don't help!
Robert

**Comment by shafi-OZ** [comment]
Hi Robert
Thanks for the prompt reply. The summary.jason issue is not there anymore. However, I faced another issue while going through the tutorial example. I believe the qaust package was missing from the conda env, I install the quast and rerun the tut. I will update you 

Command error:
  .command.sh: line 30: quast: command not found
 
Regards
Shafi

**Comment by shafi-OZ** [comment]
Hi Robert
The run failed again with a similar error. I have attached the command file here. 

Command exit status:
  127
Command output:
  (empty)
Command error:
  .command.sh: line 30: quast: command not found

[command.txt](https://github.com/bactopia/bactopia/files/11215286/command.txt)

Regards
Shafi
