### ISSUE TITLE
[question] using Bactopia Tools on non-bactopia output?

### ISSUE THREAD

**Issue by Svnipni** [bactopia/bactopia#407]
Hi again,

After some playing around with the bactopia assembly output, I wondered if it was possible to use some of the bactopia tools on results from other pipelines.

I was dealing with some contaminated samples and have been cleaning them up after assembly. I now have a bunch of `*_cleaned.fna` files for each sample that I'd like to run through abricate. Of course, I could set up a new conda env and install abricate separately, but it would be cool if I could use the module in bactopia.

Will I need to convert and/or "mimic" a bactopia results directory structure?

**Comment by rpetit3** [comment]
Hi @Svnipni, 
 
You are correct, if you would like to run the Bactopia Tools, you will need to either run the samples through Bactopia or mimic the output directory. 

Cheers,
Robert

**Comment by rpetit3** [comment]
Hi @Svnipni 

Happy tio report I've release v3 of Bactopia! 

Thank you very much for your feedback and suggestions!
Robert
