### ISSUE TITLE
Bactopia fails to set up AMRFinder+ database

### ISSUE THREAD

**Issue by qi-shen** [bactopia/bactopia#409]
Issue description:

I'm running Bactopia to analyze some bacterial genomes and encountered an issue while setting up the AMRFinder+ database. I've installed AMRFinder+ version 3.10.45 and curl version 7.88.1, but the process of creating Bactopia datasets fails with the following error message:

``
2023-04-22 08:33:01:root:INFO - Setting up latest AMRFinder+ database
External command failed with exit code 1!

Command:
bash -c 'mv 2022-10-11.2/* amrfinderdb/'

Standard error:
mv: cannot stat '2022-10-11.2/*': No such file or directory
``

Software versions:

Bactopia: 2.2.0
AMRFinder+: 3.10.45
curl: 7.88.1

System information:
Operating System: Ubuntu 20.04

I've tried the following troubleshooting steps:

Reinstalled AMRFinder+.
Checked my network connection.
However, the issue persists. I can proceed with my analysis using --skip_amr, but I'd like to resolve this issue and include the AMR predictions in my results.

Any help or guidance would be appreciated.

**Comment by rpetit3** [comment]
Hi @qi-shen 

Let's get this fixed for you, we have a few options: 

1. manually download the file described here: https://github.com/bactopia/bactopia/issues/377#issuecomment-1385578774

2. Try Bactopia v3 described here: https://github.com/bactopia/bactopia/issues/394

Let me know if neither of these work for you!
Robert

**Comment by qi-shen** [comment]
@rpetit3 
I have manually downloaded the amrfinderdb.tar.gz file and placed it in the ./datasets/antimicrobial-resistance directory. The directory structure is as follows:

``
.
├── amrfinderdb
├── amrfinderdb-temp
│   ├── 2022-10-11.2
│   │   ├── (all necessary files and folders)
│   └── latest -> 2022-10-11.2
└── amrfinderdb.tar.gz
``

However, when I run bactopia datasets, I still encounter the same issue:

``
2023-04-22 11:22:54:root:INFO - Setting up pre-computed Genbank/Refseq minmer datasets
...
2023-04-22 11:22:54:root:INFO - Setting up antimicrobial resistance datasets
2023-04-22 11:22:54:root:INFO - Setting up latest AMRFinder+ database
External command failed with exit code 1!

Command:
bash -c 'mv 2022-10-11.2/* amrfinderdb/'

Standard error:
mv: cannot stat '2022-10-11.2/*': No such file or directory

``
Please let me know if you have any suggestions on how to resolve this issue using this method.

Thank you for your assistance.
