### ISSUE TITLE
[bug] bactopia search using "Invalid fieldName(s)"

### ISSUE THREAD

**Issue by lenorakepler** [bactopia/bactopia#410]
**Description**
bactopia search command produces blank ena-accessions.txt, even using given example accession searches. ena-results.txt says: "Invalid fieldName(s) supplied: cram_index_ftp,cram_index_aspera,cram_index_galaxy"

**Steps to Reproduce**
```
bactopia search PRJNA480016
```

**Execution Environment**

- Bactopia Version: 2.2.0
- OS: Ubuntu
- Environment: conda

**Additional Information**
I edited bactopia/bin/bactopia-search.py to remove those fields from the ENA query, and that seemed to get everything working.

**Comment by rpetit3** [comment]
Nice catch @lenorakepler!

Just had a similar issue over on fastq-dl: https://github.com/rpetit3/fastq-dl/issues/15

**Comment by rpetit3** [comment]
Hi @lenorakepler 

I'm happy to report I have [released version 3 of Bactopia](https://github.com/bactopia/bactopia/releases/tag/v3.0.0). With this release, your issue should now be taken care of. 

If not please feel free to reopen this issue or create a new one.

Thanks for using Bactopia!
Robert
