### ISSUE TITLE
AMR Finder update

### ISSUE THREAD

**Issue by veganm** [bactopia/bactopia#411]
Running Bactopia 2.2.0. Got a warning while building a database: "WARNING: A newer version of the database exists (2023-04-17.1), but it requires a newer version of the software (3.11) to install.
See https://github.com/ncbi/amr/wiki/Upgrading for more information."

**Comment by rpetit3** [comment]
Hi @veganm 

I'm happy to report I have [released version 3 of Bactopia](https://github.com/bactopia/bactopia/releases/tag/v3.0.0). With this release, your issue should now be taken care of. 

If not please feel free to reopen this issue or create a new one.

Thanks for using Bactopia!
Robert
