### ISSUE TITLE
[feature] Add masking support to snippy workflow

### ISSUE THREAD

**Issue by embatty** [bactopia/bactopia#412]
Is it possible to add support for the snippy-core --mask option in future versions? It would be great to be able to use the auto-mask feature or to supply a BED file for masking.

**Comment by rpetit3** [comment]
Great idea! I'll get this added in the next version.

Also noticed I missed the catch all parameters (e.g. `--snippy_opts` and `--snippy_core_opts`). I'll get those in as well.

Will update soon!

**Comment by rpetit3** [comment]
Hi @embatty 

Been a while, but I've added this (via `--mask`) in my dev build for v3. I tested with a basic BED file for my test genomes and it seemed to work. But if you have time to give it a spin, let me know if it doesn't work as expected.

Thank you for the suggestion!

**Comment by rpetit3** [comment]
Hi @embatty 

Happy to say I've finally release v3, which includes support for your suggestion!

Thank you so much for all your feedback and ideas!
Robert
