### ISSUE TITLE
[feature] Adding support for medaka_model r1041_e82_400bps_sup_g615 in assembly for Nanopore reads

### ISSUE THREAD

**Issue by llk578496** [bactopia/bactopia#416]
Hi @rpetit3 !

**Related To**

- [x] Bactopia
- [ ] Bactopia Tools

**Is this related to a problem?**
We are moving towards from R9.4.1 flowcell to R10.4.1 flowcell for Nanopore sequencing. 
However, when we tried to tried to use the option `--model r1041_e82_400bps_sup_g615`, it gives the following error:

> Command error:
>   [dragonflye] Hello stranger
>   [dragonflye] You ran: /opt/conda/envs/bactopia-assemble_genome/bin/dragonflye --reads BatchX003_V_11_ESBL_02_Sub.fastq.gz --gsize 8000000 --outdir results --force --minlen 500 --mincov 2 --namefmt BatchX003_V_11_ESBL_02_Sub_%05d --keepfiles --cpus 8 --ram 31 --assembler flye --depth 0 --minreadlen 0 --minquality 0 --racon 1 --medaka 1 --model r1041_e82_400bps_sup_g615 --nanohq
>   [dragonflye] This is dragonflye 1.0.13
>   [dragonflye] Written by Robert A Petit III
>   [dragonflye] Homepage is https://github.com/rpetit3/dragonflye
>   [dragonflye] Operating system is linux
>   [dragonflye] Perl version is v5.32.1
>   [dragonflye] Machine has 20 CPU cores and 125.72 GB RAM
>   [dragonflye] Verifying input model (--model): r1041_e82_400bps_sup_g615
>   [dragonflye] Unable to verify model 'r1041_e82_400bps_sup_g615', please check spelling and try again.
>   [dragonflye] Available Medaka models include:
>   [dragonflye] 	r103_fast_g507
>   [dragonflye] 	r103_hac_g507
>   [dragonflye] 	r103_min_high_g345
>   [dragonflye] 	r103_min_high_g360
>   [dragonflye] 	r103_prom_high_g360
>   [dragonflye] 	r103_sup_g507
>   [dragonflye] 	r104_e81_fast_g5015
>   [dragonflye] 	r104_e81_hac_g5015
>   [dragonflye] 	r104_e81_sup_g5015
>   [dragonflye] 	r10_min_high_g303
>   [dragonflye] 	r10_min_high_g340
>   [dragonflye] 	r941_min_fast_g303
>   [dragonflye] 	r941_min_fast_g507
>   [dragonflye] 	r941_min_hac_g507
>   [dragonflye] 	r941_min_high_g303
>   [dragonflye] 	r941_min_high_g330
>   [dragonflye] 	r941_min_high_g340_rle
>   [dragonflye] 	r941_min_high_g344
>   [dragonflye] 	r941_min_high_g351
>   [dragonflye] 	r941_min_high_g360
>   [dragonflye] 	r941_min_sup_g507
>   [dragonflye] 	r941_prom_fast_g303
>   [dragonflye] 	r941_prom_fast_g507
>   [dragonflye] 	r941_prom_hac_g507
>   [dragonflye] 	r941_prom_high_g303
>   [dragonflye] 	r941_prom_high_g330
>   [dragonflye] 	r941_prom_high_g344
>   [dragonflye] 	r941_prom_high_g360
>   [dragonflye] 	r941_prom_high_g4011
>   [dragonflye] 	r941_prom_sup_g507
>   grep: results/dragonflye.log: No such file or directory
> 
> Work dir:
>   /mnt/data2/Food/REAL/work/12/04288b4e170384ccb32960cb42678e
> 
> Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
> 

**Is this something you would like to see added?**
We would like to have the updated version `medaka` which includes the model `r1041_e82_400bps_sup_g615`. 

Thank you very much!

Eddie

**Comment by rpetit3** [comment]
Hi @llk578496 

This is fixed in Dragonflye (https://github.com/rpetit3/dragonflye/releases/tag/v1.1.1), if you'd like to take advantage of it you can either manually run Dragonflye or test out my dev build of bactopia (https://github.com/bactopia/bactopia/issues/394)

Let me know if these don't work for you, 
Robert

**Comment by llk578496** [comment]
@rpetit3 Thank you so much for the update!

We just tried to use your dev build `bactopia-dev` with the following command:

`bactopia --ont --SE /mnt/data2/Food/REAL/02_fastq/Batch064_C_02_S_ESBL_03_Sub.fastq.gz --sample Batch064_C_02_S_ESBL_03_Sub --datasets /mnt/data2/Food/REAL/datasets --outdir /mnt/data2/Food/REAL/04_bactopia/04.1_tmp/Batch064_C_02_S_ESBL_03_Sub -profile docker --max_cpus 10 --max_memory 110 --max_time 360 --dragonflye_opts="--nanohq" --medaka_model r1041_e82_400bps_sup_g615 --genome_size 8000000 --min_coverage 50 --medaka_steps 2 --racon_steps 3 --cleanup_workdir`

However, we got the following error in the `process > BACTOPIA:ASSEMBLER:ASSEMBLER_MODULE` and seems to be related with the option `--dragonflye_opts="--nanohq"`:

> executor >  local (8)
> [34/028964] process > BACTOPIA:DATASETS                                                 [100%] 1 of 1 ✔
> [55/78e7fb] process > BACTOPIA:GATHER:GATHER_MODULE (Batch064_C_02_S_ESBL_03_Sub)       [100%] 1 of 1 ✔
> [e3/c0c78a] process > BACTOPIA:GATHER:CSVTK_CONCAT (meta)                               [100%] 1 of 1 ✔
> [e4/90596e] process > BACTOPIA:QC:QC_MODULE (Batch064_C_02_S_ESBL_03_Sub)               [100%] 1 of 1 ✔
> [43/780834] process > BACTOPIA:ASSEMBLER:ASSEMBLER_MODULE (Batch064_C_02_S_ESBL_03_Sub) [100%] 4 of 4, failed: 4, retries: 3 ✘
> [-        ] process > BACTOPIA:ASSEMBLER:CSVTK_CONCAT                                   -
> [-        ] process > BACTOPIA:SKETCHER:SKETCHER_MODULE                                 -
> [-        ] process > BACTOPIA:ANNOTATOR:PROKKA_MODULE                                  -
> [-        ] process > BACTOPIA:AMRFINDERPLUS:AMRFINDERPLUS_RUN                          -
> [-        ] process > BACTOPIA:AMRFINDERPLUS:GENES_CONCAT                               -
> [-        ] process > BACTOPIA:AMRFINDERPLUS:PROTEINS_CONCAT                            -
> [-        ] process > BACTOPIA:MLST:MLST_MODULE                                         -
> [-        ] process > BACTOPIA:MLST:CSVTK_CONCAT                                        -
> [-        ] process > BACTOPIA:DUMPSOFTWAREVERSIONS                                     -
> [4b/81f131] NOTE: Process `BACTOPIA:ASSEMBLER:ASSEMBLER_MODULE (Batch064_C_02_S_ESBL_03_Sub)` terminated with an error exit status (1) -- Execution is retried (3)
> ERROR ~ Error executing process > 'BACTOPIA:ASSEMBLER:ASSEMBLER_MODULE (Batch064_C_02_S_ESBL_03_Sub)'
> 
> Caused by:
>   Process `BACTOPIA:ASSEMBLER:ASSEMBLER_MODULE (Batch064_C_02_S_ESBL_03_Sub)` terminated with an error exit status (1)
> 
> Command executed:
> 
>   if [ "null" == "true" ]; then
>       mkdir results
>       gzip -cd empty.fna.gz > results/Batch064_C_02_S_ESBL_03_Sub.fna
>   elif [[ "ont" == "hybrid" || "false" == "true" ]]; then
>       # Unicycler
>       unicycler \
>           -1 Batch064_C_02_S_ESBL_03_Sub.fastq.gz -2 null \
>           --keep 1 --min_fasta_length 500 --mode normal --min_component_size 1000 --min_dead_end_size 1000 \
>            \
>           -o results/ \
>           --threads 10
>       sed -r 's/^>([0-9]+)(.*)/>Batch064_C_02_S_ESBL_03_Sub_\1\2/' results/assembly.fasta > results/Batch064_C_02_S_ESBL_03_Sub.fna
>       mv results/assembly.gfa results/unicycler.gfa
>   elif [[ "ont" == "ont" || "ont" == "short_polish" ]]; then
>       # Dragonflye
>       if ! dragonflye \
>           --reads Batch064_C_02_S_ESBL_03_Sub.fastq.gz \
>           --gsize 8000000 \
>           --outdir results \
>           --assembler flye --opts '--nanohq' --model r1041_e82_400bps_sup_g615 --polypolish 1 --minlen 500 --mincov 2 --force --keepfiles --depth 0 --minreadlen 0 --minquality 0 --racon 3 --medaka 2 \
>           --namefmt "Batch064_C_02_S_ESBL_03_Sub_%05d" \
>           --cpus 10 \
>           --ram 31; then
>   
>           # Check if error is due to no contigs
>           if grep "has zero contigs" results/dragonflye.log; then
>               touch results/contigs.fa
>           else
>               exit 1
>           fi
>       fi
>       mv results/contigs.fa results/Batch064_C_02_S_ESBL_03_Sub.fna
>   else
>       # Shovill
>       if ! shovill-se --SE Batch064_C_02_S_ESBL_03_Sub.fastq.gz \
>           --gsize 8000000 \
>           --outdir results \
>           --assembler skesa --minlen 500 --mincov 2 --force --keepfiles --depth 0 --noreadcorr \
>           --namefmt "Batch064_C_02_S_ESBL_03_Sub_%05d" \
>           --cpus 10 \
>           --ram 31; then
>   
>           # Check if error is due to no contigs
>           if grep "has zero contigs" results/shovill.log; then
>               touch results/contigs.fa
>           else
>               exit 1
>           fi
>       fi
>       mv results/contigs.fa results/Batch064_C_02_S_ESBL_03_Sub.fna
>   
>       # Rename Graphs
>       if [ -f "results/contigs.gfa" ]; then
>           mv results/contigs.gfa results/skesa-unpolished.gfa
>       elif [ -f "results/contigs.fastg" ]; then
>           mv results/contigs.fastg results/skesa-unpolished.gfa
>       elif [ -f "results/contigs.LastGraph" ]; then
>           mv results/contigs.LastGraph results/skesa-unpolished.gfa
>       fi
>   
>       if [ -f "results/flye-info.txt" ]; then
>           mv results/flye-info.txt results/flye.log
>       fi
>   fi
>   
>   # Check quality of assembly
>   TOTAL_CONTIGS=`grep -c "^>" results/Batch064_C_02_S_ESBL_03_Sub.fna || true`
>   if [ "${TOTAL_CONTIGS}" -gt 0 ]; then
>       assembly-scan results/Batch064_C_02_S_ESBL_03_Sub.fna --prefix Batch064_C_02_S_ESBL_03_Sub > results/Batch064_C_02_S_ESBL_03_Sub.tsv
>       TOTAL_CONTIG_SIZE=$(cut -f 3 results/Batch064_C_02_S_ESBL_03_Sub.tsv | tail -n 1)
>       if [ "${TOTAL_CONTIG_SIZE}" -lt 100000 ]; then
>           mv results/Batch064_C_02_S_ESBL_03_Sub.fna results/Batch064_C_02_S_ESBL_03_Sub-error.fna
>           mv results/Batch064_C_02_S_ESBL_03_Sub.tsv results/Batch064_C_02_S_ESBL_03_Sub-error.tsv
>           echo "Batch064_C_02_S_ESBL_03_Sub assembled size (${TOTAL_CONTIG_SIZE} bp) is less than the minimum allowed genome
>                   size (100000 bp). If this is unexpected, please investigate Batch064_C_02_S_ESBL_03_Sub to
>                   determine a cause (e.g. metagenomic, contaminants, etc...) for the poor assembly.
>                   Otherwise, adjust the --min_genome_size parameter to fit your need. Further assembly
>                   based analysis of Batch064_C_02_S_ESBL_03_Sub will be discontinued." |             sed 's/^\s*//' > Batch064_C_02_S_ESBL_03_Sub-assembly-error.txt
>       fi
>   else
>       mv results/Batch064_C_02_S_ESBL_03_Sub.fna results/Batch064_C_02_S_ESBL_03_Sub-error.fna
>       echo "Batch064_C_02_S_ESBL_03_Sub assembled successfully, but 0 contigs were formed. Please investigate
>               Batch064_C_02_S_ESBL_03_Sub to determine a cause (e.g. metagenomic, contaminants, etc...) for this
>               outcome. Further assembly-based analysis of Batch064_C_02_S_ESBL_03_Sub will be discontinued." |         sed 's/^\s*//' > Batch064_C_02_S_ESBL_03_Sub-assembly-error.txt
>   fi
>   
>   # Cleanup and compress
>   if [ "false" == "false" ]; then
>       # Remove intermediate files
>       rm -rfv results/shovill.bam* \
>               results/shovill-se.bam* \
>               results/flash.extendedFrags* \
>               results/flash.notCombined* \
>               results/skesa.fasta* \
>               results/*.fq.gz \
>               results/00*.gfa \
>               results/pilon_polish* \
>               results/flye/ \
>               results/flye.fasta* \
>               results/raven/ \
>               results/raven.fasta* \
>               results/raven.cereal \
>               results/miniasm/ \
>               results/miniasm.fasta* \
>               results/spades/ \
>               results/spades.fasta* \
>               results/megahit/ \
>               results/megahit.fasta* \
>               results/velvet.fasta* \
>               results/velvet/
>   fi
>   
>   if [[ false == "false" ]]; then
>       # Compress based on matched extensions
>       find results/ -type f |             grep -E "\.fna$|\.fasta$|\.fa$|\.gfa$" |             xargs -I {} pigz -n --best -p 10 {}
>   fi
>   find results -maxdepth 1 -name "*.log" | xargs -I {} mv {} ./
>   
>   # Capture versions
>   if [[ "$OSTYPE" == "darwin"* ]]; then
>   
>   cat <<-END_VERSIONS > versions.yml
>   "BACTOPIA:ASSEMBLER:ASSEMBLER_MODULE":
>       assembly-scan: $(echo $(assembly-scan --version 2>&1) | sed 's/assembly-scan //')
>       bwa: $(echo $(bwa 2>&1) | sed 's/^.*Version: //;s/ .*$//')
>       flash: $(echo $(flash --version 2>&1) | sed 's/^.*FLASH v//;s/ .*$//')
>       megahit: $(echo $(megahit --version 2>&1) | sed 's/MEGAHIT v//')
>       miniasm: $(echo $(miniasm -V))
>       pigz: $(echo $(pigz --version 2>&1) | sed 's/pigz //')
>       pilon: $(echo $(pilon --version 2>&1) | sed 's/^.*Pilon version //;s/ .*$//')
>       racon: $(echo $(racon --version 2>&1) | sed 's/v//')
>       samclip: $(echo $(samclip --version 2>&1) | sed 's/samclip //')
>       samtools: $(echo $(samtools --version 2>&1) |sed 's/^.*samtools //;s/ .*$//')
>       shovill: $(echo $(shovill --version 2>&1) | sed 's/shovill //')
>       shovill-se: $(echo $(shovill-se --version 2>&1) | sed 's/shovill-se //')
>       skesa: $(echo $(skesa --version 2>&1) | sed 's/^.*SKESA //;s/ .*$//')
>       spades.py: $(echo $(spades.py --version 2>&1) | sed 's/SPAdes genome assembler v//')
>       velvetg: $(echo $(velvetg 2>&1) | sed 's/^.*Version //;s/ .*$//')
>       velveth: $(echo $(velveth 2>&1) | sed 's/^.*Version //;s/ .*$//')
>       unicycler: $(echo $(unicycler --version 2>&1) | sed 's/^.*Unicycler v//;s/ .*$//')
>   END_VERSIONS
>   
>   else
>   
>   cat <<-END_VERSIONS > versions.yml
>   "BACTOPIA:ASSEMBLER:ASSEMBLER_MODULE":
>       any2fasta: $(echo $(any2fasta -v 2>&1) | sed 's/any2fasta //')
>       assembly-scan: $(echo $(assembly-scan --version 2>&1) | sed 's/assembly-scan //')
>       bwa: $(echo $(bwa 2>&1) | sed 's/^.*Version: //;s/ .*$//')
>       flash: $(echo $(flash --version 2>&1) | sed 's/^.*FLASH v//;s/ .*$//')
>       flye: $(echo $(flye --version))
>       medaka: $(echo $(medaka --version 2>&1) | sed 's/medaka //')
>       megahit: $(echo $(megahit --version 2>&1) | sed 's/MEGAHIT v//')
>       miniasm: $(echo $(miniasm -V))
>       minimap2: $(echo $(minimap2 --version))
>       nanoq: $(echo $(nanoq --version 2>&1) | sed 's/nanoq //')
>       pigz: $(echo $(pigz --version 2>&1) | sed 's/pigz //')
>       pilon: $(echo $(pilon --version 2>&1) | sed 's/^.*Pilon version //;s/ .*$//')
>       racon: $(echo $(racon --version 2>&1) | sed 's/v//')
>       rasusa: $(echo $(rasusa --version 2>&1) | sed 's/rasusa //')
>       raven: $(echo $(raven --version))
>       samclip: $(echo $(samclip --version 2>&1) | sed 's/samclip //')
>       samtools: $(echo $(samtools --version 2>&1) |sed 's/^.*samtools //;s/ .*$//')
>       shovill: $(echo $(shovill --version 2>&1) | sed 's/shovill //')
>       shovill-se: $(echo $(shovill-se --version 2>&1) | sed 's/shovill-se //')
>       skesa: $(echo $(skesa --version 2>&1) | sed 's/^.*SKESA //;s/ .*$//')
>       spades.py: $(echo $(spades.py --version 2>&1) | sed 's/SPAdes genome assembler v//')
>       velvetg: $(echo $(velvetg 2>&1) | sed 's/^.*Version //;s/ .*$//')
>       velveth: $(echo $(velveth 2>&1) | sed 's/^.*Version //;s/ .*$//')
>       unicycler: $(echo $(unicycler --version 2>&1) | sed 's/^.*Unicycler v//;s/ .*$//')
>   END_VERSIONS
>   
>   fi
> 
> Command exit status:
>   1
> 
> Command output:
>   [flye] usage: flye (--pacbio-raw | --pacbio-corr | --pacbio-hifi | --nano-raw |
>   [flye] 	     --nano-corr | --nano-hq ) file1 [file_2 ...]
>   [flye] 	     --out-dir PATH
>   [flye] 
>   [flye] 	     [--genome-size SIZE] [--threads int] [--iterations int]
>   [flye] 	     [--meta] [--polish-target] [--min-overlap SIZE]
>   [flye] 	     [--keep-haplotypes] [--debug] [--version] [--help] 
>   [flye] 	     [--scaffold] [--resume] [--resume-from] [--stop-after] 
>   [flye] 	     [--read-error float] [--extra-params] 
>   [flye] 	     [--deterministic]
>   [flye] flye: error: unrecognized arguments: --nanohq
> 
> Command error:
>   [dragonflye] Using kmc - /usr/local/bin/kmc | K-Mer Counter (KMC) ver. 3.2.1 (2022-01-04)
>   [dragonflye] Using medaka - /usr/local/bin/medaka | medaka 1.8.0
>   [dragonflye] Using miniasm - /usr/local/bin/miniasm | 0.3-r179
>   [dragonflye] Using minimap2 - /usr/local/bin/minimap2 | 2.26-r1175
>   [dragonflye] Using nanoq - /usr/local/bin/nanoq | nanoq 0.10.0
>   [dragonflye] Using pigz - /usr/local/bin/pigz | pigz 2.6
>   [dragonflye] Using pilon - /usr/local/bin/pilon | Pilon version 1.24 Thu Jan 28 13:00:45 2021 -0500
>   [dragonflye] Using polypolish - /usr/local/bin/polypolish | Polypolish v0.5.0
>   [dragonflye] Using porechop - /usr/local/bin/porechop | 0.2.4
>   [dragonflye] Using racon - /usr/local/bin/racon | 1.5.0
>   [dragonflye] Using rasusa - /usr/local/bin/rasusa | rasusa 0.7.1
>   [dragonflye] Using raven - /usr/local/bin/raven | 1.8.1
>   [dragonflye] Using samclip - /usr/local/bin/samclip | samclip 0.4.0
>   [dragonflye] Using samtools - /usr/local/bin/samtools | Version: 1.17 (using htslib 1.17)
>   [dragonflye] Using seqtk - /usr/local/bin/seqtk | Version: 1.4-r122
>   [dragonflye] Using tempdir: /tmp/hI0mhe2DRw
>   [dragonflye] Changing into folder: results
>   [dragonflye] Collecting raw read statistics with 'seqtk'
>   [dragonflye] Running: seqtk fqchk -q3 \/mnt\/data2\/Food\/REAL\/work\/e4\/90596e69a832836062348098d4b381\/results\/Batch064_C_02_S_ESBL_03_Sub\.fastq\.gz 2>&1 1>/tmp/NbvrqkcLsE | sed 's/^/[seqtk] /' | tee -a dragonflye.log
>   [dragonflye] Read stats: total_bp = 667941920
>   [dragonflye] Read stats: max_len = 46604
>   [dragonflye] Read stats: min_len = 1068
>   [dragonflye] Read stats: avg_len = 4894
>   [dragonflye] Using genome size 8000000 bp
>   [dragonflye] Estimated sequencing depth: 83x
>   [dragonflye] No read filtering requested or necessary.
>   [dragonflye] No read depth reduction requested or necessary.
>   [dragonflye] No read adapter trimming requested.
>   [dragonflye] Running: ln -sf \/mnt\/data2\/Food\/REAL\/work\/e4\/90596e69a832836062348098d4b381\/results\/Batch064_C_02_S_ESBL_03_Sub\.fastq\.gz READS.fq.gz 2>&1 | sed 's/^/[ln] /' | tee -a dragonflye.log
>   [dragonflye] Collecting qc'd read statistics with 'seqtk'
>   [dragonflye] Running: seqtk fqchk -q3 READS\.fq\.gz 2>&1 1>/tmp/eJhOKoU8kS | sed 's/^/[seqtk] /' | tee -a dragonflye.log
>   [dragonflye] Final Read stats: avg_len = 4894
>   [dragonflye] Final Read stats: min_len = 1068
>   [dragonflye] Final Read stats: total_bp = 667941920
>   [dragonflye] Final Read stats: max_len = 46604
>   [dragonflye] Average read length looks like 4894 bp
>   [dragonflye] Assembling reads with 'flye'
>   [dragonflye] Running: flye --nano-raw READS.fq.gz -g 8000000 -i 0 --threads 10 -o flye --nanohq 2>&1 | sed 's/^/[flye] /' | tee -a dragonflye.log
>   [flye] usage: flye (--pacbio-raw | --pacbio-corr | --pacbio-hifi | --nano-raw |
>   [flye] 	     --nano-corr | --nano-hq ) file1 [file_2 ...]
>   [flye] 	     --out-dir PATH
>   [flye] 
>   [flye] 	     [--genome-size SIZE] [--threads int] [--iterations int]
>   [flye] 	     [--meta] [--polish-target] [--min-overlap SIZE]
>   [flye] 	     [--keep-haplotypes] [--debug] [--version] [--help] 
>   [flye] 	     [--scaffold] [--resume] [--resume-from] [--stop-after] 
>   [flye] 	     [--read-error float] [--extra-params] 
>   [flye] 	     [--deterministic]
>   [flye] flye: error: unrecognized arguments: --nanohq
>   [dragonflye] Error running command: flye --nano-raw READS.fq.gz -g 8000000 -i 0 --threads 10 -o flye --nanohq 2>&1 | sed 's/^/[flye] /' | tee -a dragonflye.log
> 
> Work dir:
>   /mnt/data2/Food/REAL/work/43/7808343f7755ade2a339321657cc15
> 
> Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
> 
>  -- Check '.nextflow.log' file for details

**Comment by rpetit3** [comment]
Hopefully an easy fix, but I think `--dragonflye_opts="--nanohq"` should be `--dragonflye_opts="--nano-hq"`
