### ISSUE TITLE
summary path not consistant with the tool suggest argument [bug]

### ISSUE THREAD

**Issue by alarawms** [bactopia/bactopia#417]
**Description**
A description of the bug you are experiencing.
when running summary program
bactopia summay --bactopia /path/to/bactopia/results

**Steps to Reproduce**
a summary of run 
```
bactopia ...
bactopia tools ...
!!ERROR!!
```

**Expected Behavior**
A description of what is expected to happen.
a resulted summary 
**Execution Environment**
bash - using conda and env and docker as execution 
- Bactopia Version: [output from `bactopia version`]
3.0.0
- OS: [e.g. Mac, Ubuntu, etc...]
Linux Fedora 38
- Environment: [e.g. conda, cluster, container, etc...]
conda, docker 
**Additional Information**
correction of the arrangement in the main program                                                                                                                                                                                    
 Missing option '--bactopia-path' / '-b'.

**Comment by rpetit3** [comment]
Hi @alarawms 

Looking into this, will report back soon

Cheers,
Robert

**Comment by rpetit3** [comment]
Hi @alarawms 

This should be fixed in the latest version of Bactopia (v3.0.1). If not please feel free to reopen

Cheers,
Robert
