### ISSUE TITLE
BACTOPIA STOPS AT GATHER SAMPLE STEP

### ISSUE THREAD

**Issue by Michaelijesse** [bactopia/bactopia#419]
I used the following command to check the running status of this tool.

bactopia --use_ena --accession SRX4563634 --datasets datasets/ --species "Staphylococcus aureus" --coverage 100 --outdir ena-single-sample --max_cpus 8 -profile docker

But it returns ERROR at GATHER_SAMPLES, the very first step. Please help me.

ATTACHMENT Log File.
[output.log](https://github.com/bactopia/bactopia/files/11594709/output.log)

**Comment by rpetit3** [comment]
Hi @Michaelijesse, 

Based on the error message: 

```
  docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
  See 'docker run --help'.
```

Can you verify Docker is running?

Cheers,
Robert

**Comment by Michaelijesse** [comment]
First, I used 
1) docker run command
2) docker exec command

Now I am working as root user and inside bactopia environment.

'docker run --help' gives

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Create and run a new container from an image

Aliases:
  docker container run, docker run

Options:
      --add-host list                  Add a custom host-to-IP mapping
                                       (host:ip)
  -a, --attach list                    Attach to STDIN, STDOUT or STDERR
      --blkio-weight uint16            Block IO (relative weight),
                                       between 10 and 1000, or 0 to
                                       disable (default 0)
      --blkio-weight-device list       Block IO weight (relative device
                                       weight) (default [])
      --cap-add list                   Add Linux capabilities
      --cap-drop list                  Drop Linux capabilities
      --cgroup-parent string           Optional parent cgroup for the
                                       container
      --cgroupns string                Cgroup namespace to use
                                       (host|private)
                                       'host':    Run the container in
                                       the Docker host's cgroup namespace
                                       'private': Run the container in
                                       its own private cgroup namespace
                                       '':        Use the cgroup
                                       namespace as configured by the
                                                  default-cgroupns-mode
                                       option on the daemon (default)
      --cidfile string                 Write the container ID to the file
      --cpu-period int                 Limit CPU CFS (Completely Fair
                                       Scheduler) period
      --cpu-quota int                  Limit CPU CFS (Completely Fair
                                       Scheduler) quota
      --cpu-rt-period int              Limit CPU real-time period in
                                       microseconds
      --cpu-rt-runtime int             Limit CPU real-time runtime in
                                       microseconds
  -c, --cpu-shares int                 CPU shares (relative weight)
      --cpus decimal                   Number of CPUs
      --cpuset-cpus string             CPUs in which to allow execution
                                       (0-3, 0,1)
      --cpuset-mems string             MEMs in which to allow execution
                                       (0-3, 0,1)
  -d, --detach                         Run container in background and
                                       print container ID
      --detach-keys string             Override the key sequence for
                                       detaching a container
      --device list                    Add a host device to the container
      --device-cgroup-rule list        Add a rule to the cgroup allowed
                                       devices list
      --device-read-bps list           Limit read rate (bytes per second)
                                       from a device (default [])
      --device-read-iops list          Limit read rate (IO per second)
                                       from a device (default [])
      --device-write-bps list          Limit write rate (bytes per
                                       second) to a device (default [])

**Comment by rpetit3** [comment]
Is your user apart of the docker group?

**Comment by Michaelijesse** [comment]
I am working in CentOS through user. 
For docker, I used docker run -itd and docker exec which entered into root of docker.

**Comment by Michaelijesse** [comment]
Still I cannot able to figure out the problem. Is this problem for everyone or just for me.??

**Comment by Michaelijesse** [comment]
I am waiting for your reply.

**Comment by Michaelijesse** [comment]
@rpetit3 
[staph_aur.txt](https://github.com/bactopia/bactopia/files/11597129/staph_aur.txt)

**Comment by Michaelijesse** [comment]
Even the following command
 bactopia search PRJNA480016 --limit 5
 Creates the files but no contents inside the file.
 
[ena-accessions.txt](https://github.com/bactopia/bactopia/files/11607186/ena-accessions.txt)
[ena-filtered.txt](https://github.com/bactopia/bactopia/files/11607187/ena-filtered.txt)
[ena-results.txt](https://github.com/bactopia/bactopia/files/11607188/ena-results.txt)
[ena-summary.txt](https://github.com/bactopia/bactopia/files/11607189/ena-summary.txt)

**Comment by rpetit3** [comment]
Hi @Michaelijesse

I would recommend trying my dev version: https://github.com/bactopia/bactopia/issues/394

There have been some recent changes to the ENA API (fields no longer available). My dev version is starting to get these fixes. I'm hoping to release a new version soon, but have a few loose ends I would like to tie up first.

Let me know if you have any questions on getting started.
Robert

**Comment by Michaelijesse** [comment]
I bactopia v2, I faced this new error when setting up datasets

(bactopia) bactopia datasets --outdir /home/centos/Michael/Bacto_new/datasets --species 'Staphylococcus aureus' --include_genus
2023-06-12 23:59:32:root:INFO - Staphylococcus aureus verified in ENA Taxonomy database
2023-06-12 23:59:32:root:INFO - Setting up pre-computed Genbank/Refseq minmer datasets
2023-06-12 23:59:32:root:INFO - /home/centos/Michael/Bacto_new/datasets/minmer/sourmash-genbank-k21.json.gz exists, skipping
2023-06-12 23:59:32:root:INFO - /home/centos/Michael/Bacto_new/datasets/minmer/sourmash-genbank-k31.json.gz exists, skipping
2023-06-12 23:59:32:root:INFO - /home/centos/Michael/Bacto_new/datasets/minmer/sourmash-genbank-k51.json.gz exists, skipping
2023-06-12 23:59:32:root:INFO - /home/centos/Michael/Bacto_new/datasets/minmer/mash-refseq-k21.msh exists, skipping
2023-06-12 23:59:32:root:INFO - Setting up antimicrobial resistance datasets
2023-06-12 23:59:32:root:INFO - Setting up latest AMRFinder+ database
2023-06-12 23:59:47:root:INFO - AMRFinder+ database saved to /home/centos/Michael/Bacto_new/datasets/antimicrobial-resistance/amrfinderdb.tar.gz
2023-06-12 23:59:47:root:INFO - Setting up MLST datasets
2023-06-12 23:59:47:root:INFO - Staphylococcus aureus MLST Schema (default) exists, skipping
2023-06-12 23:59:47:root:INFO - Setting up custom Prokka proteins
2023-06-12 23:59:47:root:INFO - Incomplete setup, deleting /home/centos/Michael/Bacto_new/datasets/species-specific/staphylococcus-aureus/annotation to start over
2023-06-12 23:59:47:root:INFO - Setting up custom Prokka proteins for Staphylococcus aureus
2023-06-12 23:59:47:root:INFO - Downloading genomes (assembly level: complete)
External command failed with exit code 1!

Command:
bash -c 'ncbi-genome-download bacteria -g "Staphylococcus" -l complete -F genbank -r 80 --dry-run'

Standard error:
Traceback (most recent call last):
  File "/home/centos/miniconda3/envs/bactopia/bin/ncbi-genome-download", line 10, in <module>
    sys.exit(main())
  File "/home/centos/miniconda3/envs/bactopia/lib/python3.9/site-packages/ncbi_genome_download/__main__.py", line 26, in main
    ret = args_download(args)
  File "/home/centos/miniconda3/envs/bactopia/lib/python3.9/site-packages/ncbi_genome_download/core.py", line 178, in args_download
    return config_download(config)
  File "/home/centos/miniconda3/envs/bactopia/lib/python3.9/site-packages/ncbi_genome_download/core.py", line 197, in config_download
    download_candidates = select_candidates(config)
  File "/home/centos/miniconda3/envs/bactopia/lib/python3.9/site-packages/ncbi_genome_download/core.py", line 308, in select_candidates
    for entry in filter_entries(entries, config):
  File "/home/centos/miniconda3/envs/bactopia/lib/python3.9/site-packages/ncbi_genome_download/core.py", line 354, in filter_entries
    if not config.is_compatible_assembly_accession(entry['assembly_accession']):
KeyError: 'assembly_accession'
(bactopia)

**Comment by rpetit3** [comment]
Hi @Michaelijesse 

This is related to a upstream change needed to ncbi-genome-download. I've submitted a patch to the Bioconda recipe based on an open PR to ncbi-genome-download.

Please see https://github.com/bactopia/bactopia/issues/422 for more details if you want to manually edit a file with a fix.

Hopefully this will get sorted soon.

Cheers,
Robert

**Comment by rpetit3** [comment]
@Michaelijesse 

I'm happy to report I have [released version 3 of Bactopia](https://github.com/bactopia/bactopia/releases/tag/v3.0.0). With this release, your issue should now be taken care of. 

If not please feel free to reopen this issue or create a new one.

Thanks for using Bactopia!
Robert
