### ISSUE TITLE
[bactopia-tool] Phispy

### ISSUE THREAD

**Issue by Kiratrea** [bactopia/bactopia#421]
Tool Name: Phispy (or the equivalent, to identify prophages in bacterial genomes) 

Tool Link:

Available on [Bioconda](https://anaconda.org/bioconda/phispy)

Available on [nf-core/modules](https://github.com/nf-core/modules/tree/master/modules/nf-core/phispy)

Sorry if there is a already a tool for this and I missed it, thank you so much for the awesome pipeline!

**Comment by lfenske-93** [comment]
I would appreciate this as well! I am still looking for a tool for phage detection and Phispy sounds very promising.

**Comment by rpetit3** [comment]
This was on my list to include, I'll get it added to my dev build. 

Will update soon!

**Comment by rpetit3** [comment]
This is now available in my dev build

**Comment by rpetit3** [comment]
Hi @lfenske-93 

I've finally released v3! This is in there, thank you so much for all your feedback and support!

Robert
