### ISSUE TITLE
new version of bactopia sif file[question]

### ISSUE THREAD

**Issue by mtswanson2017** [bactopia/bactopia#423]
Hi!

Thanks for all of your work on bactopia!

I've been having a lot of trouble getting bactopia to run on my university's HPC system with singularity, specifically running into an error not being able to run the cat command during the prokka annotation step. I'm trying to run bactopia now with the sif file in order to fix potential temp directory issues, but the sif file that results from the instructions on the installation page (singularity pull library://rpetit3/bactopia/bactopia) is for bactopia 1.5.5. Is there a way I can access a newer version of the sif file for bactopia?

Thanks again!
Mark

**Comment by mtswanson2017** [comment]
Sweet, thank you so much Robert!!!
[slurm-6801894.txt](https://github.com/bactopia/bactopia/files/12036075/slurm-6801894.txt)

Our job scheduler is slurm. I've been using the conda install of the bactopia development version. Nextflow seems to be working. I attached an example outfile. The QC, assembly, and initial annotation steps work well, but there is a problem with prokka. I've seen that this has been a problem with setting the temp directory in the past, but even when I run everything through my scratch directory I still get this problem.

Thank you again for your help and I would be grateful for any suggestions you could provide!!
Mark

**Comment by rpetit3** [comment]
Take a look at this: https://github.com/bactopia/bactopia/blob/master/conf/profiles/arcc.config

This is a config file I use for a SLURM cluster here in Wyoming. It looks something like this:

```
conda activate bactopia-dev
bactopia -profile test,arcc
```

So I'm using conda to launch Bactopia, but then with my `arcc` profile Nextflow is submitting the jobs to SLURM and using Singularity for the jobs.

Do you by chance a sbatch script with the options (e.g. queue name) that you used to submit before? I bet we can start with the `slurm` profile in Bactopia and change these options: https://github.com/bactopia/bactopia/blob/master/conf/profiles/slurm.config#L6-L8 

Eventually if we get it working, we can create a profile for you and I can add it to bactopia, or you can just hold on to it, but eitherway it would save you the hassle of always remembering the parameters.

**Comment by mtswanson2017** [comment]
Thanks so much Robert!!

Bactopia doesn't make it as far using -profile test,arcc as it does using -profile singularity. I've attached the sbatch job script I've been using and the output file from using -profile test,arcc. Its always worked for me to set a minimum memory needed for the job instead of setting a specific queue on our HPC.

I'm wondering now if I just need to use a newer version of anaconda than is available as a module on our HPC.

[bactopia_mts73_july4.txt](https://github.com/bactopia/bactopia/files/12065138/bactopia_mts73_july4.txt)

[slurm-7096517.txt](https://github.com/bactopia/bactopia/files/12065139/slurm-7096517.txt)

Thank you again for all of your help and I apologize if I am missing something obvious!!!
Mark

**Comment by rpetit3** [comment]
OK, let's give this a try:

```
# On the log in node (not after submitting a job via sbatch)
conda activate bactopia-dev

# We'll use Nextflow via Conda, but tell Nextflow to submit jobs to SLURM and to use Singularity
bactopia -profile test,slurm --slurm_queue "" --slurm_opts="--account pi-blekhman"

```

Let's see if this works for you. If it does, Nextflow will handle all the creation of the sbatch scripts passively, but I can point you to where they are actually created. 

We might have to make a few tweaks, but step in the right direction. Does your SLURM cluster have any publicly available docs by chance?

**Comment by mtswanson2017** [comment]
Sweet! Thank you so much Robert!

I'm not sure what the output is supposed to look like, but here is what happened when I added those flags to the command and ran it on the login node:

[bactopia_loginnode_out.txt](https://github.com/bactopia/bactopia/files/12100777/bactopia_loginnode_out.txt)

I tried to run it on our build node but it has been busy.

This is the user guide for our cluster (midway3) but let me know if you are looking for a different type of doc:
https://rcc-uchicago.github.io/user-guide/midway23/midway_getting_started/

Thank you again for your help with this!!

**Comment by mtswanson2017** [comment]
Hi Robert!
I just wanted to update you that I got the same result when I ran those commands on the build node, and when I just used the line you suggested instead of adding those flags to the other bactopia commands:
[bactopia_buildnode_out.txt](https://github.com/bactopia/bactopia/files/12149487/bactopia_buildnode_out.txt)

Thanks again for your help and let me know if you have other ideas or need more information!

**Comment by rpetit3** [comment]
Hi @mtswanson2017 

Do you by chance have the STDERR output from this run?

**Comment by rpetit3** [comment]
Also, thank you for the docs! 

I wonder if we should use the `caslake` partition (https://rcc-uchicago.github.io/user-guide/midway23/midway_partitions/)

```
bactopia -profile test,slurm --slurm_queue "caslake" --slurm_opts="--account pi-blekhman"
```

**Comment by mtswanson2017** [comment]
Ok, thanks! Specifying caslake as the partition pushed it a lot farther. Now the test dataset is getting stuck on the same step my real datasets were getting stuck at on the annotation step with prokka. This is the output from running the command in your previous message on our build node:
[bactopia_rcc_caslake.txt](https://github.com/bactopia/bactopia/files/12178259/bactopia_rcc_caslake.txt)

I'm not quite sure where the STDERR is, I've been looking but haven't found it.

Thank you so much for your help and I'm happy to provide any other information you need!

**Comment by rpetit3** [comment]
Awesome! Looking at the log, it looks like things are being submitted to SLURM, so that is really good.

The prokka error is here:
```
  [19:04:14] Could not run command: cat SRR2838702\/SRR2838702\.proteins\.tmp\.77\.faa | parallel --gnu --plain -j 2 --block 6310 --recstart '>' --pipe blastp -query - -db SRR2838702/proteins -evalue 1e-09 -qcov_hsp_perc 80 -num_threads 1 -num_descriptions 1 -num_alignments 1 -seg no > SRR2838702\/SRR2838702\.proteins\.tmp\.77\.blast 2> /dev/null
```

I've seen this one before on another cluster, I think ti was related to the temp directory. Let me check reach out to those folks to see what their solution was.

**Comment by mtswanson2017** [comment]
Thanks so much Robert!

I tried setting the temp directory to some different places with the HPC staff here, but we never found a solution that got past that error. I'm looking forward to hearing what worked for that other group!

**Comment by rpetit3** [comment]
Reached out, one solution they had that worked for them was to reduce the number of threads and/or jobs being submitted.

Did the test profile also fail for you? If so, let's try this:

```
bactopia -profile test,slurm --slurm_queue "caslake" --slurm_opts="--account pi-blekhman" -qs 1 --max_cpus 1
```

This will submit only 1 job at a time (`-qs 1`) and limit each job to 1 cpu (`--max_cpus 1`). We're purely debugging at this point to see if we can get a solution that actually finishes this go from there.

**Comment by mtswanson2017** [comment]
I was also wondering if there is an option for turning off the annotation step? When I use the assembled contigs for a separately installed version of prokka it works just fine. When I use the bakta option, I get a different error message.
Thanks again for your help!

**Comment by rpetit3** [comment]
Currently no way to disable annotation.

Are you running Prokka on the cluster as well? 

What's the error message on Bakta?

**Comment by mtswanson2017** [comment]
Yep, I used prokka independently on the same cluster I have bactopia-dev installed on.

Here is the error message for running the bakta option on the cluster:
[bactopia_bakta_error.txt](https://github.com/bactopia/bactopia/files/12236105/bactopia_bakta_error.txt)

Thanks for your continued help!!

**Comment by rpetit3** [comment]
The Bakta one looks similar to this which seems TMPDIR related as well: https://github.com/oschwengers/bakta/issues/187

I wonder if its worth doing some more debugging here, if you are interested. Since we know Prokka works independently on the cluster, I'm wondering if its related to Nextflow's communication with SLURM cluster.

Can you share the sbatch script you submit to run Prokka independently? I'm wondering if we can play around a bit, I'm thinking it might be interesting to see what environment variables (`env`) are present between independent Prokka and Bactopia's Prokka

**Comment by mtswanson2017** [comment]
Hi Robert!
I am really sorry for the late reply. I had a hard time recreating what I did to get working prokka working independently on the cluster and I took a week of vacation.

It turns out, I didn't get prokka working independently on the cluster! The independent installation of of prokka produces the same error as when it is run as a part of the bactopia pipeline. BUT(!) it works on the cluster when I activate the bactopia-dev environment and call prokka separately. No idea what that means but seems interesting.

I'm happy to do anything that is helpful as far as debugging goes! I'll reply faster next time!

Here is my sbatch script that successfully produces prokka annotations:
[prokka_bactopia_env.txt](https://github.com/bactopia/bactopia/files/12308049/prokka_bactopia_env.txt)

Here is the output from that script:
[slurm-7666841.txt](https://github.com/bactopia/bactopia/files/12308069/slurm-7666841.txt)

Thanks again for your help and let me know what I can do!
Mark

**Comment by rpetit3** [comment]
Welcome back! I hope your time away was nice!

I have played around with Prokka a bit, and made some changes to hopefully help us get the error message we need.

When you have the time, rebuild the `bactopia-dev` environment, and give the test profile (or one of your samples a try)

```
mamba create -n bactopia-dev -c rpetit3 -c conda-forge -c bioconda bactopia
bactopia -profile test,slurm --slurm_queue "caslake" --slurm_opts="--account pi-blekhman" -qs 1 --max_cpus 1
```

**Comment by chantisakee** [comment]
Hi, 

I am a Slurm Cluster user. First, I ran the Bactopia pipeline with the singularity container and got an error in the Prokka process as @mtswanson2017 got. then I changed to the Conda environment, and it works fine.

**Comment by rpetit3** [comment]
Hi All!

I'm not too sure where we left off here. Given the time, I think it might be best to open a new issue. 

Cheers,
Robert

**Comment by Sylvial-00** [comment]
If anyone ever has the same issue with Prokka/Bakta again on an HPC slurm environment, I just added --container_opts '-B $TMPDIR:$TMPDIR' to my bactopia run, using singularity. The TMPDIR variable may be different for your own HPC, check for that. But this worked for me.
