### ISSUE TITLE
[question] Usage of modules

### ISSUE THREAD

**Issue by Kokejuli** [bactopia/bactopia#424]
Hello there, I am Koke. The first thing i want to say is thank you for such an incredible job! Secondly, I have completed a bactopia standard analysis and my results are stored in the output path `OUTDIR/Test1`, all the output directories are created. However, I was trying to run the module `seqsero2` in order to perform a sequence typing in _Salmonella_ species samples, but I did not reach this.

As it is specified in the documentation, the only necessary input is the bactopia output, but it seems the module didn't get the input files:

This is the command I am using:

`bactopia --wf seqsero2 --bactopia OUTDIR/Test1`

Here I leave the verbose:

Thank you so much!

```
antimicrobial-resistance does not appear to be a Bactopia sample, skipping...
blast does not appear to be a Bactopia sample, skipping...
minmers does not appear to be a Bactopia sample, skipping...
annotation does not appear to be a Bactopia sample, skipping...
variants does not appear to be a Bactopia sample, skipping...
assembly does not appear to be a Bactopia sample, skipping...
logs does not appear to be a Bactopia sample, skipping...
mlst does not appear to be a Bactopia sample, skipping...
quality-control does not appear to be a Bactopia sample, skipping...
mapping does not appear to be a Bactopia sample, skipping...
Found 0 samples to process

If this looks wrong, now's your chance to back out (CTRL+C 3 times).
Sleeping for 5 seconds...
--------------------------------------------------------------------
[-        ] process > BACTOPIATOOLS:SEQSERO2:SEQSERO2_MODULE    -
[-        ] process > BACTOPIATOOLS:SEQSERO2:CSVTK_CONCAT       -
[-        ] process > BACTOPIATOOLS:CUSTOM_DUMPSOFTWAREVERSIONS -

    Bactopia Tools: `seqsero2 Execution Summary
    ---------------------------
    Bactopia Version : 2.2.0
    Nextflow Version : 22.10.1
    Command Line     : nextflow run /opt/conda/envs/bactopia//share/bactopia-2.2.x/main.nf -w /media/work/ --wf seqsero2 --bactopia OUTDIR/Test1
    Resumed          : false
    Completed At     : 2023-07-17T14:44:05.732235606Z
    Duration         : 9.5s
    Success          : true
    Exit Code        : 0
    Error Report     : -
    Launch Dir       : /media
```

**Comment by rpetit3** [comment]
Hi @Kokejuli 

Try running it as `--bactopia OUTDIR/` Let me know if that works!

Cheers,
Robert

**Comment by Kokejuli** [comment]
Hi @rpetit3 ,

Yes, it works!

As you suggested, I had to pass as input the --outdir and not the folder with the results for the sample.

Thank you so much!!

**Comment by rpetit3** [comment]
Great, glad we got it figured out! If you are interested, I have a preview of Bactopia v3 that you can try here: https://github.com/bactopia/bactopia/issues/394

I'd be very curious to hear feedback!

**Comment by rpetit3** [comment]
Hi @Kokejuli 

I'm happy to report I have [released version 3 of Bactopia](https://github.com/bactopia/bactopia/releases/tag/v3.0.0). With this release, your issue should now be taken care of. 

If not please feel free to reopen this issue or create a new one.

Thanks for using Bactopia!
Robert
