### ISSUE TITLE
[question] AWS Batch/NF Tower Queue Size 

### ISSUE THREAD

**Issue by rwilliams** [bactopia/bactopia#425]
I'm trying to run Bactopia 3 on Nf Tower with AWS Batch as the executor. I'm using only the Docker profile (the AWS profile mostly gets overridden from Tower I think). I cannot figure out how to specify the queue size and it keeps calculating it based on the CPU's available to the Bactopia Head process. Can I add the `qs` or `queueSize` parameter to the params file or something similar? I've tried `executor.$awsbatch.queueSize = 1000` but have not had any luck.

Thanks and cheers.

**Comment by rpetit3** [comment]
I realize this isn't specifically for Batch, but do you have something similar to "queue size" under the advanced options seen here: https://help.tower.nf/23.1/compute-envs/altair-grid-engine/?h=queue+size#advanced-options

If we need to we can potentially get some of the Seqera/Tower folks looped in and they'll definitely be able to help out.

**Comment by rpetit3** [comment]
Sounds good. Please feel free to share any feedback on making Bactopia work better with Nextflow Tower. I plan to improve the Tower support going forward
