### ISSUE TITLE
[bug] WARN: There's no process matching config selector:

### ISSUE THREAD

**Issue by rwilliams** [bactopia/bactopia#430]
**Description**
When using the AWS profile to run bactopia via NF Tower/Batch we get warnings that there are no processes that match some of the profile config selectors.

output sample
```
!! Only displaying parameters that differ from the pipeline defaults !!
--------------------------------------------------------------------
If you use bactopia for your analysis please cite:
* Bactopia
  https://doi.org/10.1128/mSystems.00190-20
* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x
* Software dependencies
  https://bactopia.github.io/acknowledgements/
--------------------------------------------------------------------
WARN: There's no process matching config selector: fastq_status|qc_original_summary|qc_final_summary|mapping_query
WARN: There's no process matching config selector: mapping_query
WARN: There's no process matching config selector: qc_reads
WARN: There's no process matching config selector: assemble_genome|assembly_qc
Monitor the execution with Nextflow Tower using this URL: https://tower.nf/orgs/stuff/XdxxGclXQuGcS
[skipping] Stored process > BACTOPIA:DATASETS
```
**Steps to Reproduce**
The params file just has required params to run the pipeline
```
nextflow run https://github.com/bactopia/bactopia \
		 -name drunk_wright \
		 -params-file https://api.tower.nf/ephemeral/jBBKSpzEUnKZU3P7g98F8A.json \
		 -with-tower \
		 -r dev \
		 -profile aws \
		 -latest
```

**Expected Behavior**
Expect config selector in the profile to find the matching processes

**Execution Environment**

- Bactopia Version:  latest dev
- OS: Linux
- Environment: Tower with Batch Executor

**Additional Information**
I tried making a profile for NF Tower with Batchforge https://github.com/rwilliams/bactopia/commit/8791081bd6506fd70a0a3d89c8629dbe30d0e670. Tower overwrites most of the config from the AWS profile so this is a paired down version. It seems like some of the process names or labels are not present in 3.0.

**Comment by rpetit3** [comment]
Hi @rwilliams 

You are correct, much of the `withName` do not exist in v3. I'm getting to the point where I can start updating the old v2 configs for v3. They should be simpler going forward. I'm also hoping conduct some testing on Tower in the near future. 

I'm working on updating the documentation to reflect v3, once that's completed, then I should be able to circle back to the configs.

Cheers,
Robert

**Comment by rpetit3** [comment]
Hi @rwilliams 

I think this should no longer be an issue in v3. So I will go ahead an close for now.

In other news! I've release [Bactopia v3.0.1](https://bactopia.github.io/latest/changelog/#v301-bactopiabactopia-thats-my-girl-20240325). 

Also, it would be super useful if you took the time to complete my [2024 Bactopia Usage Survey](https://forms.gle/BA2BDHRQvZtpVcD38). 

Thank you so much!
Robert
