### ISSUE TITLE
[bug] Corrupted read inputs silently fail in BACTOPIA:GATHER:GATHER_MODULE

### ISSUE THREAD

**Issue by rwilliams** [bactopia/bactopia#431]
**Description**
Corrupted read inputs silently fail in gather step when running directly with Nextflow or via Tower.

**Steps to Reproduce**
Attempt to process corrupt read pairs running directly with Nextflow and BACTOPIA:GATHER:GATHER_MODULE returns with `succeeded` status.

Execution log for Gather module
```
gzip: invalid magic
Nothing to parse in STDIN, please verify your file is not empty.
gzip: invalid magic
Nothing to parse in STDIN, please verify your file is not empty.
Traceback (most recent call last):
  File "/usr/local/bin/check-fastqs.py", line 96, in
    r1 = read_json(args.fq1)
  File "/usr/local/bin/check-fastqs.py", line 14, in read_json
    json_data = json.load(json_fh)
  File "/usr/local/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Expected Behavior**
BACTOPIA:GATHER:GATHER_MODULE should return an error or failed status if corrupt fastq.gz files are run. 

**Execution Environment**
- Bactopia Version: latest dev
- OS: Linux
- Environment: Tower Batchforge

**Additional Information**
It looks like Bactopia checks for this but when run directly with Nextflow/Tower it bypasses this check. I was accidentally corrupting my samples when uploading to s3 and this had me pretty stumped.

**Comment by rpetit3** [comment]
Hi @rwilliams

You are correct again, locally it does the check, but when files are remote it skips the check.

Let me figure out why the `check-fastqs.py` script didn't capture this. 

Thanks for reporting,
Robert

**Comment by rpetit3** [comment]
OK I added a gzip check (https://github.com/bactopia/bactopia/commit/2da04df06aebefbd5a04eae050a5a1dd57ed1dab) in the `gather` step. 

It should produce a file `<SAMPLE_NAME>-gzip-error.txt` when `gzip -t` fails.

**Comment by rpetit3** [comment]
Hi @rwilliams 

I'm happy to report I have [released version 3 of Bactopia](https://github.com/bactopia/bactopia/releases/tag/v3.0.0). With this release, your issue should now be taken care of. 

If not please feel free to reopen this issue or create a new one.

Thanks for using Bactopia!
Robert
