### ISSUE TITLE
[question] Testing Prokka Module

### ISSUE THREAD

**Issue by rwilliams** [bactopia/bactopia#438]
I'm running into some issues with the Prokka module on NF Tower. I'd like to be able to just feed it a fasta to test without running the full bactopia pipeline. It tried to use the syntax from the [tests](https://github.com/bactopia/bactopia/blob/dev/tests/subworkflows/test_prokka.yml) but it looks like it's outdated. Is there a quick way to just run the Prokka module using similar syntax to the old test?

Cheers
Ron

**Comment by rpetit3** [comment]
Hi Ron, 

Take a look at these: 

https://github.com/bactopia/bactopia/blob/dev/subworkflows/local/prokka/test.nf
https://github.com/bactopia/bactopia/blob/dev/subworkflows/local/prokka/test.yml

These are the actual tests of Prokka, there other is to just see if the help message prints.

**Comment by rpetit3** [comment]
Should add, here's how I run it locally:

```
BACTOPIA_ARGS="-profile docker --is_ci --test_data_dir /home/robert_petit/repos/bactopia-tests/data" TMPDIR=~ pytest --wt 10 --symlink --keep-workflow-wd --ignore conda/ --ignore bactopia-tests/ --ignore temp/ --git-aware --tag prokk
```

**Comment by rpetit3** [comment]
Also, mind sharing the error message on Tower? I wonder if it was related to tmpdir at the parallel step with prokka

**Comment by rpetit3** [comment]
Thanks for sharing! Keep me posted. I don't get to play with AWS much (haven't touched Wave at all yet), but we can probably get it figured out.
