### ISSUE TITLE
ERROR ~ Error executing process > 'BACTOPIA:GATHER:GATHER_MODULE

### ISSUE THREAD

**Issue by nksjplai** [bactopia/bactopia#444]
HI Bactopia team,

I use the following command in bactopia environment, locally,  to test the pipeline:

```
bactopia \
    --r1 ISS_1F1_P_R1.fastq.gz \
    --r2 ISS_1F1_P_R2.fastq.gz \
    --sample ISS_1F1_P \
    --coverage 100 \
    --genome_size 2800000 \
    --outdir local-single-sample \
    --max_cpus 36

This command resulted in following error:
--------------------------------------------------------------------------------------------------------------------
executor >  local (5)
[1b/6aef88] process > BACTOPIA:DATASETS                         [  0%] 0 of 1
[85/665064] process > BACTOPIA:GATHER:GATHER_MODULE (ISS_1F1_P) [ 75%] 3 of 4, failed: 3, retries: 3
[-        ] process > BACTOPIA:GATHER:CSVTK_CONCAT              -
[-        ] process > BACTOPIA:QC:QC_MODULE                     -
[-        ] process > BACTOPIA:ASSEMBLER:ASSEMBLER_MODULE       -
[-        ] process > BACTOPIA:ASSEMBLER:CSVTK_CONCAT           -
[-        ] process > BACTOPIA:SKETCHER:SKETCHER_MODULE         -
[-        ] process > BACTOPIA:ANNOTATOR:PROKKA_MODULE          -
[-        ] process > BACTOPIA:AMRFINDERPLUS:AMRFINDERPLUS_RUN  -
[-        ] process > BACTOPIA:AMRFINDERPLUS:GENES_CONCAT       -
[-        ] process > BACTOPIA:AMRFINDERPLUS:PROTEINS_CONCAT    -
[-        ] process > BACTOPIA:MLST:MLST_MODULE                 -
[-        ] process > BACTOPIA:MLST:CSVTK_CONCAT                -
[-        ] process > BACTOPIA:DUMPSOFTWAREVERSIONS             -
[66/e56ce4] NOTE: Process `BACTOPIA:GATHER:GATHER_MODULE (ISS_1F1_P)` terminated with an error exit status (1) -- Execution is retried (1)
[af/970758] NOTE: Process `BACTOPIA:GATHER:GATHER_MODULE (ISS_1F1_P)` terminated with an error exit status (1) -- Execution is retried (2)
[04/f57b7f] NOTE: Process `BACTOPIA:GATHER:GATHER_MODULE (ISS_1F1_P)` terminated with an error exit status (1) -- Execution is retried (3)
ERROR ~ Error executing process > 'BACTOPIA:GATHER:GATHER_MODULE (ISS_1F1_P)'
-------------------------------------------------------------------------------------------------------------------------------------------
```

Please help trouble shooting the same

Thanks for your time and effort.

Nitin

**Comment by rpetit3** [comment]
Hi @nksjplai 

Could you by chance share the `.nextflow.log` file? It will be in the same directory you executed the command

**Comment by nksjplai** [comment]
[bactopia-trace.txt](https://github.com/bactopia/bactopia/files/12623698/bactopia-trace.txt)
Don't See one in the directory. I have attache the one text file I do see in the nf-reports directory.

Thank for the prompt reply.

**Comment by rpetit3** [comment]
Let's try running the command again, then in the same directory you ran the command there should be a hidden `.nextflow.log` file (`ls -lha`).

otherwise if you can share more of the error message that gets printed to the screen (the red text)

**Comment by nksjplai** [comment]
here is everything that got printed in red:

executor >  local (5)
[-        ] process > BACTOPIA:DATASETS                         -
[98/2f6826] process > BACTOPIA:GATHER:GATHER_MODULE (ISS_1F1_P) [100%] 4 of 4, failed: 4, retries: 3 ✘
[-        ] process > BACTOPIA:GATHER:CSVTK_CONCAT              -
[-        ] process > BACTOPIA:QC:QC_MODULE                     -
[-        ] process > BACTOPIA:ASSEMBLER:ASSEMBLER_MODULE       -
[-        ] process > BACTOPIA:ASSEMBLER:CSVTK_CONCAT           -
[-        ] process > BACTOPIA:SKETCHER:SKETCHER_MODULE         -
[-        ] process > BACTOPIA:ANNOTATOR:PROKKA_MODULE          -
[-        ] process > BACTOPIA:AMRFINDERPLUS:AMRFINDERPLUS_RUN  -
[-        ] process > BACTOPIA:AMRFINDERPLUS:GENES_CONCAT       -
[-        ] process > BACTOPIA:AMRFINDERPLUS:PROTEINS_CONCAT    -
[-        ] process > BACTOPIA:MLST:MLST_MODULE                 -
[-        ] process > BACTOPIA:MLST:CSVTK_CONCAT                -
[-        ] process > BACTOPIA:DUMPSOFTWAREVERSIONS             -
[6f/c2a76c] NOTE: Process `BACTOPIA:GATHER:GATHER_MODULE (ISS_1F1_P)` terminated with an error exit status (1) -- Execution is retried (1)
[d4/81845c] NOTE: Process `BACTOPIA:GATHER:GATHER_MODULE (ISS_1F1_P)` terminated with an error exit status (1) -- Execution is retried (2)
[be/457dbf] NOTE: Process `BACTOPIA:GATHER:GATHER_MODULE (ISS_1F1_P)` terminated with an error exit status (1) -- Execution is retried (3)
ERROR ~ Error executing process > 'BACTOPIA:GATHER:GATHER_MODULE (ISS_1F1_P)'

Caused by:
  Process `BACTOPIA:GATHER:GATHER_MODULE (ISS_1F1_P)` terminated with an error exit status (1)

Command executed:

  MERGED="multiple-read-sets-merged.txt"
  mkdir -p fastqs
  mkdir -p extra
  
  if [ "paired-end" == "paired-end" ]; then
      # Paired-End Reads
      cp -L 001-r1 fastqs/ISS_1F1_P_R1.fastq.gz
      cp -L 001-r2 fastqs/ISS_1F1_P_R2.fastq.gz
      touch extra/empty.fna.gz
  elif [ "paired-end" == "single-end" ]; then
      # Single-End Reads
      cp -L 001-r1 fastqs/ISS_1F1_P.fastq.gz
      touch extra/empty.fna.gz
  elif [ "paired-end" == "ont" ]; then
      # Nanopore reads
      cp -L 001-r1 fastqs/ISS_1F1_P.fastq.gz
      touch extra/empty.fna.gz
  elif  [ "paired-end" == "hybrid" ] || [ "paired-end" == "short_polish" ]; then 
      # Paired-End Reads
      cp -L 001-r1 fastqs/ISS_1F1_P_R1.fastq.gz
      cp -L 001-r2 fastqs/ISS_1F1_P_R2.fastq.gz
      cp -L EMPTY_EXTRA extra/ISS_1F1_P.fastq.gz
  elif [ "paired-end" == "merge-pe" ] || [ "paired-end" == "hybrid-merge-pe" ] || [ "paired-end" == "short_polish-merge-pe" ]; then 
      # Merge Paired-End Reads
      echo "This sample had reads merged." > ${MERGED}
      echo "R1:" >> ${MERGED}
      find -name "*r1" | sort | xargs -I {} readlink {} | xargs -I {} ls -l {} | awk '{print $5"	"$9}' >> ${MERGED}
      find -name "*r1" | sort | xargs -I {} readlink {} | xargs -I {} cat {} > fastqs/ISS_1F1_P_R1.fastq.gz
      echo "Merged R1:" >> ${MERGED}
      ls -l fastqs/ISS_1F1_P_R1.fastq.gz | awk '{print $5"	"$9}' >> ${MERGED}
  
      echo "R2:" >> ${MERGED}
      find -name "*r2" | sort | xargs -I {} readlink {} | xargs -I {} ls -l {} | awk '{print $5"	"$9}' >> ${MERGED}
      find -name "*r2" | sort | xargs -I {} readlink {} | xargs -I {} cat {} > fastqs/ISS_1F1_P_R2.fastq.gz
      echo "Merged R2:" >> ${MERGED}
      ls -l fastqs/ISS_1F1_P_R2.fastq.gz | awk '{print $5"	"$9}' >> ${MERGED}
  
      if [ "paired-end" == "hybrid-merge-pe" ]; then
          cp -L EMPTY_EXTRA extra/ISS_1F1_P.fastq.gz
      else
          touch extra/empty.fna.gz
      fi
  elif [ "paired-end" == "merge-se" ]; then 
      # Merge Single-End Reads
      echo "This sample had reads merged." > ${MERGED}
      echo "SE:" >> ${MERGED}
      find -name "*r1" | sort | xargs -I {} readlink {} | xargs -I {} ls -l {} | awk '{print $5"	"$9}' >> ${MERGED}
      find -name "*r1" | sort | xargs -I {} readlink {} | xargs -I {} cat {} > fastqs/ISS_1F1_P.fastq.gz
      echo "Merged SE:" >> ${MERGED}
      ls -l fastqs/ISS_1F1_P.fastq.gz | awk '{print $5"	"$9}' >> ${MERGED}
  
      touch extra/empty.fna.gz
  elif [ "paired-end" == "sra_accession" ] || [ "paired-end" == "sra_accession_ont" ]; then
      if [ "4" == "3" ]; then
          echo "Unable to download ISS_1F1_P from both SRA and ENA 3 times. This may or may 
              not be a temporary connection issue. Rather than stop the whole Bactopia run, 
              further analysis of ISS_1F1_P will be discontinued." | \
          sed 's/^\s*//' > ISS_1F1_P-fastq-download-error.txt
          exit
      else
          # Download accession from ENA/SRA
          fastq-dl \
              --accession ISS_1F1_P \
              --provider SRA \
              --cpus 36 \
              --outdir fastqs/ \
              --prefix ISS_1F1_P \
              --group-by-experiment
          touch extra/empty.fna.gz
      fi 
  elif [ "false" == "true" ]; then
      if [ "paired-end" == "assembly_accession" ]; then
          if [ "4" == "3" ]; then
              touch extra/empty.fna.gz
              echo "Unable to download ISS_1F1_P from NCBI Assembly 3 times. This may or may
                  not be a temporary connection issue. Rather than stop the whole Bactopia run, 
                  further analysis of ISS_1F1_P will be discontinued." | \
              sed 's/^\s*//' > ISS_1F1_P-assembly-download-error.txt
              exit
          else
              # Verify Assembly accession
              check-assembly-accession.py ISS_1F1_P > accession.txt 2> check-assembly-accession.txt
  
              if [ -s "accession.txt" ]; then
                  # Download from NCBI assembly and simulate reads
                  mkdir fasta/
                  ncbi-genome-download bacteria -o ./ -F fasta -p 36 \
                                              -s null -A accession.txt -r 50 
                  find . -name "*ISS_1F1_P*.fna.gz" | xargs -I {} mv {} fasta/
                  rename 's/(GC[AF]_\d+).*/$1.fna.gz/' fasta/*
                  gzip -cd fasta/ISS_1F1_P.fna.gz > ISS_1F1_P-art.fna
                  rm check-assembly-accession.txt
              else
                  mv check-assembly-accession.txt ISS_1F1_P-assembly-accession-error.txt
                  exit
              fi
          fi
      elif [ "paired-end" == "assembly" ]; then
          if [ "false" == "true" ]; then
              gzip -cd EMPTY_EXTRA > ISS_1F1_P-art.fna
          else 
              cat EMPTY_EXTRA > ISS_1F1_P-art.fna
          fi
      fi
  
      # Simulate reads from assembly, reads are 250bp without errors
      art_illumina -p -ss MSv3 -l 250 -m 400 -s 30 --fcov 150 -ir 0 -ir2 0 -dr 0 -dr2 0 -rs 42                        -na -qL 33 -qU 40 -o ISS_1F1_P_R --id ISS_1F1_P -i ISS_1F1_P-art.fna
  
      mv ISS_1F1_P_R1.fq fastqs/ISS_1F1_P_R1.fastq
      mv ISS_1F1_P_R2.fq fastqs/ISS_1F1_P_R2.fastq
      pigz -p 36 --fast fastqs/*.fastq
      cp ISS_1F1_P-art.fna extra/ISS_1F1_P.fna
      pigz -p 36 --best extra/ISS_1F1_P.fna
  fi
  
  # Validate input FASTQs
  IS_PAIRED="unknown"
  if [ "false" == "false" ]; then
      ERROR=0
      # Check paired-end reads have same read counts
      OPTS="--sample ISS_1F1_P --min_basepairs 2241820 --min_reads 7472 --min_proportion 0.5 --runtype paired-end"
      if [ -f  "fastqs/ISS_1F1_P_R2.fastq.gz" ]; then
          # Paired-end
          IS_PAIRED="true"
          gzip -cd fastqs/ISS_1F1_P_R1.fastq.gz | fastq-scan > r1.json
          gzip -cd fastqs/ISS_1F1_P_R2.fastq.gz | fastq-scan > r2.json
          if ! reformat.sh in1=fastqs/ISS_1F1_P_R1.fastq.gz in2=fastqs/ISS_1F1_P_R2.fastq.gz qin=auto out=/dev/null 2> ISS_1F1_P-paired-end-error.txt; then
              ERROR=1
              echo "ISS_1F1_P FASTQs contains an error. Please check the input FASTQs.
                  Further analysis is discontinued." | \
              sed 's/^\s*//' >> ISS_1F1_P-paired-end-error.txt
          else
              rm -f ISS_1F1_P-paired-end-error.txt
          fi
  
          if [[ -s r1.json ]] && [[ -s r2.json ]]; then
              if ! check-fastqs.py --fq1 r1.json --fq2 r2.json ${OPTS}; then
                  ERROR=1
              fi
          else
              NOT_GZIP=0
              if ! gzip -t fastqs/ISS_1F1_P_R1.fastq.gz; then
                  NOT_GZIP=1
              elif ! gzip -t fastqs/ISS_1F1_P_R2.fastq.gz; then
                  NOT_GZIP=1
              fi
  
              if [ "${NOT_GZIP}" -eq "0" ]; then
                  echo "ISS_1F1_P FASTQs are empty. Please check the input FASTQs.
                      Further analysis is discontinued." | \
                  sed 's/^\s*//' > ISS_1F1_P-empty-error.txt
                  ERROR=1
              else
                  echo "ISS_1F1_P FASTQs failed Gzip tests. Please check the input FASTQs.
                      Further analysis is discontinued." | \
                  sed 's/^\s*//' > ISS_1F1_P-gzip-error.txt
                  ERROR=1
              fi
          fi
          rm r1.json r2.json
      else
          # Single-end
          IS_PAIRED="false"
          gzip -cd fastqs/ISS_1F1_P.fastq.gz | fastq-scan > r1.json
  
          if [[ -s r1.json ]]; then
              if ! check-fastqs.py --fq1 r1.json ${OPTS}; then
                  ERROR=1
              fi
          else
              if ! gzip -t fastqs/ISS_1F1_P.fastq.gz; then
                  echo "ISS_1F1_P FASTQs failed Gzip tests. Please check the input FASTQs.
                      Further analysis is discontinued." | \
                  sed 's/^\s*//' > ISS_1F1_P-gzip-error.txt
                  ERROR=1
              elif ! gzip -t fastqs/ISS_1F1_P_R2.fastq.gz; then
                  echo "ISS_1F1_P FASTQs are empty. Please check the input FASTQs.
                      Further analysis is discontinued." | \
                  sed 's/^\s*//' > ISS_1F1_P-empty-error.txt
                  ERROR=1
              fi
          fi
          rm r1.json
      fi
  
      # Short polish should not be considered paired-end
      if [ "paired-end" == "short_polish" ]; then
          IS_PAIRED="false"
      fi
  
      # Failed validations so, let's keep them from continuing
      if [ "${ERROR}" -eq "1" ]; then
          mv fastqs/ failed-tests-fastqs/
      fi
  fi
  
  # Dump meta values to a TSV
  echo "sample<TAB>runtype<TAB>original_runtype<TAB>is_paired<TAB>is_compressed<TAB>species<TAB>genome_size" | sed 's/<TAB>/	/g' > ISS_1F1_P-meta.tsv
  echo "ISS_1F1_P<TAB>paired-end<TAB>paired-end<TAB>$IS_PAIRED<TAB>true<TAB>null<TAB>2800000" | sed 's/<TAB>/	/g' >> ISS_1F1_P-meta.tsv
  
  # Capture versions
  cat <<-END_VERSIONS > versions.yml
  "BACTOPIA:GATHER:GATHER_MODULE":
      art: $(echo $(art_illumina --help 2>&1) | sed 's/^.*Version //;s/ .*$//')
      fastq-dl: $(echo $(fastq-dl --version 2>&1) | sed 's/fastq-dl, version //')
      fastq-scan: $(echo $(fastq-scan -v 2>&1) | sed 's/fastq-scan //')
      ncbi-genome-download: $(echo $(ncbi-genome-download --version 2>&1))
      pigz: $(echo $(pigz --version 2>&1) | sed 's/pigz //')
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  ln: failed to create symbolic link '001-r1': Operation not permitted

Work dir:
  /media/bio5995/3/bactopia_test/work/98/2f6826543e8cb83a64870ad9d9843d

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details

**Comment by rpetit3** [comment]
Hmmm, can you share some details about your system?

Also, I'm curious if you get the same error when running this in your home directory

**Comment by nksjplai** [comment]
Its a nextcomputing HPC, with intel 22 core, 44 threads processor and 256 GB Ram, OS is Xubuntu 22.04. 

If you suggest, i will try running it on home directory :)

**Comment by nksjplai** [comment]
Hmmm, strange, it didn't fail in home directory. Ok let's see. 

Will touch back again if it fails :+1: 

thanks for your time and effort and prompt responses

nitin

**Comment by rpetit3** [comment]
I've seen this before, is `/media/bio5995` and external or network drive?

**Comment by nksjplai** [comment]
/media/bio5995 is home but /media/bio5995/3 is external drive.

**Comment by rpetit3** [comment]
Thank you @brross60 

I'll look into this to see if I can replicate and get a proper fix in place!

**Comment by rpetit3** [comment]
Hi @nksjplai 

I'm unsure what was the end result here. For the time being, I will close this. Please feel free to reopen.

Cheers,
Robert
