### ISSUE TITLE
[bug] sketcher error | mash screen step | *.msh.xz does not look like a sketch (.msh)

### ISSUE THREAD

**Issue by waoverholt** [bactopia/bactopia#450]
**Description**

The main bactopia wf, using a single complete assembly (4 genetic elements) as input does not get classified against the refseq88 sketch.
I believe the ${mash_db} doesn't get correctly updated in the nextflow script to the .msh path and continues to use the compressed .msh.xz path.

**Steps to Reproduce**

```
bactopia --assembly bar01_assembly.fasta.gz --sample barcode01 --max_cpus 4 -qs 1 --genome_size 5000000

!!ERROR!!
Sketching from stdin...
Writing to barcode01-k21.msh...
Sketching from stdin...
Writing to barcode01-k31.msh...

[K
== This is sourmash version 4.8.4. ==

[K== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==


[Kcomputing signatures for files: barcode01.fna.gz

[KComputing a total of 1 signature(s) for each input.

[K... reading sequences from barcode01.fna.gz

[K... barcode01.fna.gz 4 sequences

[Kcalculated 1 signature for 4 sequences taken from 1 files

[Ksaved 1 signature(s) to 'barcode01.sig'
ERROR: mash-refseq88.k21.msh.xz does not look like a sketch (.msh)

[K
== This is sourmash version 4.8.4. ==

[K== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==


[K
[K
[K... loading database gtdb-rs207.genomic-reps.dna.k31.lca.json.gz

[K
[K
[Kloaded 1 LCA databases. ksize=31, scaled=10000 moltype=DNA

[Kfinding query signatures...

[Koutputting classifications to -

[K
[K
[K... classifying barcode01 (file 1 of 1)

[K
[K
[Kclassified 1 signatures total

```

**Expected Behavior**
A description of what is expected to happen.

**Execution Environment**

- Bactopia Version: 3.0.0
- OS: CentOS Linux 7
- Environment: conda

**Additional Information**
Any other information you think might be helpful in squashing this bug.

**Comment by rpetit3** [comment]
Hi @waoverholt 

Thank you for finding this! Looks like I have a bug on this line: https://github.com/bactopia/bactopia/blob/master/modules/local/bactopia/sketcher/main.nf#L50

I fixed on the dev side: https://github.com/bactopia/bactopia/commit/00732c6a50a10cdb2e32be611adbc9c0dd4a3d42

If you just want to keep moving you have a few options:

1. uncompress the mash sketch file
2. manually edit the sketcher module to implement the change above

I can point you in the right direction if you want to edit the sketcher module, but will need the output of `which bactopia`

Thanks again for reporting!
Robert

**Comment by waoverholt** [comment]
Hi @rpetit3,
Awesome, glad you were able to address it so quickly. I had already manually run the mash screen command outside of bactopia, so all good on my side.
Best,
Will

**Comment by rpetit3** [comment]
Hi @waoverholt 

I've release [Bactopia v3.0.1](https://bactopia.github.io/latest/changelog/#v301-bactopiabactopia-thats-my-girl-20240325). Since I had previously marked this as "fixed" (haha my reminder to close after the next release!), I will go ahead and close this, please feel free to reopen if you think it should still be open.

Also, it would be super useful if took the time to complete my [2024 Bactopia Usage Survey](https://forms.gle/BA2BDHRQvZtpVcD38). 

Thank you so much!
Robert
