### ISSUE TITLE
[question?] Best way to process multiple options for `--abricate_db`?

### ISSUE THREAD

**Issue by incoherentian** [bactopia/bactopia#451]
**Questions:**
What is the best way to process multiple options for `--abricate_db`?

Can this be done after an initial, other abricate run with full per-sample results?

**Is this related to a problem?**
When I run abricate as a bactopia tool using `--abricate_db vfdb`, all works as expected. 

When I follow up with additional abricate workflows such as `--abricate_db resfinder`, no results seem to be written for per-sample results.

I believe all bactopia abricate runs after the first still expect to write abricate results to the pre-existing file `$OUTDIR/$SAMPLENAME/tools/abricate/$SAMPLENAME.TXT` without accounting for it already being a different database's run. 

(For `$OUTDIR/$SAMPLENAME/tools/abricate/$SAMPLENAME.TXT` I'm referring to the file with full outputs, e.g. columns for `#FILE	SEQUENCE	START	END	STRAND	GENE	COVERAGE	COVERAGE_MAP	GAPS	%COVERAGE	%IDENTITY	DATABASE	ACCESSION	PRODUCT`)

_This is based on me being unable to find the per-sample results, and I am very open to being wrong!_

**Is this something you would like to see added?**
If it isn't already possible, yes! 

**Describe the solution you'd like**
Consecutive commands such as:

```
bactopia\
 -profile arcc\
 -resume\
 --max_cpus 8\
 --datasets_cache /home/scw1940/.nextflow/bactopia_repo_20230421/datasets\
 --wf abricate\
 --abricate_db argannot\
 --bactopia $OUTDIR\
 --cleanup_workdir

wait

bactopia\
 -profile arcc\
 -resume\
 --max_cpus 8\
 --datasets_cache /home/scw1940/.nextflow/bactopia_repo_20230421/datasets\
 --wf abricate\
 --abricate_db megares\
 --bactopia $OUTDIR\
 --cleanup_workdir
```

Would write to separate subfolders within `$OUTDIR/$SAMPLENAME/tools/abricate/`. 

i.e. 
`$OUTDIR/$SAMPLENAME/tools/abricate/argannot/$SAMPLENAME.TXT` for `--abricate_db argannot`
`$OUTDIR/$SAMPLENAME/tools/abricate/megares/$SAMPLENAME.TXT` for  `--abricate_db megares`

**Additional Information**

I still find relevant merged abricate results in e.g. `$OUTDIR/bactopia-runs/abricate-20230925-130817/merged-results/abricate.tsv` for follow-on abricate runs; this requires looking at the nf-logged command in e.g. `$OUTDIR/bactopia-runs/abricate-20230925-130817/nf-reports/abricate-report.html` to determine which subfolder is for which `--abricate_db` but is otherwise an amazing time saver. This overview does not (& shouldn't try to) contain the full abricate results typically written to `$OUTDIR/$SAMPLENAME/tools/abricate/$SAMPLENAME.TXT` however.

Tangentially related to a prior response of yours! - 

>              > Is it possible to use the main bactopia pipeline with both --ask_merlin and --wf abricate in one go?
> 
> It is not. At the moment the only solution is to run bactopia, then the bactopia tools. 
> 
> You are correct though, there's no reason why something similar to merlin could be done for amr/virulence tools. They could  be added to merlin and be "always on" (e.g. distance to references is not taken into account).  Haha I would need to come up with some criteria for addition to merlin, otherwise I could see my self just adding them all.
> 
> Or, a separate "merlin"-like thing could be added (e.g. https://github.com/pha4ge/hAMRonization).
> 
> Or, as last measure, just run the bactopia tool.

_Originally posted by @rpetit3 in https://github.com/bactopia/bactopia/issues/436#issuecomment-1703279549_

**Comment by rpetit3** [comment]
This is definitely a bug, you are correct the per-sample folders should get a subfolder for the the database. I'll also get that run folder to include the database name

Will update soon, with a fix!

**Comment by rpetit3** [comment]
This is now fixed in my dev version: https://github.com/bactopia/bactopia/commit/ad261c4d91785d5758c177baecf2153594070ebb

```
bactopia/
├── SRR2838702
│   ├── main
│   │   ├── annotator
│   │   ├── assembler
│   │   ├── gather
│   │   ├── qc
│   │   └── sketcher
│   └── tools
│       ├── abricate
│       │   ├── ncbi
│       │   └── vfdb
│       ├── amrfinderplus
│       ├── mlst
│       └── spatyper
└── bactopia-runs
    ├── abricate-ncbi-20230925-202142
    ├── abricate-vfdb-20230925-202256
    ├── bactopia-20230925-200813
    └── spatyper-20230925-202334
```

There are likely other tools where this might be needed (e.g. snippy) but they are a bit more complicated. I'll have to figure out a better way to handle those. Might have to make it an optional user input (e.g. snippy again `--reference_name`)

**Comment by incoherentian** [comment]
> This is definitely a bug

I'm not sure I've ever correctly labelled an issue 🙃 

<details>

```
[...]
`-- tools
    |-- abricate
    |   |-- COV1231_S44_.txt
    |   |-- argannot
    |   |   |-- COV1231_S44_.txt
    |   |   `-- logs
    |   |       |-- nf-abricate.begin
    |   |       |-- nf-abricate.err
    |   |       |-- nf-abricate.log
    |   |       |-- nf-abricate.out
    |   |       |-- nf-abricate.run
    |   |       |-- nf-abricate.sh
    |   |       |-- nf-abricate.trace
    |   |       `-- versions.yml
    |   |-- card
    |   |   |-- COV1231_S44_.txt
    |   |   `-- logs
    |   |       |-- nf-abricate.begin
    |   |       |-- nf-abricate.err
    |   |       |-- nf-abricate.log
    |   |       |-- nf-abricate.out
    |   |       |-- nf-abricate.run
    |   |       |-- nf-abricate.sh
    |   |       |-- nf-abricate.trace
    |   |       `-- versions.yml
    |   |-- logs
    |   |   |-- nf-abricate.begin
    |   |   |-- nf-abricate.err
    |   |   |-- nf-abricate.log
    |   |   |-- nf-abricate.out
    |   |   |-- nf-abricate.run
    |   |   |-- nf-abricate.sh
    |   |   |-- nf-abricate.trace
    |   |   `-- versions.yml
    |   |-- megares
    |   |   |-- COV1231_S44_.txt
    |   |   `-- logs
    |   |       |-- nf-abricate.begin
    |   |       |-- nf-abricate.err
    |   |       |-- nf-abricate.log
    |   |       |-- nf-abricate.out
    |   |       |-- nf-abricate.run
    |   |       |-- nf-abricate.sh
    |   |       |-- nf-abricate.trace
    |   |       `-- versions.yml
    |   |-- plasmidfinder
    |   |   |-- COV1231_S44_.txt
    |   |   `-- logs
    |   |       |-- nf-abricate.begin
    |   |       |-- nf-abricate.err
    |   |       |-- nf-abricate.log
    |   |       |-- nf-abricate.out
    |   |       |-- nf-abricate.run
    |   |       |-- nf-abricate.sh
    |   |       |-- nf-abricate.trace
    |   |       `-- versions.yml
    |   |-- resfinder
    |   |   |-- COV1231_S44_.txt
    |   |   `-- logs
    |   |       |-- nf-abricate.begin
    |   |       |-- nf-abricate.err
    |   |       |-- nf-abricate.log
    |   |       |-- nf-abricate.out
    |   |       |-- nf-abricate.run
    |   |       |-- nf-abricate.sh
    |   |       |-- nf-abricate.trace
    |   |       `-- versions.yml
    |   `-- vfdb
    |       |-- COV1231_S44_.txt
    |       `-- logs
    |           |-- nf-abricate.begin
    |           |-- nf-abricate.err
    |           |-- nf-abricate.log
    |           |-- nf-abricate.out
    |           |-- nf-abricate.run
    |           |-- nf-abricate.sh
    |           |-- nf-abricate.trace
    |           `-- versions.yml
    |-- amrfinderplus
    |   |-- COV1231_S44_-genes.tsv
    |   |-- COV1231_S44_-proteins.tsv
    |   `-- logs
    |       |-- nf-amrfinderplus.begin
    |       |-- nf-amrfinderplus.err
    |       |-- nf-amrfinderplus.log
    |       |-- nf-amrfinderplus.out
    |       |-- nf-amrfinderplus.run
    |       |-- nf-amrfinderplus.sh
    |       |-- nf-amrfinderplus.trace
    |       `-- versions.yml
[...]
```

</details>

Thank you!
