### ISSUE TITLE
docker image and non-home default folder 

### ISSUE THREAD

**Issue by aheravi** [bactopia/bactopia#452]
Hi @rpetit3 
Just wondering is there any running parameter I can use for not creating ~/.bactopia folder? I have a limited space there and getting error on that.
Also, I wonder if you could update the docker image to the latest version (v.3)?
https://hub.docker.com/r/bactopia/bactopia/tags

Thanks,
Ali

**Comment by rpetit3** [comment]
Hi @aheravi 

Thank you for reaching out.

To change the cache directory, you have a few options here:

1. set environment variable `BACTOPIA_CACHEDIR` to where you would like it to be
2. Adjust the `--datasets_cache` parameter, and if applicable the `--condadir` and/or `--singularity_cache` parameters

As for the docker container, you will want this one: `quay.io/biocontainers/bactopia:3.0.0--hdfd78af_0`

Let me know if this doesn't work for you!

**Comment by aheravi** [comment]
Hi @rpetit3 
Thanks for your prompt reply. 
Here is the error I'm getting in running the following command:
```
singularity exec bactopia_3.0.0.sif bactopia -profile test --datasets_cache /projects/Software/bacteria/bactopia/v3/ --singularity_cache /projects/Software/bacteria/bactopia/v3/ --condadir /projects/Software/bacteria/bactopia/v3/
```

```
ERROR ~ Error executing process > 'BACTOPIA:GATHER:GATHER_MODULE (SRR2838702)'

Caused by:
  Process `BACTOPIA:GATHER:GATHER_MODULE (SRR2838702)` terminated with an error exit status (127)

Command executed:

  MERGED="multiple-read-sets-merged.txt"
  mkdir -p fastqs
  mkdir -p extra
  
...

  # Dump meta values to a TSV
  echo "sample<TAB>runtype<TAB>original_runtype<TAB>is_paired<TAB>is_compressed<TAB>species<TAB>genome_size" | sed 's/<TAB>/	/g' > SRR2838702-meta.tsv
  echo "SRR2838702<TAB>paired-end<TAB>paired-end<TAB>$IS_PAIRED<TAB>true<TAB>null<TAB>358242" | sed 's/<TAB>/	/g' >> SRR2838702-meta.tsv
  
  # Capture versions
  cat <<-END_VERSIONS > versions.yml
  "BACTOPIA:GATHER:GATHER_MODULE":
      art: $(echo $(art_illumina --help 2>&1) | sed 's/^.*Version //;s/ .*$//')
      fastq-dl: $(echo $(fastq-dl --version 2>&1) | sed 's/fastq-dl, version //')
      fastq-scan: $(echo $(fastq-scan -v 2>&1) | sed 's/fastq-scan //')
      ncbi-genome-download: $(echo $(ncbi-genome-download --version 2>&1))
      pigz: $(echo $(pigz --version 2>&1) | sed 's/pigz //')
  END_VERSIONS

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 126: fastq-scan: command not found

Work dir:
  /projects/Software/bacteria/bactopia/work/96/92593c524afebbdacd45b0ffe52264

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
```

**Comment by rpetit3** [comment]
The issue here is the Bactopia container doesn't have the environments for each of the process. So this instance is trying to run Conda within the Singularity containers. But, we have a few options here:

1. Install bactopia through Conda, but use the `-profile` parameter to tell Nextflow it to use Singularity (e.g. `-profile singualrity`)
2. If conda is not an option, but Nextflow is available, run it directly from the repo (e.g. `nextflow run bactopia/bactopia -profile singualrity ...`)

Here's more information: https://bactopia.github.io/v3.0.0/tutorial/#selecting-a-profile

Also if you have any feedback on improving the documentation, please feel free to share with me!

Robert

**Comment by aheravi** [comment]
Thanks, @rpetit3 .
Love your software. Does everything!
Great job.

**Comment by rpetit3** [comment]
Thank you so much @aheravi it means alot. If you ever have questions or issues please feel free to contact me!

**Comment by rpetit3** [comment]
Hi @aheravi 

I'm doing some spring cleaning. I think we resolved this issue. Please feel free to reopen if not.

Cheers,
Robert
