### ISSUE TITLE
[bug?] Bactopia 3.0.1 from bactopia-dev: no unicycler from '--hybrid'

### ISSUE THREAD

**Issue by incoherentian** [bactopia/bactopia#453]
Possible bug in bactopia-dev env created today:

**Description**
Bactopia 3.0.1 not hybrid (unicycler) assembling when all parameters given. 

<details>

  <summary>...despite being recognized in the initialization overview!</summary>

```
N E X T F L O W  ~  version 23.04.3
Launching `/home/scw1940/.conda/envs/bactopia-dev202309abricompat/share/bactopia-3.0.1/main.nf` [agitated_kowalevski] DSL2 - revision: 0cd9f79ba7


---------------------------------------------
   _                _              _
  | |__   __ _  ___| |_ ___  _ __ (_) __ _
  | '_ \ / _` |/ __| __/ _ \| '_ \| |/ _` |
  | |_) | (_| | (__| || (_) | |_) | | (_| |
  |_.__/ \__,_|\___|\__\___/| .__/|_|\__,_|
                            |_|
  bactopia v3.0.1
  Bactopia is a flexible pipeline for complete analysis of bacterial genomes
---------------------------------------------
Core Nextflow options
  runName             : agitated_kowalevski
  containerEngine     : singularity
  container           : quay.io/bactopia/bactopia:3.0.1
  launchDir           : /scratch/c.medib/sh_bactopia
  workDir             : /scratch/c.medib/sh_bactopia/work
  projectDir          : /home/scw1940/.conda/envs/bactopia-dev202309abricompat/share/bactopia-3.0.1
  userName            : c.medib
  profile             : arcc
  configFiles         : /home/scw1940/.conda/envs/bactopia-dev202309abricompat/share/bactopia-3.0.1/nextflow.config

Required Parameters
  r1                  : /scratch/c.medib/data.nextflow/d50_NNMR_20230925reassembly/NN-MR_R1_001.fastq.gz
  r2                  : /scratch/c.medib/data.nextflow/d50_NNMR_20230925reassembly/NN-MR_R2_001.fastq.gz
  ont                 : /scratch/c.medib/lr_fastq/notrim/NNMR_FAST5merge20230526_gpy657sup_63648736/NN-MR_nanomerge_notrim.fastq.gz
  hybrid              : true

Dataset Parameters
  ask_merlin          : true
  genome_size         : 0

QC Parameters
  use_porechop        : false
  adapters            : /home/scw1940/.conda/envs/bactopia-dev202309abricompat/share/bactopia-3.0.1/data/EMPTY_ADAPTERS
  phix                : /home/scw1940/.conda/envs/bactopia-dev202309abricompat/share/bactopia-3.0.1/data/EMPTY_PHIX

Assembler Parameters
  trim                : true
  nanohq              : null

[...]

--------------------------------------------------------------------
ERROR ~ Cannot use --r1, --r2, and --ont together, unless using --short_polish or --hybrid

 -- Check '.nextflow.log' file for details
ERROR ~ ERROR: Validation of pipeline parameters failed!
Please correct to continue

 -- Check '.nextflow.log' file for details
```

</details>

**Steps to Reproduce**
```
bactopia\
 -profile arcc\
 --max_cpus 8\
 --datasets_cache /home/scw1940/.nextflow/bactopia_repo_20230421/datasets\
 --trim\
 --hybrid\
 --ont $ONT\
 --r1 $R1\
 --r2 $R2\
 --ask_merlin\
 --outdir $OUTDIR\
 --cleanup_workdir
[...]
ERROR ~ Cannot use --r1, --r2, and --ont together, unless using --short_polish or --hybrid
```

**Expected Behavior**
Trimming + Unicycler assembly

**Execution Environment**
- Bactopia Version: 3.0.1
- OS: RHEL
- Environment: 
Mamba-built conda env for nf 
SLURM-executed singularity containers

**Additional Information**
-Can email unadulterated log if wanted.
-I used --trim while what I think I actually wanted was --use_porechop, but fortunately it never got that far! (super-cheeky incidental note that [chopper](https://github.com/wdecoster/chopper) is on bioconda!)
-I hope someone reads https://github.com/conda-forge/tensorflow-feedstock/pull/283 soon so unicycler can have the rest it deserves 🧓

**Comment by rpetit3** [comment]
@incoherentian was `--sample` also provided? I think the issue is `--sample` wasn't provided, and its a bug that you didn't get this information.

**Comment by incoherentian** [comment]
Hrm, the first time I tried running this was with a sample sheet (`--samples $WDPATH/${SAMPLES}` and `--hybrid` where e.g. `SAMPLES=d50_NNMR_20230925reassembly.fofn`) using the `extra` field for `$ONT` instead of  `--ont $ONT --r1 $R1 --r2 $R2` as above. I wasn't confident about manually placed ONT reads in the FOFN so spelled them out as arguments... maybe will try again both ways!

**Comment by incoherentian** [comment]
> I think the issue is `--sample` wasn't provided

Lacking `--sample` does seem to be the cause for aforementioned `Cannot use --r1, --r2, and --ont together, unless using --short_polish or --hybrid` error. Haven't tested with --samples because I first need to rename some files.

```
Command error:
  Error: could not find NN-MR.fastq.gz
```

I want to check if the FOFN accepts wildcards `*` or `?` between the unique sampleid and r1/r2 affixes too. (Sheer laziness, I just don't want to manage temporary copies of ONT fastq without their barcodes in the filename.) So I'll close this but let you know once I have a chance to test!
