### ISSUE TITLE
No such file or directory 2022-10-11.2/* 

### ISSUE THREAD

**Issue by arsp-dev** [bactopia/bactopia#455]
Hi,

Im trying to install bactopia on an ubuntu server 22.04 but i have these following error,

(bactopia) jmg@arslserver:~/bactopia$ bactopia datasets
2023-10-02 15:09:02:root:INFO - Setting up pre-computed Genbank/Refseq minmer datasets
2023-10-02 15:09:02:root:INFO - ./datasets/minmer/sourmash-genbank-k21.json.gz exists, skipping
2023-10-02 15:09:02:root:INFO - ./datasets/minmer/sourmash-genbank-k31.json.gz exists, skipping
2023-10-02 15:09:02:root:INFO - ./datasets/minmer/sourmash-genbank-k51.json.gz exists, skipping
2023-10-02 15:09:02:root:INFO - ./datasets/minmer/mash-refseq-k21.msh exists, skipping
2023-10-02 15:09:02:root:INFO - Setting up antimicrobial resistance datasets
2023-10-02 15:09:02:root:INFO - Setting up latest AMRFinder+ database
External command failed with exit code 1!

Command:
bash -c 'mv 2022-10-11.2/* amrfinderdb/'

Standard error:
mv: cannot stat '2022-10-11.2/*': No such file or directory

I just installed mamba and running the following commands 

mamba create -y -n bactopia -c conda-forge -c bioconda bactopia
conda activate bactopia
bactopia datasets

when it comes to "bactopia datasets" the error above shows.

Can anyone please help me how to successfully download the datasets?

Thank you.

**Comment by rpetit3** [comment]
Hi @arsp-dev,

Are you able to install version 3 of Bactopia? The issue you are experiencing has been fixed in v3.

Thank you!
Robert

**Comment by arsp-dev** [comment]
Hi, 

How do i upgrade? is there a command for this? or how will I reinstall bactopia as v3? 

Im looking at the documentation and it did not mention how to do that.

Thank you.

**Comment by rpetit3** [comment]
Hi @arsp-dev 

I'd recommend either creating a new environment or overwriting an existing one. More details available here https://bactopia.github.io/v3.0.0/installation/

Cheers,
Robert

**Comment by arsp-dev** [comment]
Hi Robert,

Thank you, Will try that now.

I will update you on this.

**Comment by rpetit3** [comment]
Sounds good! Let me know if it gives you any problems!

**Comment by arsp-dev** [comment]
Hi Robert,

I am able to fix the issue with your help.

Thank you very much. 

I will now close this issue.

Thank you for helping.

**Comment by rpetit3** [comment]
Hi @arsp-dev 

I've released [Bactopia v3.0.1](https://bactopia.github.io/latest/changelog/#v301-bactopiabactopia-thats-my-girl-20240325), if you give it a try let me know if you have any issues or feedback!

I've also put together a long overdue survey that would be super useful for getting feedback and helping guide future directions of Bactopia. If you have time, I would be super thankful is you completed my [2024 Bactopia Usage Survey](https://forms.gle/BA2BDHRQvZtpVcD38)!

Thank you so much!
Robert
