### ISSUE TITLE
Error report 

### ISSUE THREAD

**Issue by Saudubey** [bactopia/bactopia#456]
Dear Robert, 
I'm a new user of Bactopia, and I decided to try out the tool by following the instructions provided in the tutorial located at https://bactopia.github.io/v3.0.0/tutorial/#verify-bactopia-is-working. However, I ran into an issue after executing the initial command "bactopia -profile test,standard " . The issue is "Error Report  : Error executing process > 'BACTOPIA:DUMPSOFTWAREVERSIONS (1)".  I would greatly appreciate it if you could guide me on resolving this problem.

 Bactopia Execution Summary
    ---------------------------
    Bactopia Version : 3.0.0
    Nextflow Version : 23.04.3
    Command Line     : nextflow run /mnt/users/saudubey/.conda/envs/bactopia//share/bactopia-3.0.0/main.nf -w /mnt/users/saudubey/work/ -profile test,standard
    Resumed          : false
    Completed At     : 2023-10-02T09:06:36.168627137+02:00
    Duration         : 6m 48s
    Success          : false
    Exit Code        : 1
    Error Report     : Error executing process > 'BACTOPIA:DUMPSOFTWAREVERSIONS (1)'

Command error:
  Traceback (most recent call last):
    File ".command.sh", line 52, in <module>
executor >  local (16)
[skipped  ] process > BACTOPIA:DATASETS                                               [100%] 1 of 1, stored: 1 ✔
[c4/19956f] process > BACTOPIA:GATHER:GATHER_MODULE (SRR2838702)                      [100%] 1 of 1 ✔
[95/6b56c0] process > BACTOPIA:GATHER:CSVTK_CONCAT (meta)                             [100%] 1 of 1 ✔
[b9/56694c] process > BACTOPIA:QC:QC_MODULE (SRR2838702)                              [100%] 1 of 1 ✔
[ab/5edab0] process > BACTOPIA:ASSEMBLER:ASSEMBLER_MODULE (SRR2838702)                [100%] 1 of 1 ✔
[8f/073a70] process > BACTOPIA:ASSEMBLER:CSVTK_CONCAT (assembly-scan)                 [100%] 1 of 1 ✔
[aa/43a30f] process > BACTOPIA:SKETCHER:SKETCHER_MODULE (SRR2838702)                  [100%] 1 of 1 ✔
[7c/097a37] process > BACTOPIA:ANNOTATOR:PROKKA_MODULE (SRR2838702)                   [100%] 1 of 1 ✔
[90/ab3639] process > BACTOPIA:AMRFINDERPLUS:AMRFINDERPLUS_RUN (SRR2838702)           [100%] 1 of 1 ✔
[80/a179ba] process > BACTOPIA:AMRFINDERPLUS:GENES_CONCAT (amrfinderplus-genes)       [100%] 1 of 1 ✔
[36/0de36e] process > BACTOPIA:AMRFINDERPLUS:PROTEINS_CONCAT (amrfinderplus-proteins) [100%] 1 of 1 ✔
[b6/f768e8] process > BACTOPIA:MLST:MLST_MODULE (SRR2838702)                          [100%] 1 of 1 ✔
[43/27265f] process > BACTOPIA:MLST:CSVTK_CONCAT (mlst)                               [100%] 1 of 1 ✔
[f2/da52f3] process > BACTOPIA:DUMPSOFTWAREVERSIONS (1)                               [100%] 4 of 4, failed: 4, retries: 3 ✘
[e5/067665] NOTE: Process `BACTOPIA:DUMPSOFTWAREVERSIONS (1)` terminated with an error exit status (1) -- Execution is retried (1)
[83/0c6213] NOTE: Process `BACTOPIA:DUMPSOFTWAREVERSIONS (1)` terminated with an error exit status (1) -- Execution is retried (2)
[62/db620f] NOTE: Process `BACTOPIA:DUMPSOFTWAREVERSIONS (1)` terminated with an error exit status (1) -- Execution is retried (3)
ERROR ~ Error executing process > 'BACTOPIA:DUMPSOFTWAREVERSIONS (1)'

**Comment by rpetit3** [comment]
Hi @Saudubey 

THank you for reaching out. This issue looks related to this one: https://github.com/bactopia/bactopia/issues/454

If you share more of your log file I can point you in the right direction to verify.

Cheers,
Robert Petit

**Comment by Saudubey** [comment]
Dear Robert, 
                   Thanks for your Reply. Here is nextflow.log file.
[nextflow.log file.txt](https://github.com/bactopia/bactopia/files/12790836/nextflow.log.file.txt)

**Comment by rpetit3** [comment]
Thank you for sharing! Its the same as the previous issue.

Think you can share the output of the following with me?

```
conda activate /mnt/users/saudubey/.bactopia/conda/bioconda--bactopia-gather-1.0.4
conda env export
```

I want to see what I'm getting differently on my end that is causing this to not work for you

**Comment by Saudubey** [comment]
Dear Robert,
                    I am sorry for the late response. My university HPC server was down yesterday. Please find the output file of the cond env export. 
[conda-env export.txt](https://github.com/bactopia/bactopia/files/12814189/conda-env.export.txt)

**Comment by rpetit3** [comment]
Good news! I was able to replicate your issue using your env file. Thank you very much for sharing!

Few things stood out. The channel order was: defaults, bioconda, daler, conda-forge. You could probably remove daler, unless you have a specific usecase for it. Otherwise, you will want to reorder the order to: conda-forge, bioconda, daler, defaults

As a quick fix you can try the following:

```
conda activate /mnt/users/saudubey/.bactopia/conda/bioconda--bactopia-gather-1.0.4
mamba install -c conda-forge -c bioconda 'pandas==3.1.1'

# Test if working now
fastq-dl --version
conda deactivate
```

On another note, you mentioned the usage of an HPC system. Do you know if this HPC system supports Singularity?

**Comment by Saudubey** [comment]
Dear Robert,

I want to express my gratitude for your generous assistance and timely response. As a microbiologist, I'm currently facing challenges with my university's HPC resources and I'm looking to transition towards cloud computing using Microsoft Azure Machine Learning compute instances. I'd like to request the opportunity to visit your lab in the United States for a one-week training session on "Bactopia." This training could take place in October or at a time that is most convenient for you. Your flexibility in scheduling would be greatly appreciated.

**Comment by Saudubey** [comment]
Dear Robert,
                   I ran the following command mentioned above. There are some errors attached. My HPC at university supports the Singularity container.
[Error after running.txt](https://github.com/bactopia/bactopia/files/12925001/Error.after.running.txt)

**Comment by rpetit3** [comment]
Hi @Saudubey 

I'm not sure on the status of this issue. If you think this still needs to be addressed, please feel free to reopen.

Cheers,
Robert
