### ISSUE TITLE
[feature] [question] arcca_hawk.config

### ISSUE THREAD

**Issue by incoherentian** [bactopia/bactopia#462]
Hi @rpetit3 and thank you as always for being amazing! Also for having good pipelines.

I have been trying to thin down the edited arcc.cfg to little avail, resulting in the following:

```
/*
This file includes default values to simplify Bactopia runs on ARCCA HAWK.

Some SCW users may need to add accessible params as bactopia arguments:

params.slurm_opts replacement argument:
 --cluster_opts '--account scw1234 --qos=maxjobs1234'

params.singularity_cache overwrite argument:
 --singularity_cache /home/scw1234/.nextflow/bactopia/singularitycache/

Contact boostrom@cf.ac.uk if help is required with these arguments.
Contact arcca@cf.ac.uk to manage your SLURM QOS.
*/

params {
    config_profile_name = 'ARCCA_HAWK'
    config_profile_description = 'Advanced Research Computing at Cardiff (ARCCA) - HAWK cluster'
    config_profile_contact = 'Ian Boostrom, or more realistically (@rpetit3) c/o (@incoherentian)'
    config_profile_url = 'https://www.cardiff.ac.uk/advanced-research-computing/research/collaboration'
    slurm_queue = 'htc'
    slurm_opts = '--account scw1773 --qos=maxjobs1500'
    singularity_cache = '/home/scw1940/.nextflow/bactopia/singularitycache/'
    slurm_use_scratch = false
}

process {
  executor = 'slurm'
  queue = "${params.slurm_queue}"
  scratch = params.slurm_use_scratch
  clusterOptions = "${params.slurm_opts}"
  beforeScript = 'module load singularity-ce/3.11.4'
}

singularity {
    enabled = true
    autoMounts = true
    cacheDir = "${params.singularity_cache}"
}

```

Singularity errors when I use the `--singularity_cache /path/to/cache` argument after removing `params.singularity_cache`. SLURM problems when I try to remove `params.slurm_opts` and use `--cluster_opts '--account scw1234 --qos=maxjobs1234'` as an argument. Smooth sailing when I leave the values there _and_ add arguments to bactopia's execution. So I guess those params both require a value in place to use the relevant arguments? 

If I'm not wrong about that, may I please have that cfg added to [/share/bactopia-3.0.N/conf/profiles/](https://github.com/bactopia/bactopia/tree/89885c5dd9824ac6540ca10becc138876bf2b5bf/conf/profiles) + append [custom user configs](https://github.com/bactopia/bactopia/blob/89885c5dd9824ac6540ca10becc138876bf2b5bf/conf/profiles.config#L73) with (I think)
```
    arcca_hawk {
        includeConfig "base.config"
        includeConfig "profiles/arcca_hawk.config"
    }
```
...hoping arcca_hawk.config will make it more distinct than arcca vs arcc?

 If that's OK!

**Comment by rpetit3** [comment]
Yep! Let's get this added. I'll update when its in the dev build

**Comment by rpetit3** [comment]
@incoherentian this should now be in the dev build `-profile arcc_hawk`

**Comment by incoherentian** [comment]
Working perfectly as `arcc_hawk` - thanks so much!
