### ISSUE TITLE
issue when using docker image

### ISSUE THREAD

**Issue by ybdong919** [bactopia/bactopia#463]
[dongyibo@c0710a-s29 Test_bactopia2]$ apptainer exec docker://bactopia/bactopia:2.0.3 bactopia --R1 J_L001_R1_001.fastq.
gz --R2 J_L001_R2_001.fastq.gz --sample xx
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Copying blob b5799026cefa skipped: already exists
Copying blob 852e50cd189d skipped: already exists
Copying blob a6236801494d skipped: already exists
Copying blob 679c171d6942 skipped: already exists
Copying blob d4aa7baa0fb2 skipped: already exists
Copying blob 66daf37955ba skipped: already exists
Copying blob 2f1dfa7ac532 done
Copying blob e8d0440bab33 done
Copying config 539650159b done
Writing manifest to image destination
Storing signatures
2023/11/15 12:04:14  info unpack layer: sha256:852e50cd189dfeb54d97680d9fa6bed21a6d7d18cfb56d6abfe2de9d7f173795
2023/11/15 12:04:14  info unpack layer: sha256:a6236801494d5ca9acfae6569427398c2942c031375b96cac887cafe1de5a09b
2023/11/15 12:04:16  info unpack layer: sha256:679c171d6942954a759f2d3a1dff911321940f23b0cdbe1d186f36bef0025124
2023/11/15 12:04:17  info unpack layer: sha256:66daf37955ba6c39bcb1f2363f10f3b8207b8eec3e45a396aa1291562bf9a686
2023/11/15 12:04:17  info unpack layer: sha256:d4aa7baa0fb282cf0d6e24b6379617016089de2029519daf2aced7437a8bc199
2023/11/15 12:04:17  info unpack layer: sha256:b5799026cefac0ad27ad581b6d5c501ef76927959c6ea60228fbc01c017400a0
2023/11/15 12:04:17  info unpack layer: sha256:2f1dfa7ac5329fc78a2a5344608e884687880bb4d9c7639d8b5b0b942e5dc050
2023/11/15 12:04:17  info unpack layer: sha256:e8d0440bab33983c0b1bf258238c4d081ad913dcfb7ab1347d7ddb7dae2cb91e
INFO:    Creating SIF file...
Illegal option --
Traceback (most recent call last):
  File "/opt/conda/envs/bactopia/bin/bactopia-download.py", line 515, in <module>
    workflow_modules = parse_workflows(bactopia_path, include_merlin=include_merlin, build_all=args.build_all)
  File "/opt/conda/envs/bactopia/bin/bactopia-download.py", line 146, in parse_workflows
    nf_config, stderr = execute(f'nextflow config -flat {bactopia_path}/main.nf', capture=True)
TypeError: cannot unpack non-iterable NoneType object
Illegal option --
CAPSULE EXCEPTION: Capsule not extracted. while processing system property capsule.java.cmd: java (for stack trace, run with -Dcapsule.log=verbose)
Unable to initialize nextflow environment

**Comment by rpetit3** [comment]
hi @ybdong919 

I've release [Bactopia v3.0.1](https://bactopia.github.io/latest/changelog/#v301-bactopiabactopia-thats-my-girl-20240325). Since I had previously marked this as "fixed" (haha my reminder to close after the next release!), I will go ahead and close this, please feel free to reopen if you think it should still be open.

Also, it would be super useful if took the time to complete my [2024 Bactopia Usage Survey](https://forms.gle/BA2BDHRQvZtpVcD38). 

Thank you so much!
Robert
