### ISSUE TITLE
[bug] Error when using --medaka_model r941_min_sup_g507

### ISSUE THREAD

**Issue by llk578496** [bactopia/bactopia#470]
**Description**
Hi @rpetit3 ,

We just tried to run the following command:  
`bactopia --ont /mnt/data/test/bactopia-v3.0.0/test-003/02_fastq/23MB170490-3.fastq.gz --sample 23MB170490-3 --outdir /mnt/data/test/bactopia-v3.0.0/test-003/04_bactopia/04.1_tmp/23MB170490-3 -profile docker --max_retry 10 --max_cpus 10 --max_memory 110 --max_time 360 --nanohq --medaka_model r941_min_sup_g507 --genome_size 8000000 --min_coverage 50 --medaka_rounds 2 --racon_rounds 3 --cleanup_workdir`

But we encountered the below error messages:

> [polishing - medaka (1 of 2)] RuntimeError: Error validating model from '--model' argument: The model file for r941_min_sup_g507 is not installed and could not be installed to any of /usr/local/lib/python3.8/site-packages/medaka/data or /.medaka/data. If you cannot gain write permissions, download the model file manually from https://github.com/nanoporetech/medaka/raw/master/medaka/data/r941_min_sup_g507_model.tar.gz and use the downloaded model as the --model option..
>   [dragonflye] Error running command: medaka_consensus -i READS.fq.gz -d flye/polish/racon/3/consensus.fasta -o flye/polish/medaka/1 -m r941_min_sup_g507 -t 10  2>&1 | sed 's/^/[polishing - medaka (1 of 2)] /' | tee -a dragonflye.log
> 

Thank you for your help.

Regards,
Eddie

**Steps to Reproduce**
-

**Expected Behavior**
We expect the `--medaka_model r941_min_sup_g507` should not be causing an error because it is ok in `bactopia v2.2.0`.

**Execution Environment**
- Bactopia Version: v3.0.0
- OS: Ubuntu
- Environment: conda

**Additional Information**
-

**Comment by rpetit3** [comment]
Hi @llk578496 

This looks very familiar to the following: https://github.com/rpetit3/dragonflye/issues/20#issuecomment-1574214005

I'm wondering if a `-v ${PWD}:/.medaka` might be needed for this. We might need to play around with the docker runoptions (https://github.com/bactopia/bactopia/blob/master/conf/profiles.config#L21) with this one.

Want to give it a try? If so, I can try adding custom config/profile for this on the dev build

Thanks for reporting this!
Robert

**Comment by llk578496** [comment]
Sure! We would want to have a try.

**Comment by rpetit3** [comment]
Hi @llk578496 

As of v3.0.1, I think this [should be fixed](https://github.com/bactopia/bactopia/blob/master/conf/profiles.config#L21). 

Please let me know if you still ahve issues,
Robert
