### ISSUE TITLE
Run aborted, 

### ISSUE THREAD

**Issue by andreaniml** [bactopia/bactopia#475]
**Description**
I am trying to run the "Tutorial" lines, but with my samples

**Steps to Reproduce**
```
bactopia     --accessions Test_FoFn_accSE.txt     --coverage 100     --outdir Bactopia_Processed     --max_cpus 4 -qs 2


[-        ] process > BACTOPIA:DATASETS                        -
[-        ] process > BACTOPIA:GATHER:GATHER_MODULE            -
[-        ] process > BACTOPIA:GATHER:CSVTK_CONCAT             -
[-        ] process > BACTOPIA:QC:QC_MODULE                    -
[-        ] process > BACTOPIA:ASSEMBLER:ASSEMBLER_MODULE      -
[-        ] process > BACTOPIA:ASSEMBLER:CSVTK_CONCAT          -
[-        ] process > BACTOPIA:SKETCHER:SKETCHER_MODULE        -
[-        ] process > BACTOPIA:ANNOTATOR:PROKKA_MODULE         -
[-        ] process > BACTOPIA:AMRFINDERPLUS:AMRFINDERPLUS_RUN -
[-        ] process > BACTOPIA:AMRFINDERPLUS:GENES_CONCAT      -
[-        ] process > BACTOPIA:AMRFINDERPLUS:PROTEINS_CONCAT   -
[-        ] process > BACTOPIA:MLST:MLST_MODULE                -
[-        ] process > BACTOPIA:MLST:CSVTK_CONCAT               -
[-        ] process > BACTOPIA:DUMPSOFTWAREVERSIONS            -
ERROR ~ Cannot invoke method startsWith() on null object

[skipped  ] process > BACTOPIA:DATASETS                        [100%] 1 of 1, stored: 1 ✔
[-        ] process > BACTOPIA:GATHER:GATHER_MODULE            -
[-        ] process > BACTOPIA:GATHER:CSVTK_CONCAT             -
[-        ] process > BACTOPIA:QC:QC_MODULE                    -
[-        ] process > BACTOPIA:ASSEMBLER:ASSEMBLER_MODULE      -
[-        ] process > BACTOPIA:ASSEMBLER:CSVTK_CONCAT          -
[-        ] process > BACTOPIA:SKETCHER:SKETCHER_MODULE        -
[-        ] process > BACTOPIA:ANNOTATOR:PROKKA_MODULE         -
[-        ] process > BACTOPIA:AMRFINDERPLUS:AMRFINDERPLUS_RUN -
[-        ] process > BACTOPIA:AMRFINDERPLUS:GENES_CONCAT      -
[-        ] process > BACTOPIA:AMRFINDERPLUS:PROTEINS_CONCAT   -
[-        ] process > BACTOPIA:MLST:MLST_MODULE                -
[-        ] process > BACTOPIA:MLST:CSVTK_CONCAT               -
[-        ] process > BACTOPIA:DUMPSOFTWAREVERSIONS            -
ERROR ~ Cannot invoke method startsWith() on null object
 -- Check script '/home/malu/anaconda3/envs/bactopia/share/bactopia-3.0.0/./workflows/../lib/nf/bactopia.nf' at line: 171 or see '.nextflow.log' file for more details
```

**Expected Behavior**
I was expecting to get the same results I get on the tutorial

**Execution Environment**

- Bactopia Version: bactopia 3.0.0
- OS: Ubuntu

**Additional Information**

If I try just a single sample it also crashes, but it is different than this one, on the Gather Step ( I can open another issue if necessary). 
The test profile works just fine.

**Comment by rpetit3** [comment]
Hi @andreaniml 

Can you share the `Test_FoFn_accSE.txt` file? Also for the single sample did you do it with a FOFN or at the command line (`--r1 <sample> --r2 <sample>`)?

Thanks!
Robert

**Comment by andreaniml** [comment]
Hi, @rpetit3 

I tinkered a little bit after posting and I discovered that the run was crashing because somehow the facility that sequenced my reads handed them to me double compressed in a way that after the first decompression it droped the ".gz" (I don't know why). And also, I messed up on the comand line! It should be --samples and not --accessions

So the correct line was:
`bactopia     --samples Test_FoFn_accSE.txt     --coverage 100     --outdir Bactopia_Processed     --max_cpus 4 -qs 2`

After fixing this, it ran without problems! I think my problem is just too specific for it to be of use, maybe trow an error if it fails because the reads seem corrupted?

I ran into another problem though!

I am working with a remote server, I log into it by using ssh. Usually, when I am going to do an analysis that can take long to run, I use nohup to make sure that if I disconnect the process keeps running. 

However, when I try using the line on the post with nohup, it starts to run and then the server stops the job it says: `[1]+  Stopped nohup bactopia -optionsIused`. It runs normaly if I don't use nohup. 

As I never used any nextflow pipeline before, I am wondering if it is just nextflow incompatible with nohup, and if it is, what can I do instead.

To this second problem I can open another issue if necessary!

Thanks!

**Comment by andreaniml** [comment]
It worked! Thanks! 

Just out of curiosity, what would be printed on the screen if I hadn't add the -bg option goes somewhere? Or should I redirect it alongside the command, like adding "> Screen_log.txt" or "&> Screen_log.txt"

I find it useful that it shows the progress

**Comment by rpetit3** [comment]
If you are looking to keep the progress I think you'll want to look into something like `screen` or `tmux`. This is because when you write the normal progress to a file you get a ton of repeated lines as the progress is refreshed.

However, there is a file that is called `.nextflow.log` that you can kind of use to track progress.

A final option would be to use the free version of Nextflow Tower (https://tower.nf/) to have the progress sent there. But not sure if you want to send progress to a third-party site.

**Comment by andreaniml** [comment]
Got it, thank you very much!
