### ISSUE TITLE
MOB-Suite recon [bug]

### ISSUE THREAD

**Issue by kruem-ar** [bactopia/bactopia#478]
Hi Robert, 

Hope all is well with you... I ran into an issue while using MOB-Suite, could you please help me? See details below... 

**Description**
Mobsuite crashed with an error message: " ValueError: No objects to concatenate,"  at the mob_recon step. The weird thing is that it was able to process some of the samples, but not all of them. I checked the QC for the samples that failed, everything was within the expected metrics and the failed samples were successfully processed by other bactopia modules.
**Steps to Reproduce**
I ran the following command on a new set of samples and it crashed during the analysis (See the full error log attached)
[MobSuiteError.txt](https://github.com/bactopia/bactopia/files/14186188/MobSuiteError.txt)
bactopia --wf mobsuite --bactopia bactopia/ -profile singularity --cleanup_workdir

**Execution Environment**
- Bactopia Version:3.0.0
- Environment: conda

Thank you, 
Ana

**Comment by rpetit3** [comment]
Hi @kruem-ar 

I'm hoping this is an easy fix, as it looks like it might have been fixed in teh latest version of Mob-Suite.

I've switch to the latest version in my dev build. Please feel free to give it a try and let me know it it works for you!

```
mamba create -n bactopia-dev -c rpetit -c conda-forge -c bioconda bactopia
```

**Comment by kruem-ar** [comment]
Hi Robert, 

Unfortunately, that didn't worked...

**Comment by kruem-ar** [comment]
Hi @rpetit3, 

Hope all is well... any updates on this? 
Thank you, 
Ana

**Comment by rpetit3** [comment]
Apologies, I was away for training, I am back!

Would it be possible to share the FASTQ files file me, to see if I can replicate on my end? Feel free to contact me at my personal email (robbie.petit at gmail.com)

**Comment by kruem-ar** [comment]
Thanks Robert! I will get those files to you soon

**Comment by rpetit3** [comment]
@kruem-ar reminding myself that this is something related to HPC setup, let me know if I can help in anyway

**Comment by rpetit3** [comment]
Hi @kruem-ar 

I've release [Bactopia v3.0.1](https://bactopia.github.io/latest/changelog/#v301-bactopiabactopia-thats-my-girl-20240325). Since I had previously marked this as "fixed" (haha my reminder to close after the next release!), I will go ahead and close this, please feel free to reopen if you think it should still be open.

Also, it would be super useful if took the time to complete my [2024 Bactopia Usage Survey](https://forms.gle/BA2BDHRQvZtpVcD38). 

Thank you so much!
Robert
