### ISSUE TITLE
[bug] PlasmidFinder CSV Concat doesn't include sample name column

### ISSUE THREAD

**Issue by rwilliams** [bactopia/bactopia#481]
**Description**
PlasmidFinder CSV Concat doesn't include sample name

**Steps to Reproduce**
`bactopia --wf plasmidfinder   --bactopia bactopia_results`

**Expected Behavior**
The concatenated CSV should include the sample name column for the relevant results.

**Execution Environment**

- Bactopia Version: 
BACTOPIATOOLS:PLASMIDFINDER:CSVTK_CONCAT:
  csvtk: 0.27.2
BACTOPIATOOLS:PLASMIDFINDER:PLASMIDFINDER_MODULE:
  plasmidfinder: 2.1.6
Workflow:
  Nextflow: 23.10.1
  bactopia: 3.0.0
  date: 2024-02-12 18:14:33.114331
custom_dumpsoftwareversions:
  python: 3.11.4
  yaml: '6.0'
- OS: [Amazon Linux 2023]
- Environment: [local,nextflow tower with AWS batch]

**Additional Information**
<img width="993" alt="image" src="https://github.com/bactopia/bactopia/assets/29144/660c0983-896c-4d1e-9392-81cc44c43423">

**Comment by rpetit3** [comment]
Hi @rwilliams 

Oh that is no bueno. Do you know if this is the default behavior of Plasmidfinder (e.g. not to include the sampel name)?

There are a few other programs I had to add the sample name to their outputs. I can do the same here.

Will update soon, thank you for reporting!
Robert

**Comment by rpetit3** [comment]
This is now fixed in the dev version https://github.com/bactopia/bactopia/commit/eab0695215a4a222d065575d106472b0664dc0e1

Example
```
Sample  Database        Plasmid Identity        Query / Template length Contig  Position in contig      Note    Accession number
SRX4563634      Inc18   rep16   100.0   744 / 744       SRX4563634_00015 len=26922 cov=244.9 corr=0 origname=Contig_8_244.882_pilon sw=shovill-skesa/1.1.0 date=20240125        13011..13754    CDS6(pSJH101)   CP000737
SRX4563634      RepA_N  rep19   100.0   984 / 984       SRX4563634_00015 len=26922 cov=244.9 corr=0 origname=Contig_8_244.882_pilon sw=shovill-skesa/1.1.0 date=20240125        11602..12585    CDS20(pSJH901)  CP000704
SRX4563634      Rep_trans       rep7c   99.76   821 / 821       SRX4563634_00002 len=403111 cov=52.3 corr=0 origname=Contig_12_52.3135_pilon sw=shovill-skesa/1.1.0 date=20240125       115801..116621  rep(MSSA476)    BX571857
```

Feel free to use the dev version, otherwise it will be in the next release.

thanks again for reporting this!
