### ISSUE TITLE
Error creating conda environment during test [bug] [mac]

### ISSUE THREAD

**Issue by aperreault** [bactopia/bactopia#484]
**Description**
Hi there! I followed the instructions for downloading mamba-forge and was able to create the bactophia environment. Moving to the tutorial, I ran the first line of code bactopia -profile test,standard and get the following error:
2024-02-15 09:28:10 INFO 2024-02-15 09:28:10:root:INFO - Checking if environment pre-builds are needed (this may take a while if building for the first time)
2024-02-15 09:28:10:root:INFO - Begin gather create to /Users/aperreault/.bactopia/conda/bioconda--bactopia-gather-1.0.4
2024-02-15 09:29:00 ERROR 2024-02-15 09:29:00:root:ERROR - Error creating Conda environment, retrying after short sleep.

**Steps to Reproduce**
conda activate bactopia
bactopia -profile test,standard

**Expected Behavior**
Expected output as described on the bactopia tutorial website.

**Execution Environment**
- Bactopia Version: bactopia 3.0.0
- OS: Mac (NOT the M1 or M2 chip!)
- Environment: conda

**Comment by rpetit3** [comment]
Hi @aperreault 

Unfortunately, at the moment for some reason unknown sra-tools (a part of `bactopia-gather`) is no longer built for OSX. I can attempt to ping the NCBI folks to see if they can reconsider building for OSX.

You do still have an option if interested through the use of Docker. If you are interested in trying this, I'm happy to help where I can!

Cheers,
Robert

**Comment by aperreault** [comment]
Hi @rpetit3. Thanks for the response. How unfortunate! I'd love to get working with Docker. If you have any advice, I'd love to hear it. Thanks!

**Comment by rpetit3** [comment]
So here's what I'm thinking.

1. Download [Docker Desktop](https://www.docker.com/products/docker-desktop/), specifically "Download for Mac - Intel Chip"
2. After installation, tweak some settings
    a. [Resources (cpu, memory, storage)](https://docs.docker.com/desktop/settings/mac/#advanced)
    b. [Enable startup when signing on](https://docs.docker.com/desktop/settings/mac/#general)
3. Install bactopia through Conda (the main install does not depend on anything unavailable for OSX)
4. Run the bactopia test profile with docker
    a. `bactopia -profile test,docker`
    
If this all works, you should be all set! In the future to analyze your own samples you would just always add `-profile docker` to the command.

**Comment by aperreault** [comment]
Thanks for the help @rpetit3! Docker has worked great for the basic bactopia analysis, but I've run into an error when running the `summary` command. Below is my line of code:
`bactopia summary --bactopia-path /Users/aperreault/ErynData/test-022824/ -profile docker`
where within test-022824 I have 3 sample directories from 3 individual runs 

Any advice would he helpful!

**Comment by rpetit3** [comment]
This shouldn't happen and I will look into why it happening.

But as a hopefully quick fix. In your bactopia environment, let's try manually installing `typing_extensions` with:

```
pip install typing-extensions
```

**Comment by aperreault** [comment]
That line fixed it! Thanks @rpetit3. I didn't need to add the docker profile to the original line of code either.

**Comment by pvanheus** [comment]
@rpetit3 I had a student hit exactly the same problem on a Linux setup so that `typing-extension` weirdness is not MacOS specific. It only happened once though and I couldn't figure out why.

**Comment by rpetit3** [comment]
Thank you @pvanheus I'll add this as an explicit dependency

**Comment by rpetit3** [comment]
Hi @aperreault 

Me again excuse the same copy and paste, haha only way for me to stay sane! Here it again!

I've release [Bactopia v3.0.1](https://bactopia.github.io/latest/changelog/#v301-bactopiabactopia-thats-my-girl-20240325). Since I had previously marked this as "fixed" (haha my reminder to close after the next release!), I will go ahead and close this, please feel free to reopen if you think it should still be open.

Also, it would be super useful if took the time to complete my [2024 Bactopia Usage Survey](https://forms.gle/BA2BDHRQvZtpVcD38). 

Thank you so much!
Robert
