### ISSUE TITLE
Error linking to bactopia results for ariba tool[bug]

### ISSUE THREAD

**Issue by aperreault** [bactopia/bactopia#488]
**Description**
I tried running the ariba tool after completing the initial bactopia analysis, but received an error related to linking those results to ariba. Something related to the datasets_cache I'm assuming? It's a bit unclear to me if this tool is to find genes in the general species (I'm working with S. aureus) or if it can be used to find differential genes within local samples (I'm working with a few different strains). 

**Steps to Reproduce**
```
bactopia --r1 EB_83_S2_R1_001.fastq.gz --r2 EB_83_S2_R2_001.fastq.gz --sample EB_83_S2 --coverage 100 --genome_size 2800000 --outdir /Users/aperreault/ErynData/test-022824 --max_cpus 4 -profile docker
*ran a similar line of code for 2 other samples*
bactopia summary --bactopia-path /Users/aperreault/ErynData/test-022824/
bactopia --wf ariba --bactopia /Users/aperreault/ErynData/test-022824/ -profile docker
```

**Expected Behavior**
Expected ariba to run, but seems it can't find the files to identify genes. 

**Execution Environment**
- Bactopia Version: v3
- OS: Mac Intelx64
- Environment: Docker (thanks for the help setting this up!)

**Comment by rpetit3** [comment]
Hi @aperreault 

Looks liek there is some missing info on the docs that I can improve.

You will need to provide `--ariba_db` with one of the following values:

```
argannot
card
ncbi
megares
plasmidfinder
resfinder
srst2_argannot
vfdb_core
vfdb_full
virulencefinder
```

Let me know if this helps

**Comment by aperreault** [comment]
Thanks @rpetit3! Do you have a short description of what each of those values represents or would impact in the analysis? New to bactopia so looking to get a good understanding of what each analysis is doing!

**Comment by rpetit3** [comment]
Sure! I guess it depends on what you are looking for.

here's a link from the ariba wiki: https://github.com/sanger-pathogens/ariba/wiki/Task:-getref

argannot --- AMR genes
card --- AMR genes
ncbi --- AMR genes (maybe virulence as well, but this one might not work)
megares -- AMR genes
plasmidfinder -- plasmids
resfinder - haha another AMR one
srst2_argannot --- same as argannot, but a database built with SRST2
vfdb_core --- virulence genes
vfdb_full --- virulence genes (but more!)
virulencefinder --- virulence genes

If you are looking to see genes precents/absent between your samples, I wonder if a [pangenome](https://bactopia.github.io/latest/bactopia-tools/pangenome/) is what you might want?

**Comment by aperreault** [comment]
Thanks for the info! I'm currently running pangenome (it takes a really long time!) so I think that might be more what I'm looking for.

**Comment by rpetit3** [comment]
Hi @aperreault 

This one too, I think we are good to close, feel free to reopen if not! 

message inbound again!

I've release [Bactopia v3.0.1](https://bactopia.github.io/latest/changelog/#v301-bactopiabactopia-thats-my-girl-20240325). Since I had previously marked this as "fixed" (haha my reminder to close after the next release!), I will go ahead and close this, please feel free to reopen if you think it should still be open.

Also, it would be super useful if you took the time to complete my [2024 Bactopia Usage Survey](https://forms.gle/BA2BDHRQvZtpVcD38). 

Thank you so much!
Robert
