### ISSUE TITLE
Staphtyper module compilation error

### ISSUE THREAD

**Issue by Kiratrea** [bactopia/bactopia#503]
Hello, after successfully processing all my samples I have been trying to use the staphtyper workflow. Each time I come across this error. I can't seem to figure out what is causing the unexpected input, could my file structure be part of the issue? 

N E X T F L O W  ~  version 23.10.1
Launching `/home/grege/anaconda3/envs/bactopia-dev/share/bactopia-3.0.2/main.nf` [distracted_ptolemy] DSL2 - revision: 0cd9f79ba7
ERROR ~ Module compilation error
- file : /home/grege/anaconda3/envs/bactopia-dev/share/bactopia-3.0.2/./workflows/../lib/nf/bactopia_tools.nf
- cause: Unexpected input: '{\n        // Default to Bakta faa\n        faa = "${base_dir}/${PATHS['faa']}/bakta/${sample}.faa"\n        gff = "${base_dir}/${PATHS['faa']}/bakta/${sample}.gff3"\n        if (!file("${faa}").exists() && !file("${faa}.gz").exists()) {\n            // Fall back on Prokka\n            faa = "${base_dir}/${PATHS['faa']}/prokka/${sample}.faa"\n            gff = "${base_dir}/${PATHS['faa']}/bakta/${sample}.gff"\n        }\n\n        if (file("${fna}.gz").exists() && file("${faa}.gz").exists() && file("${gff}.gz").exists()) {\n            return tuple([id:sample, is_compressed:true], [file("${fna}.gz")], [file("${faa}.gz")], [file("${gff}.gz")])\n        } else if (file(fna).exists() && file(faa).exists() && file(gff).exists() {\n            return tuple([id:sample, is_compressed:false], [file("${fna}")], [file("${faa}")], [file("${gff}")])\n        }\n    }' @ line 188, column 5.
       } else if (extension == 'fna_faa') {
       ^

1 error

 -- Check script 'anaconda3/envs/bactopia-dev/share/bactopia-3.0.2/./workflows/bactopia-tools.nf' at line: 9 or see '.nextflow.log' file for more details

Here is the nextflow log file 
[.nextflow.log](https://github.com/bactopia/bactopia/files/14906319/default.nextflow.log)

**Comment by rpetit3** [comment]
Hi @Kiratrea 

Thank you for bringing this to my attention! It is now fixed (https://github.com/bactopia/bactopia/commit/cfd4c125fde9e76fe2ff2b28bbe746382f8f8202) and available from the dev version.

Cheers,
Robert

**Comment by Kiratrea** [comment]
Wahoo, looks great! Thanks!

**Comment by rpetit3** [comment]
Hi @Kiratrea 

I've released a new version of Bactopia (https://github.com/bactopia/bactopia/releases/tag/v3.1.0). I think you will be interested in the new `sccmec` tool I've added.

I will go ahead and close, 
Robert
