### ISSUE TITLE
Module installation

### ISSUE THREAD

**Issue by aida-god92** [bactopia/bactopia#505]
Hello!

My question is related to the installation of the bactopia modules. When a process is launched for the first time, the program checks to see if they are installed and if it cannot find them, it proceeds to download it.

Due to the architecture of my server, I would need the installation and search for modules to be carried out in another directory. Is it possible to tell bactopia to install modules in another path other than the user home?

Thanks for the attention!

All the best,

Aida

**Comment by rpetit3** [comment]
Hi @aida-god92 

Are you using Conda or Singularity?

if Conda you will want to use `--condadir` and for Singularity you will want to use `--singularity_cache_dir`.

Now for the pre-downloaded datasets, you will want to use `--datasets_cache`

If this is something you will be doing regularly, I would recommend creating a config file which will save you needing to remember to add it to the command-line each time. Happy to tell you more about this route, if interested.

Cheers,
Robert

**Comment by aida-god92** [comment]
Thank you very much for this super quick answer!
I'm sorry I did not see these flags, but I used and it works perfectly.

Best,

Aida

**Comment by rpetit3** [comment]
Awesome! Glad to hear it worked out for you!

Any suggestions on how I could make these parameters easier to find?

**Comment by aida-god92** [comment]
In this case, I think it was my fault, because I did not read the whole manual. But maybe it could be useful in the installation section:

https://bactopia.github.io/v3.0.0/installation/

Thank you very much! Bactopia is very helpful

**Comment by rpetit3** [comment]
Hi @aida-god92 

I have released a new version of Bactopia (https://github.com/bactopia/bactopia/releases/tag/v3.1.0).

I will go ahead and close this

Robert
