### ISSUE TITLE
[bug] PIRATE cannot run because of unexpected extension

### ISSUE THREAD

**Issue by telatin** [bactopia/bactopia#507]
**Description**
Running PIRATE fails under --wf pangenome with error:

```text
Standardising and checking input files:

 - ERROR: too few gff files (0) have passed QC to be analysed by PIRATE.
 ```

My working directory has these files:
```text
J74_S555.gff3.gz
J75_S556.gff3.gz
J76_S557.gff3.gz
J92_S570.gff3.gz
results
```

the .command.sh is:
```bash
find . -name "*.gff.gz" | sed 's/.gz//' | xargs -I {} bash -c 'gzip -cdf {}.gz > {}'
#              ^^^^^

PIRATE \
    --steps 50,60,70,80,90,95,98 --features CDS \
    --align \
    --threads 4 \
    --input ./ \
    --output results/
...
```

The first command expects .gff.gz but .gff3.gz are present instead

**Steps to Reproduce**

```
# Run bactopia
bactopia --samples S_hominis.tsv --outdir S_hominis \
  --use_bakta  --bakta_db /qib/platforms/Informatics/transfer/outgoing/databases/bakta/bactopia \
 --download_bakta --bakta_db_type full \
 -profile singularity -resume --max_cpus 16 -qs 96

# Run snippy WF
bactopia -profile singularity --wf snippy --bactopia S_hominis/ --reference ncbi_dataset/data/GCA_003812505.1/genomic.gbff 

# Try pangenome wf
bactopia -profile singularity --wf pangenome --bactopia S_hominis
```

**Expected Behavior**
`BACTOPIATOOLS:PANGENOME:PG_TOOL:PIRATE_MODULE (pirate)` can start finding the required input files

**Execution Environment**

- Bactopia Version: `bactopia 3.0.1`
- OS: Ubuntu 20.04.3 LTS
- Environment: VM with Singularity 3.8.5

**Additional Information**
Thanks for checking on this!

**Comment by rpetit3** [comment]
Hi @telatin 

Thank you for reporting this! I found the issue, and it also affects Roary and Panaroo.

Issue with Roary and PIRATE is I wasn't accounting for the `gff3` extension. Then further, Roary and PIRATE only support the `gff` extension, so I have to rename the `gff3` to `gff`

For Panaroo, it supports both `gff3` and `gff` extensions, but you have to use a file of file names (FOFN) input. So, I need to adjust it to utilize a FOFN.

Good news is I think I've fixed Bakta support for each of these tools. I'm currently downloading a Bakta database (might take a little while) and running some samples through Bactopia.

Once I've verified its fixed, I'll update here.

Thanks again for bringing this to my attention!
Robert

**Comment by rpetit3** [comment]
OK! this should now be fixed: https://github.com/bactopia/bactopia/commit/60b805373f13e1135103a3034cad730ab8280218

It's available in my dev build and will be in the next release

```
# dev build
mamba create -n bactopia-dev -c rpetit3 -c conda-forge -c bioconda bactopia
```

Thanks again for letting me know about this!

**Comment by telatin** [comment]
Star support ⭐️ ⭐️ ⭐️ ⭐️ ⭐️

Thanks Rob
