### ISSUE TITLE
How to mix public and local files 

### ISSUE THREAD

**Issue by andreaniml** [bactopia/bactopia#508]
Hello! 

I understand that you can run bactopia workflow for public data by creating a FOFN file using `bactopia --search`. You can also create a file that takes your local samples by doing bactopia --prepare. 

What I am a little confused about is how to structure this if I have both local samples and publicly available genomes on my dataset.

If I've got the working FOFN file for each case should I only concatenate them and run `bactopia --samples`? Should I run bactopia twice pointing to the same outdir?

I wanted to run snippy +gubbins and do some pangenome analysis on this dataset (I don't know if this is relevant for the task at hand)

Thanks for any help!

**Comment by rpetit3** [comment]
Hi @andreaniml 

In Bactopia v3, the outputs for each sample are self-contained. So as long as you run your local samples and public samples in the same directory (or place the sample folders into the same), the Bactopia Tools should find all the samples. 

For your use-case, you would run Bactopia twice:
```
# Run all these in the same directory

# Local samples
bactopia prepare ... > local-samples.txt
bactopia --samples local-samples.txt

# Public samples (samples will go in same directory as local samples)
bactopia search ...
bactopia --accessions bactopia-accessions.txt

# Snippy + Gubbins
bactopia --wf snippy --bactopia bactopia/ <ADDITIONAL_OPTIONS>
```

Now I'm curious if you could combine the two (`--samples` and `--accessions`). I never actually tried something like this:
```
bactopia prepare ... > local-samples.txt
bactopia search ...
bactopia --samples local-samples.txt --accessions bactopia-accessions.txt
```

Does this make sense? Happy to describe it more

Cheers,
Robert

**Comment by andreaniml** [comment]
This makes sense! 

Thank you for the quick reply, will try this over here

Cheers!

**Comment by rpetit3** [comment]
Awesome! _(let me know if you try mixing them!)_

**Comment by andreaniml** [comment]
Hi, coming back to tell you that I ran a test with two local samples and two publicly available genomes.

I've found that bactopia ignores the  `--accessions` flag when the `--samples` is used. Does not matter in which order you input it.

If I face any problems running one after the other I'll come back here (it's going to take a while to process)

**Comment by andreaniml** [comment]
A little deviation on the original post, but how can I make bactopia use bakta? I need to download the db, but I can't get the command line right (--use_bakta asks for the path of the db, --download_bakta asks for it as well, and if I specify the --bakta_db it does not work either)

**Comment by rpetit3** [comment]
I actually just tried this today (was dev build, but should work in v3.0.1)

```
# first time downloading
bactopia --samples samples.txt --use_bakta --download_bakta --bakta_db /path/to/save/bakta

# second run
bactopia --accessions accessions.txt --use_bakta --bakta_db /path/to/save/bakta
```

**Comment by andreaniml** [comment]
Everything worked! Thanks for the help!

I however have another problem, I'm going to open a new issue!
