### ISSUE TITLE
One file from Gubbins output is missing

### ISSUE THREAD

**Issue by andreaniml** [bactopia/bactopia#510]
**Description**
Hi Robert! It's me again, I think I've found another bug

I am running the snippy workflow, I passed the bootstrap options to gubbins and it ran flawlessly, except that when I checked the results, the bootstraped final tree from Gubbins was missing. 

**Steps to Reproduce**
```
bactopia --wf snippy --bactopia Results_Processed --reference genomic_LT2.gbff --iterations 8 --gubbin_opts="--bootstrap 1000 --tree-builder iqtree --custom-model GTR+I+G" --skip_phylogeny --outdir Results_Processed --max_cpus 15 -qs 1 -bg -resume
```
The resume flag is there because I made a typo onthe gubbins options the first time

**Expected Behavior**
All the gubbins outputs into the gubbins folder.

**Execution Environment**

- Bactopia Version:bactopia-dev
- OS: Ubuntu
- Environment: conda

**Additional Information**

I was able to find the tree into the work directory, I think that maybe bactopia did not copy that tree into the final folder because it's named "core-snp.final_bootstrapped_tree.tre" and the other trees are named "core-snp.final_tree.tre" or "core-snp.node_labelled.final_tree.tre"

I can provide the logs, just not sure which one as there is no error message.

Cheers!

**Comment by rpetit3** [comment]
This one might have been an easy fix: https://github.com/bactopia/bactopia/commit/9a532ac60b10cb6ec8d903dae62bd74053aea01c

I do have a question for you. If you are using `--boostrap` would you like the final IQTree to be based off the final_tree (current behavior) or the bootstrap_final_tree?

**Comment by andreaniml** [comment]
I think that the current behavior is ok, but I do not have much experience on this, so someone may have a different opinion

I am still deciding on what to do with the tree (If I use the that comes directly from Gubbins for downstream analysis or to use the recombination free alignment while informing constant sites in order to create another tree).

**Comment by rpetit3** [comment]
Sounds good, I'll leave it as is.

**Comment by rpetit3** [comment]
HI @andreaniml 

I have released a new version of Bactopia (https://github.com/bactopia/bactopia/releases/tag/v3.1.0).

I will go ahead and close this.

Cheers,
Robert
