### ISSUE TITLE
[feature] BACTOPIATOOLS:MLST:MLST_MODULE untar database once in cache instead of for every sample

### ISSUE THREAD

**Issue by nickjhathaway** [bactopia/bactopia#514]
***Related To***  
- [ ] Bactopia
- [x] Bactopia Tools

***Is this related to a problem?***  
The MLST module, every time it runs for a sample, untars the MLST database from the database cache directory (e.g. https://github.com/bactopia/bactopia/blob/master/modules/nf-core/mlst/main.nf#L32) which isn't a big deal for a small sample set but as the number of samples increases this causes a couple of issues. The database contains over 1,000 files, so there are a lot of I/O operations to create all those files. It's an extreme example, but I was analyzing over 100K samples, and so in the **work** directory, it created over 100 million files for all the untar MLST database, which ended up being over 2TB of data for all the copies. It's a week out and I'm still in the process of deleting all those files lol. 

***Describe the solution you'd like***
It may be more optimal if instead of symlinking in a copy of the mlst.tar.gz and untaring it each time if instead a symlink to an untar mlst.tar.gz was used. For example, I untared the mlst.tar.gz in the dataset cache directory, and then I hacked my local copy of https://github.com/bactopia/bactopia/blob/master/modules/nf-core/mlst/main.nf#L32 to be 

```
    #tar -xzvf $db
    ln -s /tank/data/bacteria/all/bactopia/testing_new/datasets/v3.0.1/mlstdb
```
and it appears to work well. When I used it on my next set of 100,000 samples, it created a much more manageable **work** directory and ran faster as it wasn't constantly untaring the database. 

I would have changed the nextflow code and put in a pull request to do this but I haven't worked with modifying nextflow and I actually couldn't figure out how to do this automatically within the pipeline lol. I also wasn't sure if there may have been a specific reason why the module was running this way that I may have been missing.

**Comment by rpetit3** [comment]
Hi @nickjhathaway 

Haha I learned this the hard way as well! I'll get a band-aid (delete the database at after completion) then work on a single extraction method, which should play nicer on local/HPC systems.

I think it should work like the kraken databases work, an option of passing the tarball or path to extracted tarball.

Will update soon! Thanks for reporting this!
Robert

**Comment by rpetit3** [comment]
OK here's a band-aid: https://github.com/bactopia/bactopia/commit/77302486fb658c7b2b9ab18ac9b5e6d5eb8b0a8e available from dev-build

I'll look into the tarball/untarred approach

Curious, when species were you running mlst on? I was running on the s. aureus ATB assemblies ~109k

**Comment by nickjhathaway** [comment]
Similarly, I was doing the ATB but with the E. coli assemblies set, which is about 270kb assemblies. 

I like the option of passing the tarball or path to an extracted tarball idea. It would also allow for custom MLST databases. In version 2 of bactopia I had created a custom MLST for a gene in ecoli fimH so I could type my samples based on that gene in addition to the other MLSTs, which is a functionality I haven't been able to see how I could replicate in version 3

**Comment by rpetit3** [comment]
If you are ok with the tarball for now, in the next version (available from dev build) I've added `--mlst_db` that will take priority over the built in MLST database (https://github.com/bactopia/bactopia/commit/16545ce5b73758969235871ce33463f4aacf6300) 

I think this will allow you to pass your custom database. At the moment the only requirement is that the base directory after extraction is called `mlstdb` (this will be fixed so that its more similar to kraken's setup)

**Comment by nickjhathaway** [comment]
This might be a silly question, but how do I build from the dev build? I've been installing via conda/mamba via the instructions here: https://github.com/bactopia/bactopia?tab=readme-ov-file#installation. I'm fairly unfamiliar with mamba/conda and looking around I couldn't figure out how to install via a specific git branch

**Comment by rpetit3** [comment]
No worries 

```
mamba create -n bactopia-dev -c rpetit3 -c conda-forge -c bioconda bactopia
```

**Comment by rpetit3** [comment]
hi @nickjhathaway 

You can now pass either a tarball or directory to `--mlst_db` and `--amrfinder_db` (https://github.com/bactopia/bactopia/commit/a3ed0f22403830d7916332d75d978b6dc6ad8c19)

If you have a chance to test it, please rebuild the dev environmeny. Let me know if it gives you any issues.

Cheers,
Robert

**Comment by nickjhathaway** [comment]
I got it to work with the `--mlst_db` argument with both the default mlstdb directory and my custom mlst but for some reason, even with using the default --wf mlst without `--mlst_db` the output isn't binding into the results directory, I can see in the `work` directory the finished results and the nextflow log shows the message 

```
May-07 17:24:58.131 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Process BACTOPIATOOLS:MLST:MLST_MODULE > Skipping output binding because one or more optional files are missing: fileoutparam<1>
```
Steps I took. I have a test directory with the following files 

```bash
> ls testingSamplesAssemblies
SAMD00075830.fa.gz  SAMD00075836.fa.gz  SAMD00075838.fa.gz  SAMD00075842.fa.gz  SAMD00075850.fa.gz  SAMD00075857.fa.gz  SAMD00075860.fa.gz  SAMD00075865.fa.gz  SAMD00075871.fa.gz  SAMD00075873.fa.gz
```
```bash
mamba create -n bactopia-dev -c rpetit3 -c conda-forge -c bioconda bactopia
conda activate bactopia-dev

bactopia atb-formatter --path testingSamplesAssemblies --recursive --bactopia-dir testingSamplesAssemblies_bactopiaAnalysis --extension .fa.gz

```

and then all 3 of these commands successfully run and I can see the correct results in the `work` directory but they don't get copied into the `testingSamplesAssemblies_bactopiaAnalysis` directory 

```bash
bactopia     -profile docker     --max_cpus 2     --datasets_cache /tank/data/bacteria/all/bactopia/testing_new/datasets     --wf mlst     --bactopia testingSamplesAssemblies_bactopiaAnalysis/

bactopia     -profile docker     --max_cpus 2     --datasets_cache /tank/data/bacteria/all/bactopia/testing_new/datasets     --wf mlst     --bactopia testingSamplesAssemblies_bactopiaAnalysis/ --mlst_db /tank/data/bacteria/all/bactopia/testing_new/datasets/v3.0.1/mlstdb/

bactopia     -profile docker     --max_cpus 2     --datasets_cache /tank/data/bacteria/all/bactopia/testing_new/datasets     --wf mlst     --bactopia testingSamplesAssemblies_bactopiaAnalysis/ --mlst_db /tank/data/bacteria/e_coli/fimH/2024_04_28/bactopia3/mlstdb/
```

and I see this message multiple times in the .nextflow.log file 

```
May-07 17:24:58.131 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Process BACTOPIATOOLS:MLST:MLST_MODULE > Skipping output binding because one or more optional files are missing: fileoutparam<1>
```

**Comment by rpetit3** [comment]
I'll give this a try with some ATB samples and report back to you, thanks for letting me know!

**Comment by nickjhathaway** [comment]
So I did some digging on it too, and it looks like there's a slight difference in the default behavior of the output directory between `3.0.1` and the `dev` version. I find that this is true for all the workflows, not just the `mlst` workflow. In `3.0.1`, the output directory will default to the `--bactopia` directory that is supplied and in the `dev` version it will default to be a directory named `bactopia` unless explicitly set with `--outdir`. 

So for the above examples 
```bash
bactopia     -profile docker     --max_cpus 2     --datasets_cache /tank/data/bacteria/all/bactopia/testing_new/datasets     --wf mlst     --bactopia testingSamplesAssemblies_bactopiaAnalysis/

bactopia     -profile docker     --max_cpus 2     --datasets_cache /tank/data/bacteria/all/bactopia/testing_new/datasets     --wf mlst     --bactopia testingSamplesAssemblies_bactopiaAnalysis/ --mlst_db /tank/data/bacteria/all/bactopia/testing_new/datasets/v3.0.1/mlstdb/

bactopia     -profile docker     --max_cpus 2     --datasets_cache /tank/data/bacteria/all/bactopia/testing_new/datasets     --wf mlst     --bactopia testingSamplesAssemblies_bactopiaAnalysis/ --mlst_db /tank/data/bacteria/e_coli/fimH/2024_04_28/bactopia3/mlstdb/
```

The output of the run was placed in a directory named `bactopia` for the `dev` version, however with the `3.0.1 `version  the following command  
```bash
bactopia     -profile docker     --max_cpus 2     --datasets_cache /tank/data/bacteria/all/bactopia/testing_new/datasets     --wf mlst     --bactopia testingSamplesAssemblies_bactopiaAnalysis/
```
will output results to `testingSamplesAssemblies_bactopiaAnalysis/`

And with the `dev` version, I can fix this by adding `--outdir`
```bash
bactopia     -profile docker     --max_cpus 2     --datasets_cache /tank/data/bacteria/all/bactopia/testing_new/datasets     --wf mlst     --bactopia testingSamplesAssemblies_bactopiaAnalysis/ --outdir testingSamplesAssemblies_bactopiaAnalysis/
```
What's interesting is in the run info that is out in the `dev` version when you don't supply the `--outdir` argument, it still says the output directory will be the input `--bactopia` directory but then will still place things in a directory named `bactopia`  

```bash 
Core Nextflow options
  runName              : jolly_brown
  containerEngine      : docker
  container            : quay.io/bactopia/bactopia:3.0.2
  launchDir            : /cauldron/data/bacteria/e_coli/bactopia/AllTheBacteria/testing_site
  workDir              : /cauldron/data/bacteria/e_coli/bactopia/AllTheBacteria/testing_site/work
  projectDir           : /home/hathawan/miniforge3/envs/bactopia-dev/share/bactopia-3.0.2
  userName             : hathawan
  profile              : docker
  configFiles          : /home/hathawan/miniforge3/envs/bactopia-dev/share/bactopia-3.0.2/nextflow.config

Required Parameters
  bactopia             : testingSamplesAssemblies_bactopiaAnalysis/

Optional Parameters
  outdir               : testingSamplesAssemblies_bactopiaAnalysis/
```

So the simple fix for now is to always supply the `--outdir` flag explicitly, but I wanted to give you the heads up as this seems to be an unintended behavior

**Comment by rpetit3** [comment]
Found the issue, and should now be fixed. Will just need a rebuild of dev env

Issue was the function for saving files was imported prior to when `outdir` was set to the value of `--bactopia`. So it would always be the default (`bactopia`) unless `--outdir` was utilized.

Hopefully this should be good to go now! Thanks again for finding this!

**Comment by nickjhathaway** [comment]
Happy to help! Thanks for making such a great tool, I'll close out the issue as things are working now
