### ISSUE TITLE
how to use with Fasta file 

### ISSUE THREAD

**Issue by Ronykumawat** [bactopia/bactopia#516]
hello 
 I am using Bactopia for comparative analysis of genome i have 1300 fasta file analysis these through pipeline i need guidance what should i went to do and please share the steps with details.

Thank  you

**Comment by rpetit3** [comment]
Hi @Ronykumawat 

You have a few options here.

1. Use `bactopia prepare` to create a FOFN to process genomes

Here are more details on using `bactopia prepare` for multiple local samples: https://bactopia.github.io/latest/beginners-guide/#local-samples 

For this you may need to adjust `--assembly_ext` to match the extension of your assemblies. The default is `.fna.gz.`

2. Use `bactopia atb-formatter` 

I recently made a blog post called [Using Bactopia with AllTheBacteria Assemblies](https://bactopia.github.io/latest/blog/2024/bactopia-allthebacteria-tutorial/). In this tutorial I highlight how you can use assemblies from the [AllTheBacteria](https://github.com/iqbal-lab-org/AllTheBacteria) project with Bactopia. While your assemblies are not from ATB, you can use `bactopia atb-formatter` for your assemblies. 

For each of these methods, upon completion you will have access to each of the available [Bactopia Tools](https://bactopia.github.io/latest/bactopia-tools/) that leverage the assemblies.

Let me know if you have any questions! 
Robert

**Comment by Ronykumawat** [comment]
Hello Robert
               I hope you are well.Thank you for reply and i went to know
can i apply at your lab for Phd can you help me out in these I am  very
grateful if you help me.

Thank You



* Your Sincerely*
*Rounak Kumawat *
Studying in Department of Biotechnology, at  *Dr. Hari Singh Gour
Vishwavidyalaya, Sagar (Central University) *
Contact no. 7413810194
E-mail ***@***.***

**Comment by rpetit3** [comment]
Hi @Ronykumawat 

Unfortunately, I do not work in academia with a lab to host students.

In other news, I have released a new version of Bactopia (https://github.com/bactopia/bactopia/releases/tag/v3.1.0)

I will go ahead and close this, 
Robert
