### ISSUE TITLE
[bug] Bactopia doesn't like uncompressed FASTQs from ONT

### ISSUE THREAD

**Issue by fanninpm** [bactopia/bactopia#518]
**Description**
I was trying out Bactopia with some uncompressed FASTQs from ONT, when the run crashed during the gathering stage. It seems like Bactopia is assuming that ONT reads are properly gzip'd.

**Steps to Reproduce**
```
bactopia --sample my_sample --ont my_sample.fastq
```

**Expected Behavior**
Bactopia should detect that this file is uncompressed and proceed as normal.

**Execution Environment**

- Bactopia Version: `bactopia 3.0.1`
- OS: Debian 12
- Environment: Google Batch (it shouldn't matter for the purposes of this bug report)

**Additional Information**
I can't easily gzip the input files in situ, as I specify my inputs from a Google Cloud bucket.

**Comment by rpetit3** [comment]
Hi @fanninpm 

You will need to compress the input FASTQs. The requirement for compressed FASTQs is a practice shared by Bactopia and nf-core.

Cheers,
Robert

**Comment by rpetit3** [comment]
Hi @fanninpm 

I have released a new version of Bactopia (https://github.com/bactopia/bactopia/releases/tag/v3.1.0).

Given this is something that will not change in Bactopia, I will go ahead and close this.

Cheers,
Robert
