### ISSUE TITLE
[bug] Iqtree Usage/Missing?

### ISSUE THREAD

**Issue by rwilliams** [bactopia/bactopia#522]
**Description**
I'm attempting to run Iqtree against my Bactopia results and Bactopia says "iqtree is not a known workflow". Bactopia also does not show IQtree under the workflow list.

**Steps to Reproduce**
```
bactopia --wf iqtree \
  --bactopia /path/to/your/bactopia/results \ 
  --include includes.txt  
```

```
bactopia --list_wfs
```

**Expected Behavior**
Iqtree module to be launched. 

**Execution Environment**
- Bactopia Version: Bactopia 3.0.1 - via Conda
- OS: Amazon Linux 2023
- Environment: conda
- Nextflow: 23.10.1 build 5891

**Comment by rpetit3** [comment]
Hi @rwilliams,

IQTree is built into bactopia tools that use it (e.g. pangenome, snippy, etc) and isn't directly runnable since a multiple sequence alignment is needed.

What were you hoping to do?

Cheers,
Robert
