### ISSUE TITLE
[bug] Hicap 1.0.3 for Docker

### ISSUE THREAD

**Issue by MartinVad** [bactopia/bactopia#528]
**Description**
Hicap 1.0.3 uses Docker v1 which is disabled in newer Docker installations.

**Steps to Reproduce**
```
    nextflow run bactopia/bactopia \
        --wf merlin \
        --bactopia ${bactopia} \
        -profile docker
...
  Command error:
    Unable to find image 'quay.io/biocontainers/hicap:1.0.3--py_0' locally
    1.0.3--py_0: Pulling from biocontainers/hicap
    docker: [DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of quay.io/biocontainers/hicap:1.0.3--py_0 to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/.
    See 'docker run --help'.
```

**Expected Behavior**
It should be able to use Hicap in Docker Format v2. This should be solved in Hicap 1.0.4

**Execution Environment**

- Bactopia Version: v3.0.1
- Environment: Docker

**Comment by rpetit3** [comment]
Hi @MartinVad 

Your PR is now available in https://github.com/bactopia/bactopia/releases/tag/v3.1.0

Going to go ahead and close this, thanks again for the PR!
Robert
