### ISSUE TITLE
[question] Include samples file location 

### ISSUE THREAD

**Issue by rwilliams** [bactopia/bactopia#529]
In the example below does include.txt need to be a local file or can it point to cloud storage like s3? Thanks!

```
bactopia --wf pangenome \
  --bactopia /path/to/your/bactopia/results \ 
  --include includes.txt  
```

**Comment by rpetit3** [comment]
Hi @rwilliams 

I think the answer is yes, but I have never done it. NextFlow should recognize the s3 and automatically stage the file to be read.

Let me know if it doesn't!
Robert

**Comment by rpetit3** [comment]
Hi @rwilliams 

You PR is now available in https://github.com/bactopia/bactopia/releases/tag/v3.1.0

Going to go a head and close this, thank you again for the PR!
Robert
