### ISSUE TITLE
installing databases (datasets) in a different location [question]

### ISSUE THREAD

**Issue by bharat1912** [bactopia/bactopia#534]
Hi, 
I wanted to install all the databases in a different location and not the default location but I may have missed the section which refers to this in the documents. Grateful if you could advise on this.
Thanks
Bharat

**Comment by rpetit3** [comment]
Hi @bharat1912 

I have released a new version of bactopia (https://github.com/bactopia/bactopia/releases/tag/v3.1.0).

I'm going to go ahead and close this,
Robert
