### ISSUE TITLE
[feature] Adding --accession and modify --reference in snippy

### ISSUE THREAD

**Issue by llk578496** [bactopia/bactopia#543]
Hi @rpetit3 ,

**Related To**

- [ ] Bactopia
- [x] **Bactopia Tools**

**Is this something you would like to see added?**
I would like to propose adding two enhancements to the subworkflow - `snippy`:

- Add a new option `--accession`
- Modify the existing `--reference` option to automatically download the GenBank file from NCBI

Thank you for your consideration!

Best regards,
Eddie

**Comment by rpetit3** [comment]
@llk578496 thanks for the suggestion, let me look into this and see if I can squeeze it into this next release (I think I can steal code from the fastani subworkflow)

**Comment by rpetit3** [comment]
Added in https://github.com/bactopia/bactopia/commit/e8e4a77866e333cd578d5e48edc4a0a19e207018

You can provide either `--accession` or `--reference` not both

Will be available in next release

**Comment by llk578496** [comment]
Thank you very mcuh!

**Comment by rpetit3** [comment]
Hi @llk578496 

This is now available in https://github.com/bactopia/bactopia/releases/tag/v3.1.0

Let me know if it gives you any issues!
Robert
