### ISSUE TITLE
[bug] Panaroo stuck for hours 

### ISSUE THREAD

**Issue by kruem-ar** [bactopia/bactopia#552]
Hey Robert, for the last couple of days I have been trying to run panaroo on my samples and it is getting stuck on the initial step for hours. There was no error message, its just stuck on the same place after 20+ hours. I tested the same samples with --use_roary and it worked, so it might be a panaroo problem? 

**Steps to Reproduce**
nextflow run bactopia/bactopia --wf pangenome --use_panaroo \
 --bactopia bactopia -c scicomp.config -profile test,singularity,scicomp_rosalind \
 --cleanup_workdir --outdir panaroo

**output after 20hrs**
--------------------------------------------------------------------
   _                _              _         _              _
  | |__   __ _  ___| |_ ___  _ __ (_) __ _  | |_ ___   ___ | |___
  | '_ \ / _` |/ __| __/ _ \| '_ \| |/ _` | | __/ _ \ / _ \| / __|
  | |_) | (_| | (__| || (_) | |_) | | (_| | | || (_) | (_) | \__ \
  |_.__/ \__,_|\___|\__\___/| .__/|_|\__,_|  \__\___/ \___/|_|___/
                            |_|
bactopia tools pangenome v3.0.1
  Pangenome analysis with optional core-genome phylogeny
--------------------------------------------------------------------
Core Nextflow options
  revision                  : master
  runName                   : sharp_brattain
  containerEngine           : singularity
  container                 : quay.io/bactopia/bactopia:3.0.1
  launchDir                 : /scicomp/groups-pure/OID/NCEZID/DFWED/EDLB/projects/NBETT_bot/projects/2024_IBRCC_Surveillance
  workDir                   : /scicomp/scratch/quc0/nextflow/work
  projectDir                : /scicomp/home-pure/quc0/.nextflow/assets/bactopia/bactopia
  userName                  : quc0
  profile                   : test,singularity,scicomp_rosalind
  configFiles               : /scicomp/home-pure/quc0/.nextflow/assets/bactopia/bactopia/nextflow.config, /scicomp/groups-pure
/OID/NCEZID/DFWED/EDLB/projects/NBETT_bot/projects/2024_IBRCC_Surveillance/scicomp.config

Required Parameters
  bactopia                  : bactopia

Panaroo Parameters
  use_panaroo               : true

Prokka Parameters
  proteins                  : /scicomp/home-pure/quc0/.nextflow/assets/bactopia/bactopia/data/proteins.faa

Optional Parameters
  outdir                    : panaroo

Max Job Request Parameters
  max_cpus                  : 2
  max_memory                : 6

Nextflow Configuration Parameters
  cleanup_workdir           : true

Institutional config options
  config_profile_description: HPC @ CDC
  config_profile_contact    : OAMD
  config_profile_url        : https://info.biotech.cdc.gov/info/

Nextflow Profile Parameters
  condadir                  : /scicomp/home-pure/quc0/.bactopia/conda
  datasets_cache            : /scicomp/home-pure/quc0/.bactopia/datasets
  singularity_cache_dir     : /scicomp/home-pure/quc0/.bactopia/singularity

Helpful Parameters
  wf                        : pangenome

[-        ] process > BACTOPIATOOLS:PANGENOME:CLO... -
[-        ] process > BACTOPIATOOLS:PANGENOME:CLO... -
[-        ] process > BACTOPIATOOLS:PANGENOME:FIN... -
[-        ] process > BACTOPIATOOLS:CUSTOM_DUMPSO... -
Pulling Singularity image https://depot.galaxyproject.org/singularity/panaroo:1.4.2--pyhdfd78af_0 [cache /scicomp/scratch/quc0/nextflow/singularity_cache/depot.galaxyproject.org-singularity-panaroo-1.4.2--pyhdfd78af_0.img]
WARN: The operator `first` is useless when applied to a value channel which returns a single value by definition
Updating max_memory: '[:]' to 26 based on available resources
Updating max_memory: '[:]' to 26 based on available resources

[-        ] process > BACTOPIATOOLS:PROKKA:PROKKA... -
[-        ] process > BACTOPIATOOLS:PANGENOME:PG_... [  0%] 0 of 1
[-        ] process > BACTOPIATOOLS:PANGENOME:SNP... -
[-        ] process > BACTOPIATOOLS:PANGENOME:CLO... -
[-        ] process > BACTOPIATOOLS:PANGENOME:CLO... -
[-        ] process > BACTOPIATOOLS:PANGENOME:FIN... -
[-        ] process > BACTOPIATOOLS:CUSTOM_DUMPSO... -
Pulling Singularity image https://depot.galaxyproject.org/singularity/panaroo:1.4.2--pyhdfd78af_0 [cache /scicomp/scratch/quc0/nextflow/singularity_cache/depot.galaxyproject.org-singularity-panaroo-1.4.2--pyhdfd78af_0.img]
WARN: The operator `first` is useless when applied to a value channel which returns a single value by definition

executor >  sge (1)
[-        ] process > BACTOPIATOOLS:PROKKA:PROKKA... -
[06/b434d9] process > BACTOPIATOOLS:PANGENOME:PG_... [  0%] 0 of 1
[-        ] process > BACTOPIATOOLS:PANGENOME:SNP... -
[-        ] process > BACTOPIATOOLS:PANGENOME:CLO... -
[-        ] process > BACTOPIATOOLS:PANGENOME:CLO... -
[-        ] process > BACTOPIATOOLS:PANGENOME:FIN... -
[-        ] process > BACTOPIATOOLS:CUSTOM_DUMPSO... -
Pulling Singularity image https://depot.galaxyproject.org/singularity/panaroo:1.4.2--pyhdfd78af_0 [cache /scicomp/scratch/quc0/nextflow/singularity_cache/depot.galaxyproject.org-singularity-panaroo-1.4.2--pyhdfd78af_0.img]
WARN: The operator `first` is useless when applied to a value channel which returns a single value by definition

**Execution Environment**

- Bactopia Version: 3.0.1
- Environment: cluster

**Comment by maxlcummins** [comment]
How many genomes are you analysing?

Core genome alignment from a pangenomic tool for big sample sizes can take a long time.

What step is it stuck on?

**Comment by rpetit3** [comment]
Hi @kruem-ar 

Agree with @maxlcummins, would you mind sharing more info about your sample set.

**Comment by kruem-ar** [comment]
Hi there, 

Thank you for checking my request... It turns out that I was able to run those in the conda environment and this seems to be an issue only when I try to run it directly from the GitHub repository using nextflow and combining it with my institution's nextflow config and profile parameters. 

I will go ahead and close it!
Thanks again
