### ISSUE TITLE
[question] What are the requirements for running v3 directly from the repo

### ISSUE THREAD

**Issue by mehalter** [bactopia/bactopia#555]
It is mentioned a couple times in [the documentation](https://bactopia.github.io/latest/quick-start/) that Bactopia can be run directly from the github repo with Nextflow using:

```sh
nextflow bactopia/bactopia -profile test,standard
```

I keep trying this out but run into the error

```
Project config file is malformed -- Cause: No signature of method: groovy.util.ConfigObject.toInteger() is applicable for argument types: () values: []
```

My guess is maybe there is some configuration that I am missing when trying to execute the pipeline directly rather than through the CLI helper. Could you possibly provide some more insight into what is necessary for it to run like this?

I currently attempting this from an AWS EC2 instance running Amazon Linux 2023 with Docker and Nextflow installed. My end goal is to be kicking off a pipeline directly on AWS and doing processing with the AWS Batch executor, but am taking some baby steps along the way.

Thank so much in advance!

**Comment by rpetit3** [comment]
Do you mind trying the following? 

```
nextflow run bactopia/bactopia -r v3.1.0 -profile test,standard
```

I receive the config error when I try with v3.0.1

```
nextflow run bactopia/bactopia -r v3.0.1 -profile test,standard
```

**Comment by mehalter** [comment]
@rpetit3 I get the error when running v3.1.0 and I do not get the error with v3.0.1
![2024-09-30_11:33:30_screenshot](https://github.com/user-attachments/assets/9dbebcf4-5b11-4937-a0b5-da7629c41e53)

**Comment by rpetit3** [comment]
Ok! I was able to replicate this on a fresh system, I'll update soon

**Comment by mehalter** [comment]
You are the best! Thank you so much sir

**Comment by rpetit3** [comment]
Also, reading the original issue. Docker is mentioned, so I would even suggest replacing `standard` with `docker` in the `-profile` section. 

This should at least remove any potential Conda related headaches that might pop up

**Comment by mehalter** [comment]
Aweseome, looks like that fixed things! I'll go ahead and close this issue :)

Could I ask a follow up question here just to not create a bunch of noise by opening more issues? Now that I have it able to be easily run with `nextflow run` I'm trying to configure usage with the `awsbatch` profile and I think I may be missing something. Here is the command that I am running:

```sh
nextflow run bactopia/bactopia -r dev \
  -profile test,awsbatch \
  -work-dir s3://nextflow-s3-bucket-1234/bactopia/workdir \
  --outdir s3://nextflow-s3-bucket-1234/bactopia/out \
  --awsqueue analysis-jobq-9f9048f \
  --awsregion us-east-2 \
  --awscli /usr/bin/aws
```

I am getting an error that the container is unable to create a shim task:

```

ERROR ~ Error executing process > 'BACTOPIA:DATASETS'

Caused by:
  Task failed to start - CannotStartContainerError: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/usr/local/env-execute": stat /usr/local/env-e


Command executed:

  mkdir -p v3.0.1
  wget -O v3.0.1/amrfinderplus.tar.gz https://datasets.bactopia.com/datasets/v3.0.1/amrfinderplus.tar.gz
  wget -O v3.0.1/mlst.tar.gz https://datasets.bactopia.com/datasets/v3.0.1/mlst.tar.gz
  wget -O gtdb-rs207.genomic-reps.dna.k31.lca.json.gz https://datasets.bactopia.com/datasets/gtdb-rs207.genomic-reps.dna.k31.lca.json.gz
  wget -O mash-refseq88.k21.msh.xz https://datasets.bactopia.com/datasets/mash-refseq88.k21.msh.xz

Command exit status:
  -

Command output:
  (empty)

Work dir:
  s3://nextflow-s3-bucket-1234/bactopia/workdir/75/026e0325a6044e9614850b72bb9cfb
```

I'm wondering if I am missing something which tells it where to store the `env-execute` shim task since that's what it seems to mess up creating (if I am understanding the error correctly at least)

Oh another question is what are the minimum memory/cpu requirements to set up the AWS Batch Queue? I have looked through all the documentation and can't find the answers to this stuff, if it is somewhere then just pointing me in the right direction is good as well 😄 


Thanks again so much!

**Comment by rpetit3** [comment]
First one, if you are attempting this with the `awsbatch` profile built into bactopia it should be `-profile test,aws` 

For the second, the resources are specified here: https://github.com/bactopia/bactopia/blob/master/conf/base.config#L21-L54

Where the maximum memory and cpus is set by `params.max_memory` and `params.max_cpus`

@rwilliams is utilizing AWS as well, any input/advice you have @rwilliams will be well received

**Comment by mehalter** [comment]
Aweseome, thanks so much @rwilliams ! I just got a solution working yesterday afternoon with a bare EC2 instance running Nextflow spinning out jobs to an AWS Batch queue. Currently all implemented as an infrastructure fully defined as infrastructure as code (IaC) as well as custom AMIs built using Packer (also defined/automated as code). I think we are on the correct path, but will definitely check out this workshop for a batch² approach!

Getting to a place with a fully reproducible infrastructure for spinning out some genomics sequencing platforms 🥳

**Comment by mehalter** [comment]
@rpetit3 I have bactopia running without any errors it seems on AWS Batch using `nextflow run bactopia/bactopia` but it seems to not be completing the entire list of steps. Could you please provide any guidance as to why these steps would be getting skipped or not ran at at all. Here is the output and summary from the run.

I'm currently running the following command:

```sh
nextflow run bactopia/bactopia -r v3.0.1 -work-dir 's3://nextflow-s3-bucket-1234/bactopia/workdir' -profile test,aws --aws_queue analysis-jobq-9f9048f --aws_region us-east-2 --outdir 's3://nextflow-s3-bucket-1234/bactopia/out_test_tutorial' --aws_cli_path /home/ec2-user/miniconda/bin/aws --max_memory 3 --max_cpus 2 --accession SRX4563634 --sample SRX4563634 --coverage 100 --genome_size 2800000
```

and I'm getting the following output:

```
[skipped  ] BACTOPIA:DATASETS                          | 1 of 1, stored: 1 ✔                            
[97/70a1fc] BACTOPIA:GATHER:GATHER_MODULE (SRX4563634) | 1 of 1 ✔                                       
[62/0fe79d] BACTOPIA:GATHER:CSVTK_CONCAT (meta)        | 1 of 1 ✔                                       
[32/a05fa4] BACTOPIA:QC:QC_MODULE (SRX4563634)         | 1 of 1 ✔                                       
[-        ] BACTOPIA:ASSEMBLER:ASSEMBLER_MODULE        -                                                
[-        ] BACTOPIA:ASSEMBLER:CSVTK_CONCAT            -                                                
[-        ] BACTOPIA:SKETCHER:SKETCHER_MODULE          -                                                
[-        ] BACTOPIA:ANNOTATOR:PROKKA_MODULE           -                                                
[-        ] BACTOPIA:AMRFINDERPLUS:AMRFINDERPLUS_RUN   -
[-        ] BACTOPIA:AMRFINDERPLUS:GENES_CONCAT        -
[-        ] BACTOPIA:AMRFINDERPLUS:PROTEINS_CONCAT     -
[-        ] BACTOPIA:MLST:MLST_MODULE                  -
[-        ] BACTOPIA:MLST:CSVTK_CONCAT                 -
[03/651531] BACTOPIA:DUMPSOFTWAREVERSIONS (1)          | 1 of 1 ✔

    Bactopia Execution Summary                       
    ---------------------------                      
    Bactopia Version : 3.0.1                         
    Nextflow Version : 24.04.4                       
    Command Line     : nextflow run bactopia/bactopia -r v3.0.0 -work-dir 's3://nextflow-s3-bucket-1234/
bactopia/workdir' -profile test,aws --aws_queue analysis-jobq-9f9048f --aws_region us-east-2 --outdir 's
3://nextflow-s3-bucket-1234/bactopia/out_test_tutorial' --aws_cli_path /home/ec2-user/miniconda/bin/aws 
--max_memory 3 --max_cpus 2 --accession SRX4563634 --sample SRX4563634 --coverage 100 --genome_size 2800
000             
    Resumed          : false
    Completed At     : 2024-10-08T15:46:52.941146529Z
    Duration         : 8m 1s
    Success          : true
    Exit Code        : 0
    Error Report     : -
    Launch Dir       : /home/ec2-user
```

I get the same results when running with `-r dev` as well

**Comment by rpetit3** [comment]
Hi @mehalter 

Can we try a few adjustments?

```
nextflow run bactopia/bactopia -r v3.0.1 \
    -work-dir 's3://nextflow-s3-bucket-1234/bactopia/workdir' \
    -profile aws \
    --aws_queue analysis-jobq-9f9048f \
    --aws_region us-east-2 \
    --outdir 's3://nextflow-s3-bucket-1234/bactopia/out_test_tutorial' \
    --aws_cli_path /home/ec2-user/miniconda/bin/aws \
    --max_memory 8.GB \
    --max_cpus 2 \
    --accession SRX4563634 \
    --coverage 100 \
    --genome_size 2800000
```

Mostly removing `test` from `-profile` and bumping the memory to `8.GB`

**Comment by mehalter** [comment]
Ah...... I see.... 😅 I bet it is the `test` profile, if that's it I'm so sorry for the noise. I'm re-running now with that removed. Based on how our AWS Batch compute environments are set up at the moment I am capped out at 3G of RAM just because it's dictated by the `c4.large` EC2 size. Once we get a bit further down and are getting full results I'm going to start bumping up some resources. Thanks so much for helping identify the test profile being left in! 🫡

**Comment by rpetit3** [comment]
Totally understandable. I'll warn you there may be a few steps (e.g. `SKETCHER`) that will fail with 3GB memory. I've been considering adding an option to disable querying databases in that step which should make it play nicely in low memory settings

Either way, keep me posted on any issues or any feedback/adjustments you might have
