### ISSUE TITLE
[bug] `--singularity_cache_dir` ignored

### ISSUE THREAD

**Issue by victorlin** [bactopia/bactopia#560]
**Description**
Running with `--singularity_cache_dir` does not change the destination for image download.

**Steps to Reproduce**

1. Install `bactopia` via conda
2. Make a custom directory `mkdir -p ~/custom-directory`
3. Run `bactopia --singularity_cache_dir ~/custom-directory`

Images are still downloaded to `.bactopia/singularity`:

```
2024-10-02 14:41:09 INFO     2024-10-02 14:41:09:root:INFO - Checking if environment pre-builds are needed (this may take a    download.py:544
                             while if building for the first time)                                                                            
                    INFO     2024-10-02 14:41:09:root:INFO - Begin qc download to                                              download.py:290
                             /home/vlin/.bactopia/singularity/depot.galaxyproject.org-singularity-bactopia-qc-1.0.2--hdfd78af_                
                             0.img
```

**Expected Behavior**

Image in the output above should download to `/home/vlin/custom-directory/depot.galaxyproject.org-…`

**Execution Environment**

- Bactopia Version: tested on 3.0.1, 3.1.0, 3.1.1 (dev)
- OS: Ubuntu 18.04.6 LTS
- Environment: [cluster](https://sciwiki.fredhutch.org/scicomputing/compute_overview/)

**Additional Information**

I have also tried `params.singularity_cache_dir` to the same effect.

**Comment by rpetit3** [comment]
That's unexpected, let me get this fixed for you!

**Comment by rpetit3** [comment]
OK, the is an easy fix, use `--singularity_cache`

Can you point me to where I still had `--singularity_cache_dir`?

**Comment by rpetit3** [comment]
This should now be fixed in the dev version. I've replaced  `--singularity_cache_dir` with `--singularity_cache` to match `bactopia download`.

```
mamba create -n bactopia-dev -c rpetit3 -c conda-forge -c bioconda bactopia
```

Thank you so much for reporting this!

**Comment by victorlin** [comment]
Thanks (again) for the quick fix! I'll give it a try tomorrow and report back.

**Comment by victorlin** [comment]
Confirmed that `bactopia --singularity_cache` works as expected!

**Comment by rpetit3** [comment]
Awesome! Thanks again for reporting this!
