### ISSUE TITLE
[bug] Cannot run directly from Github using Nextflow

### ISSUE THREAD

**Issue by marchoeppner** [bactopia/bactopia#563]
**Description**
Trying to run bactopia directly from github, as one would a "normal" nf-core pipeline, fails with a validation error:

nextflow run bactopia/bactopia -profile singularity,test

 N E X T F L O W   ~  version 24.04.4

Pulling bactopia/bactopia ...
Project config file is malformed -- Cause: No signature of method: groovy.util.ConfigObject.toInteger() is applicable for argument types: () values: []

**Steps to Reproduce**

See above

**Expected Behavior**

No error ;)

**Execution Environment**

- Bactopia Version: main branch as of writing. 
- OS: AlmaLinux
- Environment: singularity 4.1
- Nextflow: 24.04.4

**Additional Information**

Test pipeline with nextflow? ;)

**Comment by rpetit3** [comment]
Hi @marchoeppner 

This is fixed: https://github.com/bactopia/bactopia/issues/555 and will be available in the next version. For now you can try the `-r dev` with the fix.

Cheers,
Robert
