### ISSUE TITLE
[question] Snippy run on multiple Bactopia results folders

### ISSUE THREAD

**Issue by gilliantarr** [bactopia/bactopia#572]
We have three datasets with sequences we have assembled using Bactopia. We need to keep the results from each dataset separate for some analyses, but for others, we need to analyze them together. Our file structure is thus set up as:

results_folder
- dataset_a
- - sample1
- - sample2
- - ...
- dataset_b
- - sample10
- - sample11
- - ...
- dataset_c
- - sample100
- - sample101
- - ...

We are currently trying to generate a core SNP alignment for the samples from all three datasets. From results_folder, we're running this as:

bactopia --wf snippy --bactopia ./*/ --reference ref_o121_h19.gbff -qs 24  -profile singularity

However, this leads to it treating each dataset folder separately, generating a core SNP alignment for each dataset. We need all 3 together. Is it possible to accomplish that using the Snippy workflow without changing the file structure (as mentioned, we need to keep them separated for other analyses)?

**Comment by rpetit3** [comment]
Hi @gilliantarr 

Is this what your are hoping to acheive? https://github.com/bactopia/bactopia/issues/547

Cheers,
Robert

**Comment by gilliantarr** [comment]
Yes, exactly that, thanks. I will close this.

**Comment by rpetit3** [comment]
Awesome, I will start putting more thought into how to implement this.
