### ISSUE TITLE
Snippy workflow

### ISSUE THREAD

**Issue by yasir5565** [bactopia/bactopia#575]
I am facing issue while running the snippy workflow. Output is given below:
executor >  local (146)
[12/e15374] BAC…LE (SRR31182841 - genomic) | 142 of 184, failed: 142, retries: 141
[-        ] BAC…:SNIPPY:SNIPPY_CORE_MODULE -
[-        ] BACTOPIATOOLS:SNIPPY:SNPDISTS  -
[-        ] BAC…PPY:GUBBINS:GUBBINS_MODULE -
[-        ] BAC…NIPPY:IQTREE:IQTREE_MODULE -
[-        ] BAC…USTOM_DUMPSOFTWAREVERSIONS -
[05/71891f] NOTE: Process `BACTOPIATOOLS:SNIPPY:SNIPPY_RUN_MODULE (SRR31182848 - genomic)` terminated with an error exit status (2) -- Execution is retried (3)
[d6/ca7427] NOTE: Process `BACTOPIATOOLS:SNIPPY:SNIPPY_RUN_MODULE (SRR31182855 - genomic)` terminated with an error exit status (2) -- Execution is retried (3)
[d6/49b2a4] NOTE: Process `BACTOPIATOOLS:SNIPPY:SNIPPY_RUN_MODULE (SRR31182849 - genomic)` terminated with an error exit status (2) -- Execution is retried (3)
[f5/a43b0c] NOTE: Process `BACTOPIATOOLS:SNIPPY:SNIPPY_RUN_MODULE (SRR31182856 - genomic)` terminated with an error exit status (2) -- Execution is retried (3)
[3f/5dc77d] NOTE: Process `BACTOPIATOOLS:SNIPPY:SNIPPY_RUN_MODULE (SRR31182850 - genomic)` terminated with an error exit status (2) -- Execution is retried (3)
[6a/ed4752] NOTE: Process `BACTOPIATOOLS:SNIPPY:SNIPPY_RUN_MODULE (SRR31182857 - genomic)` terminated with an error exit status (2) -- Execution is retried (3)
[0c/e8ef5b] NOTE: Process `BACTOPIATOOLS:SNIPPY:SNIPPY_RUN_MODULE (SRR31182858 - genomic)` terminated with an error exit status (2) -- Execution is retried (3)
[d2/45960b] NOTE: Process `BACTOPIATOOLS:SNIPPY:SNIPPY_RUN_MODULE (SRR31182854 - genomic)` terminated with an error exit status (2) -- Execution is retried (3)
[55/48f557] NOTE: Process `BACTOPIATOOLS:SNIPPY:SNIPPY_RUN_MODULE (SRR31182852 - genomic)` terminated with an error exit status (2) -- Execution is retried (3)
[e2/c3a36e] NOTE: Process `BACTOPIATOOLS:SNIPPY:SNIPPY_RUN_MODULE (SRR31182860 - genomic)` terminated with an error exit status (2) -- Execution is retried (3)
[ed/f7905e] NOTE: Process `BACTOPIATOOLS:SNIPPY:SNIPPY_RUN_MODULE (SRR31182862 - genomic)` terminated with an error exit status (2) -- Execution is retried (3)
[80/9e1f75] NOTE: Process `BACTOPIATOOLS:SNIPPY:SNIPPY_RUN_MODULE (SRR31182864 - genomic)` terminated with an error exit status (2) -- Execution is retried (3)
[a3/dbdd26] NOTE: Process `BACTOPIATOOLS:SNIPPY:SNIPPY_RUN_MODULE (SRR31182859 - genomic)` terminated with an error exit status (2) -- Execution is retried (3)
[3d/10f097] NOTE: Process `BACTOPIATOOLS:SNIPPY:SNIPPY_RUN_MODULE (SRR31182865 - genomic)` terminated with an error exit status (2) -- Execution is retried (3)
[9f/38d955] NOTE: Process `BACTOPIATOOLS:SNIPPY:SNIPPY_RUN_MODULE (SRR31182861 - genomic)` terminated with an error exit status (2) -- Execution is retried (3)
ERROR ~ Error executing process > 'BACTOPIATOOLS:SNIPPY:SNIPPY_RUN_MODULE (SRR16134454 - genomic)'

Caused by:
  Process `BACTOPIATOOLS:SNIPPY:SNIPPY_RUN_MODULE (SRR16134454 - genomic)` terminated with an error exit status (2)

Command executed:

  if [ "false" == "true" ]; then
      gzip -c -d genomic.gbff > genomic.gbff
  fi
  
  if ! head -n 1 genomic.gbff | grep "^LOCUS"; then
      echo "ERROR: Reference file (genomic.gbff) does not appear to be a GenBank file"
      exit 1
  fi
  
  snippy \
      --mapqual 60 --basequal 13 --mincov 10 --minfrac 0 --minqual 100 --maxsoft 10 \
      --cpus 4 \
      --outdir SRR16134454 \
      --reference genomic.gbff \
      --prefix SRR16134454 \
      --R1 SRR16134454_R1.fastq.gz --R2 SRR16134454_R2.fastq.gz
  
  # Add GenBank annotations
  vcf-annotator SRR16134454/SRR16134454.vcf genomic.gbff > SRR16134454/SRR16134454.annotated.vcf
  
  # Get per-base coverage
  grep "^##contig" SRR16134454/SRR16134454.vcf > SRR16134454/SRR16134454.full-coverage.txt
  genomeCoverageBed -ibam SRR16134454/SRR16134454.bam -d >> SRR16134454/SRR16134454.full-coverage.txt
  cleanup-coverage.py SRR16134454/SRR16134454.full-coverage.txt > SRR16134454/SRR16134454.coverage.txt
  rm SRR16134454/SRR16134454.full-coverage.txt
  
  # Mask low coverage regions
  mask-consensus.py \
      SRR16134454 \
      genomic \
      SRR16134454/SRR16134454.consensus.subs.fa \
      SRR16134454/SRR16134454.subs.vcf \
      SRR16134454/SRR16134454.coverage.txt \
      --mincov 10 > SRR16134454/SRR16134454.consensus.subs.masked.fa
  
  # Clean Up
  rm -rf SRR16134454/reference SRR16134454/ref.fa* SRR16134454/SRR16134454.vcf.gz*
  
  if [[ false == "false" ]]; then
      find SRR16134454/ -type f |             grep -v -E "\.bam$|\.bai$|\.log$|\.txt$|\.html$|\.tab$" |             xargs -I {} pigz -n --best -p 4 {}
      pigz -n --best -p 4 SRR16134454/SRR16134454.coverage.txt
  fi
  mv SRR16134454/ results/
  mv results/*.log ./
  
  cat <<-END_VERSIONS > versions.yml
  "BACTOPIATOOLS:SNIPPY:SNIPPY_RUN_MODULE":
      bedtools: $(echo $(bedtools --version 2>&1) | sed 's/bedtools v//')
      pigz: $(echo $(pigz --version 2>&1) | sed 's/pigz //')
      snippy: $(echo $(snippy --version 2>&1) | sed 's/^.*snippy //')
      vcf-annotator: $(echo $(vcf-annotator --version 2>&1) | sed 's/vcf-annotator.py //')
  END_VERSIONS

Command exit status:
  2

Command output:
  LOCUS       AE016823             4277185 bp    DNA     circular BCT 31-JAN-2014

Command error:
         -B INT        penalty for a mismatch [4]
         -O INT[,INT]  gap open penalties for deletions and insertions [6,6]
         -E INT[,INT]  gap extension penalty; a gap of size k cost '{-O} + {-E}*k' [1,1]
         -L INT[,INT]  penalty for 5'- and 3'-end clipping [5,5]
         -U INT        penalty for an unpaired read pair [17]
  
         -x STR        read type. Setting -x changes multiple parameters unless overridden [null]
                       pacbio: -k17 -W40 -r10 -A1 -B1 -O1 -E1 -L0  (PacBio reads to ref)
                       ont2d: -k14 -W20 -r10 -A1 -B1 -O1 -E1 -L0  (Oxford Nanopore 2D-reads to ref)
                       intractg: -B9 -O16 -L5  (intra-species contigs to ref)
  
  Input/output options:
  
         -p            smart pairing (ignoring in2.fq)
         -R STR        read group header line such as '@RG\tID:foo\tSM:bar' [null]
         -H STR/FILE   insert STR to header if it starts with @; or insert lines in FILE [null]
         -o FILE       sam file to output results to [stdout]
         -j            treat ALT contigs as part of the primary assembly (i.e. ignore <idxbase>.alt file)
         -5            for split alignment, take the alignment with the smallest coordinate as primary
         -q            don't modify mapQ of supplementary alignments
         -K INT        process INT input bases in each batch regardless of nThreads (for reproducibility) []
  
         -v INT        verbosity level: 1=error, 2=warning, 3=message, 4+=debugging [3]
         -T INT        minimum score to output [30]
         -h INT[,INT]  if there are <INT hits with score >80% of the max score, output all in XA [5,200]
         -a            output all alignments for SE or unpaired PE
         -C            append FASTA/FASTQ comment to SAM output
         -V            output the reference FASTA header in the XR tag
         -Y            use soft clipping for supplementary alignments
         -M            mark shorter split hits as secondary
  
         -I FLOAT[,FLOAT[,INT[,INT]]]
                       specify the mean, standard deviation (10% of the mean if absent), max
                       (4 sigma from the mean if absent) and min of the insert size distribution.
                       FR orientation only. [inferred]
  
  Note: Please read the man page for detailed description of the command line and options.
  
  [samclip] samclip 0.4.0 by Torsten Seemann (@torstenseemann)
  [samclip] Loading: reference/ref.fa.fai
  [samclip] Found 2 sequences in reference/ref.fa.fai
  [samclip] Total SAM records 0, removed 0, allowed 0, passed 0
  [samclip] Header contained 0 lines
  [samclip] Done.
  [W::hts_set_opt] Cannot change block size for this format
  samtools sort: failed to read header from "-"
  [bam_mating_core] ERROR: Couldn't read header
  [W::hts_set_opt] Cannot change block size for this format
  samtools sort: failed to read header from "-"
  [11:07:14] Error running command, check SRR16134454/SRR16134454.log

Work dir:
  /scratch.global/ammar/Puerto/da/96d3daa3f4bad9c544950f4a1da6ad

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details

**Comment by rpetit3** [comment]
Hi @yasir5565 

Apologies for the delay, did you figure things out on your end?
