### ISSUE TITLE
Bactopia tool - spatyper

### ISSUE THREAD

**Issue by rpetit3** [bactopia/bactopia#58]

**Comment by rpetit3** [comment]
No way, remind me in 30 days!

**Comment by rpetit3** [comment]
Will need to look into  getting https://github.com/HCGB-IGTP/spaTyper added to Bioconda

**Comment by JFsanchezherrero** [comment]
Definitely take a look! Came to me if you need further assistance or new developments!
https://github.com/HCGB-IGTP/spaTyper

**Comment by rpetit3** [comment]
Hi @JFsanchezherrero !

Looks like this would work great! Are there plans to submit to BioConda?

Thank you!
Robert

**Comment by JFsanchezherrero** [comment]
Hi there,

I guess it would make completely sense. 
I would let you know when available.

Thanks
Jose F.

**Comment by rpetit3** [comment]
Hey @JFsanchezherrero 

I got SpaTyper put on Bioconda (https://github.com/bioconda/bioconda-recipes/pull/26044). Do you think it would be possible to add an option for tabular output? Or something that is a little easier to parse?

Current:
```
spaTyper -f contgs.fasta
Start the identification of repeats in Spa protein:
+ Check or download repeats fasta file in folder:  /home/rpetit/miniconda3/envs/spatyper/bin
+ Check or download repeats types file in folder:  /home/rpetit/miniconda3/envs/spatyper/bin

-----------------
Results:
-----------------
Sequence name:  NODE_9_length_139906_cov_50.416415 Repeats: 07-23-12-21-12-17-20-17-12-12-17 Repeat Type: t148

Sequence name:  NODE_21_length_36657_cov_56.067510 Repeats: 17 Repeat Type: 17
```

Alternative:
```
spaTyper -f contgs.fasta --table output.txt
cat output.txt
name	repeats	repeat_type
NODE_9_length_139906_cov_50.416415	07-23-12-21-12-17-20-17-12-12-17	t148
NODE_21_length_36657_cov_56.067510	17	17
```

Thanks!

**Comment by JFsanchezherrero** [comment]
Hi @rpetit3,

Thanks for the update and implementation in bioconda.

I did not create the tabular output so far as I was using it as a python module within my pipeline returning a dataframe but it would definitely make sense to create a tabular or csv format when using it independently. I would implemented and let you know. 

I would like to thank and give credit again to @mjsull who originally created the code and initiate the project.

Best regards,

**Comment by JFsanchezherrero** [comment]
Hi there @rpetit3 , 

I have updated and set tabular output (either a file or standard out) for spaTyper. 

I have added some test genomes (_S. aureus MRSA252_ and _NCTC 8325_) in a test folder as an example.

I have accidentally discovered that spaTyper also supports protein fasta files. You can provide one or thousands of proteins (CDS from annotation) and it detects the repeats in the protein A. I have also added test files for this new feature in tests folder.

Best regards!
Jose

**Comment by rpetit3** [comment]
Nice! When you are ok with it, submit a new release on Github and Bioconda will automatically update. Once the new version is on Bioconda I'll get the tool Bactopia Tool made.

**Comment by JFsanchezherrero** [comment]
Hi there,

It is done already and updated on github and pip. Its new version is 0.3.3.

https://github.com/HCGB-IGTP/spaTyper
https://pypi.org/project/spaTyper/

Best

**Comment by rpetit3** [comment]
Ah that's right! I forgot it was on PyPi, I'll keep an eye out for the PR and get it merged into Bioconda. Thanks for the update!

**Comment by rpetit3** [comment]
This is done (https://github.com/bactopia/bactopia/blob/master/tools/staph-typer/README.md) and will be in the next version of Bactopia.
