### ISSUE TITLE
species error

### ISSUE THREAD

**Issue by pavlo888** [bactopia/bactopia#65]
Hi, 

When I run the command:

bactopia --R1 /home/sam/Downloads/BAGEP/fastq/018_R1.fastq.gz --R2 /home/sam/Downloads/BAGEP/fastq/018_R2.fastq.gz --sample 018 --datasets /home/sam/Downloads/datasets/ --species "Agrobacterium rhizogenes" --coverage 100 --cpus 2 --outdir bactopia-test1

I get the following error: 

 Species 'Agrobacterium rhizogenes' not available, please check spelling or use '--available_datasets' to verify the dataset has been set up. Exiting

Could you help me solve this issue please? 

Cheers, 
Pablo

**Comment by rpetit3** [comment]
Hi Pablo! Sure thing! 

Do you by chance have the command you used to create the datasets? Also, what's in this directory `/home/sam/Downloads/datasets/species-specific`?

**Comment by pavlo888** [comment]
Hi, 

This is the command I used for creating the dataset: 

bactopia datasets --species "Agrobacterium rhizogenes" --include_genus --cpus 4

Then in that directory, I can see a file  named "agrobacterium-rhizogenes" and subfolders for annotation, minmer, and optionals. 

Cheers, 
Pablo

**Comment by rpetit3** [comment]
I'm going to try and replicate locally here. In the meantime whats the output when you add `--available_datasets` ?

```
bactopia --R1 /home/sam/Downloads/BAGEP/fastq/018_R1.fastq.gz \
               --R2 /home/sam/Downloads/BAGEP/fastq/018_R2.fastq.gz \
               --sample 018 \
               --datasets /home/sam/Downloads/datasets/ \
               --species "Agrobacterium rhizogenes" \
               --coverage 100 \
               --cpus 2 \
               --outdir bactopia-test \
               --available_datasets
```

**Comment by pavlo888** [comment]
Hi, 

When I run the command you suggest, I get the following output: 

WARN: Access to undefined parameter `dataset` -- Initialise it to a default value eg. `params.dataset = some_value`
Please use '--dataset' to specify the path to pre-built datasets.

**Comment by rpetit3** [comment]
Saw that as well: https://github.com/bactopia/bactopia/issues/67

Would it be possible to get the `ls` outputs for:

```
ls /home/sam/Downloads/datasets

ls /home/sam/Downloads/datasets/species-specific
```

**Comment by rpetit3** [comment]
Alright! Quick update. I've tried to replicate this and have been unsuccessful.

Here's what I've done:
```
cd ~/
mkdir test
cd test

bactopia datasets datasets --species "Agrobacterium rhizogenes" --include_genus --cpus 4
2020-02-11 15:41:37:root:INFO - Agrobacterium rhizogenes verified in ENA Taxonomy database
2020-02-11 15:41:37:root:INFO - Setting up Ariba datasets
2020-02-11 15:41:37:root:INFO - Setting up card Ariba dataset
2020-02-11 15:42:52:root:INFO - Setting up vfdb_core Ariba dataset
2020-02-11 15:49:49:root:INFO - Setting up pre-computed Genbank/Refseq minmer datasets
2020-02-11 15:50:40:root:INFO - Setting up pre-computed PLSDB (plasmids) datasets
2020-02-11 15:51:50:root:INFO - Setting up MLST datasets
2020-02-11 15:51:50:root:ERROR - Agrobacterium rhizogenes is not available from pubMLST.org
2020-02-11 15:51:50:root:INFO - No valid MLST schemas to setup, skipping
2020-02-11 15:51:50:root:INFO - Setting up custom Prokka proteins
2020-02-11 15:51:50:root:INFO - Setting up custom Prokka proteins for Agrobacterium rhizogenes
2020-02-11 15:51:50:root:INFO - Downloading completed genomes
2020-02-11 15:52:01:root:INFO - Processing 27 Genbank files
2020-02-11 15:52:58:root:INFO - Median genome size: 5482241 (n=1)
2020-02-11 15:52:58:root:INFO - Running CD-HIT on 142243 proteins
2020-02-11 15:54:02:root:INFO - Writing summary of available datasets

ls datasets/
ariba  minmer  plasmid  species-specific  summary.json

ls datasets/species-specific/
agrobacterium-rhizogenes

cat datasets/summary.json
{
    "ariba": [
        {
            "name": "card.tar.gz",
            "last_update": "2020-02-11T20:42:52Z"
        },
        {
            "name": "vfdb_core.tar.gz",
            "last_update": "2020-02-11T20:49:49Z"
        }
    ],
    "minmer": {
        "sketches": [
            "genbank-k21.json.gz",
            "genbank-k31.json.gz",
            "genbank-k51.json.gz",
            "refseq-k21-s1000.msh"
        ],
        "last_update": "2020-02-11T20:50:40Z"
    },
    "plasmid": {
        "sketches": "plsdb.msh",
        "blastdb": "plsdb.fna",
        "last_update": "2020-02-11T20:51:50Z"
    },
    "species-specific": {
        "agrobacterium-rhizogenes": {
            "mlst": [],
            "minmer": {
                "mash": "species-specific/agrobacterium-rhizogenes/minmer/refseq-genomes.msh",
                "last_updated": "2020-02-11T20:54:02Z"
            },
            "annotation": {
                "proteins": "species-specific/agrobacterium-rhizogenes/annotation/proteins.faa",
                "last_updated": "2020-02-11T20:54:02Z"
            },
            "genome_size": {
                "min": 5482241,
                "median": 5482241,
                "mean": 5482241,
                "max": 5482241,
                "total": 1,
                "description": "Genome size values are based on 1 completed genomes (RefSeq)."
            },
            "optional": {
                "blast": [
                    "species-specific/agrobacterium-rhizogenes/optional/blast/genes",
                    "species-specific/agrobacterium-rhizogenes/optional/blast/primers",
                    "species-specific/agrobacterium-rhizogenes/optional/blast/proteins"
                ],
                "insertion-sequences": "species-specific/agrobacterium-rhizogenes/optional/insertion-sequences",
                "mapping-sequences": "species-specific/agrobacterium-rhizogenes/optional/mapping-sequences",
                "reference-genomes": "species-specific/agrobacterium-rhizogenes/optional/reference-genomes"
            }
        }
    }
}

bactopia --datasets datasets --SE SRX477044.fastq.gz --sample SRX477044 --species "Agrobacterium rhizogenes"
N E X T F L O W  ~  version 19.10.0
Launching `bactopia/bactopia` [amazing_meninsky] - revision: 0dd1c52b29 [v1.2.4]
bactopia - 1.2.4
Found 2 ARIBA datasets
/home/rpetit3/test/datasets/ariba/card.tar.gz
/home/rpetit3/test/datasets/ariba/vfdb_core.tar.gz
Found 5 minmer sketches/signatures
/home/rpetit3/test/datasets/minmer/genbank-k21.json.gz
/home/rpetit3/test/datasets/minmer/genbank-k31.json.gz
/home/rpetit3/test/datasets/minmer/genbank-k51.json.gz
/home/rpetit3/test/datasets/minmer/refseq-k21-s1000.msh
/home/rpetit3/test/datasets/plasmid/plsdb.msh
Found 3 PLSDB (plasmid) BLAST files
datasets/plasmid/plsdb.fna.nsq
datasets/plasmid/plsdb.fna.nhr
datasets/plasmid/plsdb.fna.nin
Found Prokka proteins file
/home/rpetit3/test/datasets/species-specific/agrobacterium-rhizogenes/annotation/proteins.faa
Found Mash Sketch of RefSeq genomes
/home/rpetit3/test/datasets/species-specific/agrobacterium-rhizogenes/minmer/refseq-genomes.msh
Found 0 MLST datasets
Found 0 reference genomes
Found 0 insertion sequence FASTAs
Found 0 FASTAs to align reads against
Found 0 FASTAs to query with BLAST
If something looks wrong, now's your chance to back out (CTRL+C 3 times).
```

I would be interested in seeing your `summary.json` file when you have a chance.

**Comment by pavlo888** [comment]
Hi, 

So this what's inside datasets and species-specific folder: 

(bactopia) sam@BioInf2:~/Downloads$ ls datasets
ariba          bactopia-test1  minmer   species-specific  work
bactopia-info  datasets        plasmid  summary.json
(bactopia) sam@BioInf2:~/Downloads$ ls datasets/species-specific/
agrobacterium-rhizogenes

then I tried running the two commands you ran previously and I got an error, something to do with gather_fastqs (1) 

Any idea what could be wrong?

**Comment by pavlo888** [comment]
Sorry, that's a mistake on my part about the last comment. 

This is the output of ls on the specific folders you asked 
(bactopia) sam@BioInf2:~/Downloads$ ls datasets
ariba          bactopia-test1  minmer   species-specific  work
bactopia-info  datasets        plasmid  summary.json
(bactopia) sam@BioInf2:~/Downloads$ ls datasets/species-specific/
agrobacterium-rhizogenes

**Comment by pavlo888** [comment]
I do not know why it strikes it through when i post it. sorry about that issue

**Comment by rpetit3** [comment]
If you have a moment, I can try helping through chat on Gitter:  https://gitter.im/bactopia/Lobby

Otherwise, whats the output of `/home/sam/Downloads/datasets/summary.json` and which OS are you using?

**Comment by pavlo888** [comment]
[summaryjson_bactopia.txt](https://github.com/bactopia/bactopia/files/4198520/summaryjson_bactopia.txt)

Hi, 

It seems I saw this message a bit too late and could not find you online on the lobby chat. 
However, attached you will find the output of the summary.json file. 

The OS I am using is Ubuntu 16.4 Xenial. 

Cheers, 
Pablo

**Comment by rpetit3** [comment]
Do you have any issues if you run bactopia without datasets?

```
bactopia --R1 /home/sam/Downloads/BAGEP/fastq/018_R1.fastq.gz \
         --R2 /home/sam/Downloads/BAGEP/fastq/018_R2.fastq.gz \
         --sample 018  \
         --coverage 100 \
         --cpus 2 \
         --outdir bactopia-test1
```

**Comment by pavlo888** [comment]
I get the following error

Error executing process > 'gather_fastqs (1)'

Caused by:
  Conda prefix path does not exist or it's not a directory: /home/sam/anaconda2/envs/bactopia/.nextflow/assets/bactopia/bactopia/conda/envs/gather_fastqs-1.2.2
Failed to invoke `workflow.onComplete` event handler

 -- Check script '/home/sam/anaconda2/envs/bactopia/.nextflow/assets/bactopia/bactopia/main.nf' at line: 603 or see '.nextflow.log' file for more details

**Comment by rpetit3** [comment]
Alright, I'm going to release a new version update soon. This update has some changes in how bactopia is executed and conda fixes. I'll keep you posted.

What version of bactopia are you using? 

I'm assuming 1.2.4 (`bactopia --version`)

**Comment by rpetit3** [comment]
@pavlo888 Bactopai v1.3.0 is now available from Bioconda (you might have to clear cache). Let me know if this helps resolve your issue.

**Comment by amymariecampbell** [comment]
Hi there, 

I'm having a similar issue to the above (https://github.com/bactopia/bactopia/issues/65#issuecomment-585762554) when I run the tutorial. I get the following error:

`Error executing process > 'gather_fastqs (SRX4563634)'

Caused by:
  Conda prefix path does not exist or it's not a directory: /home/amymariecampbell/miniconda3/envs/bactopia/share/bactopia-1.6.x/conda/envs/gather_fastqs-1.6.x
`

Here is the ls of that envs folder:
`annotate_genome.md5           ariba_analysis.yml   call_variants.md5        download_references.yml  qc_reads.md5
annotate_genome.yml           assemble_genome.md5  call_variants.yml        gather_fastqs.md5        qc_reads.yml
antimicrobial_resistance.md5  assemble_genome.yml  count_31mers.md5         gather_fastqs.yml        README.md
antimicrobial_resistance.yml  assembly_qc.md5      count_31mers.yml         minmers.md5              sequence_type.md5
ariba_analysis.md5            assembly_qc.yml      download_references.md5  minmers.yml              sequence_type.yml`

Would be really grateful for any help, thanks so much!
