### ISSUE TITLE
[feature] Bactopia - Each optional blast query is an individual job

### ISSUE THREAD

**Issue by rpetit3** [bactopia/bactopia#88]
**Related To**

- [X] Bactopia

**Is this related to a problem?**
If you have populated the `optional/{genes|proteins}` folder it will create a separate job for each FASTA. For local jobs this is not a problem, but for cloud based analyses its going to take way longer to import the containers (>1 minute) then it will to actually blast (~10 seconds). This will add up as the number of FASTAs in the optional folder goes up.

**Describe the solution you'd like**
Merge all the FASTAs into a multi-fasta and let parallel do it's thing.

**Comment by plasmid02** [comment]
Note - group merged pastas by the type of blast job and parameters (short-blast, megablast etc)
