### ISSUE TITLE
Problem with Prokka module

### ISSUE THREAD

**Issue by theInnuendoProject** [bactopia/bactopia#95]
Hi,
I had to modify the `miniconda3/envs/bactopia/share/bactopia-1.3.0/templates/annotate_genome.sh` for inserting the `--centre X --compliant` due to long file name that sometime (unfortunately) I need to handle. However, after I got again an error which I'm not able to understand. 
 ````
[dreamy_euclid]
Nextflow workflow report
[dreamy_euclid]
Workflow execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: 2.

The full error message was:

Error executing process > 'annotate_genome (ERR2278729)'

Caused by:
  Process `annotate_genome (ERR2278729)` terminated with an error exit status (2)

Command executed [/home/mrossi/miniconda3/envs/bactopia/share/bactopia-1.3.0/templates/annotate_genome.sh]:

  #!/bin/bash
  set -e
  set -u
  
  if [ "false" == "true" ]; then
      mkdir -p annotation
      touch annotation/ERR2278729.gbk
  else
      if [[ false == "true" ]]; then
          gunzip -f ERR2278729.fna
      fi
  
      prokka --outdir annotation \
          --force \
          --prefix ERR2278729 \
          --addgenes \
           \
          --locustag ERR2278729 \
          --centre Bactopia \
          --genus Genus \
          --species species \
           \
           \
           \
          --evalue '1e-09' \
          --coverage 80 \
          --cpus 4 \
          --mincontiglen 500 \
          --centre X \ 
  	--compliant \
  	 \
           \
           \
           \
          ERR2278729.fna
  
      if [[ false == "true" ]]; then
          find annotation/ -type f -not -name "*.txt" -and -not -name "*.log*" | \
              xargs -I {} pigz -n --best -p 4 {}
      fi
  fi

Command exit status:
  2

Command output:
  (empty)

Command error:
  [12:15:48] This is prokka 1.14.5
  [12:15:48] Written by Torsten Seemann 
  [12:15:48] Homepage is https://github.com/tseemann/prokka
  [12:15:48] Local time is Wed Mar 25 12:15:48 2020
  [12:15:48] You are mrossi
  [12:15:48] Operating system is linux
  [12:15:48] You have BioPerl 1.007002
  [12:15:48] System has 32 cores.
  [12:15:48] Will use maximum of 4 cores.
  [12:15:48] Annotating as >>> Bacteria <<<
  [12:15:48] ' ' is not a readable non-empty FASTA file
````

**Comment by rpetit3** [comment]
Hi @theInnuendoProject !

Thanks for giving Bactopia a go! 

So first thing that sticks out is that I need to add an option to turn on `compliant`.

Second thing, and this is only because Nextflow is very peculiar about spaces but based on the output above I think there is a space after the `--centre X \`. Try removing that for a temporary fix.

In the meantime I will attempt get this added ASAP so its not an issue in the future.

Thanks for bringing that to light!
Robert

**Comment by rpetit3** [comment]
@theInnuendoProject apologies, Githun auto closed.

I've added `--compliant` as an option. I'm going to run some tests and if good I'll create a v1.3.1 release

**Comment by rpetit3** [comment]
@theInnuendoProject I've submitted a release for v1.3.1 which includes the `--compliant` option. It should be available from bioconda soon

**Comment by rpetit3** [comment]
@theInnuendoProject I'm going to close this issue since the `--compliant` option was added. Please feel free to reopen if it doesn't solve your problem. Thank you very much for using Bactopia.
