### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by maguileraf** [bactopia/bactopia#97]
I get the following error during installation:
Executing transaction: failed
ERROR conda.core.link:_execute(502): An error occurred while installing package 'conda-forge::appdirs-1.4.3-py_1'.
FileNotFoundError(2, "No such file or directory: '/home/maguileraf23/.conda/envs/bactopia/bin/python3.6'")

**Comment by rpetit3** [comment]
@maguileraf Let's see if we can get this figured out. I'll need some more info

Which Bactopia version are you using? (output from `bactopia version`)
Which conda version?
Which OS?
Is this a fresh conda environment? 

Also, does this look similar? https://github.com/conda/conda/issues/9761

**Comment by maguileraf** [comment]
conda version: 4.5.4
I am using the command (conda create -y -n bactopia -c conda-forge -c bioconda bactopia) on your readme page to install bactopia so I am guessing the current version?
OS: Linux
Yes, fresh conda env

**Comment by rpetit3** [comment]
I've just released v1.3.1 of Bactopia. I'm going to use that to see if I can replicate your error. Apologies for the delay!

**Comment by rpetit3** [comment]
Hi @maguileraf. I've been unable to replicate your error, although I'm on a newer version of conda (v4.7.4). I wonder if upgrading your conda version (`conda upgrade conda`) would help.

**Comment by rpetit3** [comment]
Hi @maguileraf going to close this. Please feel free to reopen it if you are still having problems. Thanks!
