### ISSUE TITLE
[bug] Broken link to Bactopia Tools page in README

### ISSUE THREAD

**Issue by mikemc** [bactopia/bactopia#98]
The link [Bactopia Tools](https://bactopia.github.io/tools/bactopia-tools/) in README.md is broken. Looks like it should instead be linking to https://bactopia.github.io/bactopia-tools/

**Comment by rpetit3** [comment]
Thank you very much for finding that! Fixed as of https://github.com/bactopia/bactopia/commit/e5327b08cc327f753a99c63a4e75ac91c2141873
